### ISSUE TITLE
Non-integer formation values in lith block?

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gempy#100]
Hello!
I have a clarification question:
The documentation says that `lith = gp.compute_model(interp_data)` creates an array with formation information:

> Lithology block model solution:
>- Entry [0]: This array shows what kind of lithological formation is found in each voxel, as indicated by a respective formation number.
>- Entry [1]: Potential field array that represents the orientation of lithological units and layers in the block model.

When I look at `lith[0]`, it includes non-integer float values that are in between formation values. Is this normal? Thanks!

notebook [here](https://github.com/cfandel/gempy/blob/master/notebooks/prototype_notebooks/Chloe_Gottesacker/Gottesacker_geology_v4.ipynb), sections 118 & 119
exported csv file of `lith[0]` [here](https://github.com/cfandel/gempy/blob/master/notebooks/prototype_notebooks/Chloe_Gottesacker/lith.csv) for easier viewing

**Comment by Leguark** [comment]
Yes, that is black magic to do the calculations differentiable for AD. In principle the floats should be around the boundary. If they disturb you, you can always use round.
Probably in the future I will leave the option to choose black magic or normal discretization
