### ISSUE TITLE
Issue running GemPy_paper-model_topology notebook; no formation number for fault? 

### ISSUE THREAD

**Issue by two-phaseflow** [cgre-aachen/gempy#108]
Dear all,

First off, thanks for putting the time and effort into developing what is sure to be a very useful tool! I'm excited to learn how to work with gempy. 

I just wanted to bring to your attention to what is likely a trivial issue I've encountered while trying to go through the jupyter notebooks. If I execute the fourth block (```gp.set_series(geo_data, {'fault_serie1': 'fault1','younger_serie' : 'Unconformity', 'older_serie': ('Layer1', 'Layer2')},
              order_formations= ['fault1', 'Unconformity', 'Layer2', 'Layer1'], verbose=2) ```) but not the fifth (to specifically select 'older_serie' which is anyways commented out in the notebook), and then run the ``` gp.plot_data(geo_data)```, I get the following error: 

```python 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-56b55006c2f9> in <module>
----> 1 gp.plot_data(geo_data)

/anaconda3/lib/python3.7/site-packages/gempy/gempy_front.py in plot_data(geo_data, direction, data_type, series, legend_font_size, **kwargs)
    930 
    931     # TODO saving options
--> 932     return plot.plot_data(direction=direction, data_type=data_type, series=series, legend_font_size=legend_font_size, **kwargs)
    933 
    934 

/anaconda3/lib/python3.7/site-packages/gempy/plotting/visualization.py in plot_data(self, direction, data_type, series, legend_font_size, ve, **kwargs)
    139         # Change dictionary keys numbers for formation names
    140         for i in zip(self.formation_names, self.formation_numbers):
--> 141             self._color_lot[i[0]] = self._color_lot[i[1]]
    142 
    143         #fig, ax = plt.subplots()

KeyError: nan   
```

It seems that the problem is that there is no formation name or number associated with the fault, which is clear from table generated by running the next block (get_data). 

To be clear, if I run ``` geo_data = gp.select_series(geo_data, ['older_serie']) ``` this is not an issue. But anyways probably worth bringing attention to. 

FYI I just today did a clean install of a Python 3.7 conda environment on a Mac. Installed gempy using ``` pip install gempy ```

Regards,
Sam Scott (Reykjavik University)

**Comment by two-phaseflow** [comment]
Yup, that was it. Thanks. 

Maybe you want to edit the notebook file anyways since it is not transparent what the fault is called when the dataframe is created without inspecting the input data files.

**Comment by elimh** [comment]
Yeah, thanks for pointing that out, I just fixed it! :)  
At the moment we can only guarantee that the notebooks in the tutorial folder will work properly, but someone will probably take care of the other notebooks soon.
