### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ejhgeo** [cgre-aachen/gempy#113]
I have tried installing GemPy a couple of ways and am having some problems down the line. I am very new to programming and python in general, so your patience is appreciated. First, I installed gempy using 'pip install gempy' in a conda environment, which did not automatically install all dependencies as stated in the documentation (so I installed them manually), and it did not download the files needed for the tutorials, which I now know is a known issue. 

I then tried cloning the GitHub repository and installed gempy manually in a separate conda environment. While this did download all the necessary files to my home folder (outside the environment for some reason), the only things installed in my environment were .egg files (I don't understand what those are or how to access them). Trying to import gempy in a Jupyter Notebook linked with this environment did not work, as it did not seem to find gempy installed anywhere. It does not work in the base environment either. Jupyter does import the gempy I installed with pip, but again there are no tutorial files available and there are some other issues with numpy (which I have posted separately). 

With the manual install, why is it only installing egg files? and how can I get around this/expand these so that Jupyter will properly import gempy? Again, I'm very new to programming and terminal and such, so any explanation is helpful. Thank you.

**Comment by Leguark** [comment]
Mmm I definetly hope to work in the conda and docker distribution in the next weeks!  Cannot be so difficult to play with it, apologies for that.

First the solution. To import a package in python you have two options: 
(i) either you install it so it is move to the python folder (the PATH to this folder is already in the environment so when you do import gempy it finds it ) or
(ii) You add manually the PATH to wherever the package is at the beginning of the Jupyter Notebook in this case.
If you look at the gempy tutorials all of the them have these lines: 
import sys, os
sys.path.append("../..")

this means that we are adding to parent folders (i.e. the main gempy folder) to the enviroment. Therefore, **if you run the tutorials where they are you do not need to install gempy**. I hope you can check this.


The weird thing of your experience is that when you install gempy  manually only the .egg folder is copied. That is not normal. I will take a look at that. Thank you for the report!

Just let me know if that answer you

**Comment by cfandel** [comment]
I have an addendum to this question - when trying to install GemPy on a new computer, in a new environment (note: I am using conda to manage my environments), I'm able to install it using 
`pip install gempy`
 I get the message `Successfully installed gempy-1.15`  and gempy appears in the list of packages in my environment. But when I try to import the package in a Jupyter Notebook, using 
`import gempy`
I get the following message
`ModuleNotFoundError: No module named 'gempy'`

Any tips? Should I just wait for the conda distribution? Thanks!

**Comment by Leguark** [comment]
That is pretty weird. When you install gempy using pip, the path is added automatically. Are you sure you are installing gempy in the same python environment that later you use to run the Jupyter notebook?

**Comment by cfandel** [comment]
Yeah super weird. I needed to clean up a bunch of other stuff anyways, so I ended up uninstalling Anaconda entirely, reinstalling it from scratch, and creating a new environment. I made sure to install pip into the new environment rather than just into the base environment, and then it worked fine.

**Comment by cfandel** [comment]
More install issues....
when I run gempy, I get theano-related error messages. So I tried uninstalling theano from the environment, then installing mingw libpython m2w64-toolchain, then reinstalling theano using conda install (as recommended in the getting started doc).
Installing theano results in anaconda prompt crashing every time I try to activate the environment I'm working in. There seems to be some sort of major problem with getting theano installed in a way that gempy can use, but I can't figure out how to solve it.
Any ideas?

**Comment by cfandel** [comment]
notes: 
-installing gempy alone without pre-installing theano does not work - I get theano errors when I try to import gempy in python. 
-theano help suggests installing vs2015_win-64 first - this also causes anaconda prompt to crash

**Comment by SimonVirgo** [comment]
I remember coming across a similar problem on a windows machine a while ago. It seems to be caused by Visual Studio. Try locating the vs2015_compiler_vars.bat and delete/rename it. maybe this will help...

**Comment by cfandel** [comment]
It seems to work if I do the following:
- uninstall vs2015_win-64
- conda install mkl, mkl-service, and mingw libpython m2w64-toolchaininstall
- set a system variable MKL_THREADING_LAYER = GNU
- pip install gempy

**Comment by cfandel** [comment]
The following allows gempy and theano to be installed without crashing:
- uninstall vs2015_win-64
- conda install mkl, mkl-service, and mingw libpython m2w64-toolchaininstall
- set a system variable MKL_THREADING_LAYER = GNU
- pip install gempy

GemPy does run, but I get the following warning:
`WARNING (theano.gof.compilelock): Overriding existing lock by dead process '6048' (I am process '2200')`

It doesn't seem to interfere with the model running, but it is a little worrisome nonetheless.

**Comment by cfandel** [comment]
More install questions...sorry!
First, congrats on releasing GemPy 2.0!
Second, I see on your shiny new website here https://www.gempy.org/get-gempy that I should now be able to use conda to install gempy, with `conda install gempy`
However, when I try this, I get a package not found error, and gempy doesn't show up when I search anaconda.org.
Is the conda installer not set up yet? Should I stick to pip? Thanks!

**Comment by Leguark** [comment]
I just link the answer to the other issue #172 just adding that hopefully we have the conda installation  and also a non-developers release of pip within the next two weeks
