### ISSUE TITLE
input data format

### ISSUE THREAD

**Issue by ejhgeo** [cgre-aachen/gempy#121]
I have a few issues related to conventions used for input data:

1) My depths are measured positive downwards. When plotting my interfaces, the plot is upside down. Is there a way to reverse the Z axis with 'gp.plotting.plot_data'? I need to make sure that GemPy knows my depths are positive downwards. Also, are there any other ways to manipulate plots when using this function?

2) How exactly is polarity defined for the orientations? I have strikes (azimuth) and dips, and I'm assuming polarity is simply the azimuthal direction of dip (e.g. dipping due east is 90 E of N), but I wasn't sure. When I plot the orientations with 'gp.plotting.plot_data' as in the tutorial, large irregular black lines show up, not arrows as in the output from the tutorial data.

Thanks. Any info on how to better manipulate the plots and define input data is welcome!

**Comment by WesleyTheGeolien** [comment]
I am not fully aware with all the ins and outs of gempy but is this what the polarity column doesin this example?
https://github.com/cgre-aachen/gempy/blob/master/notebooks/input_data/tut_chapter1/simple_fault_model_orientations.csv

Else maybe it is possible using the pandas dataframe to multiple the depths column by -1 to flip the data, This seems like more of a 'workaround' and 'data cleaning' though ....

**Comment by Leguark** [comment]
thank you for the help @WesleyTheGeolien
