### ISSUE TITLE
computation time

### ISSUE THREAD

**Issue by ejhgeo** [cgre-aachen/gempy#123]
I have a very high resolution data set with a lot of points. I am wondering, for N as the number of interface points, how does the CPU time grow with N? Is there a limit to the number of points one can reasonably use with GemPy?

**Comment by Leguark** [comment]
so the first important aspect is to set the theano flag to "fast_run" when you create the interpolation_data. As rule of the thumb the maximum I have deal with in one run is around 2000 input data (orientations count as 3) and 1 million voxels (something around 100*100*100). For each series we are creating a matrix n_input_points*n_voxels. Those number should be equivalent to 4-5 Gb of memory ram. beyond that point I start to loop the grid (so we sacrifice time for memory).

If your model is much bigger than that I recommend you to split manually the grid (just use `compute_at` passing a numpy array) and then combining all together to have a better control of it.

We have quite a few projects running internally to improve the grid and other cases of high data density but they are going to take several months until they get online.
