### ISSUE TITLE
add plot section kwarg to flip Y-axis (for negative Z extent)

### ISSUE THREAD

**Issue by pytzcarraldo** [cgre-aachen/gempy#126]
![image](https://user-images.githubusercontent.com/17277800/54072692-9be06e00-427e-11e9-8262-2bb568ce0b15.png)

add plot section kwarg to flip Y-axis (for negative Z extent) for correctly oriented section plots

**Comment by Leguark** [comment]
are you going to do it? Otherwise write a better description and set a help wanted or this will be changed @elimh ?

**Comment by pytzcarraldo** [comment]
I'll take care of it by next week ;-)

**Comment by Leguark** [comment]
this is closed on your last PR isnt it?

**Comment by AndrewAnnex** [comment]
@Leguark looks like I am having this issue currently, my plot is upside down 
![example](https://user-images.githubusercontent.com/2126916/64028320-f70a6380-cb31-11e9-95d4-55e53f9d80a3.png)

**Comment by Leguark** [comment]
Yes, I had the same problem the other day. The fix will go live in the next minor patch.

for the time being you can just add to the cell
plt.gca().invert_yaxis()
