### ISSUE TITLE
import point data report an error

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#128]
import point data the system said:
AssertionError: One or more columns do not match with the expected values Index(['x', 'y', 'z', 'formation'], dtype='object')
 I wonder what is gempy's requirement for point data?
Can someone answer?
thanks very much

**Comment by Leguark** [comment]
I think it is simply that x, y and z must be capitol letters XYZ

**Comment by lllxllll** [comment]
Oh!Thank you very much! Thank you for your reply！I am a Chinese Postgraduate.I am testing the code in the first chapter，I still have a question that I only get the data as followed,but there is no azimuth and dip ,can I build the model without azimuth and dip?And What are the requirements for the interface data and orientation data?  Thank you again for your reply.You are really enthusiastic！！！！Thank you!

X | Y | Z | formation
666285 | 2573431.4 | 658 | P1m
666087 | 2573670.3 | 599 | P1q
665843.6 | 2573964.1 | 602 | C3
665699.4 | 2574138 | 710 | C2d
665436.5 | 2574455.1 | 641 | C1y
664922.8 | 2575075 | 620 | D3l
664733.6 | 2575303.2 | 734 | D2d
664235.5 | 2575904.1 | 860 | D1y
664086.7 | 2576083.8 | 822 | D1y
663327.9 | 2576999.2 | 1110 | D1y
668613.8 | 2573755.7 | 770 | T1m
668156.9 | 2574307.1 | 697 | T1m
667455.6 | 2575153.2 | 674 | P1m
667294.6 | 2575347.4 | 735 | P1q
666997.7 | 2575705.6 | 616 | C3
666770.2 | 2575980.1 | 617 | C2d
666552.4 | 2576242.8 | 648 | C1y
666298.2 | 2576549.6 | 623 | D3l

**Comment by Leguark** [comment]
It is necessary at least one orientation per series.
For your words I deduct that you installed gempy via pip. I recommend you to clone it from the repository better. If you do so the input data for the tutorials are there and you should be able to simply run them directly

**Comment by lllxllll** [comment]
Thank you very much！！！ You gave me a lot of help.
I have solved the problem of importing data.
But I still have a question that I have 1117 point data ,Can gempy handle so much data?There are 4 series, if only four orientation data are feasible?

**Comment by Leguark** [comment]
the minimum is one orientation for series. 1k surface points are still manageable (technically any amount but the computational time scales quadratically)
