### ISSUE TITLE
data

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#129]

**Comment by lllxllll** [comment]
when I test this code
 %matplotlib inline
gp.plot_data(geo_data, direction='y')
the system said
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'
some point data's Z is '0',Is there no ‘0’ value in the data?

**Comment by Leguark** [comment]
That is that the coordinates (the numbers) that you are importing are not recognize as number by python for some reason. I am not sure what dtype('O') means to be honest. Just google how to transform that data type to float numbers

**Comment by lllxllll** [comment]
Thanks a lot!  When I run this code:gp.plot_section(geo_data, fault_block[0], cell_number=25, plot_data=False)
the system said :IndexError: index 0 is out of bounds for axis 0 with size 0
I can't understand what is going on here. Is there any problem with my data?
Thank you again for your help.

**Comment by Leguark** [comment]
Please just follow the bug report template (just set) or this guidelines (https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) for a better way to create issues.
