### ISSUE TITLE
parameter question

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#134]
And can you please explain what this parameter  "lith_block[1] "means?
The difference between the two parameter  "lith_block[1] " and  "lith_block[0] "？
gp.plot_scalar_field(geo_data, lith_block[1], cell_number=5, N=100,direction='y', plot_data=False)

**Comment by pytzcarraldo** [comment]
In the current master branch version lith_block contains two arrays: lith_block[0] are the actual lithology values, and lith_block[1] is the scalar field. That's why you pass lith_block[1] to the plot_scalar_field function.

**Comment by lllxllll** [comment]
If there is no fault ,Can I write the code as this: lith_block=gp.compute_model(interp_data)

**Comment by Leguark** [comment]
if there is not fault, gempy will return None
