### ISSUE TITLE
Chapter 2 error in new_grid.set_regular_grid(geo_data.extent,[res, res, res])

### ISSUE THREAD

**Issue by bluetyson** [cgre-aachen/gempy#138]
AttributeError                            Traceback (most recent call last)
<ipython-input-30-1bff567b7985> in <module>
      3 
      4 # Create a new grid object with the new resolution
----> 5 new_grid.set_regular_grid(geo_data.extent,[res, res, res])
      6 
      7 # Setting the new grid to the geodata

AttributeError: 'GridClass' object has no attribute 'set_regular_grid'

**Comment by Leguark** [comment]
Please just follow the bug report template (just set) or this guidelines (https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) for a better way to create issues.
