### ISSUE TITLE
i can not run the first example,the fault_block is null,this parameter has nothing.

### ISSUE THREAD

**Issue by nanlou-zc** [cgre-aachen/gempy#140]
lith_block, fault_block = gp.compute_model(interp_data)
fault_block has nothing.so i cannot do next work

**Comment by nanlou-zc** [comment]
ok，i have solved this problem by using the latest version of gempy.
thank you

**Comment by Leguark** [comment]
yes, sorry for that. We are preparing a big release and the pip version is lacking serious love from our side since a while.
