### ISSUE TITLE
how to use data of geomodeller?

### ISSUE THREAD

**Issue by nanlou-zc** [cgre-aachen/gempy#143]
now i want to use the data myself to get a model,and i know gempy can use geomodeller's data,but i cannot find an example for it.could you give me one?
Is there a document to describe what each gempy python file does?or entire framework

**Comment by Leguark** [comment]
most of the tutorials read data csv as Geomodeller 3D export it. Export 3D data I think is the Geomodeller functionality. The sequential pile you would have to set it up by hand.
We were also working to read directly the xml file of GeoModeller but I am sure what is its state in the master branch, @elimh  can you help us here?

**Comment by nanlou-zc** [comment]
Thanks for your reply.
So now the geomodeller module is not in use yet, right?
I need to program myself to implement this function——convert geomodeller data to gempy data,right?

**Comment by Leguark** [comment]
Geomodeller has a function to export csv files with the input data in the format that GemPy reads. 
Furthermore we have the geomodeller module which tried to read also the sequential pile and things like the extent and so. This functionality is the one I am not sure if is running right now

**Comment by nanlou-zc** [comment]
oh thank you

**Comment by elimh** [comment]
Hey, sorry for the late reply! There is a module for reading the geomodeller xml, but it is currently not in the master branch. I will check whether or not it is working properly tomorrow and, if yes, push it to the master

**Comment by elimh** [comment]
Okay, so the module is in the current state not really working properly. I will have a look at it, but this can take a while.
Thus, I would recommend exporting the interface and orientation data frames of your project in geomodeller (header 'export' and then '3D structural data'). Then you can create the geo_data object with these two data frames. In the next step, you have to define the sequential pile in accordance with the pile in geomodeller, but then you should be good to go!

**Comment by nanlou-zc** [comment]
ok，thank you very much!I will try it ,thank you again.

**Comment by Leguark** [comment]
This question is linked to this issue which I am unsure if is solved @elimh  #18
