### ISSUE TITLE
Can DEM data be used as a constraint in model computing in current version?

### ISSUE THREAD

**Issue by Leocug** [cgre-aachen/gempy#144]
I find a class Named DEM which deal with the surface constraint of geological model. But is it work now in the model computing? if yes, where is the example? Thank you.

**Comment by elimh** [comment]
Hey!
yes, there is a class that deals with raster formats. It includes the topography into 2D plots of the model and allows to compute a map at the surface coordinates. The loading of raster files relies on GDAL, so it is necessary to have it installed. 
Unfortunately, the topography is still under development and there is no documentation yet, but to see how it works maybe this notebook helps a bit: 
https://github.com/cgre-aachen/gempy/blob/development_elisa/notebooks/prototype_notebooks/ElisaThesis/Model%203%20.ipynb
In general, we are currently working a lot to improve the functionality of gempy, so there will be better documentation and plotting options, soon!

**Comment by Leocug** [comment]
Thank you for guide, Elisa。 Looking forward to the coming new version of Gempy.

**Comment by Leguark** [comment]
gempy 2 beta is already in the master branch (and in pre-release in pip), and the functionality for topography up and running
