### ISSUE TITLE
How to plot the whole 3d potential field model?

### ISSUE THREAD

**Issue by Leocug** [cgre-aachen/gempy#145]
Is there a example to plot the whole 3d potential field model?

**Comment by Leguark** [comment]
Plotting the scalar field in 3D is something we did not implemented. I saw that plotly has the to plot 3d contour fields. The easiest way that comes to my mind is to do marching cubes in several scalar field values. You can check in gp.get_surfaces how we call the marching cube function of scikit image.

Also take into account that in the current version we overprint all the scalar fields in one (in case of unconformities). In the upcoming 1.2 we will retrieve all the full scalar fields for each series.

Looking forward to see if you get some progress in here!
