### ISSUE TITLE
Can Gempy calculate the 3d geological bodies of potential field？

### ISSUE THREAD

**Issue by Leocug** [cgre-aachen/gempy#146]
Gempy is so powerful as Geomodeller. Can Gempy calculate the 3d geological bodies automatically of potential field as Geomodeller？

**Comment by Leguark** [comment]
I am not sure what do you mean in this one? If you meant something like dikes in GeoModeller 3D, no, we do not have the option yet. We are working though in a way to create low parametric close surfaces but it will need some more time in the oven.

However, you can always get close surfaces by making a own series and pointing the orientations either outwards or inwards

**Comment by Leocug** [comment]
Gempy can get geological surfaces now. But sometimes we want to obtain the closed bodies for every formation. Does Gempy plan to support this?

**Comment by Leguark** [comment]
For volumetric meshing the best option out there would be to couple GemPy with cgal. We are doing some progress in this direction but any help is welcome!
