### ISSUE TITLE
How to toggle the GPU switch of theano in gempy?

### ISSUE THREAD

**Issue by Leocug** [cgre-aachen/gempy#147]
As we know, python is slower than c++ in cpu mode. I want to use the gpy to accelerate the cokriging algorithm. Can anybody tell me HOW to open the GPU mode of theano in gempy?

**Comment by Leguark** [comment]
If you installed theano properly by default you are using already cython code but yes, with a good GPU we have speed up x20 depending on the models.
You need to activate the GPU for theano http://deeplearning.net/software/theano/tutorial/using_gpu.html
If you get it running for the example they have it there, it will work in GemPy as well.

If everything works out fine, you would just need to install cuda drivers and change the theano flag in the config flag from device='cpu' to device='gpu'.

I think online there are way better guides of how to use the gpu in theano that anything I can write you here but if you get stuck just let me know
