### ISSUE TITLE
Is it have other Variance function model instead of cuba?

### ISSUE THREAD

**Issue by nanlou-zc** [cgre-aachen/gempy#150]
If so, how do I use other model?
And i use the sample data(CaseStudyA) of geomodeller to model by gempy,the result of gempy is not consistent with geomodeller.What caused this situation?

**Comment by Leguark** [comment]
Right now only cubic covariance is possible. It is not very complicated to add a different one if you want. You just need to go to the theano_graph.py module and change the terms in the specific covariance methods. It would be a nice contribution!

Regarding the CaseStudy A, I have never tried but usually disparities are due to the default kriging parameters (the number of universal eq is a classical) or if there is well data in the model, geomodeller treat them as "soft data". Without seeing the model I cannot say more so it would be great if you upload it to github

**Comment by nanlou-zc** [comment]
![1](https://user-images.githubusercontent.com/49156720/55781235-4812b000-5adc-11e9-9bbc-3323c50145b0.png)
![2](https://user-images.githubusercontent.com/49156720/55781237-48ab4680-5adc-11e9-9c2a-5e9773dcb95c.png)
this is the model of CaseStudyA using gempy,and the result looks a bit strange.

**Comment by Leguark** [comment]
can you push the notebook somewhere (ideally in a fork of gempy in you repository).

 However I think the problem in the intrusion is mainly a marching cubes problem artifact (I have a pull request in scikit-image to solve it in the next release)

The extra folding of the green layer I would have to see the code

**Comment by nanlou-zc** [comment]
import gempy as gp
import numpy as np
import time
import matplotlib.pyplot as plt
geo_data = gp.create_data([100000, 110000, 2000000, 2010000, -8000, 2000], [80, 80, 80],
                          path_o="test_Foliations.csv",
                          path_i="test_Points.csv")

gp.set_series(geo_data, {"Fault_Series":'SW_NE_Fault',
                         "i_Series":'Granite',
                         "Strat_Series": ('UpperCover','MiddleCover','LowerCover')},
                       order_series = ["Fault_Series", "i_Series","Strat_Series"],
                       order_formations=['SW_NE_Fault',
                                         'Granite',
                                         'UpperCover',
                                         'MiddleCover',
                                         'LowerCover',
                                         ], verbose=0)


t0 = time.time()
interp_data = gp.InterpolatorData(geo_data, u_grade=[1,1], output='geology', compile_theano=True, theano_optimizer='fast_compile')
lith_block, fault_block = gp.compute_model(interp_data)
t1 = time.time()
print("%d seconds" % (t1 - t0))
ver, sim = gp.get_surfaces(interp_data,lith_block[1], fault_block[1], original_scale=True)
gp.plot_surfaces_3D(geo_data, ver, sim, alpha=1)
plt.show()



This is the full code of it.And the data is from geomodeller CaseStudyA.Thank you very much.
[data.zip](https://github.com/cgre-aachen/gempy/files/3058709/data.zip)
