### ISSUE TITLE
Why did the speed slow down after I used the GPU?

### ISSUE THREAD

**Issue by nanlou-zc** [cgre-aachen/gempy#151]
According to theano's tutorial, I successfully called the GPU for calculations, and I can apply the example given by the official website. The effect is obvious. But in gempy,the speed slow down after i used the GPU.

**Comment by nanlou-zc** [comment]
Is it necessary make some settings in gempy?

**Comment by Leguark** [comment]
First do you have the theano_optimization to 'fast_run'?
Depends on the gpu and the model. the improvement is better the bigger the model is

**Comment by nanlou-zc** [comment]
theano_optimization,i use Whether fast_compile or fast_run,the speed are all slow down.
Run the first example,cpu takes 23 seconds and gpu takes 62 seconds.

**Comment by Leguark** [comment]
23 secs in fast run is quite a lot. Maybe you are running out of memory or other bottle neck
