### ISSUE TITLE
fault

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#152]
gp.set_series(geo_data, {"Fault_Series":'Main_Fault',
                      "Strat_Series": ('Sandstone_2','Siltstone', 'Shale', 'Sandstone_1')},
                       order_series = ["Fault_Series", 'Strat_Series'],
                       order_formations=['Main_Fault',
                                         'Sandstone_2','Siltstone', 'Shale', 'Sandstone_1',
                                         ], verbose=0)
Is this means that the "Fault_Series" and "Strat_Series" can not use the same formation name .

**Comment by Leguark** [comment]
No, series are sets of "formations" (of surfaces in general), therefore a surface can only belong to one series. Basically all surfaces of a series are interpolated together
