### ISSUE TITLE
Comments on GemPy function from BGS colleagues

### ISSUE THREAD

**Issue by metazool** [cgre-aachen/gempy#169]
My colleague Richard Haslam in BGS Geoanalytics and Modelling has been doing some evaluation of GemPy and had the following comment, not sure if github issues are the best place but it would be good to know whether these limitations are just in our understanding!

"I guess one of the biggest limitations I have found to date is the inability to model faults that terminate within the model volume and not on another fault or the boundary of the model. This is a similar problem that I have found with Leapfrog. Additionally, when the surfaces are created they include the stair step grid along the fault and therefore there is quite a bit of tidying up required before the models can be used for simulations. "

**Comment by Leguark** [comment]
Thank you for the feedback. Regarding to the faults, in GemPy 2.0 we can terminate faults on other faults or uncomformities as well as support finite faults. Possibly, we will need to better document this behaviour

Regarding stair step grids, yes, as long as we discretise the models into regular grids we will get that effect. We have currently a student starting to couple gempy with cgal which is the obvious way forward to run proper simulation in GemPy models

**Comment by metazool** [comment]
Thank you for this @Leguark - and for all the effort you are making. I will pass this along when we return to working with GemPy.
