### ISSUE TITLE
Compute the scalar field

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#171]
How to compute the scalar field and how to export scalar field value?

**Comment by Leguark** [comment]
In gempy 1, the scalar field is stored in the lith_block[1] and is simply a numpy array. 
In gempy 2 the scalar fields of each series are stored on geo_model.solutions.scalar_field_matrix

**Comment by lllxllll** [comment]
Thank you vvery much, I have another question, how to  compute the potential field at  the interpolation points and export the potential field value
