### ISSUE TITLE
installation issues with v 2.0

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gempy#172]
I would like to install gempy v2.0.

`conda install gempy` gives the following error:
`PackagesNotFoundError: The following packages are not available from current channels`
and when I search for gempy on anaconda.org I can't find it.

`pip install gempy` installs v.1.15

Does this mean my only installation option is to manually clone the current GitHub repository?
Thanks!

PS: Are the tutorials and doc at gempy.org for v1 or v2?

**Comment by Leguark** [comment]
hey Chloe, you can use pip but it is a development version with... 
pip install gempy==2.0b0.dev1

the tricky bit are the requirements, I think pip does not install them (definitely not the optional) and until the next release of scikit image we need to use the fork on my repo so... for the requirements you can dowload requirements.txt and optional-requirements and do:

pip install -r requirements.txt

and 

pip install -r optional-requirements

Regarding the tutorial in gempy.org, yes they are for the v2 and they are also in the master branch if you wanna run them.

Sorry for the pain to update. I hope it will be worth it!

**Comment by cfandel** [comment]
Thanks!
Was able to install OK and am converting my old model to the new version. Really looking forward to using the updated faults!
