### ISSUE TITLE
TypeError: set_series() got an unexpected keyword argument 'order_series'

### ISSUE THREAD

**Issue by tgautam03** [cgre-aachen/gempy#178]
I am just following the tutorial steps and I encountered this error. I have no idea why I am getting this?

**Comment by tgautam03** [comment]
# Assigning series to formations as well as their order (timewise)
gp.set_series(geo_data, {"Fault_Series":'Main_Fault',
                      "Strat_Series": ('Sandstone_2','Siltstone', 'Shale', 'Sandstone_1')},
                       order_series = ["Fault_Series", 'Strat_Series'],
                       order_formations=['Main_Fault',
                                         'Sandstone_2','Siltstone', 'Shale', 'Sandstone_1',
                                         ], verbose=0)

# unconformity model:
#gp.set_series(geo_data, {"Fault_Series":'Main_Fault', "Unconf_Series":'Carbonate',
#                      "Strat_Series": ('Sandstone_2','Siltstone', 'Shale', 'Sandstone_1')},
#                       order_series = ["Fault_Series", "Unconf_Series", 'Strat_Series'],
#                       order_formations=['Main_Fault', 'Carbonate',
#                                         'Sandstone_2','Siltstone', 'Shale', 'Sandstone_1',
#                                         ], verbose=0)

**Comment by tgautam03** [comment]
`gp.set_series(geo_data, {"Fault_Series":'Main_Fault',
                      "Strat_Series": ('Sandstone_2','Siltstone', 'Shale', 'Sandstone_1')},
                       order_series = ["Fault_Series", 'Strat_Series'],
                       order_formations=['Main_Fault',
                                         'Sandstone_2','Siltstone', 'Shale', 'Sandstone_1',
                                         ], verbose=0)`

**Comment by elimh** [comment]
Hey! :)
The problem is that we just released a new version of GemPy, which also renamed the function names a bit. Unfortunately, not all tutorial notebooks have been updated to the new version yet, including the notebook you tried to run. Therefore, I would recommend using only the notebooks in the tutorials folder until we have updated all other notebooks as well. Sorry for the inconvenience!

**Comment by Leguark** [comment]
yes, which version of gempy and which notebook are you trying to use?

**Comment by elimh** [comment]
> 
> 
> yes, which version of gempy and which notebook are you trying to use?

 	examples/Model 6 - Unconformity.ipynb

**Comment by tgautam03** [comment]
I am using v2.0 and I was attempting the tutorial from gempy website. 
Now I am using tuts provided with the v2.0 and it's working fine.
Thanks a lot...

**Comment by Leguark** [comment]
yep sorry for that, we are in the middle of way too many changes. We are also moving the website to https://www.gempy.org/ I will try to delete the other one to avoid mistakes

In any case, glad that you got it running! Looking forward to the results of your project
