### ISSUE TITLE
Why rescale the data in this way?

### ISSUE THREAD

**Issue by nanlou-zc** [cgre-aachen/gempy#181]
` new_coord_interfaces = (geo_data.interfaces[['X', 'Y', 'Z']] -
                                centers) / rescaling_factor + 0.5001`
in this way，the data will in （0.25,0.75）but not (0,1),could you tell me why?
and i dont know why calculate range_var and c0 in this way?
`range_var = np.sqrt((self.geo_data_res_no_basement.extent[0] - self.geo_data_res_no_basement.extent[1]) ** 2 +
                                    (self.geo_data_res_no_basement.extent[2] - self.geo_data_res_no_basement.extent[3]) ** 2 +
                                    (self.geo_data_res_no_basement.extent[4] - self.geo_data_res_no_basement.extent[5]) ** 2)`
`c_o = range_var ** 2 / 14 / 3`

**Comment by Leguark** [comment]
between 0, 1 will be the longest possible distance, not the ortogonal distances. 

The default values of range and covariance at 0 are chosen to be as large as the maximum distance of your input data but it is rather arbitrary. Depending on the model other values would be more suitable. I recommend you to take a look to the GemPy paper and its references if you really want to get into the theory
