### ISSUE TITLE
return fault block array

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gempy#188]
In order to use GemPy with the karst evolution simulator that I am using, I need a 3D array of 1s and 0s indicating which cells have a fault in them and which cells do not.
I think you started doing this by shifting the fault blocks to see which cells are different after the shift?
I'll then export that array as a GSLIB file.

Thanks!

**Comment by Leguark** [comment]
Here you have a small example how to do it

https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-9b_Fault_relations.ipynb

it could use some added functionality like looping over all faults and things like that but I guess that is something you can do without dealing with annoying GemPy logic :D Just let me know if you need something else from me for this topic.
