### ISSUE TITLE
ch2-1-Gravity.ipynb loaded data densities confusion

### ISSUE THREAD

**Issue by divad-nhok** [cgre-aachen/gempy#190]
**Problem**
In looking at ch1-2_Data_Manipulation.ipynb & ch2-1-Gravity.ipynb it is not clear to me how a set of "surface values" are mapped to a given interpolator or a given likelihood. In ch2-1-Gravity.ipynb I'm _guessing_  that the value_0 series are the densities of each surface used in the gravity forward model at some point.
Down the modelling line, it is also not clear to me where this data is called/invoked in the forward modelling process.
Additionally, if I was thinking about adding another sensor model, it is not clear to me how I would map a set of "surface values" to a specific sensor model.

**Potential solutions**
In ch1-2_Data_Manipulation.ipynb, make clear how the "surface values" are used by GemPy in "downstream" function calls.
In ch2-1-Gravity.ipynb, build the whole model from scratch so the user can clearly see what's going on, instead of loading the model in.
Naming conventions could also potentially be improved for various "surface values", so that when reading the code it would be obvious when the "surface values" are being used in the modelling process. 

**Alternatives**
I've tried reading the theano_graph_pro methods and properties to understand what data is being used, but these are difficult to read as they mainly consistent of index based accessing of lists and arrays.

**Additional context**
In ch2-1-Gravity.ipynb, I'm assuming value_0 are the data density values for each surface?
<img width="1135" alt="gempy-grav-notebook" src="https://user-images.githubusercontent.com/3292906/59984615-4f733f80-966f-11e9-89c7-2bc943ab2e23.png">

**Comment by Leguark** [comment]
Yes, all the gravity tutorials need much more documentation. I will try to give a short description here while the proper documentation gets ready:
I will take the name of the objects of the tutorials for clearness. 

1) By default the label given to the geo_model.solution.lith_block and geo_model.solutions.block_matrix (when we call gempy.compute_model(geo_model) are the id on the Surfaces object

2) We can add labels by using geo_model.add_surface_values (you can add a str to name the column properly, like 'density'): this will add a column to the df but more importantly will add a new vector to   
geo_model.solution.lith_block and geo_model.solutions.block_matrix (axis=0) with the value e.g.

geo_model.solution.lith_block: [[1, 2,2, 5, ....,]
                                                       2.61, 2.92, 2.92, 2.61]]

All this discretisation of space accordingly to the scalar field is happening within the theano code

Finally, the model is created on gempy/notebooks/examples/Greenstone

Was I able to clarify it a bit?
