### ISSUE TITLE
TheanoGraphPro init hardcodes gravity/density properties

### ISSUE THREAD

**Issue by divad-nhok** [cgre-aachen/gempy#191]
**Problem**
The TheanoGraphPro class init hardcodes gravity/density properties:

```
class TheanoGraphPro(object):
    def __init__(self, optimizer='fast_compile', verbose=None, dtype='float32', ):
        ...
        self.tz = theano.shared(np.empty(0, dtype=dtype), 'tz component')
        self.density_matrix = T.vector('density vector')
```

**Solution**
TheanoGraphPro seems like it's a general class that could be used for any sensor model. Its property names should be generalized to reflect that and allow further sensor model integrations.

**Describe alternatives you've considered**
The current property names could be used, but this would decrease code legibility/readability.

**Comment by Leguark** [comment]
Hey David, thanks for your detail issues. Sorry for taking a while to answer but there were holidays and before we had a visitor. Now I am back to routine.

Regarding the question, on theano we need to explicitly create each parameter (for the symbolic graph), therefore if eventually we want to do join inversion grav/mag we need to have both variables in the frame. I agree that we could create a more functional approach to the creation of the graph, but I have the feeling that the graph themselves end up being a quite unique and I am not sure how worth it is generalizations on this direction. 

The way I have it implemented right now (and after some prototyping I did not find anything better) is having that single class which methods create different pieces of the symbolic graph at compilation time. For magnetics we would need to add the logic to compute the forward magnetics and passing the results of compute_final_model:

<img width="802" alt="Screenshot 2019-06-24 at 17 35 58" src="https://user-images.githubusercontent.com/12543466/60032293-8dd82100-96a6-11e9-90f1-a64451b70457.png">

In any case, I think that the first prototype is better to do it in numpy retrieving the results from theano via gempy.compute_model(geo_model). What do you think?

**Comment by divad-nhok** [comment]
Not sure I quite get your diagram and explanation. But based on what you wrote, my initial thought in keeping the structure you've enumerated would be to subclass TheanoGraphPro for every sensor and every combination of sensor. E.g. separate subclasses for grav, mag, grav-mag, etc. That way you're always creating the sensors in the same graph (frame?) but still reusing the TheanoGraphPro code? Let me know if what I said makes sense or I missed the mark - don't quite know how Theano works and what you mean by having both variables in the same frame.

**Comment by Leguark** [comment]
(not my best diagram...)

yes, makes a lot of sense. That is very similar to what I tried to do on theano_kriging.py and theano_export.py during two weeks and I failed  spectacularly :D 

The problem I had is that when we  pass the 'graph' to the theano compiler it really need to find all pointers to all the nodes and partly because of how python handles pointers at some point it was a really pain. That was the reason why I went to the original design of having all in the same frame. So answering your question, yes, I think can be done and it would be the proper way but it is not trivial.

Also, we are planning to port gempy to TensorFlow (and probably also to numpy) in the following months (end 2019 beginning 2020) and for what I have seen TensorFlow is more Pythonic in their constructors

**Comment by divad-nhok** [comment]
Wow, interesting to hear that you have to be so careful about initialising all the objects within the same object. Getting the Theano computational graph working correctly sounds non-trivial. I guess ideally you wouldn't repeat the TheanoGraphPro code for every object, but for extreme convenience TheanoGraphPro could just be duplicated for each sensor model with corresponding properties and methods for each of the various sensor models. But yeah, feels a bit uhhh "non-best practice" to just duplicate an entire class.

**Comment by Leguark** [comment]
Before you read any further, I think we should try to write the sensor models in numpy using the gempy interpolation solution (geo_model.solutions.lith_block) as input and leave the translation to theano (or tensorflow) for later.  In this way, you could make a quite independent module from the core.

Take into account that the TheanoGraphPro is a class to **generate** graphs so we do not need to duplicate the whole class. Different methods gives you different pieces of the graph. If you look the compute_forward_gravity method, within it I have compute_final_block that in turn calls other method all the way to the input of the graph.

The way I would do it (in principle) is as you explain creating a gempy/core/interpolator.py:InterpolatorMag() with each own piece of the graph. However if we want to allow joint inversions probably the best way would be to combine all the physic engines in one graph and then in run time select which parts of the graph gets evaluated (similar to what I have in compute_a_series for the tectonics).

Also another thing I did not explain you yet and it is quite weird too is that the theano code we use it for automatic differentiation so the constants we can just precompute it and added to the graph once. In the case of gravity we have:
G = tz*densitity*volume

where tz is the decomposition of the component z of the vector which link each cell and the device. From these 3 parameters tz and volume are constant from iteration to iteration (if you do not change the grid) and therefore I can precompute it (Now I do it in the grid class which propably does not make too much sense) and added to theano as a shared variable (which do not affect the Jacobbian).

**Comment by Leguark** [comment]
This has been solved in the last restructure of theano. Now the type of outputs theano return is controlled by a list of strings
