### ISSUE TITLE
Refactor series to stack and geo_features

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#192]
Rename series to a more accurate name.

This is the current state: series for the object and the column property

<img width="1250" alt="Screenshot 2019-06-26 at 10 05 45" src="https://user-images.githubusercontent.com/12543466/60162539-06032b80-97fa-11e9-8562-59b86b1a83bb.png">

**Suggestion**

1 - Changing the name of the object to geo_stack since its main goal is to set the order of computation of the scalar fields
2 - Refer to each member of the object as geo_feature 

<img width="1253" alt="Screenshot 2019-06-26 at 10 07 56" src="https://user-images.githubusercontent.com/12543466/60162746-727e2a80-97fa-11e9-94ef-c3a428fe6aaf.png">

thoughts?

**Comment by elimh** [comment]
I like the idea of renaming it, but I think if you call them "geo_stack", it could be a bit repetitive with the word geo. How about just calling it "stack" or "bundle" (with or without surface)?
Also, I don't think the term geo_features is really clear. I would call it "relative age" or something like that. But that is just my opinion :)

**Comment by lachlangrose** [comment]
I don't know about geo_stack or stack.. Let me have a think about it. This is really just a graph that repersents the geological topology between the different things in the model....

It depends what you try and represent with the "series"/features class. You could have multiple fields that are the same age describing a different geological feature - so I think age is not enough. Age is a property of a feature.

**Comment by Leguark** [comment]
This is the strict order of interpolation of different scalar fields - which 95% of cases correlates to the geological timing - and the type of scalar field it is. Some argument for stack is that it is so no intuitive that people needs to check the documentation :D 

Features is vague but considering that they can be (so far) stratigraphic series, faults and folds)
, we need something a quite general term

**Comment by lachlangrose** [comment]
But different geological features probably should be daughter classes of the parent class.... so a fold inherets some things from a geological feature... etc. I think it realy depends how object oriented the code is....

**Comment by Japhiolite** [comment]
I'm with elisa that one can skip the "geo_". And looking strictly at the model without its geological meaning, faults, folds, stratigraphic units would all be equally treated _model_ features, right?  

But I don't really understand why change from _series_ to something else in the first place. Because object and property have the same name? 
In my opinion, _series_ is advantegeous to _stack_ (for example) as the name is already the [geoscientific definition](https://en.wikipedia.org/wiki/Series_(stratigraphy)). And one could argue that _stack_ is confusing as well for people who normally process seismics ;)

**Comment by lachlangrose** [comment]
Folds are and faults are described by more than the stratigraphy that is folded/faulted. So you can't describe them as stratigraphy.....
Reason to use geological feature over model feature is that a model feature could be the support that represents the geological feature. Think about what is actually being represented in the model, then name it as that. In my opinion and i'm just a structural geologist.... faults/folds/unconformities are not the same as stratigraphy and so we need to distinguish between them in the model....

**Comment by MichaelHillier** [comment]
I am also not sure about the geo_stack/stack naming. Would geological_history/geo_history be more suitable for describing the order of the computed scalar fields?

@Japhiolite 
I think series is a okay descriptor for the sequence of stratigraphic and possibly erosional geological events. But for faults and intrusion events no so much. 

Also, some questions:
1) In your screenshots, Out[31] shows geo_features as an integer, while Out[32] shows geo_features as a string. Why is that?
2) Is the 'order_surfaces' column the order in which scalar fields are computed for their corresponding geo_features? All the faults in the table have the same order number. What does that mean in terms of how their scalar fields are computed?

**Comment by flohorovicic** [comment]
Good discussion! Here some (very) quick thoughts:

-  I am in favour of separating faults/ folds/ strati sequences/ magmatic/ metamorphic - I think we should leave a reference to the semantic aspect, as this aspect could become useful later (also if we think about the developments of Boyen, etc.), even if they are treated in a similar way *at the moment*.
- It would be good to include a clear *hierarchy* of features - i.e. the possibility to have sedimentary features inside a larger unit; metamorphic features; veins, etc.

**Comment by Japhiolite** [comment]
@lachlangrose and @MichaelHillier ah, I think I misinterpreted how things are currently defined in gempy. I was under the impression that _series_ comprises rock-/ stratigraphic-sequences only in gempy. 
Obviously, structural features should not fall under that descriptor.   

And what I wanted to say concerning features is: Several _different_ geological features can be seen as being an _equal_ model feature (e.g. geometrical distinctions/features). So that the name feature may not be the best. Maybe also there, my wording wasn't the best.  

I like @flohorovicic suggestion of separating structural, stratigraphic ... features ..(there it is again). But I'm not sure whether this would increase the complexity unnecessarily?

**Comment by MichaelHillier** [comment]
Definitely agree with Florian's points.

Thinking about the semantic aspects and including hierarchical features into the data structure now will yield so much more possibilities and better models. This is especially so once the knowledge manager becomes usable.

**Comment by Japhiolite** [comment]
Just so I am sure this time I understood it correctly, and I'm more of a visual guy in terms of understanding.. something generally in this direction?
![image](https://user-images.githubusercontent.com/13364692/60187361-b9394800-982d-11e9-9631-4e7e40d4c723.png)

**Comment by Leguark** [comment]
wow, interesting discussion. Now I am unsure if democracy is the best way to rule GemPy :P 

Okay couple of points of how I see it. 

- The current series object is working as a (kind of) private object to feed the interpolator what it needs as well as front end for the user to specify the geological feature. That is what is making impossible to find the right name/structure.

What I propose:
- Rename series to Stack an keeping it mostly hidden from the user. By using stack we delete any trace of any geological meaning.
- Create a Geological features object - with the subclasses as @Japhiolite proposed - which feed the Stack object for GemPy and Surfe and FME under the hood.

Actions:
- For GemPy 2 that has to be release in the following weeks just to refactor series to stack
- For GemPy 2.1 create the Geological features abstraction

**Comment by pytzcarraldo** [comment]
I'm with @Japhiolite: renaming series to stack could be confusing for people involved with seismic. basically you replace the geological word series with the geophysical word stack used in seismic processing 😁
