### ISSUE TITLE
install pymc

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#197]
I have some problem when I installed the pymc, after I installed the gempy,numpy,pandas,matplotlib and other packages via pip install, I install pymc like conda install pymc,but there is always problem,that is why? How can I install the pymc in the right way.

**Comment by pytzcarraldo** [comment]
Hey @lllxllll !

Can you give us any detail on what exactly is the problem when installing pymc? Any error messages?

**Comment by lllxllll** [comment]
I configured the environment in the following order：
1. pip install gempy
2. pip install theano
3. pip install pymc,    but there are something wrong like:
![image](https://user-images.githubusercontent.com/45480246/60797556-0f997580-a1a2-11e9-8d29-d22c2ff17e86.png)


Then I install the pymc by :conda install pymc.    But it still failed:
![image](https://user-images.githubusercontent.com/45480246/60797754-7a4ab100-a1a2-11e9-9442-61a23dcbc943.png)
I can not understand why and how to solve this problem.
Thank you for your answer.

**Comment by pytzcarraldo** [comment]
Hm, only idea I have is to update your C++ and Fortran compilers (probably gcc and gfortran) - otherwise head over to the people of pymc and see if others have encountered similar problems.

**Comment by lllxllll** [comment]
Is there any way to clone the gempy and other packages  from github?  or  Can I install pymc2 in a Python 3.6 environment?Is there a compatibility issue with pymc and Python 3.6?

**Comment by pytzcarraldo** [comment]
Sure, you can just clone gempy from this repository and install it manually or alternatively import it to your script from wherever you cloned it to (`sys.path.append`). pymc2 should work just fine in python 3.6 - if you experience any issues with pymc, better ask the pymc developers.
