### ISSUE TITLE
GemPy_paper-model

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#204]
I have a question that Is this model implemented in gempy or other library?
![image](https://user-images.githubusercontent.com/45480246/61633700-3b4c4d80-acc2-11e9-8657-f56be0e906db.png)

**Comment by Leguark** [comment]
gempy, but the plot I did it with pyvista + vtk in a quite hacking way, hopefully by fall we will have some if this functionality on the main library
