### ISSUE TITLE
number of series unclear?

### ISSUE THREAD

**Issue by markjessell** [cgre-aachen/gempy#210]
Hi all, 

I am missing something in the creation of multiple series. I would like to have erosional bases to each series, and I can define the surfaces:

surfaces

![image](https://user-images.githubusercontent.com/6822240/64062291-365eb000-cc17-11e9-9cb7-87d1f332821a.png)

but if I ignore the gp.map_series_to_surfaces() step and go straight to geo_model.additional_data.structure_data I get

geo_model.additional_data.structure_data (1 series, when I want 6)

![image](https://user-images.githubusercontent.com/6822240/64062315-8178c300-cc17-11e9-81d1-70124fdbc814.png)

but if I try to do the following to map the series to surfaces after the gp.set_interpolation_data step() I get the errors below. All help gratefully accepted, and of course I can send more code if this is not enough.

cheers

Mark

gp.map_series_to_surfaces(geo_model,
                        {'Wyloo_Group':('P_-WYa-s','P_-WYm-sp','P_-WYd-kd'), 
                        'Shingle_Creek_Group':('P_-SKb-bb','P_-SKq-stq'), 
                        'Turee_Creek_Group':('P_-TKk-sf','P_-TKo-stq','P_-TKa-xs-k','P_-TK-s'),
                        'Hamersley_Group':('P_-HAo-ci','P_-HAw-fr','P_-HAj-xci-od','P_-HAb-cib','A-HAu-xsl-ci','A-HAd-kd','A-HAm-cib'),
                        'Fortescue_Group':('A-FOj-xs-b','A-FOu-bbo','A-FOp-bs','A-FOo-bbo','A-FOh-xs-f','A-FOr-b'),
                        'A-b-PRK':('A-b-PRK2')},remove_unused_series=True)

------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-116089757381> in <module>
      5                         'Hamersley_Group':('P_-HAo-ci','P_-HAw-fr','P_-HAj-xci-od','P_-HAb-cib','A-HAu-xsl-ci','A-HAd-kd','A-HAm-cib'),
      6                         'Fortescue_Group':('A-FOj-xs-b','A-FOu-bbo','A-FOp-bs','A-FOo-bbo','A-FOh-xs-f','A-FOr-b'),
----> 7                         'A-b-PRK':('A-b-PRK')},remove_unused_series=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\gempy_api.py in map_series_to_surfaces(geo_model, mapping_object, set_series, sort_geometric_data, remove_unused_series)
     72                            set_series=True, sort_geometric_data: bool = True, remove_unused_series=True):
     73     """"""
---> 74     geo_model.map_series_to_surfaces(mapping_object, set_series, sort_geometric_data, remove_unused_series)
     75     return geo_model.surfaces
     76 # endregion

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\model.py in map_series_to_surfaces(self, mapping_object, set_series, sort_geometric_data, remove_unused_series)
    494 
    495         self.update_from_surfaces()
--> 496         self.update_from_series()
    497 
    498         if sort_geometric_data is True:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\model.py in update_from_series(self, rename_series, reorder_series, sort_geometric_data, update_interpolator)
    815 
    816         if update_interpolator is True:
--> 817             self.interpolator.set_theano_shared_structure(reset_ctrl=True)
    818 
    819         return True

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\interpolator.py in set_theano_shared_structure(self, reset_ctrl)
    596 
    597         """
--> 598         self.set_theano_shared_loop()
    599         self.set_theano_shared_relations()
    600         self.set_theano_shared_structure_surfaces()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\interpolator.py in set_theano_shared_loop(self)
    631     def set_theano_shared_loop(self):
    632         """Set the theano shared variables that are looped for each series."""
--> 633         self._compute_len_series()
    634 
    635         self.theano_graph.len_series_i.set_value(np.insert(self.len_series_i.cumsum(), 0, 0).astype('int32'))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gempy\core\interpolator.py in _compute_len_series(self)
    627             self.len_series_f = np.zeros(1, dtype=int)
    628 
--> 629         self.len_series_w = self.len_series_i + self.len_series_o * 3 + self.len_series_u + self.len_series_f
    630 
    631     def set_theano_shared_loop(self):

ValueError: operands could not be broadcast together with shapes (5,) (7,)

**Comment by Leguark** [comment]
Mmm that seems that at some creation of a data structure some dependency did not get updated. I wonder if I missed some case. For the time being, until you feel ready to share your code :D try to use the update methods of geomodel:
- update_from_series
- update_from_surfaces
- **update_structure**
- **update_to_interpolator**

By looking at the error, I would say only the last two need to be called
