### ISSUE TITLE
About interp_data.geo_data_res.interfaces error

### ISSUE THREAD

**Issue by gislijun** [cgre-aachen/gempy#215]
I can't find the interfaces of interp_data.geo_data_res attribution. What replace it? Thank you.

**Comment by Leguark** [comment]
In GemPy 2, we got rid off the interp_data object in order to keep the uniqueness of the parameters.

The rescaled coordinates are an attribute of Model().surface_points.df. In all the new tutorials you can find it as geo_model.surface_points X_r, Y_r, Z_r
