### ISSUE TITLE
Errror I do not understand

### ISSUE THREAD

**Issue by bistek** [cgre-aachen/gempy#220]
Hello, I'm trying to learn GemPy, so I have taken the first tutorial notebook - ch1-1_Basics.ipynb - and I substituted a dataset that I use for teaching to the standard synthetic dataset. The geology is a bit more complicated since there are folds and 13 faults. The dataset is also larger and coordinates are UTM (so with larger values). I have been able to successfully follow the ch1-1_Basics.ipynb tutorial, adapting it to my data (basically incuding more faults and setting them as finite faults since they do not extend to the limits of the model), up to compiling Theano and showing kriging parameters. Then at line:

`sol = gp.compute_model(geo_model, compute_mesh=False)`

I get the following error, that I do not understand:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1680 
-> 1681         mgr = BlockManager(blocks, axes)
   1682         mgr._consolidate_inplace()

C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in __init__(self, blocks, axes, do_integrity_check)
    142         if do_integrity_check:
--> 143             self._verify_integrity()
    144 

C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in _verify_integrity(self)
    344             if block._verify_integrity and block.shape[1:] != mgr_shape[1:]:
--> 345                 construction_error(tot_items, block.shape[1:], self.axes)
    346         if len(self.items) != tot_items:

C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in construction_error(tot_items, block_shape, axes, e)
   1716     if block_shape[0] == 0:
-> 1717         raise ValueError("Empty data passed with indices specified.")
   1718     raise ValueError(

ValueError: Empty data passed with indices specified.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-44-fcb22f14be0b> in <module>
----> 1 sol = gp.compute_model(geo_model, compute_mesh=False)

D:\REPOS\gempy\gempy\core\gempy_api.py in compute_model(model, output, compute_mesh, reset_weights, reset_scalar, reset_block, sort_surfaces, debug, set_solutions)
    276             model.solutions.sections_scalfield = sol[3][:, l0: l1].astype(float)
    277         if sort_surfaces:
--> 278             model.set_surface_order_from_solution()
    279         return model.solutions
    280 

D:\REPOS\gempy\gempy\core\model.py in set_surface_order_from_solution(self)
    995 
    996                 self.surfaces.df.loc[idx, 'order_surfaces'] = self.surfaces.df.loc[idx, 'surface'].map(
--> 997                     pn.DataFrame(sfai_order, index=surface_names)[0])
    998 
    999             except IndexError:

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    438                 mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    439             else:
--> 440                 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    441 
    442         # For data is list-like, or Iterable (will consume into list)

C:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
    211         block_values = [values]
    212 
--> 213     return create_block_manager_from_blocks(block_values, [columns, index])
    214 
    215 

C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1686         blocks = [getattr(b, "values", b) for b in blocks]
   1687         tot_items = sum(b.shape[0] for b in blocks)
-> 1688         construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1689 
   1690 

C:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in construction_error(tot_items, block_shape, axes, e)
   1715         raise e
   1716     if block_shape[0] == 0:
-> 1717         raise ValueError("Empty data passed with indices specified.")
   1718     raise ValueError(
   1719         "Shape of passed values is {0}, indices imply {1}".format(passed, implied)

ValueError: Empty data passed with indices specified.
```

Please note that this line was OK (with `compute_mesh=False`) using the synthetic dataset as input.

Thanks!

**Comment by Leguark** [comment]
This is happening when gempy try to reorder the surfaces accordingly to the dataset. Try to add

sol = gp.compute_model(geo_model, compute_mesh=False, sort_surfaces=False)

Without looking at the model construction is difficult for me to guess what is empty. It seems it is either something on the geo_model.surfaces object or in the result of some of series I imagine. Can you push the notebook and dataset somewhere or send me the saved model?

**Comment by bistek** [comment]
Hello, I've spotted some error in the way I was setting the faults (I'm sending the corrected notebook separately), but I suspect now the problem is I do not understand how to set the order of stratigraphic surfaces, and since I use `sort_surfaces=False`, I need to set it, otherwise it will be messed up and the model cannot converge.

I have tried

```
formation_order = [... the list of my units in order ...]
gp.set_series(geo_model, {"Default series": formation_order}, order_formations = formation_order)
```

But it looks like `order_formations` is no more recognised after an update some time ago.

#178

How does it work now?

Thanks!!

**Comment by Leguark** [comment]
The surface object and series object now has methods to change the order. Also when use set_series since python 3.6 the dictionaries are order so I take advantage of that.

I have gone through your model and the main source of error is that only the stratigraphies have orientations. In GemPy each "series/faults" need at least an orientation (I have a function to create orientations from surface points).

The problem is that instead raising an error, it is interpolating the first fault with all the orientations and therefore the model makes no sense. I am a bit surprise that no error is risen. I will try to add some assert

**Comment by bistek** [comment]
OK thanks!

I'll manage to add some orientations to faults. Basically I need at least one point with fault dip/azimuth close to each fault, correct?

Regarding surface object and series object, where should I look in the documentation?

It looks like the series ordering is OK (hence the order of faults is correct), but the surfaces order is messed up.

![image](https://user-images.githubusercontent.com/12087912/66578173-e8748a80-eb7a-11e9-9cef-6fbcfbdd736d.png)

They should be ordered according to the increasing number, but in the table the appear in the order 03, 02, 01, 04, 05, 00, basement.

Thanks!

**Comment by Leguark** [comment]
Yeah, we need some way to find specific chunks of documentation. Even I am not sure where. But basically you can use:

geo_model.modify_order_surfaces(
    new_value: int,
    idx: int,
    series_name: str = None,
)
Docstring:
(inserted) 
Replace to the new location the old series

Args:
    new_value (int): New location
    idx (int): Index of the surface to be moved
    series_name (str): name of the series to be moved

Returns:
   :class:`Surfaces`:
Source:   
    @setdoc(Surfaces.modify_order_surfaces.__doc__, indent=False)
    def modify_order_surfaces(self, new_value: int, idx: int, series_name: str = None):
        """"""
        self.surfaces.modify_order_surfaces(new_value, idx, series_name)

        self.map_geometric_data_df(self.surface_points.df)
        self.surface_points.sort_table()
        self.map_geometric_data_df(self.orientations.df)
        self.orientations.sort_table()

        self.update_structure()
        return self.surfaces


However, once the model works fine, the order of the formations gets automatically updated to match the orientations directions. **Only the order of series has a direct impact on the interpolation results*

**Comment by bistek** [comment]
OK thanks!

**Comment by bistek** [comment]
So I should add the orientation for faults and do not use anymore the flag suggested above `sort_surfaces=False`.

Correct?

**Comment by Leguark** [comment]
exactly, but the only thing you will notice if the formations are in the wrong order is a mismatch between the color of the input data and surfaces

**Comment by bistek** [comment]
Hello, the original problem is solved by adding the orientation for faults.

Now the problem is that GemPy, or rather Theano, complains that the matrix is singular and it cannot solve the system of equations. Note that I tried with and without the sort_surfaces=False option. I do not attach the whole error message, which is huge, but the first lines say:

```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
scan_perform.pyx in theano.scan_module.scan_perform.perform()

C:\Anaconda3\lib\site-packages\theano\gof\op.py in rval(p, i, o, n)
    891             def rval(p=p, i=node_input_storage, o=node_output_storage, n=node):
--> 892                 r = p(n, [x[0] for x in i], o)
    893                 for o in node.outputs:

C:\Anaconda3\lib\site-packages\theano\tensor\slinalg.py in perform(self, node, inputs, output_storage)
    254         else:
--> 255             rval = scipy.linalg.solve(A, b)
    256         output_storage[0][0] = rval

C:\Anaconda3\lib\site-packages\scipy\linalg\basic.py in solve(a, b, sym_pos, lower, overwrite_a, overwrite_b, debug, check_finite, assume_a, transposed)
    215         lu, ipvt, info = getrf(a1, overwrite_a=overwrite_a)
--> 216         _solve_check(n, info)
    217         x, info = getrs(lu, ipvt, b1,

C:\Anaconda3\lib\site-packages\scipy\linalg\basic.py in _solve_check(n, info, lamch, rcond)
     30     elif 0 < info:
---> 31         raise LinAlgError('Matrix is singular.')
     32 

LinAlgError: Matrix is singular.
```

**Comment by bistek** [comment]
From issue #105 it looks like this problem might arise if I have points constraining different objects too close together. Correct?

If this is the case I could try either:

(1) eliminating points within a certain distance from a higher level series (e.g. eliminating surface points too close to faults).

(2) increasing grid resolution.

Correct?

Do you have any automatic tool to perform this "cleaning" or to set "exclusion zones" around objects?

Thanks as usual!!

**Comment by bistek** [comment]
When I mention "exclusion zones", I am thinking abut something that for instance SKUA does. In SKUA you first generate the fault network, taking care of all intersections, branching relationships, finite vs. infinite faults, etc. Then, when you build the stratigraphy, points closer than a threshold to faults can be excluded.

**Comment by bistek** [comment]
Would it be possible to build just the fault network and see how it goes in GemPy? This would be very useful for QC purposes. The same applies to the possibility to build just one series first, and then add some more.

**Comment by bistek** [comment]
Hello, I've downsampled my input data in order to have points at distance around 100m and I am using a grid with spacing of 50m, and the problems are solved. I still do not understand if the grid spacing is critical in this case.

Thanks!

**Comment by Leguark** [comment]
Sorry for the late answer!

By default gempy uses a quite large kriging range for the interpolation that when you have many points nearby leads to numerical instabilities. That is why decimating points helps. 

Regarding faults, that is an area I did not have too much time to develop (specially finite faults). But in general you will get better numerical behaved faults when there is data in every fault block (each independent intersected volume).

And no, the grid should not interfered with the quality of the interpolation. GemPy is data centered (as opposite of SKUA). In principle the only downside of a high resolution is the amount of memory required.

**Comment by bistek** [comment]
Perfect, thanks very much for explaining!
