### ISSUE TITLE
Fault truncation method not explained

### ISSUE THREAD

**Issue by GeologicalModeler** [cgre-aachen/gempy#222]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GeologicalModeler** [comment]
Hi everyone.

In geological modelling, I think any modeler needs to understand the method the software used by fault surface to truncate horizons very well and if there are additional advanced options.

So would you please explain to me how this happened in gempy and I recommend adding it to the documentation in future.

Thank you

**Comment by Leguark** [comment]
The faults plane are used as an extra drift function for the interpolation of the scalar field. This is very similar to the way GeoModeller 3D is doing it and I think (not 100% sure) Leapfrog. You can look the theory in the paper (although I did not focus on the theory of faults too much).

From a practical point of view I recommend you to play with simple examples (there is a couple on the tutorials) so you can see how the scalar field gets offset respect the location of the surface points.
