### ISSUE TITLE
Data requirements/kriging parameter

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#226]
I have encountered some problems during the process of using gempy.

1.The amount of data in my study area is very large,1300 points,so that the 3D model is confusion.I wonder that is there any requirments or limitation of the number of data.

![image](https://user-images.githubusercontent.com/45480246/66810291-8a241f00-ef61-11e9-8e4e-07af06fdeed5.png)

2.I want to use DEM to cut out the 3D model so that it can fit my area, but I can not find any interface to comply, Is there any way to export scalar filed with coordinate and the scalar field value.

**Comment by Leguark** [comment]
1 There are no limitation of points but usually the more (noisy) data you add, the more difficult gets to find a unique solution and you start to have mathematical instabilities 

2. scalar fields are stored on geo_model.solutions.scalar_field_matrix
