### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#227]
Is there any way to check the data structure of this code: gp.plot.plot_3D(geo_model) ,I run geo_model but get nothing?
![image](https://user-images.githubusercontent.com/45480246/66820622-9d3fea80-ef73-11e9-9092-cf8e9a4f58ca.png)
and the data structure after interpolate : gp.set_interpolation_data(geo_model)?

**Comment by Leguark** [comment]
geo_model is a container of all the data objects. The more important that come to my mind:

geo_model.grid
geo_model.surfaces
geo_model.series
geo_model.surface_points
geo_model.orientations
geo_model.interpolator
geo_model.solutions

When you use the api and pass geo_model to a function we just select the specific objects (usually a combination of the above)
