### ISSUE TITLE
document orientation conventions

### ISSUE THREAD

**Issue by AndrewAnnex** [cgre-aachen/gempy#233]
Gempy should document the conventions for the azimuth and polarity (maybe dip as well). For example is azimuth 0 to 360 degrees clockwise with north at 0 degrees (90 east, 180 south, etc)? @Leguark let me know which way it is and I can contribute docstrings easily in a PR.

**Comment by Leguark** [comment]
I would imagine that azimuth 0 is pointing north yes, but I cannot assure it 100% :D. Has anybody check this?

**Comment by elimh** [comment]
Exactly, 0 or 360 degrees is north! I have described the convention a bit [here](https://github.com/cgre-aachen/gempy/blob/9a4b7d37553ee4cf95bb8ab06b49e3e225c166f3/gempy/core/data.py#L2005-L2011), but it would definitely make sense to have it in the docstrings...

**Comment by AndrewAnnex** [comment]
Yes but it is important to note clockwise or counter clockwise (some people have different conversations where 0 is East and 90 is North for example). Just a simple table to say the common cardinal directions and expected degrees and orientation vectors should be sufficient 

-Andrew Annex

**Comment by elimh** [comment]
Yes of course, you are right, that's why I updated the comment right after I sent it, but it was already too late for the email notification you replied to. However, it is definitely important to mention this - I think many users are unsure about the convention, so thanks for pointing it out!

**Comment by Leguark** [comment]
#225 this two issues can go together

**Comment by fastamo** [comment]
This was fixed with issue #279
