### ISSUE TITLE
How to generate orientation from surface_points?

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gempy#235]
I tried to generate an orientation from three surface points with the function:
set_orientation_from_surface_points

Example:
`gp.set_orientation_from_surface_points(geo_model, [1,2,3])`

But I get this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-124-8d1a47fa38e3> in <module>
----> 1 gp.set_orientation_from_surface_points(geo_model, s)

C:\ProgramData\Anaconda3\lib\site-packages\gempy\core\gempy_api.py in set_orientation_from_surface_points(geo_model, indices_array)
    103     if np.ndim(indices_array) is 1:
    104         indices = indices_array
--> 105         form = geo_model.surface_points['surface'].loc[indices].unique()
    106         assert form.shape[0] is 1, 'The interface points must belong to the same surface'
    107         form = form[0]

TypeError: 'SurfacePoints' object is not subscriptable
---------------------------------------------------------------------------

```
What have I done wrong?
I have read in my geo_model simple 3d points with X,Y,Z coordinates.

**Comment by pytzcarraldo** [comment]
Can you tell us which version of GemPy you are using?
The bug is not present in the current master branch. If you are using GemPy by cloning the git repository, then `git pull origin master` should get rid of your problem ;-)

**Comment by domist07** [comment]
I use version Gempy 2.0.1

**Comment by domist07** [comment]
Now it works :)
Thanks for the help!
