### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SehsahH** [cgre-aachen/gempy#236]
There is a problem in creating new files or even editing any file, and I got error message: Errno 2] File b'../data/input_data/jan_models/model7_surface_points.csv' does not exist: b'../data/input_data/jan_models/model7_surface_points.csv'. The file already exist in the directory!
This is the working directory: /home/gempy/work/gempy/notebooks/examples', but this directory doesn't exist in my PC and I get error when changing it to /home/gempy/notebooks/examples'  which is the real directory.

**Comment by Leguark** [comment]
That is extrange, the notebook in the master branch is running (they are tested every time we push new changes). If the error persist please add some screenshots or any more info
