### ISSUE TITLE
Installing latest version of GemPy for surface point calculation

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#237]
**Describe the bug**
I was going to calculate the surface orientation of point as described in issue #235. In Pycharm, I can see that the missing "df" was added to the code (first screenshot). However, how can I update GemPy in Anaconda/Jupyter Python notebooks because I still see the issue there (second screenshot)? I have updated GemPy via Git Bash (third screenshot) and reinstalled GemPy. I am using version 2.0.1. Thanks for the help!

Screenshot of Pycharm where issue was fixed:
![Screenshot1](https://user-images.githubusercontent.com/45469915/72337401-d139c180-36c2-11ea-97e6-bfd703cde396.PNG)

Screenshot of Jupyter Python Notebook where issue has not been fixed:
![Screenshot2](https://user-images.githubusercontent.com/45469915/72337443-df87dd80-36c2-11ea-874c-e2f60f3e983a.PNG)

Screenshot of Git Bash: 
![Screenshot4](https://user-images.githubusercontent.com/45469915/72337507-f9c1bb80-36c2-11ea-96c6-6baff5fda216.PNG)

**Comment by Leguark** [comment]
By default when you import any package in Python, first they look in the installed folder. The pip version of gempy does not have the bug fix yet. 

First uninstall the pip version:
1) pip uninstall gempy

Then:
If you want to use the master version you can either install it manually: 
1) Go to the cloned folder of gempy 
2) python setup.py install

Or not installing gempy at all. For this you will need to add the path to the gempy files in every notebooks by

sys.append(path to gempy)

This is second option how all the tutorial notebooks work
