### ISSUE TITLE
gp.plot.plot_3D(geo_model) results in black screen - issue with vtk-installation and vertical exaggeration?

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#238]
**Describe the bug**
Instead of the 3D view of the geo_model only a black screen appears when calling `gp.plot.plot_3D(geo_model)`. There is no error message when closing the window. The current GemPy version is 2.0.1. The installed vtk version is 8.1.2.  It seems that vtk is installed as -PKG-Version (?). Uninstalling vtk via pip fails with the comment that vtk is a "distutils installed project....". Uninstalling vtk via conda results in an "InvalidArchiveError". So no reinstallation of vtk was possible. The invalid error is related to "openssl". Deleting of the folder and installing it again did not solve the issue but resulted in the same error.

So, how can I check that my vtk has been installed correctly and fix it in case it isn't and how can I set a vertical exaggeration? I could not find anything in the code.

Thanks for the help!

**Comment by Leguark** [comment]
Just run any example of the vtk website. If it is a vtk installation error we cannot do much from our end
