### ISSUE TITLE
ImportError: cannot import name 'visualization_2d_pro' from 'gempy.plot'

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#239]
**Describe the bug**
When working with the STC-Course notebook, the import of "vista" and "visualization_2d_pro as vv" fails with the import error above. I recall that we actually had to change something in the console but I forgot what it was...or was it another issue
Thanks for the help!

![Capture](https://user-images.githubusercontent.com/45469915/72341254-0e558200-36ca-11ea-98ed-4c0ed3599b0e.PNG)

**Comment by Leguark** [comment]
This should be fixed in the last update of the master
