### ISSUE TITLE
Examples about gempy code

### ISSUE THREAD

**Issue by xuhenry** [cgre-aachen/gempy#242]
Hello all,
    Is there any examples for the learning of the gempy code?
Thanks a lot!
Best regards,
Henry

**Comment by xuhenry** [comment]
Hello, all.
   I have found some examples in the code. But when I run the"Model 1" example, some errors happen:

Active grids: ['regular']

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-5bca7d754387> in <module>()
      1 geo_data = gp.create_data([0,1000,0,1000,0,1000],resolution=[50,50,50], 
      2                         path_o = os.pardir+"/data/input_data/jan_models/model1_orientations.csv",
----> 3                         path_i = os.pardir+"/data/input_data/jan_models/model1_surface_points.csv") 

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/gempy_api.py in create_data(extent, resolution, project_name, **kwargs)
    478 
    479     geo_model = create_model(project_name)
--> 480     return init_data(geo_model, extent=extent, resolution=resolution, project_name=project_name, **kwargs)
    481 
    482 

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/gempy_api.py in init_data(geo_model, extent, resolution, **kwargs)
    519 
    520     if 'path_i' in kwargs or 'path_o' in kwargs:
--> 521         read_csv(geo_model, **kwargs)
    522 
    523     if 'surface_points_df' in kwargs:

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/gempy_api.py in read_csv(geo_model, path_i, path_o, **kwargs)
     81 def read_csv(geo_model: Model, path_i=None, path_o=None, **kwargs):
     82     if path_i is not None or path_o is not None:
---> 83         geo_model.read_data(path_i, path_o, **kwargs)
     84     return True
     85 

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/model.py in read_data(self, path_i, path_o, add_basement, **kwargs)
   1196         if add_basement is True:
   1197             self.surfaces.add_surface(['basement'])
-> 1198             self.map_series_to_surfaces({'Basement': 'basement'}, set_series=True)
   1199         self.rescaling.rescale_data()
   1200 

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/model.py in map_series_to_surfaces(self, mapping_object, set_series, sort_geometric_data, remove_unused_series, twofins)
    521             if type(mapping_object) is dict:
    522                 series_list = list(mapping_object.keys())
--> 523                 self.series.add_series(series_list)
    524             elif isinstance(mapping_object, pn.Categorical):
    525                 series_list = mapping_object['series'].values

/usr/local/lib/python3.7/dist-packages/gempy-2.0.1-py3.7.egg/gempy/core/data.py in add_series(self, series_list, reset_order_series)
    535 
    536         for c in series_list:
--> 537             self.df.loc[c, 'BottomRelation'] = 'Erosion'
    538             self.faults.df.loc[c] = [False, False]
    539             self.faults.faults_relations_df.loc[c, c] = False

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexing.py in __setitem__(self, key, value)
    669             key = com.apply_if_callable(key, self.obj)
    670         indexer = self._get_setitem_indexer(key)
--> 671         self._setitem_with_indexer(indexer, value)
    672 
    673     def _validate_key(self, key, axis: int):

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value)
    858                     index = self.obj._get_axis(i)
    859                     labels = index.insert(len(index), key)
--> 860                     self.obj._data = self.obj.reindex(labels, axis=i)._data
    861                     self.obj._maybe_update_cacher(clear=True)
    862                     self.obj._is_copy = None

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    225         @wraps(func)
    226         def wrapper(*args, **kwargs) -> Callable[..., Any]:
--> 227             return func(*args, **kwargs)
    228 
    229         kind = inspect.Parameter.POSITIONAL_OR_KEYWORD

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/frame.py in reindex(self, *args, **kwargs)
   3839         kwargs.pop("axis", None)
   3840         kwargs.pop("labels", None)
-> 3841         return self._ensure_type(super().reindex(**kwargs))
   3842 
   3843     def drop(

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4531         # perform the reindex on the axes
   4532         return self._reindex_axes(
-> 4533             axes, level, limit, tolerance, method, fill_value, copy
   4534         ).__finalize__(self)
   4535 

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/frame.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   3727         if index is not None:
   3728             frame = frame._reindex_index(
-> 3729                 index, method, copy, level, fill_value, limit, tolerance
   3730             )
   3731 

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/frame.py in _reindex_index(self, new_index, method, copy, level, fill_value, limit, tolerance)
   3743     ):
   3744         new_index, indexer = self.index.reindex(
-> 3745             new_index, method=method, level=level, limit=limit, tolerance=tolerance
   3746         )
   3747         return self._reindex_with_indexers(

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexes/category.py in reindex(self, target, method, level, limit, tolerance)
    600         new_target = np.asarray(new_target)
    601         if is_categorical_dtype(target):
--> 602             new_target = target._shallow_copy(new_target, name=self.name)
    603         else:
    604             new_target = Index(new_target, name=self.name)

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexes/category.py in _shallow_copy(self, values, dtype, **kwargs)
    279         if dtype is None:
    280             dtype = self.dtype
--> 281         return super()._shallow_copy(values=values, dtype=dtype, **kwargs)
    282 
    283     def _is_dtype_compat(self, other) -> bool:

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexes/base.py in _shallow_copy(self, values, **kwargs)
    522             values = values.asi8
    523 
--> 524         return self._simple_new(values, **attributes)
    525 
    526     def _shallow_copy_with_infer(self, values, **kwargs):

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexes/category.py in _simple_new(cls, values, name, dtype)
    265         result = object.__new__(cls)
    266 
--> 267         values = cls._create_categorical(values, dtype=dtype)
    268         result._data = values
    269         result.name = name

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/indexes/category.py in _create_categorical(cls, data, dtype)
    254 
    255         if not isinstance(data, ABCCategorical):
--> 256             return Categorical(data, dtype=dtype)
    257 
    258         if isinstance(dtype, CategoricalDtype) and dtype != data.dtype:

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/arrays/categorical.py in __init__(self, values, categories, ordered, dtype, fastpath)
    383 
    384         else:
--> 385             codes = _get_codes_for_values(values, dtype.categories)
    386 
    387         if null_mask.any():

/usr/local/lib/python3.7/dist-packages/pandas-1.0.0rc0-py3.7-linux-x86_64.egg/pandas/core/arrays/categorical.py in _get_codes_for_values(values, categories)
   2577     _, cats = _get_data_algo(categories)
   2578     t = hash_klass(len(cats))
-> 2579     t.map_locations(cats)
   2580     return coerce_indexer_dtype(t.lookup(vals), cats)
   2581 

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.StringHashTable.map_locations()

TypeError: Expected unicode, got numpy.str_

**Comment by pytzcarraldo** [comment]
Hey @xuhenry !

What example were you running that gave you that error?

I'd generally recommend you start with the tutorial notebooks: https://github.com/cgre-aachen/gempy/tree/master/notebooks/tutorials

**Comment by xuhenry** [comment]
Hello, @pytzcarraldo 
I have run the examples of "Model 1 - Horizontal stratigraphic.ipynb" in :https://github.com/cgre-aachen/gempy/tree/master/notebooks/examples

Thanks a lot!
Best regards,
Henry

**Comment by xuhenry** [comment]
Furthermore, same errors will happen for the script when using the following keywords:
 
"gp.init_data(geo_model, extent=[450000, 460000, 70000,80000,-1000,500],resolution = (50,50,50),
                         path_i = data_path+"/data/input_data/tut-ch1-7/onelayer_interfaces.csv",
                         path_o = data_path+"/data/input_data/tut-ch1-7/onelayer_orient.csv")"

**Comment by pytzcarraldo** [comment]
It would really help if you could fill out our bug report template properly so we can troubleshoot your problem:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by xuhenry** [comment]
Dear @pytzcarraldo 
Thanks a lot.
The Code is compiled on : Ubuntu 19.1, Firefox. And the following is the Screenshots of the errors.
Thanks a lot!

<img width="1191" alt="截屏2020-01-30下午11 01 02" src="https://user-images.githubusercontent.com/20606262/73461146-9dde7e80-43b4-11ea-8580-55b29b222673.png">

**Comment by pytzcarraldo** [comment]
Thanks for the info! I've managed to reproduce the error. It's due to the new `pandas=1` release. If you downgrade your pandas to the previous version `pandas=0.25` it will work.  E.g. `conda install pandas=0.25` 

Cheers,
Alex

**Comment by pytzcarraldo** [comment]
Same as #243

**Comment by xuhenry** [comment]
Dear @pytzcarraldo.
     Thanks for your help. But it still has the same errors.
      Now I'm using Win10. 
Thanks a lot!
Best regards,
Henry

**Comment by Leguark** [comment]
It needs more testing but it seems that in pandas 1.0.1 the problem got solved
