### ISSUE TITLE
gp.init_data gives TypeError: Expected unicode, got numpy.str_

### ISSUE THREAD

**Issue by markjessell** [cgre-aachen/gempy#243]
Hi

Under ubuntu 18.04.1 with gempy 2.0.1 I am having trouble with the simple model init:

geo_model = gp.create_model("test_data3") 

gp.init_data(geo_model, extent=[500057, 603028, 7455348, 7567953, -8200, 1200],
    resolution = (50,50,50), 
    path_o = "../test_data3/output/orientations_clean.csv",
    path_i = "../test_data3/output/contacts_clean.csv", default_values=True); 

This causes an error under linux (but not windows for same input files):

Active grids: ['regular']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/pylibs/map2loop/notebooks/m2l_config.py in <module>
----> 1 gp.init_data(geo_model, extent=[500057, 603028, 7455348, 7567953, -8200, 1200],
      2     resolution = (50,50,50),
      3     path_o = "../test_data3/output/orientations_clean.csv",
      4     path_i = "../test_data3/output/contacts_clean.csv", default_values=True); 

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/gempy_api.py in init_data(geo_model, extent, resolution, **kwargs)
    417 
    418     if 'path_i' in kwargs or 'path_o' in kwargs:
--> 419         read_csv(geo_model, **kwargs)
    420 
    421     if 'surface_points_df' in kwargs:

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/gempy_api.py in read_csv(geo_model, path_i, path_o, **kwargs)
     81 def read_csv(geo_model: Model, path_i=None, path_o=None, **kwargs):
     82     if path_i is not None or path_o is not None:
---> 83         geo_model.read_data(path_i, path_o, **kwargs)
     84     return True
     85 

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/model.py in read_data(self, path_i, path_o, add_basement, **kwargs)
   1096         if add_basement is True:
   1097             self.surfaces.add_surface(['basement'])
-> 1098             self.map_series_to_surfaces({'Basement': 'basement'}, set_series=True)
   1099         self.rescaling.rescale_data()
   1100 

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/model.py in map_series_to_surfaces(self, mapping_object, set_series, sort_geometric_data, remove_unused_series)
    475             if type(mapping_object) is dict:
    476                 series_list = list(mapping_object.keys())
--> 477                 self.series.add_series(series_list)
    478             elif isinstance(mapping_object, pn.Categorical):
    479                 series_list = mapping_object['series'].values

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/data.py in add_series(self, series_list, reset_order_series)
    510 
    511         for c in series_list:
--> 512             self.df.loc[c, 'BottomRelation'] = 'Erosion'
    513             self.faults.df.loc[c] = [False, False]
    514             self.faults.faults_relations_df.loc[c, c] = False

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexing.py in __setitem__(self, key, value)
    668             key = com.apply_if_callable(key, self.obj)
    669         indexer = self._get_setitem_indexer(key)
--> 670         self._setitem_with_indexer(indexer, value)
    671 
    672     def _validate_key(self, key, axis: int):

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value)
    857                     index = self.obj._get_axis(i)
    858                     labels = index.insert(len(index), key)
--> 859                     self.obj._data = self.obj.reindex(labels, axis=i)._data
    860                     self.obj._maybe_update_cacher(clear=True)
    861                     self.obj._is_copy = None

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    225         @wraps(func)
    226         def wrapper(*args, **kwargs) -> Callable[..., Any]:
--> 227             return func(*args, **kwargs)
    228 
    229         kind = inspect.Parameter.POSITIONAL_OR_KEYWORD

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/frame.py in reindex(self, *args, **kwargs)
   3851         kwargs.pop("axis", None)
   3852         kwargs.pop("labels", None)
-> 3853         return self._ensure_type(super().reindex(**kwargs))
   3854 
   3855     def drop(

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4540 
   4541         # perform the reindex on the axes
-> 4542         return self._reindex_axes(
   4543             axes, level, limit, tolerance, method, fill_value, copy
   4544         ).__finalize__(self)

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/frame.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   3738         index = axes["index"]
   3739         if index is not None:
-> 3740             frame = frame._reindex_index(
   3741                 index, method, copy, level, fill_value, limit, tolerance
   3742             )

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/frame.py in _reindex_index(self, new_index, method, copy, level, fill_value, limit, tolerance)
   3754         tolerance=None,
   3755     ):
-> 3756         new_index, indexer = self.index.reindex(
   3757             new_index, method=method, level=level, limit=limit, tolerance=tolerance
   3758         )

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexes/category.py in reindex(self, target, method, level, limit, tolerance)
    607         new_target = np.asarray(new_target)
    608         if is_categorical_dtype(target):
--> 609             new_target = target._shallow_copy(new_target, name=self.name)
    610         else:
    611             new_target = Index(new_target, name=self.name)

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexes/category.py in _shallow_copy(self, values, dtype, **kwargs)
    281         if dtype is None:
    282             dtype = self.dtype
--> 283         return super()._shallow_copy(values=values, dtype=dtype, **kwargs)
    284 
    285     def _is_dtype_compat(self, other) -> bool:

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexes/base.py in _shallow_copy(self, values, **kwargs)
    540             values = values.asi8
    541 
--> 542         return self._simple_new(values, **attributes)
    543 
    544     def _shallow_copy_with_infer(self, values, **kwargs):

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexes/category.py in _simple_new(cls, values, name, dtype)
    267         result = object.__new__(cls)
    268 
--> 269         values = cls._create_categorical(values, dtype=dtype)
    270         result._data = values
    271         result.name = name

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/indexes/category.py in _create_categorical(cls, data, dtype)
    256 
    257         if not isinstance(data, ABCCategorical):
--> 258             return Categorical(data, dtype=dtype)
    259 
    260         if isinstance(dtype, CategoricalDtype) and dtype != data.dtype:

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/arrays/categorical.py in __init__(self, values, categories, ordered, dtype, fastpath)
    383 
    384         else:
--> 385             codes = _get_codes_for_values(values, dtype.categories)
    386 
    387         if null_mask.any():

~/anaconda3/envs/m2le/lib/python3.8/site-packages/pandas/core/arrays/categorical.py in _get_codes_for_values(values, categories)
   2574     _, cats = _get_data_algo(categories)
   2575     t = hash_klass(len(cats))
-> 2576     t.map_locations(cats)
   2577     return coerce_indexer_dtype(t.lookup(vals), cats)
   2578 

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.StringHashTable.map_locations()

TypeError: Expected unicode, got numpy.str_

Describe the solution you'd like

have it work like the windows version (ie no error!)

Describe alternatives you've considered

none

**Comment by markjessell** [comment]
one more precision, ubuntu is running on virtualbox on a windows machine (not that that should matter?)

m

**Comment by xuhenry** [comment]
Hello, @markjessell
   How to solve this problem in Ubuntu?
Thanks a lot!

**Comment by markjessell** [comment]
Of course if the solution is use Debian, don't be afraid to say so!

**Comment by pytzcarraldo** [comment]
Hey Mark!

The bug appears to be due to the newest `pandas=1` release. So if you're using gempy with pandas 1.0 it will break.  If you downgrade your pandas to the previous version `pandas=0.25` it should work.  E.g. `conda install pandas=0.25` 

Cheers,
Alex

**Comment by markjessell** [comment]
Thanks Alex!

excellent, that fixed it (now I get another bug but that is another issue!)

cheers

Mark
