### ISSUE TITLE
Theano compiling problems

### ISSUE THREAD

**Issue by Geonigel3** [cgre-aachen/gempy#245]
**Describe the bug**
I am running the ch1-1_Basics jupyter notebook tutorial.  On the first executable cell I am trying to run I get an error from the line: import gempy as gp

The error is:
You can find the C code in this temporary file: C:\Users\Nigel\AppData\Local\Temp\theano_compilation_error_jwmbtdcq

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>
     80                     version,
---> 81                     actual_version, force_compile, _need_reload))
     82 except ImportError:

ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>
    104                         version,
--> 105                         actual_version, force_compile, _need_reload))
    106         except ImportError:

ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\theano\gof\vm.py in <module>
    673         raise theano.gof.cmodule.MissingGXX('lazylinker will not be imported if theano.config.cxx is not set.')
--> 674     from . import lazylinker_c
    675 

~\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>
    139             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 140                                              preargs=args)
    141             # Save version into the __init__.py file.

~\Anaconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2395             raise Exception('Compilation failed (return status=%s): %s' %
-> 2396                             (status, compile_stderr.replace('\n', '. ')))
   2397         elif config.cmodule.compilation_warning and compile_stderr:

. collect2.exe: error: ld returned 1 exit status_Windows-10-10.0.18362-SP0-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-3.7.4-64/lazylinker_ext/mod.cpp:976: undefined reference to `__imp__Py_TrueStruct'Error'ndefined references to `__imp__Py_NoneStruct' followow

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-31f924f4de46> in <module>
      4 
      5 # Importing GemPy
----> 6 import gempy as gp
      7 
      8 # Embedding matplotlib figures in the notebooks

~\Anaconda3\lib\site-packages\gempy\__init__.py in <module>
     14 sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))
     15 
---> 16 from .core.gempy_api import *
     17 import gempy.plot.plot as plot
     18 

~\Anaconda3\lib\site-packages\gempy\core\gempy_api.py in <module>
     31 # This is for sphenix to find the packages
     32 # sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))
---> 33 from gempy.core.model import Model, DataMutation, AdditionalData, Faults, Grid, MetaData, Orientations, RescaledData, Series, SurfacePoints,\
     34     Surfaces, Options, Structure, KrigingParameters
     35 from gempy.core.solution import Solution

~\Anaconda3\lib\site-packages\gempy\core\model.py in <module>
      9     Surfaces, Options, Structure, KrigingParameters
     10 from gempy.core.solution import Solution
---> 11 from gempy.core.interpolator import InterpolatorModel, InterpolatorGravity
     12 from gempy.utils.meta import setdoc, setdoc_pro
     13 import gempy.utils.docstring as ds

~\Anaconda3\lib\site-packages\gempy\core\interpolator.py in <module>
      4 
      5 import numpy as np
----> 6 import theano
      7 
      8 

~\Anaconda3\lib\site-packages\theano\__init__.py in <module>
    108     object2, utils)
    109 
--> 110 from theano.compile import (
    111     SymbolicInput, In,
    112     SymbolicOutput, Out,

~\Anaconda3\lib\site-packages\theano\compile\__init__.py in <module>
     10 from theano.compile.function_module import *
     11 
---> 12 from theano.compile.mode import *
     13 
     14 from theano.compile.io import *

~\Anaconda3\lib\site-packages\theano\compile\mode.py in <module>
      9 import theano
     10 from theano import gof
---> 11 import theano.gof.vm
     12 from theano import config
     13 from six import string_types

~\Anaconda3\lib\site-packages\theano\gof\vm.py in <module>
    681 except ImportError:
    682     pass
--> 683 except (OSError, theano.gof.cmodule.MissingGXX) as e:
    684     # OSError happens when g++ is not installed.  In that case, we
    685     # already changed the default linker to something else then CVM.

AttributeError: module 'theano' has no attribute 'gof'

**To Reproduce**
run the first cell.
**Expected behavior**
I expect the packages to import and theano to compile
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Edge]
 - Version [44.18362.449.0]
![snip_20200204230733](https://user-images.githubusercontent.com/32719599/73818981-5c2e4900-47a3-11ea-8f5c-8e2219e19316.png)

**Additional context**
 - running jupyter notebooks
also ran conda install m2w64-toolchain as that was suggested in the previous error.
also get same error with import theano from python propmpt.

**Comment by Japhiolite** [comment]
This may be due to a errorneous installation of Theano. At least, after looking up the Error message, associated Issues on the Theano repository point in that direction. 
For some, a clean re-install of theano did the trick. 
Have you installed theano with pip or conda?

**Comment by Leguark** [comment]
yes this totally seems a compiler error of theano. Try first to install theano independently (better with anaconda). If you are not able to make it run in windows. I recommend you to use the linux subsystem
