### ISSUE TITLE
Model from geological sections, no orientations

### ISSUE THREAD

**Issue by nlosacco** [cgre-aachen/gempy#247]
I am trying to create a model starting from some geological sections.
I have many, rather accurate sections from which I can infer a bunch of surface points but I have
no info on orientations whatsoever. How can I create the model though without giving orientations as an input?

**Comment by nlosacco** [comment]
Ok, maybe setting default orientation, then copying the same default for all surfaces makes the job

**Comment by javoha** [comment]
Hi nloascco,
your suggestion probably already does the trick, depending on the complexity of your model. Alternatively you can also infer some orientations from your cross sections. Gempy orientations are normal vectors of the surfaces. Depending on how flat (horizontal) or folded/dipped your surfaces are, you might get better results by determining a couple of orientations at different locations.

**Comment by Japhiolite** [comment]
On that note: Next to the `set_default_orientation` method in `data.py`, there's also the method `create_orientation_from_surface_points` which, in theory, should provide an orientation fitting a surface between at least 3 indipendent surface points.

I don't know however, how well this method is tested.
