### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#270]
**Is your feature request related to a problem? Please describe.**
I would like to contribute to gempy, but I do not know how to get started or what process to follow.

**Describe the solution you'd like**
Please add a Contributing.md file which explains how to contribute.

**Describe alternatives you've considered**
I am not aware of any alternatives. I think it is the best practice to have a Contributing.md file in the repo.

**Additional context**
Here is how PyVista did it: https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md

**Comment by pytzcarraldo** [comment]
Addressed by PR #294
