### ISSUE TITLE
Integrate with Google Earth

### ISSUE THREAD

**Issue by agzimmerman** [cgre-aachen/gempy#277]
**Is your feature request related to a problem? Please describe.**
Create a link between GoogleEarth and gempy: possibility to load data from .kml files, generate models accordingly, and finally export models back to GoogleEarth (projection of geological maps as GeoTiffs). 

**Describe the solution you'd like**
Similar to *remote_geomod* (https://github.com/cgre-aachen/remote-geomod): adding flexibility to quickly generate models for a specific region, determining region from GoogleEarth, add interface and orientation points. 

**Describe alternatives you've considered**
remote_geomod - working, in principle - but tighter integration in gempy desirable.

**Additional context**
![tmp](https://user-images.githubusercontent.com/1070677/75384568-9b514500-58de-11ea-9233-7f4b1ace1d59.jpg)

**Comment by flohorovicic** [comment]
## Link to gdal

A critical aspect of this link could be the use of gdal - for coordinate transformation, and to generate the GeoTiff files. We certainly don't want to force every gempy user to go through the pain of installing gdal. 

So, we should implement it with an explicit module load, i.e.:

`import gempy.remote_geomod`

Which would then have the dependency to load gdal. Did I get this right? How would these additional dependencies be added, in fact? Would we leave it to the user to then install gdal?

And, if I understand correctly @alexanderzimmerman, @pytzcarraldo it should be placed in "addons"? Or "assets"?

**Comment by flohorovicic** [comment]
We actually need something like

`gempy.geographic`

to handle geographic data structures, etc.

**Comment by pytzcarraldo** [comment]
I would classify `remote_geomod`  as belonging `addons` 🤔 
I guess geographic data structures could be considered `utils`? 

In any way we should refactor the confusing naming scheme of `addons`, `utils` and `assets` and then define them properly in the contribution guidelines

**Comment by flohorovicic** [comment]
Yes, good point - I'll continue fixing bugs, we can then see where to finally place the modules...

**Comment by AlexanderJuestel** [comment]
If no one disagrees, I would move this issue to GemGIS shortly :)
