### ISSUE TITLE
Add missing docstrings to all __init__.py files 

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gempy#283]
Originally this issue only said "Decide on general format of Readme files", but now it supersedes #281 and I am adding more details - @alexanderzimmerman  2020/04/07

During the GemPy retreat, we identified an issue that the purposes of the sub-folders within the gempy folder, e.g. "assets" and "addons", were unclear.

A solution we thought of was to put a README.md in each folder.

An alternative would be to document each sub-folder as a sub-package (which they technically are) and simply add docstrings to their `__init__.py` files.

**Comment by flohorovicic** [comment]
# Suggestions for README.md files

## General comments

- place one in each subfolder of repository
- name: README.md
- markdown format (some info here: [https://www.makeareadme.com](https://www.makeareadme.com))

## Layout

# README.md

**Comment by alexanderzimmerman** [comment]
I think that the "Testing" and "Contribution guidelines" sections are important for our top level README but not necessarily for every lower level README. What is most important is the "Folder content".

Also the original problem was that it was unclear how we were organizing "assets", "addons", and "utils". So as long as there is enough information to make this clear, I think it's good.

**Comment by pytzcarraldo** [comment]
Yeah I agree that subfolder readme files should not contain any contribution guidelines. If relevant, they should only reference / link to the CONTRIBUTION.md located at the project top level

**Comment by flohorovicic** [comment]
I think it is important to see, in each Readme:

- are files in this folder part of the testing system
- am supposed to contribute here, or is this something for the "core" developers.

Not sure about the second point - as we expect _technically_ everyone to contribute to all gempy parts?

**Comment by alexanderzimmerman** [comment]
> I think it is important to see, in each Readme:
> 
> * are files in this folder part of the testing system

I think that files that are particularly for the testing system should be in the test folder.

> * am supposed to contribute here, or is this something for the "core" developers.
> 
> Not sure about the second point - as we expect _technically_ everyone to contribute to all gempy parts?

I don't think that we should document this in distributed README's. If we want to direct people about where they should and should not contribute, then that should go into Contributing.md.

**Comment by alexanderzimmerman** [comment]
@flohorovicic , I am not sure what is meant by "(Short description for files in this folder)" in the proposed template.

Maybe we are looking at this wrong.

The problem we identified in the retreat was that the purpose of the different folders was unclear.

Putting more thought into this now, I think that we should view them as subpackages and ensure that every __init__.py file has a docstring. The docstring documents the purpose of the subpackage.

**Comment by alexanderzimmerman** [comment]
It's unclear to me why a separate issue was created for this discussion. There is no information at the issue #281. I'm going to close that one and rename this one.

**Comment by pytzcarraldo** [comment]
> Putting more thought into this now, I think that we should view them as subpackages and ensure that every __init__.py file has a docstring. The docstring documents the purpose of the subpackage.

Sounds like a good solution to me!

**Comment by flohorovicic** [comment]
Yes, I generally agree with the __init__ and package structure. However, two points:

- the README.md files are rendered as text on the GitHub pages - can be useful for people looking on GitHub.
- We also wanted to include information on the files, especially: are they part of the automated test system (and, therefore, tests are also essential, when something is added here), and: how tightly are these files integrated into gempy (part of full gradient-based part, more experimental, helper functions, etc.). 

Of course, all points could (and maybe should) be added in the contributions.md file - but the idea was that it could be useful to have this information directly in the directory.

**Comment by AlexanderJuestel** [comment]
Will be fixed in #640
