### ISSUE TITLE
Pole sampling using van Mises Fisher distribution for orientations

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#30]
@flohorovicic  we should invite Evran to our repository so I can assign it to him

**Comment by Leguark** [comment]
for Lihuan

**Comment by pytzcarraldo** [comment]
added class `gp.utils.input_manipulation.VanMisesFisher` in my development branch with method `.rvs(size=n)` for sampling to mimic `scipy.stats` distributions (for my ABC stuff). this will not work with pymc though

**Comment by elimh** [comment]
I figured out how to sample from the vMF distribution using pymc2 and can add a tutorial notebook (like ch. 3 but for orientations) soon. In the long run it would be cool to solve problem #2458 of pymc3 so that the vMF distribution can be used directly in pymc.

**Comment by Leguark** [comment]
Is this just waiting for a test?

**Comment by AlexanderJuestel** [comment]
This may be related to #475, maybe we can solve both at some point together
