### ISSUE TITLE
Arbitrary sections are not defined as grid is not active

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#306]
**Describe the bug**
When trying to plot an arbitrary section (`gp.plot.plot_section_by_name()`) that was defined earlier (after the model initiation and before modeling), the plotting function returns that no sections have been defined (see screenshot). By executing the command `geo_model.set_section_grid(section_dict)`, only the "regular" grid is returned as active grid.

**Expected behavior**
The `geo_model.set_section_grid(section_dict)` should set the sections grid active as well so that sections can be plotted by name after the model has been computed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45469915/75470005-43731680-5990-11ea-8876-f291c826fcee.png)
![image](https://user-images.githubusercontent.com/45469915/75470053-5a196d80-5990-11ea-867a-df39271f0cbb.png)

**Additional context**

**Comment by AlexanderJuestel** [comment]
Workaround: The grid can be activated by calling `geological_model.set_active_grid("sections")`

**Comment by Leguark** [comment]
is this still happening in the current master?

**Comment by AlexanderJuestel** [comment]
> is this still happening in the current master?

No, it works now without setting the grid active manually.
