### ISSUE TITLE
Decide on location of template (xml) files

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gempy#309]
**Is your feature request related to a problem? Please describe.**
I have a couple of .xml-template files for exporting gempy line and point symbols to .kml (for viz in GE and/or other GIS systems). Do we have a place where such files should be located @alexanderzimmerman @pytzcarraldo ?

**Describe the solution you'd like**
Location, location, location

**Describe alternatives you've considered**
I could probably include the templates as strings directly in the Python modules (gempy.geographic) - but somehow not a nice solution...

**Comment by Japhiolite** [comment]
This could also be interesting for the export function for Moose, which creates a moose input file/template. Such an example file could also be stored in this location (or in a different subfolder or something)

**Comment by alexanderzimmerman** [comment]
I missed this until now.

@flohorovicic , I think they should be located as close as possible to where they are used. Where is the script that uses them?

Also do they have to be XML or can they be JSON instead? JSON is directly interpretable as a Python dict, which is the data type you should probably use if they were in the Python module itself.

**Comment by alexanderzimmerman** [comment]
Also I'm not sure that it would be a bad solution to just maintain a template as a Python dict in the Python module if that is what you need anyway. It is just as clear as a JSON (and at least as clear as an XML).

**Comment by flohorovicic** [comment]
Main use I saw for now was for gempy.geographic, e.g. xml-template files for point and line objects (to be loaded with GoogleEarth). I used the option before to include them as docstrings directly in the python modules. Was just not sure if this would be a good option when, for example, they would be used by multiple modules. But for now, that option would be fine.

**Comment by alexanderzimmerman** [comment]
How do you use the xml-template?

**Comment by alexanderzimmerman** [comment]
@flohorovicic I'm closing this because I don't think there's more input that @alex-schaaf or I can provide and it's not clear to me what you still need. Feel free to re-open it (and continue the discussion).

**Comment by AlexanderJuestel** [comment]
Hey, we could pick that up in GemGIS at some point as @flohorovicic mentioned before.

**Comment by alexanderzimmerman** [comment]
Ah I missed that this was in https://github.com/cgre-aachen/gempy/projects/18 .

Do re-open this issue if you're still tracking it.

Also I see that the project board is automated and now this was moved to "merged to master". I'll just remove that automation from the project board.
