### ISSUE TITLE
All Pull Request Docs Checks fail

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#311]
**Describe the bug**
All open Pull Requests have a failing check related to Sphinx documentation, e.g. [this](https://github.com/cgre-aachen/gempy/pull/308/checks?check_run_id=473026979) and [this](https://github.com/cgre-aachen/gempy/pull/294/checks?check_run_id=479273309).

**To Reproduce**
Make a PR or just look at the Pull Request Docs Check / docs (pull_request) in any open PR.

**Expected behavior**
Particularly with PR #294, I would not expect any changes to how documentation is handled, yet [the check fails with a configuration error](https://github.com/cgre-aachen/gempy/pull/294/checks?check_run_id=479273309).

**Screenshots**
![image](https://user-images.githubusercontent.com/9367569/75666944-056b4080-5c77-11ea-8902-ee9432121a44.png)

**Desktop (please complete the following information):**
The remote build system used for all PR's

**Additional context**
I think @Leguark mentioned that some new checks were added for the GemPy retreat, so maybe this is related to a check we didn't have before.

**Comment by Leguark** [comment]
Yes, this was an action that I activated for 1 hour because apparently you cannot have actions that are not active. All the new commits do not go through that check
