### ISSUE TITLE
How layers influence each other?

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gempy#314]
**How do the layers within a series influence each other during the calculation in GemPy?**
Regarding my attached graphic I think that currently variant 1 is the case. But in principle, in my opinion, it would be possible to implement variant 2 in GemPy. But for this, the definition of the layers would have to be adapted in a way that it is possible to define for each layer individually by which other layers it is influenced and one would have to be able to define in which order the calculation of the layers is executed.
![SurfaceInfluence](https://user-images.githubusercontent.com/59735059/75761324-2b591980-5d39-11ea-8863-e4f22645ee0f.png)

**Comment by javoha** [comment]
Hi domist07,
the interpolation in GemPy is based on Universal Cokriging. Thus all surfaces (meaning the input data related to these surfaces) that belong to one series influence each other. This is also desired as we consider these geolgoic units to have sedimented under roughly the same geometric setting, forcing them to be more or less parallel. In case of unconformities new series allow for a separate interpolation for a different set of surfaces. For more backgorund maybe check out the original literature:

*Calcagno, P., Chilès, J. P., Courrioux, G., & Guillen, A. (2008). Geological modelling from field data and geological knowledge: Part I. Modelling method coupling 3D potential-field interpolation and geological rules. Physics of the Earth and Planetary Interiors, 171(1-4), 147-157.*

*Lajaunie, C., Courrioux, G., & Manuel, L. (1997). Foliation fields and 3D cartography in geology: principles of a method based on potential interpolation. Mathematical Geology, 29(4), 571-584.*

Can you maybe give an example of a geologic setting where you want one surface to influence the location of another but not vice versa?

**Comment by domist07** [comment]
Thanks for the explanation.
I have no example where this is absolutely necessary. The question came to my mind because I have seen that in Leapfrog Works the layers are calculated one after the other and you can specify which ones affect them. I was asking myself, how this makes a difference in the resulting model.
