### ISSUE TITLE
Create some fixture models that are used for all tests

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#319]
At the moment for many of the test that we need gempy models we create similar geological modes. We should create some session fixture models -with different features -- and reuse them for all tests

#273

**Comment by javoha** [comment]
What do you think about using the model from my poster. It features quite some things we need to test (Folding, faulting, unconformity).
<img width="472" alt="Model_fixture" src="https://user-images.githubusercontent.com/38279459/76295496-032b6680-62b5-11ea-981d-96aa4b631581.png">

**Comment by pytzcarraldo** [comment]
Hell yeah! Is the input data available in the repo? If so, where?

**Comment by javoha** [comment]
It was only on my (old) remote branch - added with #340

**Comment by Japhiolite** [comment]
Concerning further models: From the work on SHEMAT-Suite, I remember that we have an extra Models repository, containing models designed to test a specific process etc. (conduction, convection, elder problem, ...). And then a few models with coupled processes.
Would it make sense, to adapt this in terms: Simple models which test one _process_ / feature of gempy (faulting or folding or ... ) and some, like Jan's, which combine several features?

**Comment by pytzcarraldo** [comment]
@WestfalNamur was looking into streamlining the loading of example models in gempy and organizing them a bit. Any update on that so far?

Depending on how many example models we amass, it might become useful to outsource them into a second repository like `gempy-examples` 🤔 Then again, input data files are relatively tiny, so they shouldn't bog down the size of gempy too much.

**Comment by javoha** [comment]
Regarding @Japhiolite s comment. I had a set of simple models in my thesis, that should cover a lot of those simple cases (`notebooks/data/input_data/jan_models)`. I think it makes sense to use those as a starting point and see what else we need?
![GeologicModels](https://user-images.githubusercontent.com/38279459/77627994-032f9580-6f48-11ea-94b2-7df5eaf4d414.png)

**Comment by Leguark** [comment]
Yes, I think for the examples we need a different repo

**Comment by pytzcarraldo** [comment]
How would we go about importing them into GemPy? Something like gp.examples.load_example("name") and it downloads the input data files from the examples repo?

**Comment by Leguark** [comment]
yes.. with csv it works. You can check in notebooks/examples/implicitBenchmark
