### ISSUE TITLE
Vista plot_topography

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gempy#321]
You have missed few letters in your code.
In the file gempy/plot/vista.py you had to add in the line 639 _[0]_ after _geological_map_ so it looks like this:
`sel = np.round(self.model.solutions.geological_map[0]).astype(int)[0]`
Otherwise it produces an error.

**Comment by javoha** [comment]
Thanks alot for catching this and letting us now. The vista functionality ist still quite WIP but it is really great that you help us with testing and improving it. 
I will add the fix to the next pull request.

**Comment by Leguark** [comment]
@javoha if this is close with the merge just close it Jan
