### ISSUE TITLE
Fault thickness and damage zone

### ISSUE THREAD

**Issue by PeterBetlem** [cgre-aachen/gempy#326]
**What is your question?**
First of all, great job on gempy so far! I have been playing around with the code trying to create faulted cross sections, but have yet to figure out how to implement changing fault core/gouge thicknesses along a section. In addition, would anyone have any suggestions on adding damage zone dynamics to the models as well? E.g., faulting-related fracturing?

**Comment by pytzcarraldo** [comment]
Hey @PeterBetlem!

GemPy is currently designed for the (stochastic) modeling of structural framework models only, and does not have any support for fault core/gouge thickness modeling. We also currently have no plans to add this feature, as far as I am aware. The same goes for damage zone dynamics.

As a fault in GemPy is created from a scalar field, it could be possible to easily use a distance/threshold on the scalar field around the fault to add a fault zone around a fault. But this is just a thought that popped into my had... not sure how much work that would actually be.

Cheers,
Alex

**Comment by javoha** [comment]
Maybe an even easier workaround would be to create two parallel faults in a single series that represent the boundaries of the fault zone (eg. by just copying the original input data and just moving it to both sides). Of course it highly depends on what you actually want to do with this zone/information/model.

**Comment by Leguark** [comment]
Linked to #53

**Comment by PeterBetlem** [comment]
My apologies for the late response. Thanks for the feedback and suggestions @pytzcarraldo @pytzcarraldo , though was expecting as much. I was actually planning on implementing the distance/threshold solution you mentioned, @pytzcarraldo , though figured asking beforehand to prevent double work would be the safest bet :). I’ll see what I end up doing, and in case it turns into a useful addon, keep you in the loop.
