### ISSUE TITLE
Increase the number of formats to be read

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#33]
So far we only accept csv but pandas is waaay more tolerant that this. It cannot be to difficult to implement pandas power directly in gempy

**Comment by michiboo** [comment]
Hi, Can I try this issue?

**Comment by AlexanderJuestel** [comment]
@Leguark, I was just wondering if that was resolved with PR #346 were the possibility of reading pandas dataframes was implemented? :)

**Comment by AlexanderJuestel** [comment]
Hey @Leguark, I think that can be closed?

**Comment by AlexanderJuestel** [comment]
I take the liberty and close that here :) 

GemPy is now capable of also using Pandas DataFrames directly. In addition, GemGIS will extend the support of even more especially spatial data formats (shape files, geojson, geopackages, etc.)

**Comment by Leguark** [comment]
sure thanks!
