### ISSUE TITLE
nptying in setup.py

### ISSUE THREAD

**Issue by prisae** [cgre-aachen/gempy#331]
I just tried to create a minimal `environment.yml` for a project in which I also have GemPy.

Having:
```
name: gallery

channels:
  - defaults
  - conda-forge
dependencies:
  - ... all my conda dependencies
  - pip:
    - gempy
```
did not work. Turns out that it was missing `nptyping`

`nptyping` is specified in `gempy/requirements.txt`, but it is missing in `gempy/setup.py`. I think it should be included in the setup file.

**Comment by Leguark** [comment]
yes, we screw in the last patch. I am already preparing a hotfix that will go live this week. Thank you for the contribution!
