### ISSUE TITLE
Setting section grid after the first time results in a bug.

### ISSUE THREAD

**Issue by WestfalNamur** [cgre-aachen/gempy#334]
Calling "geo_model.set_section_grid(section_dict)" more then once leads to
"AttributeError: 'numpy.ndarray' object has no attribute 'append'".

**Reproduce**
1. Init geo_model with gp.create_model()
2. Set section grid the 1st time with geo_model.set_section_grid()
3. Set section grid the 2nd time with geo_model.set_section_grid()

**Expected behavior**
Setting section grid new by adding or replacing old dict entries.

**Environment**
Ubuntu 18.04
Python 3.6.9
see gempy/requirements.txt

**Additional context**
Resetting the section grids is required to be able to interactively work with the geo_model in form of a service.

**Comment by Leguark** [comment]
fixed and added test 9158fd9
