### ISSUE TITLE
Bugs in Documentation

### ISSUE THREAD

**Issue by TobiasGlaubach** [cgre-aachen/gempy#338]
Hi everyone, 
first of all thanks for all the work you put into this awsome open source software! Keep up the good work!

Not sure if this is the right location to report some errors and bugs in the tutorials and documentation websites under gempy.org. If not, please excuse this issue and please point me to the right spot.

When I go through the tutorials in https://www.gempy.org/chapter-i the following links result in 404:

- https://nbviewer.jupyter.org/github/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7-Adding_Topography.ipynb
- https://nbviewer.jupyter.org/github/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch-1-2b-ModelClass.ipynb
- https://nbviewer.jupyter.org/github/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-5-InteractivePlots-WP.ipynb
- https://nbviewer.jupyter.org/github/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7b-Adding_Topography-vtk.ipynb

Also when I try to go from:
https://www.gempy.org/documentation-1

with the links at the end
**Indices and tables:**
- Index --> points to empty page (https://gempy.readthedocs.io/genindex.html)
- Module Index --> results in does not exist yet (https://gempy.readthedocs.io/py-modindex.html)

within the Data Manipulation notebook (https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-2_Data_Manipulation.ipynb) I saw, that  the code for In [12]: is the following:
```
fr = np.zeros((4, 4))
fr[2, 2] = True
faults.set_fault_relation(fr)
```
but within the dataframe shown in Out [12]: all entries are false. Is that right?

Thanks again for the good work!

**Comment by Leguark** [comment]
Hi @TobiasGlaubach, thank you for this detail examination to the documentation. I always have the feeling that there is always a documentation decay over time. We are planning to move to sphinx gallery #273 to automatize the process as much as possible but in the meantime... @fastamo can you fix the links of those notebooks? Thanks

Index link got fixed alone
Module index link removed

Regarding the Data Manipulation, only the upper triangle of the matrix can be set to true, i.e. rows offset columns. I just added the explanation in the notebook, thanks for the feedback!
