### ISSUE TITLE
gp.map_series_to_surfaces(...) does not set all surfaces as isActive == True

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#348]
**Describe the bug**
When executing gp.map_series_to_surfaces(....) only 12 of the 14 surfaces (12 faults, 1 layer and basement, all in a separate series) have the property `isActive == True`, two surfaces remain at `False` and cannot be activated. This will result in an error when computing the model later on as the length of labels is not equal to the length of the available data. A quick fix is shown below.

**To Reproduce**
A link can be provided to the private repository. 

**Expected behavior**
gp.map_series_to_surfaces(....) should set all surfaces to `isActive == True` at once when executing.

**Screenshots**
![image](https://user-images.githubusercontent.com/45469915/77997757-3b601b00-7330-11ea-8a7a-3e70b8298bf2.png)

![image](https://user-images.githubusercontent.com/45469915/77997110-1f0fae80-732f-11ea-94e3-e66c1b200597.png)

**QuickFix**
modelA4.surfaces.modify_surface_values(7, 'isActive', True)
![image](https://user-images.githubusercontent.com/45469915/77999149-83803d00-7332-11ea-9c07-ec522f61d575.png)
modelA4.surfaces.modify_surface_values(12, 'isActive', True)
![image](https://user-images.githubusercontent.com/45469915/77999405-ea055b00-7332-11ea-80eb-e4965d62e167.png)

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version: 1.01-1175-gb8334154 (latest version as of 31.03.2020)

**Comment by Leguark** [comment]
Do they have enough geometric data?

**Comment by AlexanderJuestel** [comment]
No, they did not. Got a little confused with my data there. Too many fault branches....Thanks for the hint :)
