### ISSUE TITLE
Question of Gempy

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#349]
**Hello,I have a question about how to resolve the fault contact between metamorphic rock formations in Gempy, the examples in Gempy are mostly about sendimentary,I want to know how to do that,thank you.Looking forward to your reply soon.**

**Comment by Leguark** [comment]
So far there is not a good support for dikes or other type of unstructured geometries. The only way would be to create a close series which erodes the rest of the layers but it is not by no means ideal.

We are already working on adding explicit representation and hierarchical modeling #271 to be able to create these shapes properly

**Comment by wh19971014** [comment]
How to use erosion contact，is there tutorial？

**Comment by AlexanderJuestel** [comment]
Hello, 

there is a tutorial here: https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_4_onlap_relations.html#sphx-glr-tutorials-ch1-fundamentals-ch1-4-onlap-relations-py
