### ISSUE TITLE
Change the degree of universal drift

### ISSUE THREAD

**Issue by GeorgeLiang3** [cgre-aachen/gempy#351]
**Describe the bug**
The functionality to switch between the degree of universal drift is not properly designed  

for second order drift:
modify_kriging_parameters('drift equations',[9,9]) --> modify_kriging_parameters('drift equations',[2,2]) (this is not woriking at the moment)

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.modify_kriging_parameters('drift equations',[9,9]) 
2.modify_kriging_parameters('drift equations',[2,2]) is not implemented at the moment
3.
...

**Expected behavior**
The user should just need to state what degree of universal drift they want but don't worry about the drift equations are 3 by 3 or 9 by 9

**Desktop (please complete the following information):**

  * GemPy Version
    * if cloned from GitHub: provide Git commit id : b934f07

**Comment by javoha** [comment]
Hi George, even though you are internal developer- can you fill out the form for the issue to give a little more context. It makes it a lot easier for everyone to keep track (and help). Do you plan on working on that yourself?

**Comment by GeorgeLiang3** [comment]
> Hi George, even though you are internal developer- can you fill out the form for the issue to give a little more context. It makes it a lot easier for everyone to keep track (and help). Do you plan on working on that yourself?

Hi Jan, Thanks for the comment. No, I am not going to work that by myself, actually, I created that just as a reminder for me and Miguel, after the conversation with him, maybe in some stage we will fix this. It is a simple function bug. I think the sentence itself is self-evident, anyway, as you have mentioned, I will add more details. Cheers

**Comment by Leguark** [comment]
thanks guys!
