### ISSUE TITLE
Adding vertical exaggeration to the new 2D and 3D plot api

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#353]
**Is your feature request related to a problem? Please describe.**
When plotting a cross section with `gp.plot.plot_section(geo_model,...)` not all features are shown in the legend even though they appear on the cross section (see Screenshot). This is the case for the blue fault which has no interface point in the displayed cell but the fault plane is still shown. 

**Describe the solution you'd like**
All visible elements in the cross section should be referenced in the legend, this also includes the basement as the map/legend would be incomplete without it. 

![Ashampoo_Snap_Montag, 6  April 2020_09h20m31s_008_](https://user-images.githubusercontent.com/45469915/78533769-c5edc200-77e9-11ea-882e-7547c637f288.png)

**Comment by AlexanderJuestel** [comment]
A first work around ist using the new plotting API and `plot_2d(...)`. However, it seems that no vertical exaggeration is implemented in `plot_2d(...)`  as it was in to old API so the result cannot be verified completely.

![image](https://user-images.githubusercontent.com/45469915/78543221-a8742480-77f8-11ea-9cfb-8f878b8d4c33.png)

![image](https://user-images.githubusercontent.com/45469915/78543305-c772b680-77f8-11ea-85f3-cd8305b772af.png)

**Comment by AlexanderJuestel** [comment]
@Leguark I took the freedom to add "and 3D" to the title as well since there is no vertical exxegeration in `gp._plot.plot_3D(geo_model,...)` yet either

`

**Comment by Leguark** [comment]
awesome! Thanks for the hint1 ;)
