### ISSUE TITLE
How to define non-sedimentary contact

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#354]
Hello,i have a question about how to define non-sedimentary contact,the following picture shows dinfferent lithology is fault contact,examples in GemPy is about Sedimentary rocks , Sedimentary rocks are in contact with different layers of rock,i try to write code to see what's going on,but the results are far from what they had imagined.

**Comment by wh19971014** [comment]
**Above is the picyure--the sectional view**
![5bacd2e2f8d366a006b24c3843d3390](https://user-images.githubusercontent.com/60054308/78561300-0da43600-784a-11ea-9441-2abfe931d0d2.png)

**Comment by wh19971014** [comment]
the following is the picture--the sectional view
![Uploading 5bacd2e2f8d366a006b24c3843d3390.png…]()

**Comment by wh19971014** [comment]
the following is the picture--the sectional view
![5bacd2e2f8d366a006b24c3843d3390](https://user-images.githubusercontent.com/60054308/78561613-a20e9880-784a-11ea-99dc-2927c6804549.png)

**Comment by Leguark** [comment]
If I understand your question, you will need to use "Erosion" contact between the surfaces that are does not belong to the same stratigraphic pile
