### ISSUE TITLE
Trouble of adding faults

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#355]
I want to add 15 faults,i add them one by one,but when i add 9th,it occured error.When i added 8 faults,i go to run the code ,it succeed.The following picture shows the error when i add 9th fault.
![Inked3ae5f0fd044ebb84a479bdd9bf29c25_LI](https://user-images.githubusercontent.com/60054308/78562262-a8e9db00-784b-11ea-8e47-c8392e16d61f.jpg)

**Comment by Leguark** [comment]
Does it have at least 2 surface points and 1 orientation? We really need to improve error handling in gempy

**Comment by wh19971014** [comment]
yes，it have at least 2 surface points and 1 orientation of each fault
