### ISSUE TITLE
How to define the direction of the section

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#356]
Examples of define  the direction of the section in  GemPy are all "X",or "Y",or Z",i want to see the profile of the other orientation, i don't know how to define it in the code.

**Comment by Leguark** [comment]
There is a tutorial for that. Let me know if that is not clear

https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7a-CrossSections.ipynb
