### ISSUE TITLE
Question about defining rocks

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#358]
Hello, i want to know how to define vertical or near-vertical sedimentary strata in GemPy,and in particular,many near-vertical rock formations touch each other,thank you.

**Comment by javoha** [comment]
Hello @wh19971014 ,

Gempy is an implicit modeling tool as of now. That means it will interpolate the model based on your data. Therefore you model vertical rock strata the same way as horizontal strata. Just add your data and order the surfaces accordingly. 
I am not sure what you mean by "they touch each other". It is always very helpful if you can show an example of your problem and what you expect it to look like.

Best wishes,
Jan
