### ISSUE TITLE
How to make it look like there is lithologic fill around model?

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#367]
In the 1st picture, we can see there is lithologic fill around 3D geological body model,but in the 2nd picture,we can't see it just like 1st picture.And 2nd picture also be fiied with lithology,but we can't see lithology around it,so how to achieve it, thank you?
![1](https://user-images.githubusercontent.com/60054308/78874410-ef734b80-7a7e-11ea-9b45-53c61571c779.png)
![3D Picture](https://user-images.githubusercontent.com/60054308/78874425-f437ff80-7a7e-11ea-82db-748f709a17fc.png)

**Comment by javoha** [comment]
If I understand you correctly, you want to plot a *block model* instead of just the *surfaces*. The easiest way to do that right (as far is I know) now is accessing the new beta plotting api, using the following code:

```Python
gpv = gp._plot.Vista(geo_model)
gpv.plot_structured_grid("lith")
gpv.show()
```

Cheers,
Jan
