### ISSUE TITLE
Adding Elevation data

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#368]
I download Elevation data from the internet,and i transform it to .tif format,how can I add it to the 3D geological model to make the model's surface's topography  look like the real. In GemPy's example,topography source is mostly 'random',so how can I achieve it,thank you.

**Comment by AlexanderJuestel** [comment]
Hello @wh19971014,

Adding topography data to your model works for example the following (for the models that I create):

`topo = model_name.set_topography(source='gdal',filepath='File_Path_and_Name.tif')`

You can also use the common Matplotlib commands to change the labels of your plot etc. 
Here just a screenshot of how it works for me:
![image](https://user-images.githubusercontent.com/45469915/78897397-66eeae00-7a72-11ea-9baf-23922df25183.png)

**Comment by javoha** [comment]
Thanks @AlexanderJuestel! @wh19971014 - hopefully this solves your problem. I wil close the issue, feel free to reopen it if the issue persists.
