### ISSUE TITLE
Adding Hillshades/Topography to background of geological map

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#370]
**Is your feature request related to a problem? Please describe.**
When plotting a geological map with `gp.plot.plot_map(geo_model)` it could be a nice and sometimes useful addition (for interpreation and verification purposes) to display the topography as hillshades/schummerung (geology on topography) below the geological map. Currently, the geological map is relatively flat and features in the morphology can not directly be related to the topography (see screenshot below).

![image](https://user-images.githubusercontent.com/45469915/78991128-80f2c400-7b38-11ea-8e57-e25c355156a6.png)

**Describe the solution you'd like**
I would like a plot that shows the hillshades below (the extent of the screenshot below is larger than the model area) the geological map, combining the screenshot above and below (make geology slightly transperent though - the alpha parameter is missing though). 

![image](https://user-images.githubusercontent.com/45469915/78992668-12176a00-7b3c-11ea-8608-21a0329c5c77.png)

**How could this be implemented?**

There is a nice tutorial on https://www.neonscience.org/create-hillshade-py

You basically convert the grid to an array (topo.values) and calculate the gradient and slope of the array/raster. Based on a provided azimuth and angle_altitude together with the slope, the shaded color value for each combination of x and y can be calculated. Then the new array can be plotted below the geology to get a nice 3D effect.

**Comment by flohorovicic** [comment]
Good idea! I actually have a simple which I used for the sandbox (most importantly _without_ gdal, which is always a bit of a headache...). Here the code snippet: 

`
azdeg = 135. # azimuth of light source
altdeg = 60. # altitude of light source
ve = 1. # vertical exaggeration
from matplotlib.colors import LightSource
ls = LightSource(azdeg=azdeg, altdeg=altdeg)
rgb = ls.shade(z, cmap=plt.cm.copper, vert_exag=ve, blend_mode='hsv')
plot.ax.imshow(rgb, origin='lower left', aspect='auto')
`

Here a quick example, just generated with a sinc function (light source top right):

![Unknown-15](https://user-images.githubusercontent.com/1070677/78994234-d383ae80-7b3f-11ea-989c-2f1c947b9de9.png)

**Comment by flohorovicic** [comment]
I am just experimenting with topography generation, so that fits quite well. The example is in the commit: 41aa5ffb272822c0c228a9b5fe6299a800bc2154

**Comment by AlexanderJuestel** [comment]
@flohorovicic, below I have put a geological map created with GemPy and below the underlay with hillshades. The topographic values are contained in the following variable: `topo = geo_model.grid.topography.values_3D[:, :, 2]`. Converting these with the hillshade function presented presented at https://www.neonscience.org/create-hillshade-py will return to an array that is ready to be plotted below the Geological Map which is shown below. 

It already looks quite good, the colors just have to be adapted and the remaining input data has to be plotted. But you can already clearly see that the geological boundaries in the southwestern and southeastern corner, may they be right or wrong now, are dependent on the morphologic features shown in the hillshade.  

Hillshade Function:
```
def hillshade(array,azimuth,angle_altitude):
    azimuth = 360.0 - azimuth 
    x, y = np.gradient(array)
    slope = np.pi/2. - np.arctan(np.sqrt(x*x + y*y))
    aspect = np.arctan2(-x, y)
    azimuthrad = azimuth*np.pi/180.
    altituderad = angle_altitude*np.pi/180.
    shaded = np.sin(altituderad)*np.sin(slope) + np.cos(altituderad)*np.cos(slope)*np.cos((azimuthrad - np.pi/2.) - aspect)
    return 255*(shaded + 1)/2 
```

![image](https://user-images.githubusercontent.com/45469915/79071829-0d8ab700-7cde-11ea-9ae0-665a0371cb29.png)

The map below was created using:

```
modelA1._cmap = ListedColormap(list(modelA1.surfaces.df['color']))
modelA1._norm = Normalize(vmin=0.5, vmax=len(modelA1._cmap.colors) + 0.5)
plt.imshow(hill_topo,origin='lower', extent=modelA1.grid.topography.extent, alpha = 0.75)
plt.imshow(geomap, origin='lower', extent=modelA1.grid.topography.extent, alpha = 2, cmap=modelA1._cmap,norm=modelA1._norm, zorder=-100)

```


![Ashampoo_Snap_Sonntag, 12  April 2020_16h46m51s_023_](https://user-images.githubusercontent.com/45469915/79071842-19767900-7cde-11ea-8098-c105814c2005.png)

**Comment by AlexanderJuestel** [comment]
Here also how to do it with LightSource.

![image](https://user-images.githubusercontent.com/45469915/79115772-079ce080-7d87-11ea-9316-00b089623730.png)

**Comment by Leguark** [comment]
wow that looks pretty awesome. Dont you want to try to create your first pull request to practice since you have all the code already there?

**Comment by AlexanderJuestel** [comment]
I will certainly try the next few days :)

**Comment by AlexanderJuestel** [comment]
@Leguark, if this was added to GemPy in version 2.2, please feel free to close the issue ;)

**Comment by Leguark** [comment]
True thanks~
