### ISSUE TITLE
Fault Surface Colors in new 3D plotting API not displayed correctly

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#371]
**Describe the bug**
When using the new 3D plotting API it was noticed that the color of the fault interfaces do not match with the colors of the computed fault surfaces (see screenshot, the faults go from left to right). The colors for the stratigraphic interfaces are correct though. (The light blue interfaces have a dark blue surface, the purple interfaces a yellow surface, the yellow interfaces a (light) blue surface...)

**Expected behavior**
All surfaces should have the color that was attributed to the respective surface during surface mapping, especially when using different colors for fault and not just one color. 

**Screenshots**
![ModelA1_3D_Plot3](https://user-images.githubusercontent.com/45469915/79038289-7ee04200-7bd8-11ea-8473-598080cc2895.png)

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version
    * if cloned from GitHub: 1.01-1193-gb934f07

**Additional context**
It is not a big issue but should be fixed at some point for consistency purposes

**Comment by AlexanderJuestel** [comment]
In connection with issue #386 I tried to manually add surfaces to the 3D visualition with the `fmts` argument in the `plot_surfaces_all()`-function (see screenshot 1). The code for plotting is shown in screenshot 2. The fmts argument seems not be taken in `gp._plot.plot_3d(geo_model...)`, hence the workaround. When applying the workaround, I would only like to display the "SandgewandFault" and "EasternGrabenJump", I noticed that the surface for "EasternGrabenJump" is in the wrong place and should actually be where the surface data is (purple points a little further down, screenshot 3). There seems to be a mix up with the attribution of surfaces. This mix up was also confirmed for other surfaces.

@pytzcarraldo 

Screenshot 1:
![image](https://user-images.githubusercontent.com/45469915/80193041-69c3d400-8618-11ea-9677-d6784e7afeff.png)

Screenshot 2: 
![Ashampoo_Snap_Freitag, 24  April 2020_10h38m24s_039_](https://user-images.githubusercontent.com/45469915/80193292-d212b580-8618-11ea-9782-ee671dec6bca.png)

Screenshot 3:
![Ashampoo_Snap_Freitag, 24  April 2020_10h38m45s_040_](https://user-images.githubusercontent.com/45469915/80193438-1900ab00-8619-11ea-9276-a42b50e52547.png)

**Comment by pytzcarraldo** [comment]
Thanks for the info!

So with the faults being out of order seems to be a problem with how the faults are ordered in the solutions. In my implementation I assumed the same ordering as in the series dataframe - is this not correct @Leguark?


`gp._plot.plot_3d(geo_model)` is supposed to be just a simple method to look at your model and we can only provide so much customisation options without going crazy. For anything more, the user should really use the granular plotting api using `gp._plot.Vista`, as they then have also direct and easy access to all `pyvista` functionality to fine tune their plots 🤔 






Another tip for posting code @AlexanderJuestel : best to avoid screenshotting code, as its not very legible when images are scaled - best use markdown code blocks like so https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by AlexanderJuestel** [comment]
@pytzcarraldo thanks for the hint with the screenshots, I changed the comment now. I do like the Syntax highlighting with Ruby ;) 

I agree with you with respect to fine tuning of the plot. Implementing everything possible would be a little too much.

**Comment by domist07** [comment]
@AlexanderJuestel when you defining the surfaces as faults, did you have set `geo_data.set_is_fault(['Fault1', 'Fault2'], change_color=False)` ?

**Comment by AlexanderJuestel** [comment]
Yep, since I define custom colors for my faults, turned it off (I add them one by one in case I have to deactivate some for testing purposes).

```
modelA2.set_is_fault(['FeldbissFault'],         change_color =False)
modelA2.set_is_fault(['EasternGrabenJump'],     change_color =False)
modelA2.set_is_fault(['StolbergGrabenFault'],   change_color =False)
modelA2.set_is_fault(['WesternMainJump'],       change_color =False)
modelA2.set_is_fault(['SandgewandFault'],       change_color =False)
modelA2.set_is_fault(['WeisweilerJump'],        change_color =False)
modelA2.set_is_fault(['OmerbachFault'],         change_color =False)
modelA2.set_is_fault(['BettendorfJump'],        change_color =False)
modelA2.set_is_fault(['WeisweilerJumpTrench'],  change_color =False)
modelA2.set_is_fault(['MerodeFault'],           change_color =False)
modelA2.set_is_fault(['EilendorfThrust'],       change_color =False)
modelA2.set_is_fault(['BurtscheidThrust'],      change_color =False)
modelA2.set_is_fault(['VennThrust'],            change_color =False)
```

**Comment by Leguark** [comment]
Yes, the problem happens when the faults are not on the top of the pile. We were using quite dumb code. In my branch it should work already (do not try yet because I am changing a lot).

**Comment by Leguark** [comment]
can you check this one with the new update

**Comment by AlexanderJuestel** [comment]
Will be checked with other projects soonish and then closed :)

**Comment by alexanderzimmerman** [comment]
> Will be checked with other projects soonish and then closed :)

@AlexanderJuestel did you check this yet?

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman, I am still working with GemPy 2.1.1 but I will ask someone who is already building models in 2.2.1

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman, I checked with someone else and the colors a correct now. Issue closed

**Comment by alexanderzimmerman** [comment]
> @alexanderzimmerman, I checked with someone else and the colors a correct now. Issue closed

Thanks!
