### ISSUE TITLE
Improved Error Handling or Allowing different Delimiters for CSV-Files during gp.init_data(geo_model,...)

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#372]
**Describe the bug**
When creating CSV Files with a German Version of Excel it may happen that the delimiter used is not a `,` but a `;` (see screenshots). This will result in an error when initiating the model `gp.init_data(geo_model,...)`. However, the error message is not very clarifying in terms of what the issue is (see screenshot). The issue could easily be fixed by changing the delimiter. 

CSV-file created with a German version of Excel
![Ashampoo_Snap_Sonntag, 12  April 2020_08h14m37s_019_](https://user-images.githubusercontent.com/45469915/79062046-d7761480-7c96-11ea-87b6-e9d3d4b6f23d.png)

CSV-file created with `pd.DataFrame.to_csv(df,....)` and `,` as delimiter
![Ashampoo_Snap_Sonntag, 12  April 2020_08h14m52s_020_](https://user-images.githubusercontent.com/45469915/79062052-ea88e480-7c96-11ea-995f-44a744d823ec.png)

Error message
![Ashampoo_Snap_Samstag, 11  April 2020_17h30m35s_017_](https://user-images.githubusercontent.com/45469915/79062076-1efca080-7c97-11ea-9450-826264a12d6c.png)
![Ashampoo_Snap_Samstag, 11  April 2020_17h31m09s_018_](https://user-images.githubusercontent.com/45469915/79062081-26bc4500-7c97-11ea-8296-0bd7a8d389a4.png)

**To Reproduce**
Load in a CSV with `;` as delimiter for `gp.init_data(geo_model,...)` 

**Expected behavior**
When using the standard way of loading orientations and interfaces during `gp.init_data(geo_model,...)` I would expect GemPy to be able to deal with both kinds of delimiters or with an improved error handling that tells you to check which delimiter you have used. 

**Screenshots**
See above

Desktop (please complete the following information):

- OS: Windows 10

- GemPy Version if cloned from GitHub: 1.01-1193-gb934f07

**Comment by AlexanderJuestel** [comment]
I believe just adding `;` as possible delimiter in `read_data` should do the trick (screenshot). In addition, adding `delimiter = ';'` to `gp.init_data(geo_model,...)` also solves the issue as it is one of the possible **kwargs. 

![image](https://user-images.githubusercontent.com/45469915/79064645-e2d33b00-7caa-11ea-9085-2e64abcf789c.png)

**Comment by flohorovicic** [comment]
Hi @AlexanderJuestel, can you try if it works with the small fix in the dev_flow_improved_data_read branch? (commit 8c26e6c93c4426868b2f1e60421627f508ceae64)

**Comment by AlexanderJuestel** [comment]
Closed as implemented in GemPy 2.2.1/2
