### ISSUE TITLE
'NoneType' object has no attribute 'ReadAsArray'

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#375]
I want to add topography to the 3D geological model,i get original elevation data from Internet(.asc format),the i transform it to .tif format in ArcGIS,when i import .tif format file to code ,it occured error "'NoneType' object has no attribute 'ReadAsArray'",i don't know reason,the picture is part of code screenshot
![ww](https://user-images.githubusercontent.com/60054308/79196482-c843c200-7e62-11ea-95c3-cbd447463d17.png)
![ee](https://user-images.githubusercontent.com/60054308/79196494-cda10c80-7e62-11ea-993b-2ebbfbeea53e.png)

**Comment by AlexanderJuestel** [comment]
Hello @wh19971014,
In the file path, you are using a backslash (\) instead of a slash (/). Maybe try if that fixes your issue.

**Comment by wh19971014** [comment]
Hello,@AlexanderJuestel 
I try using  / ,but it occured the same error
![1111111](https://user-images.githubusercontent.com/60054308/79199942-4b1b4b80-7e68-11ea-8451-f89bd8ff113a.png)

**Comment by Japhiolite** [comment]
see discussion in #385
