### ISSUE TITLE
Uncertainty Quantification

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#383]
I wanted to ask whether there is any tutorial on **Uncertainty Quantification** in Gempy 2.0? If can I need a tutorial about it. There is a complete tutorial entitled GemPy Paper Code: UQ (https://github.com/cgre-aachen/gempy/blob/master/notebooks/experimental/gempy-paper/GemPy%20paper-UQ.ipynb) but the codes seem old. In advance I appreciate any response.

**Comment by Leguark** [comment]
I am planning to revive those examples - or something similar - soon. Maybe even next week but not hard promises. I will try to remember to update this issue as soon they are running.

On the other hand... trying to replicate those examples could be a good exercise if you want to practice. Any help is always welcome!

**Comment by Ali1990dashti** [comment]
Thanks for your kind response. I am using the same codes and data shown in the tutorial but the final model does not show any layer displacement along the fault (i.e. fault offset is zero) and also I have a question about the code in the 12th line. How can I mimic it in GemPy 2.0?
![Pic](https://user-images.githubusercontent.com/62764899/80120131-d2229f00-859f-11ea-941d-21cf65f9ec2f.jpg)

**Comment by Leguark** [comment]
what do you mean by 12th line?

**Comment by Ali1990dashti** [comment]
I mean the 12th cell:
geo_data_stoch_init = deepcopy(interp_data.geo_data_res)
Sorry for making this misunderstanding.
