### ISSUE TITLE
Adding Elevation data to 3D Geological model

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#385]
On the basis of the already established 3D Geological model, i want to add the topography from the original elevation data,making the surface topography look like the real.I try to add the topography sevaral times,but it occured error,i don't know reason,do you have idea?
![1](https://user-images.githubusercontent.com/60054308/79815925-8b248600-83b4-11ea-9e2f-3fd2e2795bd3.png)
![2](https://user-images.githubusercontent.com/60054308/79815935-9081d080-83b4-11ea-88f6-63d41f48d4d1.png)

**Comment by AlexanderJuestel** [comment]
Duplicate to #375 

Which version/commit version of GemPy are you currently using? Please pull the latest version from the repository if you are not using the latest version. 

For my models the Topography loading works without issues. What is the name of your model? Is it `geo_model` or did you name it something differently?

**Comment by wh19971014** [comment]
version of GemPy is the latest,and the name is geo_model,no changed.The occured error is the upper photos showing. @AlexanderJuestel

**Comment by AlexanderJuestel** [comment]
Could you try to upload the file or send me a link to download it. I will try it on my system then 😉

**Comment by wh19971014** [comment]
@AlexanderJuestel  There is a zip packdge of Code and .tif  file.
[Code and  file.zip](https://github.com/cgre-aachen/gempy/files/4507946/Code.and.file.zip)

**Comment by wh19971014** [comment]
Hello, i upload the file in comment @AlexanderJuestel

**Comment by Japhiolite** [comment]
Hi @wh19971014 

your DEM Tiff seems to be corrupted / errornous. At least, this is what it looks like to me:
![image](https://user-images.githubusercontent.com/13364692/79840717-9678b100-83b6-11ea-8cf4-14843f810339.png)

**Comment by wh19971014** [comment]
Hi .I get original elevation data from internet,using ArcGIS to transform it to .tif format,i don't know where is error.How do you get the upper comment's photo. @Japhiolite

**Comment by wh19971014** [comment]
Hi @Japhiolite .maybe can i upload the original elevation data?
[Original elevation data.zip](https://github.com/cgre-aachen/gempy/files/4508606/Original.elevation.data.zip)

**Comment by Japhiolite** [comment]
See my comment above, the DEM file looks to be fine. What coordinate system do you use and what is the extent of the DEM (in said coordinate system)? 
Be sure that the x, y coordinates of your DEM match the x and y dimensions of your model (or cover a bigger area).
Maybe your model just lies outside of your DEM area and this is why there's a 'NoneType' . 
That's just an assumption on my side, however.

**Comment by wh19971014** [comment]
The coordinate system of original elevation is WGS84,but .tif file's coordinate system is not defined.
The extent is the following photo showing,the extent is (Up=29.6,  Down=29.266667,  Left=94.833333,  Right=95.2333326),the extent is so small compared to my model's extent.Hi, @Japhiolite 
![20200421171556](https://user-images.githubusercontent.com/60054308/79848679-fe012180-83f3-11ea-81e6-e6f2d5e12c60.png)

**Comment by wh19971014** [comment]
Hi , what requirements do GDALs raster file formats need? @Japhiolite

**Comment by Japhiolite** [comment]
It is not smaller than your model, the DEM is in Lat/Long. I transfromed it to WGS84 Pseudo Mercator (EPSG:3857) as a test, and it works. If it's correct, your (DEM) area is about 38 km x 38 km somewhere north of Nepal?

After transformation, the DEM loads just fine (see screenshot):
![image](https://user-images.githubusercontent.com/13364692/79855048-b5813e00-83ca-11ea-90d7-fb64a4db01e3.png)

**Comment by elimh** [comment]
Hi all! This error also occurs if the file path is wrong. Have you already checked this?

**Comment by elimh** [comment]
You could also first try opening your tif file independently of the geomodel, as shown in [this](https://github.com/cgre-aachen/gempy/blob/master/notebooks/experimental/Topography%20-%20Dealing%20with%20raster%20formats.ipynb) notebook. If the file path to the raster file is correct, the topography should be returned correctly.

**Comment by wh19971014** [comment]
Hi, @Japhiolite .Could you help me transform it to WGS84,making the coordinate's (Xmin=0, Xmax=11250,   Ymin=0,    Ymax=10000),I don't clearly know how to use ArcGIS to transform it, Maybe you can upload the .tif file after transformed？Thank you very much.

**Comment by wh19971014** [comment]
@Japhiolite Hi，See my comment above,because my model's extent is set as (Xmin=0,  Xmax=11250,  Ymin=0,   Ymax=10000,  Zmin=0,   Zmax=4350),the unit is "m".
![20200421202954](https://user-images.githubusercontent.com/60054308/79866143-e5523500-840e-11ea-9e0b-2453a1fcc765.png)

**Comment by Japhiolite** [comment]
The thing is, the DEM you provide covers a much larger area (something around 40 km in x and y direction) than the model dimensions you provide. 
This is not a problem, but it would be helpful to know *where* your model is within the area covered by the DEM. Your model is 11.25 km in x direction and 10 km in y direction, so much smaller than the area covered by your DEM.

Further, in my example, I use _global_ coordinates, hence the big x and y values (1.05...e+7, 3.4...e+6, respectively). To get from these coordinates to a _local_ coordinate system, where the point (0,0) is, for example, the lower-left corner in your model, requires some transformation of the DEM. 

So either you transform the DEM (from WGS Mercator) to your local coordinate system, or you could define your model within the _global_ coordinate system.

**Comment by wh19971014** [comment]
@Japhiolite How to transform the DEM (from WGS Mercator) to my local coordinate system,and could you upload the .tif file you  haved transformed to the global coordinate system?  Thank you very much.

**Comment by Japhiolite** [comment]
Here you go for the transformed .tif file:
[dem_mercator.zip](https://github.com/cgre-aachen/gempy/files/4510562/dem_mercator.zip)

**Comment by wh19971014** [comment]
@Japhiolite Hi, now i can add .tif file to the model,making the topography look like the following photo showing.But it looks like so long in the orientation of "Z",I set the model's extent is (Xmin=0, Xmax=11250, Ymin=0, Ymax=10000, Zmin=0, Zmax=4350),and the original elevation of topography surface is from 662m to 5631m,but the following photo's "Z" occured negative value,I am confused,do you konw reason.
![20200422114145](https://user-images.githubusercontent.com/60054308/79938128-4bca6800-848e-11ea-91c2-342de253f722.png)

**Comment by wh19971014** [comment]
@Japhiolite Hi, now i can add .tif file to the model,making the topography look like the following photo showing.But it looks like so long in the orientation of "Z",I set the model's extent is (Xmin=0, Xmax=11250, Ymin=0, Ymax=10000, Zmin=0, Zmax=4350),and the original elevation of topography surface is from 662m to 5631m,but the following photo's "Z" occured negative value,I am confused,do you konw reason.
![20200422114145](https://user-images.githubusercontent.com/60054308/79938211-90560380-848e-11ea-884b-2a05a409a961.png)

**Comment by Japhiolite** [comment]
Did you transform the DEM I sent to your local coordinate system? If so, how did you do it?
To me, it looks like your model boundaries are either bigger than the DEM now (which would be strange, since the DEM covers an area 4 times as big), or it is, at least partly, out of bounds of the DEM.
If you use the DEM I provided, I advise you to use mercator coordinates, i.e. _global_ ones.

Some funky stuff occurs, when the model bounds are not in the DEM bounds (see screenshot) 
![image](https://user-images.githubusercontent.com/13364692/79950844-f71bf280-8477-11ea-846f-add7dc77c781.png)
