### ISSUE TITLE
Select/Deselect data in gp.plot.plot_3D(geo_model)

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#386]
**Is your feature request related to a problem? Please describe.**
I am currently working with around 20 surfaces and display them with `gp.plot.plot_3D(geom_model,...)`. Due to large amount of surfaces it becomes difficult to QC single surfaces as they may be covered by other surfaces (see screenshot).

**Describe the solution you'd like**
Instead of showing the little models on the right hand side in different angles (I personally do not use those anyways) it could be useful to implement a sort of select/deselect panel to be able to select and deselect single surfaces or even turn the topography/surfaces/data points on or off. Then, the whole plot would become more interactive and it would be a nice addition to the PyVista plot. 

**Additional context**
I may try to implement that myself if I have time and the capabilities to do so

![image](https://user-images.githubusercontent.com/45469915/79861946-89b78580-83d5-11ea-89b5-948fc51ebaa5.png)

**Comment by flohorovicic** [comment]
As an additional idea: how about plots with different interfaces (or maybe one with faults only) on the right side, always with the same view angle? Could be very useful to visualise different aspects always from the same viewpoint.

**Comment by AlexanderJuestel** [comment]
What about integrating shortcuts or buttons to go to certain camera positions (top down, towards north, towards west,....) and include the select/deselect function as mentioned? Then the different models could be shown in the main display.

Or do you mean to be able to compare the model with faults on vs. faults off for example side by side?

**Comment by flohorovicic** [comment]
Yes, the latter. Could not only be interesting for faults, but also: different series or later, when we have more hierarchical modelling options, different hierarchies, etc.

**Comment by domist07** [comment]
Use PyVista for visualisation. There you can before plotting (de-) activate specific surfaces/faults.

```
from importlib import reload
reload(vista)
[...]  # interpolation code
geo_data.surfaces.df['isActive'][[1,2]] = False  # deactivate surfaces/faults with indices 1 and 2
geo_data.surfaces.df['isActive'][[0]] = True  # activate surface/faults with indices 0
gv = vista.Vista(geo_data, plotter_type='background', notebook=False,
                  real_time=True)
gv.plot_surfaces_all()  # plot all activated surfaces/faults
gv.plot_surface_points_interactive_all()
gv.plot_topography()
```

**Comment by AlexanderJuestel** [comment]
@domist07, that could be a nice workaround for now, yes. I will test it out and close the issue afterwards.

**Comment by AlexanderJuestel** [comment]
@domist07, I made the code a little bit more flexible so that you can just enter a list of surfaces you want to deactivate.  This could also be implemented in the plot_3d function as an addition option maybe...but thanks for the hint :) I can work with that now. 

```
#Create a list of surfaces that you want to deactivate
deactivate_surfaces_list = ['StolbergGrabenFault', 'FeldbissFault', 'EasternGrabenJump']

#Create list with indices of surfaces you want to deactivate
deactivate_indices_list = np.array([geo_model.surfaces.df.index[geo_model.surfaces.df['surface'] == item].tolist() for item in deactivate_string_list]).T.tolist()

#Deactivate surfaces
geo_model.surfaces.df['isActive'][deactivate_indices_list[0]] = False

gp._plot.plot_3d(geo_model,....)
```

**Comment by AlexanderJuestel** [comment]
@domist07, it seems like your workaround does not work but I found another workaround as mentioned in a comment in issue #371.
