### ISSUE TITLE
How to add contour lines to a planar geological map

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#391]
In GemPy‘s example,the geplogical map don't have contour lines to display elevation values,as the follwing  photo showing,so how to  implement that function,thank you .
Another question #390 's comment ,please.
![g p](https://user-images.githubusercontent.com/60054308/80056383-aa5b1900-8556-11ea-9958-f9001ebb5d8b.png)

**Comment by flohorovicic** [comment]
How about just extracting the generated map, loading it into a GIS (e.g. the free and open QGIS), and adjusting it there - then you have all the power of full GIS systems at your hands to adjust resulting maps to your liking.

**Comment by wh19971014** [comment]
Hi,I don' t do like that,do you know how to make it clearly,or do you do that before,or is there example？ @flohorovicic

**Comment by flohorovicic** [comment]
There is **a lot** of information online, a quick google search will help. E.g.:

https://www.hatarilabs.com/ih-en/how-to-visualize-water-quality-data-in-qgis-3-from-points-to-raster-to-contour-lines-tutorial

**Comment by AlexanderJuestel** [comment]
@flohorovicic, this could also be a feature/function for GemPy Geographic: automatically extracting contour lines from the raster with a given spacing in meters and using them as overlay in map plots.
