### ISSUE TITLE
How to make the fault show in block model

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#392]
**What is your question?**
In the following photo,it's a block model,in this model we can only see the lithology,but I actually added 8 faults to the model,the code that forms block model is:
 "gpv = gp._plot.Vista(geo_model)
gpv.plot_structured_grid("lith")
gpv.show()"
My question is how to make the fault show in block model,thank you.
![block](https://user-images.githubusercontent.com/60054308/80203801-4f124f00-865a-11ea-90c9-941c7eb02ffd.png)

**Comment by AlexanderJuestel** [comment]
Hey, 

try `gpv.plot_surfaces_all()`. By providing a list of strings with the name of your layers/faults (e.g. `gpv.plot_surfaces_all(fmts = ['EasternGrabenJump', 'SandgewandFault']),` you can choose which surfaces to display. 

I have not tried it in combination with structured grids though. There may be another way to do it maybe.

Hope that helps

**Comment by wh19971014** [comment]
Hey, @AlexanderJuestel .I write code:
gpv = gp._plot.Vista(geo_model)
gpv.plot_surfaces_all(fmts = ['Fault1'])
gpv.show()
But it occured error "index 0 is out of bounds for axis 0 with size 0"
![20200424202502](https://user-images.githubusercontent.com/60054308/80212445-124e5400-866a-11ea-918e-fad2644d75ad.png)

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
 i do as you said on your comment,but it didn't work, and the answer is just like my last comment, how to solve it, thank you very much.
