### ISSUE TITLE
Add topographic feature to a 2D section photo 

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#393]
**What is your question?**
When i plot a 2D section,the top of the 2D section photo is flat,I think that's because the modeling area is set to a cuboid at the very beginning,the terrain is added to the cuboid using "gdal" function, however,the Z value of the top surface of the cuboid is bigger than the minimum elevation value of the terrain ,so why can't the features of the terrain be shown when a 2D section is formed.
And is there a way to show the topographic features at the top of a 2D section.Thank you.
![SE](https://user-images.githubusercontent.com/60054308/80225729-066c8d00-867e-11ea-8a3a-0ca2e3d9cce1.png)

**Comment by Japhiolite** [comment]
Hi @wh19971014 
You can find examples of how to include topography in sections in the following three tutorial notebooks:  
* [Ch1-7a-Cross sections](https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7a-CrossSections.ipynb)  
* [Ch1-7b-Topography](https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7b-Topography.ipynb)  
* [Ch1-10a-2D Visualization](https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/Ch1-10a_2D_Visualization.ipynb)

I suggest to look at the examples and try to apply it to your model.

**Comment by Japhiolite** [comment]
I close this issue for now. You can re-open it, when the tutorials don't help @wh19971014 .
