### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#394]
**What is your question?**
When executing code "gp.compute_model(geo_model, compute_mesh=True, set_solutions=True)",it has strange error,i am confused what it means.Error is **MemoryError: Unable to allocate 227. MiB for an array with shape (10, 9, 330888) and data type float64**
![1](https://user-images.githubusercontent.com/60054308/80276430-65ccaa80-871b-11ea-98a7-cad417c48781.jpg)
![2](https://user-images.githubusercontent.com/60054308/80276434-6b29f500-871b-11ea-9c68-ad843cb115a6.jpg)

**Comment by Japhiolite** [comment]
This is not directly a GemPy error. It simply means that you don't have enough memory on your computer, i.e. your array is way too huge.

**Comment by AlexanderJuestel** [comment]
Just reduce the resolution (amount of cells in each direction) or increase your memory storage to avoid this error in the future.

**Comment by AlexanderJuestel** [comment]
And please copy the error message from your notebook into the issue and format it correctly. @pytzcarraldo provided the link in another issue on how to format code: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Please consider that. This will also make it easier for future users to read and understand issues.
