### ISSUE TITLE
Code of Conduct for GemPy community interaction 

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#395]
**Is your feature request related to a problem? Please describe.**
The template for asking questions should be improved so that better questions with more understandable content can be submitted. The current heading "What is your question?" may not be clear enough to provide a proper problem description. 

**Describe the solution you'd like**
Elements of the bug report and feature request template such as providing code samples, Screenshots, or the used versions should be provided as headlines to guide users through the template. This way questions could be preserved in a better way, they can be searched more easily and will be easier understandable for future users with the same issues.

**Comment by AndrewAnnex** [comment]
I think the project could also adopt a code of conduct, there are a lot of issues posted by users who are new to github and to how open source software development works which will likely cause fatigue in maintainers / friction / hostile communications. Having a code of conduct and displaying it prominently in the issue templates, readme, etc can help addressing issues or as a reminder to keep things civil.

**Comment by flohorovicic** [comment]
It sounds like we should make use of the new GitHub Discussion forums and FAQs that you mentioned, @AlexanderJuestel - and we should clearly state in the contributions.md which forum is applicable for which type of question (as mentioned by @AndrewAnnex ).

**Comment by flohorovicic** [comment]
Just came across this example code of conduct (on pygmt): 

https://www.contributor-covenant.org/version/1/4/code-of-conduct/

Could directly be adapted in gempy, I think.

**Comment by AlexanderJuestel** [comment]
@flohorovicic I just renamed the issue as it seems that we need a code of conduct for interactions of the community as proposed by @AndrewAnnex and you

**Comment by AlexanderJuestel** [comment]
Will be fixed in #640

**Comment by Japhiolite** [comment]
Closed as being merged.
