### ISSUE TITLE
[BUG] Computing a model only with sections mess up sorting surfaces with solutions

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#397]
**Describe the bug**
Computing a model only with sections mess up sorting surfaces with solutions

For some reason scalar fields at surface point are not in order

**To Reproduce**
Provide detailed steps to reproduce the behavior:

```
@pytest.fixture(scope='module')
def section_model(one_fault_model_topo_solution):
    geo_model = one_fault_model_topo_solution
    section_dict = {'section_SW-NE': ([250, 250], [1750, 1750], [100, 100]),
                    'section_NW-SE': ([250, 1750], [1750, 250], [100, 100])}
    geo_model.set_section_grid(section_dict)

    geo_model.set_active_grid('sections', reset=False)

    one_fault_model_topo_solution.update_additional_data()
    one_fault_model_topo_solution.update_to_interpolator()
    gp.compute_model(geo_model, sort_surfaces=True)
    return geo_model

```
**Expected behavior**
After one compute the color of the layers should converge

**Comment by wh19971014** [comment]
Hi, @Leguark .Now can GemPy obtain the 2D section in the NW-SE direction? A few days ago, an author said that GemPy cannot obtain the 2D section in this direction at present, as shown in the picture below. What does this BUG of yours show? Thank you very much.
![222](https://user-images.githubusercontent.com/60054308/80329928-544be580-8876-11ea-819b-1fb4273e3e19.png)

**Comment by Leguark** [comment]
No this bug is completely unrelated.
Can you make a pull request with a test showing that behavior? If you doing it like this, it is much easier for us to check what is the problem and submit a patch.

To do so:
1) Pull a fresh branch from master
2) Create in gempy/test//test_plotting/test_plot_section.py
3) Add the function:
def test_plot_East-west():
     # Your code replicating the problem here

4) git commit
5) git push to your repo
6) pull request 

If you have any doubts on the way just contact one of us.

**Comment by wh19971014** [comment]
Hi, @Leguark .In your comment,the third point "Add the function:",how can I do that,could you explain  more detailedly.And the second point means what,how can I make it,and whether I finish the second one or the third one will solve my problem,thank you.

**Comment by wh19971014** [comment]
Hi, @Leguark .Can GemPy plot any direction's 2D section,for example NW-SE,I am in a hurry  to get that function,thank you, and please see the upper comment of mine.

**Comment by AlexanderJuestel** [comment]
Hello, 

please see [ch1-7a-CrossSections](https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7a-CrossSections.ipynb) for creating custom section.

I believe you actually worked with those before.
