### ISSUE TITLE
Getting different answer in different environment in Windows System

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#398]
**What is your question?**
I run the same code in different environment in Windows System,but getting different answer,strange.The following two photos are Geological map,the first one getted in **base(root)**  environment,the second one getted in **new** environment which I set up,I upload the code below,I am confused.

![1](https://user-images.githubusercontent.com/60054308/80331265-2e284480-887a-11ea-8285-2b77ce8c4e90.png)
![2](https://user-images.githubusercontent.com/60054308/80331274-37191600-887a-11ea-8a6e-068b1ca010b3.png)
[ch1-7b-Topography (4).zip](https://github.com/cgre-aachen/gempy/files/4537291/ch1-7b-Topography.4.zip)

**Comment by javoha** [comment]
Hi @wh19971014 ,
this is indeed quite weird. Can you please check that you have the newest GemPy master branch installed in both environments and check again?

**Comment by WestfalNamur** [comment]
You could also check the dependencies of. Maybe some imported libraries differ in version that change default behavior or their API. 
In any case however, you should check if you can reproduce this behavior. To do so take your script, delete all stored values and run it again. If you encounter this behavior again you can exclude that this is not a result of some variables set and stored in memory some time ago.
