### ISSUE TITLE
Mismatch of gp.create_data loaded csv files formation number

### ISSUE THREAD

**Issue by pytzcarraldo** [cgre-aachen/gempy#4]
Loading interfaces and foliation DataFrames with gp.create_data seems to not load correctly the "formation number" column values. reordering seems to happen although it shouldn't

**Comment by Leguark** [comment]
This is may be fixed now. @pytzcarraldo if you still have the dataset could you try?

**Comment by pytzcarraldo** [comment]
Seems to work fine now
