### ISSUE TITLE
Adding Custom Section Trace to Geological Map

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#404]
**What is your question?**
I want to add a profile to the planar geological map,but the profile is no expressed on the planar geological map,as a result, the planar geological map and the profile are separated,as the two photos showing below.And my code Internet link is:http://localhost:8888/notebooks/ch1-7b-Topography%20(5).ipynb

![2](https://user-images.githubusercontent.com/60054308/80916339-9e5b2c80-8d8a-11ea-810f-a85de466a912.png)
![1](https://user-images.githubusercontent.com/60054308/80916341-a3b87700-8d8a-11ea-9532-a3475d117b4f.png)

**Comment by GeorgeLiang3** [comment]
Hi @wh19971014, you need to share the code in some other way, we have no access to your localhost port

**Comment by GeorgeLiang3** [comment]
and maybe try to plot on the same object, something like plt.gca()

**Comment by wh19971014** [comment]
Hi, @GeorgeLiang3 .I upload the code with zip file below.
[ch1-7b-Topography (5) (1).zip](https://github.com/cgre-aachen/gempy/files/4570712/ch1-7b-Topography.5.1.zip)

**Comment by AlexanderJuestel** [comment]
Hi, 
since you defined your endpoints in your section_dict, have you tried using those in your plots? Just access the elements of your dictionary and plot them. It is a little chaos on my picture but you can see the line on the left side. This is a custom section. If you have multiple sections, you could just loop through them.

```ruby
plt.plot([section_dict['CrossSection'][0][0],section_dict['CrossSection'][1][0]],[section_dict['CrossSection'][0][1],section_dict['CrossSection'][1][1]])
```

![image](https://user-images.githubusercontent.com/45469915/80917080-098e0a00-8d5d-11ea-97f8-d108b7eceaa5.png)

**Comment by wh19971014** [comment]
I try to use **plt.gca()**,it is like the photo showing below.
![20200503224137](https://user-images.githubusercontent.com/60054308/80917140-ac5f7c00-8d8f-11ea-874e-50f3acabbcf6.png)

**Comment by AlexanderJuestel** [comment]
Hi @wh19971014, 

please close the issue if the workaround helped you. Thanks!

**Comment by wh19971014** [comment]
Hi， @AlexanderJuestel .
I don't solve this problem,and I do it by following you on my last comment.

**Comment by AlexanderJuestel** [comment]
Hi @wh19971014, 

could you maybe show us with code what you have tried? Please post the code here as a comment and not as zip file. Thanks

**Comment by wh19971014** [comment]
Hi， @AlexanderJuestel .
Here is my code below:
`gp.plot.plot_section_traces(geo_model)
gp.plot.plot_section_by_name(geo_model, 's1')`

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
Here is my code below:
`gp.plot.plot_section_traces(geo_model)`
`gp.plot.plot_section_by_name(geo_model, 's1')`

**Comment by AlexanderJuestel** [comment]
Have you tried my workaround already? I would have to have a closer look at the functions now but the workaround is a quick solution.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
yes I have tried your workaround already,but the answer is just like the comment I have put on earlier.

**Comment by AlexanderJuestel** [comment]
1. Could you please show us the code and what the corresponding error message is when you use the workaround? Did you replace the name of the section dictionary and the section name according to your naming convention? Without any information on how you changed your code there is no way to assist you.

2. Do you refer to the comment: "I don't solve this problem,and I do it by following you on my last comment."? This comment however relates then to a comment by @GeorgeLiang3 which had nothing to do with my workaround. 

Please provide more accurate descriptions if you need help! Thanks!
