### ISSUE TITLE
add a tunnel to the model

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#407]
**What is your question?**
I built a 3D geological model of engineering area,because there is a tunnel within the engineering area,and there are only strata and faults in the established model, I want to add a tunnel into the established model ,is there any idea to make it,thank you .****

**Comment by wh19971014** [comment]
Hey,anybody has idea to solve my trouble,can the tunnel be seen a strata or fault?
Or is there similar function of adding a tunnel to model,thank you very much?

**Comment by domist07** [comment]
Actually to the best of my knowledge there exists no specific function for that problem - but I'm not a contributor of GemPy.

**As a Workaround**
Which format has your tunnel? If it's any kind of mesh maybe you could add it as topography. At the moment you could only insert one DTM element, so if you have a DTM in your model you have to throw out your true DTM.

**Comment by AlexanderJuestel** [comment]
Good idea, you could also add the tunnel as a mesh to your PyVista 3D Plot as additional element, maybe. The layers should then be unaffected by the tunnel mesh and you could see where the tunnel goes.

**Comment by wh19971014** [comment]
Hi,@AlexanderJuestel @domist07 ,I don't understand what's mesh,how to add the tunnel into 3D model as a mesh.Yeah, i add the DTM to my model.

**Comment by wh19971014** [comment]
@flohorovicic @AlexanderJuestel .And the next question is I asked earlier time: how to limit the fault's extension length along its direction,thank you very much,eager to solve the problem when making 3D model.

**Comment by AlexanderJuestel** [comment]
Hello, 

many pages provide explantations on what meshes are. Just use the search engine you are most familiar with. 

I used the following example to create well traces. Theoretically, a tunnel is just a large well trace. So it should be possible to create a mesh based on that example: https://en.wikipedia.org/wiki/Polygon_mesh 

It could look like the following then (image from @danielsk78). Please, let me know if you have any questions. 

![image](https://user-images.githubusercontent.com/45469915/81466324-fea9fe00-91d0-11ea-83ac-9a7f311ae395.png)

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
Cool,I just want to add like yours,and I want to ask whether the tunnel can be together with the rocks and faults in model,or it only can be a single one in model.
And I can't open your internet link,do you have the code making the picture in comment upper,thank you.
Do you have idea about my trouble on my upper comment,2nd question.

**Comment by AlexanderJuestel** [comment]
Hey,

Sorry, I put the wrong link in there. I fixed it and it should link you to a Pyvista page. On that page, code is also provided. 

You can add the mesh to your 3d plot of your rocks and faults yes. The provided picture was just an example how it could look like. 

Please refer with your comment to your other issue 😉

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel .
Your code is 2D picture,the provided picture on comment upper is at 3D space,how to get the code of upper picture

**Comment by AlexanderJuestel** [comment]
Dear @wh19971014,

as posted above, this is the example the picture of the well trace was created with: https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
I know that,I mean @danielsk78 's picture.
![81466324-fea9fe00-91d0-11ea-83ac-9a7f311ae395](https://user-images.githubusercontent.com/60054308/81467700-10a99200-920d-11ea-9605-62de371f910d.png)

**Comment by AlexanderJuestel** [comment]
The code of @danielsk78 is tailored to his needs. You would have to adapt the code on https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py to fullfill your needs for your model.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
The example of creating-spline（link is below）,there is one in a photo ,if I want to add two or more in a photo,how to make it; another question,there is no coordinate Axis on getted photo,how to get coordinate Axis on getted Axis.Thank you very much.
https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel
The example of creating-spline（link is below）,there is one polyline in a photo ,if I want to add two or more polylines in a photo,how to make it,I tried to do that,but it did't work; another question,there is no coordinate Axis on getted photo,how to get coordinate Axis on getted Axis.Thank you very much.
https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py

**Comment by AlexanderJuestel** [comment]
Hey, 

what have you tried so far? Please provide us with some code. Generally you could loop over your different tunnels/elements and create the meshes for each object ;)

**Comment by wh19971014** [comment]
Now I can only add one tunnel in a getted photo ,I don't know how to add two or more tunnels at the same time

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
Now I can only add one tunnel in a getted photo ,I don't know how to add two or more tunnels at the same time.And I can get 3D answer, but there is no coordonate Axis ,as the following first photo showing, I want to get the coordonate Axis in a photo like the following second photo showing
![20200511171229](https://user-images.githubusercontent.com/60054308/81545012-dbd34180-93aa-11ea-8f7c-be06994264b5.png)

.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel
Now I can only add one tunnel in a getted photo ,I don't know how to add two or more tunnels at the same time.And I can get 3D answer, but there is no coordonate Axis ,as the following first photo showing, I want to get the coordonate Axis in a photo like the following second photo showing
![20200511171229](https://user-images.githubusercontent.com/60054308/81545172-13da8480-93ab-11ea-8249-42c448dbb880.png)
![q](https://user-images.githubusercontent.com/60054308/81545189-189f3880-93ab-11ea-9088-f2622ef474b1.png)

**Comment by danielsk78** [comment]
Hi @wh19971014 
Please refer to Pyvista tutorials for a more detailed explanation of the method. 

As @AlexanderJuestel already comment, you can add more elements by a loop over the different elements to plot, and also adding an axis by doing:

#Create a pyvista object to plot
p = pyvista.Plotter()
# create x amounts of aditional "meshes" you like to display in your figure    
for i in range(x):
     p.add_mesh(meshes[i])
# create the axis especifiying the extent of the bounds
p.show_bounds(bounds=extent)
p.show()

Please further refer to this issue in pyvista tutorials/examples section.

**Comment by wh19971014** [comment]
Hi, @danielsk78 
I think using `for i in range(x):  ..... p.add_mesh(meshes[i])`can't make it ,my question is add different tunnels in one photo at the same time,my code is below,and I don't know how to add them in one photo in Pyvista.
```
def make_points():
    """Helper to make XYZ points"""
    x = 4497,10794,12593,26986,30134
    y = 35012,36654,28448,15318,15318
    z=  3000,2950,2900,2820,2700
    return np.column_stack((x, y, z))
points = make_points()
points[0:2, :]
```
```
def make_points():
    """Helper to make XYZ points"""
    x = 4497,12143,27885,30134,30584
    y = 37201,38295,25165,19694,16959
    z = 3000,2950,2900,2820,2700
    return np.column_stack((x, y, z))
points = make_points()
points[0:2, :]
```

**Comment by AlexanderJuestel** [comment]
Hi @wh19971014,

please see the code for creating one or more tunnel like objects:

[Well_Visualization_PyVista.zip](https://github.com/cgre-aachen/gempy/files/4613716/Well_Visualization_PyVista.zip)

**Comment by yang8038** [comment]
Is there code to generate this kind of tubular tunnel? Can't find the code in your tutorial?

**Comment by AlexanderJuestel** [comment]
Hello @yang8038, 

you cannot find the code because there is not tutorial (yet). I would kindly refer you to the PyVista documentation for now on how to create a spline: https://docs.pyvista.org/examples/00-load/create-spline.html
