### ISSUE TITLE
What does X_r mean?

### ISSUE THREAD

**Issue by fiecato** [cgre-aachen/gempy#409]
I am a newbie.  I  want know what X_r, Y_r, Z_r and G_x, G_y, G_z mean? And how are they calculated?

![image](https://user-images.githubusercontent.com/40785341/81476521-eecc0180-9244-11ea-9beb-c8e85edc0fc3.png)

**Comment by AndrewAnnex** [comment]
the `*_r` columns are the X, Y, Z columns rescaled to be within the 0-1 domain via the rescaling class.

**Comment by fiecato** [comment]
Thanks for your reply
How is the scaling scale determined? In addition, how do the `X, Y, Z, azimuth, dip, polarity, and formation` fields in origination affect the image formation?

**Comment by AndrewAnnex** [comment]
@fiecato currently gempy rescales the data to fit the range of 0 to 1 using the min and max values of the X, Y, Z columns to find the axis with the largest range, and using that largest range to rescale (divide) the values such that they all fit into the 0 to 1 range. I suggest reading through the code and comments in the related github issues for my work-in-progress PR #341 to see what is really happening, but it is roughly similar to common processes used in scikitlearn to rescale data (or it is a simpler version of what is common to the ML field). That PR is the first step in improving the way gempy does this rescaling. The rescaling does not modify the formation, azimuth, dip or polarity values in any way. All the relevant functions are found in data.py, you can also make scatter plots of the X Y Z and X_r, Y_r, Z_r columns to see what is going on. I am not sure what you mean by image formation, but essentially the X, Y, Z points are where your input data points are in whatever coordinate space you want to work in, typically meters from some origin, and the _r fields are rescaled to be within 0 to 1 range to work better with the underlying kriging code, as most models assume that the data is within a preset range. If you move the X,Y,Z values you change where the "lithologic" contact is in your model. Changing the how the _r fields are made will improve/degrade the performance of the model as it would influence the condition number of the matrices in the model. @Leguark please correct me if I got anything wrong

**Comment by fiecato** [comment]
Thank you! After I read the source code for a day, I understand the principle of scaling coordinates, but I still have a lot of things that I do n’t understand when drawing 3D models.

1. I found that the (x, y) in orientation is the same as the center during zooming, and z is the same or slightly larger. I guess they are used to determine the direction of the layer, right? How should I create these orientation points?

2. For different layers, does Gempy use the same model to decide how to draw the 3D model?

3. When training a model, how many (x, y) are needed to produce a model with a better surface?

4. If I want to obtain the surface coordinates of the simulated 3D image, how should I obtain the coordinate points of the simulated insertion?

**Comment by AndrewAnnex** [comment]
@fiecato there are plenty of example notebooks and example csv files of surface point and orientations in this repository that can answer your questions. For my own work I use a orientation for each surface point at the same position as each surface point, I do not know if there is an optimal proportion of surface points to orientations. 

Your 2nd question is best answered by the gempy 1.0 paper that is probably linked in the readme, as I understand it a single model is fitted to all the data you provide, so you can for example not have orientation data for a layer but if you have orientations above and below for other layers the model will incorporate that information to form conformal layers. 

3. I do not know, this is an area of research I have seen papers cited in this review paper of geologic modeling: https://hal.univ-lorraine.fr/hal-01921494/document (its 95 pages). I suspect there is some relation relative to the scale of variability you are interested in, like a nyquist frequency to grab a physics term. For example if you are interested in some short length scale folding in a large geologic structure you would need to have sampling points that capture that variability.  Better is also dependent on having some measurement of uncertainty or error in your models which is not exaclty built into gempy at the moment, or the uncertainty analysis code exists in the repository but may not be working given recent refactoring. 

I didn't understand your 4th question, @Leguark any ideas?

**Comment by Leguark** [comment]
@fiecato sorry for the late response! Last days have been intense trying to get the sphinx gallery up and running.

Anyway, let's see if I am able to answer your questions.

0-1) The rescaling only happens for stability of float32 reasons (for gpus). That is why after zooming it is the same proportions (so far... we are looking at playing with this concept to obtain better interpolations, but that is a different story)

2) Every Series (feature) is interpolated together, i.e. all the comfortable layers are interpolated as one single 3D scalar field to enforce that the layers do not cross each other.

3) As @AndrewAnnex said, this depends on the complexity of the geometry. Data decimation and local anisotropies are unresolved topics. We have some prototypes and even more ideas but it is work that needs to be done. Very welcome if there is some PhD out there with spare time to discuss some of this ideas :) 

4) If you mean XYZ points on the surfaces, we recover them by marching cubes. You can find them in geo_model.solutions.vertices or in the `Surfaces` df (geo_model.surfaces.df['vertices'])

Hope this works! Although @AndrewAnnex was very precise already. Thanks for that!
