### ISSUE TITLE
Reduce the "arrow" size

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#411]
**What is your question?**
As the following 2D photo showing,the size of **arrow** is much bigger than the **data point**,the photo is a 2D photo when making geological model with GemPy,and I  want to make **arrow's size** smaller,to make size ratio of the two look more harmonious, do you have any idea,thank you very much.
![2D](https://user-images.githubusercontent.com/60054308/81500555-77aa7200-9305-11ea-996f-dd595cc3e03a.png)

**Comment by wh19971014** [comment]
my code of getting upper photo is like below
```
%matplotlib qt5
import pyvista as pv
pv.set_plot_theme("document")
p2d = vv.Plot2D(geo_model)
p2d.create_figure((11.25, 9.75))
```
`ax = p2d.add_section(cell_number=1, direction='y')`
`p2d.plot_data(ax, cell_number=11)`

**Comment by wh19971014** [comment]
code of getting upper photo is like below,the code is part of making 3D geological model.
```
%matplotlib qt5
from gempy.plot import visualization_2d_pro as vv
from gempy.plot import vista
%matplotlib qt5
import pyvista as pv
pv.set_plot_theme("document")
p2d = vv.Plot2D(geo_model)
p2d.create_figure((11.25, 9.75))
ax = p2d.add_section(cell_number=1, direction='y')
p2d.plot_data(ax, cell_number=11
```

**Comment by AlexanderJuestel** [comment]
Hi, 

if you have cloned the GemPy repository to your local machine you could try to backtrace where the size of the arrow is being set. 

The function `plot_data` is defined in the file visualization_2d_pro.py file from line 349 to 461. Here just the first few lines. The arrows are so-called quivers (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.quiver.html) that also take the headwidth as an argument. You can change this argument in the code, save it, restart your kernel and your headwidth size should be adapted according to the value that your provided. Those plotting issues can usually be fixed manually, to it is always good to check out the code first ;) Let me know if you solved the issue.

 ```ruby
   def plot_data(self, ax, section_name=None, cell_number=None, direction='y',
                  legend = True,
                  projection_distance=1e10, **kwargs):
        """
        Plot data--i.e. surface_points and orientations--of a section.

        Args:
            ax:
            section_name:
            cell_number:
            direction:
            legend: bool or 'force'
            projection_distance:
            **kwargs:

        Returns:

        """
```

Thanks for providing the code ;)
