### ISSUE TITLE
How to add stochastic_surface to gempy.utils

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#413]
Hi,

Firstly I appreciate anyone who is contributing in this scientific community.
I have a problem running one of the tutorials provided here (https://github.com/cgre-aachen/gempy/blob/master/notebooks/experimental/stochasticsurface/agile_equinor_geocomp_example.ipynb).
How can I find this modules: 
stochastic_surface
calculate_probability_lithology
calculate_information_entropy.
I couldn't find them in https://github.com/cgre-aachen/gempy/tree/master/gempy.
Can someone tell me how can I add these three modules to my gempy.
In advance I appreciate any response.

**Comment by Japhiolite** [comment]
Hi @Ali1990dashti 

I dug a bit through the code, and it appears that `stochastic_surface` is implemented on the development branch of @pytzcarraldo . You can try to checkout the branch `development_alex` and see if the notebook runs then.  
@pytzcarraldo if it is already implemented somewhere else, please correct me. I lost track of it in the monster PR that is #301 

All notebooks in the experimental folder are _experimental_, hence the name. This means, that they will likely not work out of the box, and require some user-specific tweaking.

Cheers
Jan

**Comment by pytzcarraldo** [comment]
Hey @Ali1990dashti !

That functionality is currently not part of the master branch. You can find it in the `dev_stochasticsurface` branch. It should generally work on that branch 🤔 

I've been meaning to bring the code up to date and refine it for use in my next project, and maybe for @WestfalNamur's project. 

Also @Japhiolite, may we never repeat the crimes of PR #301 again 😄 

Cheers,
Alex

**Comment by Ali1990dashti** [comment]
Dear @pytzcarraldo,

Thank you for letting me know about my question. I added the **_stochastic_surface_** to the **_utils_**.
But I cannot find the **posterior_analysis**. Have you any idea where I can find it and how I can add it to my Gempy.

Regards,
Ali

**Comment by pytzcarraldo** [comment]
Right, sorry! You should be able to find the functionality in `gempy/bayesian/posterior_analysis_DEP.py` 😄

**Comment by Ali1990dashti** [comment]
Hey @pytzcarraldo,

Sorry for asking that much questions, I have others: 
Where is the **_surf_pts_groups.p_**?
I cannot find it. Is this the same as surfpts.csv?
And what type of command is **_smod.reset()_**?
Thanks again for devoting time to my questions.

**Comment by pytzcarraldo** [comment]
The `surf_pts_groups.p` contains information about which points belong to which fault block so we can easily assign probability distributions accordingly for the stochastic simulation. The same information is actually contained in `simple_fault_model_points.csv` in the column `group` - so you could load it from there and add the column to the `geo_model.surface_points.df`

`smod.reset()` resets the stochastic model to its initial state.

**Comment by Ali1990dashti** [comment]
I appreciate your detailed response @pytzcarraldo.
Thank you.

**Comment by Japhiolite** [comment]
Did everything work out? If so, we can close this issue.

If something didn't work, you can re-open the issue @Ali1990dashti
