### ISSUE TITLE
Installing Gempy

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#417]
Hi,
I have installed gempy on windows. But I am facing an error when I trz to import it jupyter. Can anyone help me to solve the problem? In the following I uploaded screenshot the error.
In advance, I appreciate any help from anyone.
![Installation_Error](https://user-images.githubusercontent.com/62764899/81701632-97a77600-946a-11ea-99d6-daadab428a16.jpg)

**Comment by domist07** [comment]
Did you have installed scikit-image? Which version do you have? I think this is the problem.

**Comment by Ali1990dashti** [comment]
Thank you @domist07.
after installing scikit-image in anaconda through the following code, it is now working:
_conda install -c conda-forge scikit-image_
