### ISSUE TITLE
Plotting scalar photo of one direction

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#418]
**What is your question?**
how to plot scalar photo of one direction，and the data is on the photo at the same time,just like the following picture,anybody knows that?Thank you very moch.
![w'w'w](https://user-images.githubusercontent.com/60054308/81780739-9e48f280-9529-11ea-914f-00a4f0dfe62e.png)

**Comment by javoha** [comment]
Hello @wh19971014 ,

sorry but I do not understand what you mean exactly by "scalar photo"? So the plot in your example shows the scalar field in a cross section in y-direction. Can you elaborate what exactly you need?

Best wishes and stay healthy,
Jan

**Comment by wh19971014** [comment]
Hi， @javoha 
My goal is to plot a scalar photo of  one direction,for example "y" direction,and I want to the dot and the arrow show on the photo,as you can see that on upper photo I upload,the dot and arrow are interface data and orientation data used for making 3D geological model.

**Comment by AlexanderJuestel** [comment]
Hello @wh19971014,

could you ellaborate what you mean by "scalar photo"? 

Looking at your posted image, you already plotted the interfaces and orientation on your scalar field plot? What else would you like to plot?

Best regards
Alex

**Comment by wh19971014** [comment]
Hi,@AlexanderJuestel @flohorovicic @javoha 
Because the paper needs to introduce some features of GemPy , can anybody directly use pictures from open source ,thank you very much.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel @javoha @flohorovicic @AndrewAnnex 
Because the paper needs to introduce some features of GemPy , can anybody directly use pictures from open source code in jupyter notebook?thank you very much.

**Comment by AlexanderJuestel** [comment]
Hello,

How is referencing an image related to your issue?

However, as long as you are citing/referencing the origin/source of the material/information you are using in your own work you can use it.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
 I want to add topography on a 3D model upper surface,and I want to a raster file,so I have to download original elevation data,but I don't know where to the elevation data of one region,thank you very much

**Comment by AlexanderJuestel** [comment]
Hello @wh19971014

If you have more not yet asked questions regarding GemPy, please open a new issue and avoid asking multiple questions in one issue if they are not related to the issue to keep the feed clean.

**Comment by wh19971014** [comment]
Hi,I  want to plot a scalar photo,my code is `gp.plot.plot_scalar_field(geo_data, 9, plot_data=True)`
but there is no data showing on the photo ,strange.
![20200518002438](https://user-images.githubusercontent.com/60054308/82154089-46e6b180-989e-11ea-8a9c-3b3fc754e5f7.png)

**Comment by wh19971014** [comment]
Hi,@AlexanderJuestel 
I want to plot a scalar photo,my code is `gp.plot.plot_scalar_field(geo_data, 9, plot_data=True)`
but there is no data showing on the photo ,strange.
![20200518002438](https://user-images.githubusercontent.com/60054308/82154135-7dbcc780-989e-11ea-9c9d-862af9c09909.png)

**Comment by AlexanderJuestel** [comment]
Hey, 

please have a look at [Visualization_2d](https://github.com/cgre-aachen/gempy/blob/master/gempy/plot/visualization_2d.py) and search for your function for more information on **how** and **what data** is plotted. 

However, have you tried plotting the scalar field at other positions (cell_number)? Is data plotted there or is it missing throughout the whole model?

If data is plotted at other positions, I would assume **that there is just no data in the range of your current cell number.** 

Please also try to set the argument `show_all_data=True`. This will plot all the data you have in your model. 

If no data is plotted at all, we can investigate further.

**Comment by javoha** [comment]
Just to wrap up - thanks @AlexanderJuestel : The input data on a cros section (slice) will only be shown by default if it is exactly located on the slice you are plotting. 

If this does not solve your problem, please reopen this issue.
