### ISSUE TITLE
making original elevation data become Digital elevation model

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#421]
**What is your question?**
Is there any code tutorial about making original elevation data(.tif format) become Digital elevation model,thank you very much.

**Comment by AlexanderJuestel** [comment]
Hello,

Could you specify your question?

GemPy has a built in function to set the topography of a model and there is also a tutorial called [Topography] (https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-7b-Topography.ipynb) that describes how to set the topography in GemPy.

If you need to work with your tif in python for other purposes, just load it as an numpy array.

Cheers Alex

**Comment by wh19971014** [comment]
Hi， @AlexanderJuestel .
There is a photo about DTM from GemPy's example,but now I can't find where it is from ,do you know.
![QQQQ](https://user-images.githubusercontent.com/60054308/82280151-cd93af80-99c0-11ea-9d99-dab80426cc56.png)

**Comment by AlexanderJuestel** [comment]
Hello, 

I unfortunately do not know where this image is from. However, it seems very similar to images posted on [Neosciences.org](https://www.neonscience.org/create-hillshade-py).

What I am still missing is the objective of your issue? Do you have issues converting your tif to a DEM or anything else? Or would you like to display the hillshades as shown in the image above? Please specify.

Cheers Alex

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
Is there easy way to make  .tif format file become DEM and DTM？

**Comment by AlexanderJuestel** [comment]
Hello,

please ellaborate more on the purpose. 

- Do you need a DEM for GemPy? Then GemPy has a function called `geo_model.set_topography(...)` to do that automatically. 

- A Digital Terrain Model (DTM) or hillshades can be generated in the upcoming release of GemPy automatically as well to aid interpretation of your geological maps computed from the model. 

- If you need it as a numpy array, then I can for instance refer you to the following thread on Stackoverflow: [Working with TIFFs (import, export) in Python using numpy
](https://stackoverflow.com/questions/7569553/working-with-tiffs-import-export-in-python-using-numpy)
