### ISSUE TITLE
what is the proportinon of other mixed colors which make up a surface's color

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#423]
**What is your question?**
The formation generated by GemPy has different.Under what color mode are these colors generated,that is ,what is the proportinon of other mixed colors which make up a surface's color.For example the red of the following photo.
![20200519201722](https://user-images.githubusercontent.com/60054308/82325447-d8c0fc80-9a0d-11ea-8538-9ba4f6da32c2.png)

**Comment by AlexanderJuestel** [comment]
Hello, 

please specify your question a little bit more? Would you like to know **how the colors for surfaces are being generated**? Or **how you can change these colors and use custom colors**? Or **how these colors are mixed (proportions of other mixed colors)**? 

I just put the example of the purple/red label below in case that is what you need:

![image](https://user-images.githubusercontent.com/45469915/82327068-24f44880-99de-11ea-8b2f-734cafdd1bb9.png)

(Source: https://www.colorhexa.com/9f0052)

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
I want to know **how these colors are mixed (RGB Decima)?**,I open the internet link you gave,but when I enter the color number,for example **#ffbe00**,it did't show the answer of RGB Decima,it's the following answer.
![QQ截图20200519220227](https://user-images.githubusercontent.com/60054308/82335858-77545a00-9a1c-11ea-86fc-ac3227f18681.png)

**Comment by elimh** [comment]
in python, you can also do this to convert the hexstring to rgb:
```python
>>> import matplotlib.colors as mcolors
>>> print(mcolors.hex2color('#9f0052'))
(0.6235294117647059, 0.0, 0.3215686274509804)
```

**Comment by Japhiolite** [comment]
> Hi, @AlexanderJuestel
> I want to know **how these colors are mixed (RGB Decima)?**,I open the internet link you gave,but when I enter the color number,for example **#ffbe00**,it did't show the answer of RGB Decima,it's the following answer.
> ![QQ截图20200519220227](https://user-images.githubusercontent.com/60054308/82335858-77545a00-9a1c-11ea-86fc-ac3227f18681.png)

https://www.colorhexa.com/ffbe00 works for me

**Comment by AlexanderJuestel** [comment]
@wh19971014,

Did this solve your issue or are there any other open questions?

**Comment by wh19971014** [comment]
Hi， @elimh 
your way can only show the  the proportinon of other mixed colors which make up a surface's color,but it can't show the RGB value of  mixed colors

**Comment by AlexanderJuestel** [comment]
Hey,

An RGB color value is specified with: rgb(red, green, blue).

Each parameter (red, green, and blue) defines the intensity of the color as an integer between 0 and 255 with 0 as the lowest and 255 with the highest intensity. 

If you multiply the result of @elimh with 255 you should get your rgb value. So your purple would convert to rgb(159,0,82).

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel 
but on your comment the RGB value of "#9f0052" is (62,0,32).
![82327068-24f44880-99de-11ea-8b2f-734cafdd1bb9](https://user-images.githubusercontent.com/60054308/82532903-d2996000-9b74-11ea-95b7-c7866ef6a856.png)

**Comment by AlexanderJuestel** [comment]
Hello,

That was only the percentage that was shown. You would have to convert it back to values between 0 and 1 or 0 and 255.

**Comment by wh19971014** [comment]
Hi, @AlexanderJuestel
now I know what @elimh means, multipling the result of @elimh with 100  should get my rgb value,not multypling 255. on your comment the RGB value of "#9f0052" is (62,0,32).

**Comment by AlexanderJuestel** [comment]
Hey,

This was not the rgb value but the fraction between the different colors.

Anyway, if your issue has been solved now, feel free to close the issue.

Let us know if you have any further questions.

Alex
