### ISSUE TITLE
How to deal with Fault Branches/Thrust Sheets in GemPy

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#425]
**What is your question?**
This is more like a general question rather than asking for support. 

In the picture below, a big detachment is shown within a fold and thrust belt. This detachment currently ends at the surface within the youngest thrust sheet (the detachment is forming the base of the thrust sheet). Further to the right, a stack of older thrust sheets with faults merging into the detachment can be seen. This is almost identical to what I am currently working. @javoha and I had also had a discussion about a while ago if I remember correctly.

Would it now be possible to define a sort of parent fault like the youngest thrust plus the detachment and multiple younger/daughter faults that merge into the detachment? I could imagine you compute the scalar field of the parent fault and then set the daughter faults finite once they intersect the detachment or maybe say that they are supposed to use the scalar field of the parent fault now. The are also other examples like flower structures where this could be applied to for instance.

What is your take on that? :) 

![image](https://user-images.githubusercontent.com/45469915/82759324-0979ab00-9ded-11ea-9391-4d6d42ed8754.png)
(Image Source: https://www.sciencedirect.com/science/article/abs/pii/S1367912014000285)

**Comment by Leguark** [comment]
This would be a very interesting structure to add to the examples. How I would do it:
1) Model the father fault as usual
2) Model the children faults as one single series.
    2.1) To make them closer together at depth, I would increase the value of the module of an 
          orientation -> changing the polarity from 1 to 3 for example (using the usual 
          model.modify_orientations)

    2.2) The parent fault offset the children. If there is not data for the children at the other side of  
       parent fault, they will automatically end at that plane (like here https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_5_fault_relations.html#sphx-glr-tutorials-ch1-fundamentals-ch1-5-fault-relations-py)

**Comment by AlexanderJuestel** [comment]
@Leguark thanks for the prompt answer. 

I was actually thinking about providing a simple example of a fold and thrust belt as part of my thesis or at least afterwards to show future users that such geometries are possible. Now I can even compare what I am currently doing (each fault as a separate series, I have not gotten to the depth of the proposed detachment though but it works more or less) with your approach. 

I will reference the model in here again once I have set it up ;)
