### ISSUE TITLE
The interactive window image disappeared

### ISSUE THREAD

**Issue by fiecato** [cgre-aachen/gempy#430]
**What is your question?**
Hello, when the geological image is displayed in the interactive window, I use the mouse to rotate, and the image disappears immediately. What is the reason?

This is the graph I drew.

![image](https://user-images.githubusercontent.com/40785341/83395827-8defad80-a42d-11ea-9b1b-a39d0360a2aa.png)

**Comment by AlexanderJuestel** [comment]
Hey @fiecato,

thanks for your question. We hope we can help out. 

Very important for us to know would be which version of GemPy you are using since version 2.2 was released last week and your described issue was not mentioned before and I have not encountered it before either during my work. 

Best regards
Alex

**Comment by fiecato** [comment]
> Hey @fiecato,
> 
> thanks for your question. We hope we can help out.
> 
> Very important for us to know would be which version of GemPy you are using since version 2.2 was released last week and your described issue was not mentioned before and I have not encountered it before either during my work.
> 
> Best regards
> Alex

Thank you very much for your reply. I just noticed that the cudnn version of my computer is too high. I am trying to reduce the cudnn version. I will keep you updated when there are new developments.

**Comment by fiecato** [comment]
Hello there!
I just installed cuDNN v6.0 (April 27, 2017), for CUDA 8.0 and cuda8.0, but in the graphical interactive window, when I zoom out, select, zoom in, etc., I ca n’t see the operation Is the image required to be set before vv = gp.plot.plot_3D (geo_data)?

gempy version
![image](https://user-images.githubusercontent.com/40785341/83408307-00b85300-a445-11ea-89a2-600fb4c7ca94.png)

cuda version
![image](https://user-images.githubusercontent.com/40785341/83408431-28a7b680-a445-11ea-9988-8c6b0601af94.png)

**Comment by AlexanderJuestel** [comment]
Hey @fiecato,

did you manage to solve the problem since you closed the issue? 

Best regards 
Alex

**Comment by fiecato** [comment]
Yes, I have solved it, it is the problem of orientation generation, because I am not very familiar with this, and there were some problems when generating this.

Thank you very much!
