### ISSUE TITLE
Gempy 2.2.0 missing gempy.api_modules

### ISSUE THREAD

**Issue by ben-cgi** [cgre-aachen/gempy#431]
Installing gempy through pip from pypi, I get the following error

>>> import gempy as gp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/Dropbox (CGI)/Projects2020/TestModelBuilderUtils/venv/lib/python3.7/site-packages/gempy/__init__.py", line 16, in <module>
    from gempy.api_modules.getters import *
ModuleNotFoundError: No module named 'gempy.api_modules'

I'm using ubuntu 18.0.4 LTS with python 3.7.7 installed with pyenv

installed gempy with pip install gempy in a fresh virtualenv

resulting environment

pip freeze:

appdirs==1.4.4
attrs==19.3.0
backcall==0.1.0
cycler==0.10.0
decorator==4.4.2
gempy==2.2.0
imageio==2.8.0
importlib-metadata==1.6.0
ipython==7.15.0
ipython-genutils==0.2.0
jedi==0.17.0
kiwisolver==1.2.0
matplotlib==3.2.1
meshio==4.0.13
more-itertools==8.3.0
networkx==2.4
numpy==1.18.4
packaging==20.4
pandas==1.0.4
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pluggy==0.13.1
prompt-toolkit==3.0.5
ptyprocess==0.6.0
py==1.8.1
Pygments==2.6.1
pyparsing==2.4.7
pytest==5.4.2
python-dateutil==2.8.1
pytz==2020.1
pyvista==0.24.2
PyWavelets==1.1.1
scikit-image==0.17.2
scipy==1.4.1
scooby==0.5.4
seaborn==0.10.1
six==1.15.0
Theano==1.0.4
tifffile==2020.5.30
traitlets==4.3.3
vtk==8.1.2
wcwidth==0.2.2
zipp==3.1.0

**Comment by ben-cgi** [comment]
I'll add that downgrading to 2.1.1 I don't have this issue (but rather an issue with nptyping that requires that package to be downgraded as well.  In this case I can import the module, but not run the tutorial examples due presumably to the documentation being for the newer version.)

**Comment by GeorgeLiang3** [comment]
Hi @ben-cgi, what's the version of your nptyping? they just released an update on pip, which will cause import issue. Try nptyping <=1.0.1

**Comment by Leguark** [comment]
thanks for the heads up. I will look at it right away!

**Comment by Leguark** [comment]
I am extremely confused why the pip version was corrupted but now in gempy 2.2.1 this should be fixed.
Thank you @ben-cgi so much for finding this so fast! Please check that now it is working properly and if it does close the issue :)

**Comment by ben-cgi** [comment]
Thank YOU @Leguark.  This fixed pip install for 2.2.1 and now the API matches the tutorial documents!

**Comment by ben-cgi** [comment]
I noticed that the documentation links return a 404 code ever since you fixed the 2.2.1 release.  Is there a chance this is related to deploying the fix?

**Comment by Leguark** [comment]
It was a bug on the travis file when we were deploying the documentation. I think now it is solved.

Sorry for the instability of the last couple of days. Many new changes :)

**Comment by domist07** [comment]
Same error arises with gempy 2.2.2
