### ISSUE TITLE
Geographic to Structural

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#432]
Gathering data from `gemgis` @AlexanderJuestel  Add a notebook explaining into GemPy

- [ ] Load an area into `pyvista`
- [ ] Interpolate height
- [ ] Adding `gempy` input data interactively 

**Additional**
- [ ] Make `geopandas`  a bridge between `gemgis` and `gempy`

**Comment by AlexanderJuestel** [comment]
I will close this issue as it was related to the Transform 2020 and things are now being worked on in the GemGIS repo ;)
