### ISSUE TITLE
Interactive 2D

### ISSUE THREAD

**Issue by Leguark** [cgre-aachen/gempy#433]
Adding/delete/modify the option to add surface points by clicking on the matplotlib figure. 

**Example**
https://github.com/Japhiolite/bqcs

---- 
In 3D we have the modifying option in place:

https://github.com/cgre-aachen/gempy/blob/master/notebooks/3d_visualization.ipynb

**Relates to**
#432

**Comment by AlexanderJuestel** [comment]
@Leguark, this could be another feature that we could implement in GemGIS and have implemented already for the Transform 2020. I would say that most geologists are familiar with software like QGIS and will store their data within this environment working with spatial data (shape files, geojsons, etc.). Especially for larger models, it becomes necessary to use such a system to keep track of your data. 

I am sure that we could implement a simple notebook solution for smaller models or just extend our current solution for map views to cross-sections. Maybe @Japhiolite will be supportive for that as well ;) In the end it is all about getting da Pandas DataFrame for GemPy and that is what we are doing with GemGIS. 

I would move this issue at some point to GemGIS then if no one disagrees :)
