### ISSUE TITLE
Interactively modify data in pyvista

### ISSUE THREAD

**Issue by nlosacco** [cgre-aachen/gempy#442]
Hi all,
so now PyVista is the default 3D renderer for GemPy, see #156 
Is it still possible to modify data directly from the 3D plots? I used to do it with VTK but does not seem to work now.
Thanks,
N

**Comment by javoha** [comment]
Hi @nlosacco ,

here is the link to the notebook showing how the interactive plotting works using the new plotting api:

https://github.com/cgre-aachen/gempy/blob/master/notebooks/3d_visualization.ipynb

I hope this solves the issue, feel free to reopen if there are any problems.
Best wishes!
