### ISSUE TITLE
How to show surface points on Pyvista

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#454]
**What is your question?**
I have installed the last version of GemPy both on my Laptop and PC. In my PC when I want to see surface points in 3d in Pyvista, it only shows the orientations. 
![Unbenannt](https://user-images.githubusercontent.com/62764899/85417582-11ee0e80-b570-11ea-938b-2959f577d444.JPG)

I followed the same way for gempy installation in my Laptop and there I can see the surface points.
In advance, I appreciate any consideration,

**Comment by javoha** [comment]
Hello @Ali1990dashti ,

sorry for the delayed answer. So you are using the exact same code on your laptop and your PC? If that is true can you check if both have the same versions of pyvista and VTK? Definitely a weird error.

**Comment by Ali1990dashti** [comment]
Dear @javoha 

Thanks for your help. I will check it,. But, I followed the same route to install Gempy 2.2.2 in a new conda environments both on my laptop and PC. I did not install pyvista or VTK seperately and all were installed just by installing gempy.

**Comment by Ali1990dashti** [comment]
Dear @javoha

Surprisingly I have the same versions of pyvista (0.24.3) and VTK (9.0.0) on my laptop and PC. As I said, I did not install them manually and they are installed as requirements of Gempy and I followed the same way to do it on both systems.

**Comment by AlexanderJuestel** [comment]
@Ali1990dashti did you manage to display your data? If so, feel free to close the issue :)
