### ISSUE TITLE
Add a classification column to input data

### ISSUE THREAD

**Issue by Japhiolite** [cgre-aachen/gempy#458]
**Is your feature request related to a problem? Please describe.**
From experience, input data for geological models ranges from true observations (e.g. interfaces from borehole stratigraphy) over inferred interface points to data points, which are necessary for model construction. An additional column could help differentiating between these points, and enable to, for example, easily modify subsets of input data.

**Describe the solution you'd like**
Add an additional column to input interface and orientation data with prescribed options of different strings (e.g. "observed", "inferred", "model-construction") or other identifiers. 

**Describe alternatives you've considered**
An alternative could be using indices in the surface-points dataframe. However, this can get quite complex to keep track of (the more data points you have).

**Additional context**

**Comment by AlexanderJuestel** [comment]
Hey :) 

I also had an issue open regarding that (#438) but good to see that you also need it :)

**Comment by Japhiolite** [comment]
ok, then let's focus on #438
