### ISSUE TITLE
Test suite opens too many figures simultaneously

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#472]
**Describe the bug**
Many of the tests make figures, display them with `plt.show()`, and never explicitly close the figures.

For example:

```
C:\Users\zimme\Desktop\gempy\gempy\plot\visualization_2d.py:158: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
```

This could be one of the causes of the intermittent bus error seen in #461 . In any case, this should be cleaned up.

**To Reproduce**
Run pytest on gempy/test.

**Expected behavior**
Not getting warnings that can be avoided by cleaning up the handling of figures.

**Additional context**
I also get a pile of these kinds of warnings:
```
test/test_plotting/test_2d.py::test_plot_2d_data_default
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:9: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_plot_2d_test_labels
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:24: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_plot_2d_test_labels
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:31: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_plot_2d_test_labels
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:38: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_plot_2d_test_labels
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:41: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_topo_sections_iterp2
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:63: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()

test/test_plotting/test_2d.py::test_topo_sections_iterp2
  C:\Users\zimme\Desktop\gempy\test\test_plotting\test_2d.py:68: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()
```
and when running the test suite, I have to manually close many figures rather than being able to go get a coffee. All of this just makes running the local test suite and debugging new code a lot harder.

**Comment by AndrewAnnex** [comment]
@alexanderzimmerman this is actually pretty easy to solve by changing how gempy uses the matplotlib api/ using plt.close('all') periodically. I think there has been recent changes to the matplotlib api that makes it a bit more object oriented, so individual functions in gempy could create and return a figure object that the user can show/close independently from eachother as well but that may require a large re-write

**Comment by alexanderzimmerman** [comment]
There have been many changes to the plotting functionality and to the test suite since I encountered this issue; and it has been a while since I have needed to run the test suite locally. As long as it's not bothering anyone else, I'm going to close this for now.
