### ISSUE TITLE
GemPy installation problem - conflict with Python versions

### ISSUE THREAD

**Issue by natuzza** [cgre-aachen/gempy#476]
With Python 3.7 I get the error message "no module named 'vtkIOExodusPython'" so I installed 3.6 as advised but with Python 3.6 it comes up with an error that says "SyntaxError: future feature annotations is not defined" which I have read one solution is to install Python 3.7. Is there another solution to this? Thank you.

**Comment by GeorgeLiang3** [comment]
Hi @natuzza ,if you got "no module named vtk", please try `$ pip install vtk `, see gempy installation instruction [here](https://www.gempy.org/installation)

**Comment by natuzza** [comment]
> Hi @natuzza ,if you got "no module named vtk", please try `$ pip install vtk `, see gempy installation instruction [here](https://www.gempy.org/installation)

hi @GeorgeLiang3 apologies I was mistaken and have edited my qs. I had actually already done that with python 3.7 and it came up with the error "No module named 'vtkIOExodusPython'".  Do you happen to know a solution to this?

**Comment by AndrewAnnex** [comment]
that is purely a vtk issue, not an issue with gempy. I recommend ensuring you don't have mixed environments (using the wrong pip, wrong python. You can also try ensuring you install vtk 8.2 as there are some issues with the newer version (forget where I heard this). Also for issues like this the OS and other system info a really critical to know

**Comment by natuzza** [comment]
thank you, i tried that as well and it came up with other errors so I decided to uninstall and reinstall Anaconda and that worked!
