### ISSUE TITLE
'Pinching out' surfaces

### ISSUE THREAD

**Issue by natuzza** [cgre-aachen/gempy#479]
Hi, apologies if this has been asked before but I couldn't find anything on it. Is there a way to 'pinch out' a surface that's between two surfaces? Like when a bed thins out and eventually 'disappears'? Is it possible to connect surface1 and surface3 at certain points in a model for example?

 Thank you

**Comment by AlexanderJuestel** [comment]
Hello natuzza, 

thanks for your question. How have you defined your layer stack? Each series is separated by an erosional surface. So you could try to put Surface3 and Surface2 in one series and Surface1 in a younger series to model an unconformity.

I hope that helps!
Cheers Alex

**Comment by natuzza** [comment]
@AlexanderJuestel thank you very much! this helped a lot.
