### ISSUE TITLE
Vertical scale to visualize a structure

### ISSUE THREAD

**Issue by Griseldum** [cgre-aachen/gempy#481]
**What is your question?**
Hello!
I have starting using GEMPY for my project and have found your software very useful, however, I am having some problems to change the vertical scale to visualize a structure. I am trying to model a carbonate pinnacle, but the visual shape is a bit flat. I wonder if there is any way to change the vertical scale.
I appreciate any advice regarding this. 

Regards, 
Grisel Jimenez

**Comment by AlexanderJuestel** [comment]
Hello @Griseldum, 

thanks for your question and great that you started using GemPy!

Back to your question: How do you visualize your data? A little code is always helpful ;)  You should be able to pass the argument `ve = 2` to the plotting function, i.e. `gp.plot_2d(geo_model, ...., ve = 2)` to achieve a 2 times vertical exaggeration of your model.

Maybe test that and just get back to us if you have any other questions.

Cheers Alex

**Comment by Griseldum** [comment]
Hello!
I have tried again and is working now. 
Many thanks!
Regards, 
Grisel
