### ISSUE TITLE
Uncertainty of the location and orientation of faults

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#482]
**What is your question?**
Hello,
I wanted to show the uncertainty of the location and orientation of faults. Anyone knows perturb both the location and orientation of the existing faults together? How can I match the change of X, Y, Z with dip and azimuth?
In advance, I appreciate any consideration.
Cheers!

**Comment by Leguark** [comment]
Hi @Ali1990dashti, 

I am not sure if I understand your question. Orientations are input data and hence technically there is nothing to match there. In the end for orientations, the location XYZ is not too important so probably you only need to perturb the angle to capture some of its uncertainty.

If you mean, matching surface points and orientations, the easiest you can do is to make the orientation dependent on the surface points (fitting a plane for example - or using `gp.set_orientation_from_surface_points`) in any case there is not an automatic way to do this built in in GemPy

**Comment by Ali1990dashti** [comment]
Dear @Leguark 

Thank you for your response.
I mean I want to fluctuate the dip and azimuth of the fault in a way that surface points of the faults also fluctuate with them. If I only perturb the dip and azimuth, still my fault plane must pass through its surface points.
I hope I have made my question clear.
Thanks again,

**Comment by Leguark** [comment]
yes, in that case either the location of the points or the orientation has to be function of the other. As I posted before, I think it is easier to find the orientation that match points:
1) You sample from your surface points the new location
2) You compute the orientation perpendicular to the new location of the points (at least 3)
3) You pass the new location of surface points and the orientation to GemPy

The alternative would be to make the location of the surface points dependent on the orientation.
1) you sample the direction of the orientation
2.1) You sample how much the surface points are moving
2.2) you move the points in the direction of the new orientation as much as the distance
3) You pass all the values to GemPy

As you can see in both cases you must manually to correlate surface points and orientations - by making one function of the other - before you set the values in the gempy data structure.

Hope this helps a bit! I am sure many people could benefit of this. It would be great if you share your example in a pull request once you crack it!

**Comment by AlexanderJuestel** [comment]
Hey @Ali1990dashti, 

You mentioned "surface points" of your fault. Does that implicate that you do not have any points at depth?

I hope this little extensive tutorial will help you. This is how I understand your question and what I would do. Let us know if you need anything else!  

1. Create a copy of your initial interfaces and orientations as they need to be reset after each realization.

```ruby
import copy 

df_int_X      = copy.copy(geo_model.surface_points.df['X'])
df_int_Y      = copy.copy(geo_model.surface_points.df['Y'])
df_int_Z      = copy.copy(geo_model.surface_points.df['Z'])

df_or_X       = copy.copy(geo_model.orientations.df['X'])
df_or_Y       = copy.copy(geo_model.orientations.df['Y'])
df_or_Z       = copy.copy(geo_model.orientations.df['Z'])
df_or_dip     = copy.copy(geo_model.orientations.df['dip'])
df_or_azimuth = copy.copy(geo_model.orientations.df['azimuth'])
```

2. Store indices - if you just want to filter for your fault interfaces filter the df 

```ruby
surfindexes = list(geo_model.surface_points.df.index)
orindexes = list(geo_model.orientations.df.index)
```

3. Reset DataFrames before each realization

```ruby
#reset Dataframes
geo_model.modify_surface_points(surfindexes, X=df_int_X, Y=df_int_Y, Z=df_int_Z)
geo_model.modify_orientations(orindexes, X=df_or_X, Y=df_or_Y, Z=df_or_Z,dip = df_or_dip, azimuth = df_or_azimuth)
geo_model.update_to_interpolator()
```

4. Change your location values. Here I have chosen a standard deviation of 100. With modify_surface_points you can change the XYZ locations of your fault interfaces. Here demonstrated for the X values.

```ruby
stdev = 100
X_sample = np.random.uniform(-stdev,stdev, size = 1)
geo_model.modify_surface_points(fault_interfaces_index, X = geo_model.surface_points.df.loc[fault_interfaces_index].X+X_sample)
```       
5. Change the dip and azimuth of your orientations. Be aware that you should rather use the von Mises Fisher distribution to sample orientations rather than normal distributions. This was just done for simplicity here. 

```ruby
dip = np.random.normal(45,10, size = 1)
azimuth = = np.random.normal(45,10, size = 1)
geo_model.modify_orientations(fault_orientations_index, dip = dip, azimuth = azimuth)

```    

6. Recompute your model. You may want to use for loops of put these steps in a function and use list comprehension to compute multiple realizations. 

```ruby
geo_model.update_to_interpolator()
gp.compute_model(geo_model)
lith_blocks = np.append(lith_blocks, geo_model.solutions.lith_block)
```

**Comment by Ali1990dashti** [comment]
Dear @Leguark  and @AlexanderJuestel 
First, I deeply appreciate your contribution and help.
I tried the detailed tutorial prepared by @AlexanderJuestel. I gave my virtual data for a fault in a way to pass a line through two data points (surface points of the fault). A simple inverse tangant can help to find it. Points were 
Point one : X=53.36, Y=15, Z=80.43
Point two : X=35, Y=15, Z=40
Then, the orientation data were orientation=np.array([270, 64.5, 1]).
After perturbing this input data using proposed procedure, I called the surface_points and orientation of the perturbed fault. 
Point one : X=106.994648, Y=15, Z=93.968914
Point two : X=88.634648, Y=15, Z=53.538914
However, dip of the new fault is changed. It is now 8.534304.
I think the only way is writing a function that honors the fluctuation of the dip of the fault regarding its two surfaces_points. It seems that right now these two parameters of the fault plane are fluctuating independently and Gempy is trying its best to pass a line cutting two surface points and also satisfying the dip value. As @Leguark said, location of the points or the orientation has to be function of the other.
Thank you again for paying attention to my request.

**Comment by domist07** [comment]
In [#318](https://github.com/cgre-aachen/gempy/pull/318) I'm working on a function which calculates the orientations from the neighbour points of the same surface. I hope that I could pull it in a few months. If you want to impliment a pre version you could insert this code into gempy/core/data.py. You have to install sklearn first. For flat faults you could use knn-search.

```
def create_orientation_from_nn(self, surface_points,  searchcrit, x_scale=1, y_scale=1, z_scale=1):
        """
        Calculates the orientation from neighbour points of the same surface
        by given radius (radius-search) or fix number (knn).

        Parameters
        ----------
        self : geo_model
            GemPy-model.
        surface_points: Pandas-dataframe
            Contains the dataframe of the (point-)data from the GemPy-model.
        searchcrit : int or float
            if is int: uses knn-search.
            if is float: uses radius-search.
        """
        
        from sklearn.neighbors import NearestNeighbors
        from sklearn.preprocessing import normalize

        # extract surface names
        surfaces = np.unique(surface_points['surface'])
        nbrs = []
        search_id = []
        # for each surface
        if isinstance(searchcrit, int):  # in case knn-search
            searchcrit = searchcrit + 1  # because the point itself is also found
            for i in range(surfaces.size):
                # extract point-ids
                i_surfaces = surface_points['surface'] == surfaces[i]
                # extract point coordinates
                p_surfaces = surface_points[i_surfaces][['X', 'Y', 'Z']]
                # rescale points
                p_surfaces['X'] = p_surfaces['X'] / x_scale
                p_surfaces['Y'] = p_surfaces['Y'] / y_scale
                p_surfaces['Z'] = p_surfaces['Z'] / z_scale
                # save order of point ids for search
                search_id.append(p_surfaces.index)
                # create search-tree
                Tree = NearestNeighbors(n_neighbors=searchcrit)
                # add data to tree
                Tree.fit(p_surfaces)
                # find neighbours
                nbrs_surfaces = Tree.kneighbors(p_surfaces, n_neighbors=searchcrit,
                                                return_distance=False)
                # add neighbours with initial index to total list
                for i in nbrs_surfaces:
                    nbrs.append(p_surfaces.index[i])
        else:  # in case radius-search
            for i in range(surfaces.size):
                # extract point-ids
                i_surfaces = surface_points['surface'] == surfaces[i]
                # extract point coordinates
                p_surfaces = surface_points[i_surfaces][['X', 'Y', 'Z']]
                # rescale points
                p_surfaces['X'] = p_surfaces['X'] / x_scale
                p_surfaces['Y'] = p_surfaces['Y'] / y_scale
                p_surfaces['Z'] = p_surfaces['Z'] / z_scale
                # save order of point ids for search
                search_id.append(p_surfaces.index)
                # create search-tree
                Tree = NearestNeighbors(radius=searchcrit)
                # add data to tree
                Tree.fit(p_surfaces)
                # find neighbours (attention: relativ index!)
                nbrs_surfaces = Tree.radius_neighbors(p_surfaces,
                                                      radius=searchcrit,
                                                      return_distance=False)
                # add neighbours with initial index to total list
                for i in nbrs_surfaces:
                    nbrs.append(p_surfaces.index[i])
        # connect search_id to one array
        search_id = np.concatenate(search_id)

        # count neighbours found
        c = []
        for i in nbrs:
            c.append(i.size)

        # initialize one orientation if none exists
        deleteFirst = False
        if self.df.empty:
            self.set_default_orientation()
            deleteFirst = True
        # compute normal vector for each point
        for i in range(len(nbrs)):
            if c[i] > 2:
                # extract point coordinates
                coo = surface_points.loc[nbrs[i]][['X', 'Y', 'Z']]
                # calculates covariance matrix
                cov = np.cov(coo.T)
                # extract eigenvalues from covariance matrix
                eig = np.diag(cov)
                # check orientation of normal vector (has to be oriented to sky)
                if eig[2] < 0:
                    eig = eig*(-1)
                # calculate normalized normal vector
                normvec = normalize(np.cross(cov[0].T, cov[1].T).reshape(1, -1))
                # change normal vector format from coordinates to azimuth and dip
                dip = np.degrees(np.arccos(normvec[0, 2])) % 360
                azimuth = np.degrees(np.arctan2(normvec[0, 0], normvec[0, 1])) % 360
                # append to the GemPy-model
                self.add_orientation(surface_points['X'][search_id[i]],
                                     surface_points['Y'][search_id[i]],
                                     surface_points['Z'][search_id[i]],
                                     surface_points['surface'][search_id[i]],
                                     orientation=[azimuth, dip, 1])
            # if computation is impossible set normal vector to default orientation
            else:
                self.add_orientation(surface_points['X'][search_id[i]],
                                     surface_points['Y'][search_id[i]],
                                     surface_points['Z'][search_id[i]],
                                     surface_points['surface'][search_id[i]],
                                     orientation=[0, 0, 1])
        # delete initialize orientation, if it was set
        if deleteFirst:
            self.del_orientation(0)
        return self
```

**Comment by AlexanderJuestel** [comment]
Any news on this here @Ali1990dashti?

**Comment by Ali1990dashti** [comment]
Dear @AlexanderJuestel 

Sorry for being late.
I tried to make location and dip of the faults as a function of each other but unfortunately I did not reach reliable outcomes. I said that the dip of faults should be updated as the following, but I think Gempy is also using this command, so I could not fix the issue:

```
new_X_fault= geo_model.surface_points.df['X'].values[fault_surf_points] + np.random.uniform(-10, 10, size=1)
new_Y_fault = geo_model.surface_points.df['Y'].values[fault_surf_points] + np.random.uniform(-10, 10, size=1)
new_Z_fault = geo_model.surface_points.df['Z'].values[fault_surf_points] + np.random.uniform(-10, 10, size=1)
new_azi_fault = geo_model.orientations.df['azimuth'].values[fault_orient] + np.random.uniform(-10, 10, size=1)
new_dip_fault = math.degrees(math.atan(new_Z_fa[0]-new_Z_fa[1])/(new_X_fa[0]-new_X_fa[1]))
```
after running it, again had produced some faults with nonlinear surfaces.
Have you found any other way to do it in gempy?

**Comment by AlexanderJuestel** [comment]
@Ali1990dashti any news here? 

In general values have been updated/modified using either `geo_model.modify_orientations(...)` or `geo_model.modify_surface_points(...)` as shown above. 

Is there anything more we can help with?
