### ISSUE TITLE
Dependency issue with mplstereonet

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#483]
**Describe the bug**
When trying to use mplstereonet with a fairly new version of matplotlib or NumPy, mplstereonet may throw an error (see screenshot). This is expected to happen if new users install GemPy and have a current version of the packages in questions. I also mentioned the error directly here: https://github.com/joferkington/mplstereonet/issues/35 

It is questionable if a new version of mplstereonet is ever released...the bug seems to be resolved when using the development version but I doubt it that many users would install an increasing number of packages manually to get GemPy running....

**To Reproduce**
Install latest versions of matplotlib and NumPy and run the example of mplstereonet

**Expected behavior**
No error should be returned

**Screenshots**
![image](https://user-images.githubusercontent.com/45469915/87878088-5e4b3380-c9e2-11ea-9860-a8a2fe199abf.png)

**Comment by AlexanderJuestel** [comment]
According to the author of the package, he may release a new version of mplstereonet shortly.

**Comment by AlexanderJuestel** [comment]
New version of the package was published and bug is resolved. 

![image](https://user-images.githubusercontent.com/45469915/87879716-d74f8880-c9ec-11ea-8c4f-b82e98e4e644.png)

**Comment by whl19910402** [comment]
Do you have a open source reservoir numerical simulator to run the geo model?




姓名：王洪利
Name: Hongli Wang


学校：中国石油大学（北京）
University: China University of Petroleum, Beijing


电话：+86.15210870454
Mobile: +86.15210870454


邮箱：15210870454@163.com
Email: 15210870454@163.com


QQ: 715500861
On 07/20/2020 00:23, AlexanderJuestel wrote:

Closed #483.

**Comment by AlexanderJuestel** [comment]
Hey @whl19910402,

How is your question related to the closed issue? 

But to answer your questions, GemPy is not capable of doing numerical reservoir simulations. Other packages may do this for you. 

Best regards 
Alex
