### ISSUE TITLE
Topography fails to load if model extent equals raster extent

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#492]
**Describe the bug**
I have a model with an extent of [0,972,0,1069]. The respective raster hast the same extent with [0,972,0,1069]. When trying to load this raster into GemPy, the error below appears. @endarthur has narrowed down the issue to the fact that no `_cropped_xyz.tif` file is created. 

**To Reproduce**
Load a raster as topography with the same extent as the model (1 m resolution) should cause the error

**Expected behavior**
A DEM of the same size as the model area should not fail to load

**Screenshots**
![image](https://user-images.githubusercontent.com/45469915/88460527-212ce880-ce9d-11ea-9fa6-4d92f18b3f79.png)

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version: 2.1.1 but still present in the latest version

**Comment by bluetyson** [comment]
What does gdalinfo say for that file?  Mentions ArcGIS in the notebook - that seems to often break them in the past.

**Comment by endarthur** [comment]
It looks like it's the result of this if:

https://github.com/cgre-aachen/gempy/blob/233944433890d482265537610618574bd930df33/gempy/core/grid_modules/create_topography.py#L97-L101

I believe that adding a check with os.path.exists at

https://github.com/cgre-aachen/gempy/blob/233944433890d482265537610618574bd930df33/gempy/core/grid_modules/create_topography.py#L61-L64

should probably fix that.

**Comment by AlexanderJuestel** [comment]
A PR was made to fix this issue ;)
