### ISSUE TITLE
AttributeError: module 'gempy' has no attribute 'utils'

### ISSUE THREAD

**Issue by Dionaea** [cgre-aachen/gempy#496]
pip installed gempy throws this error on import in google colab

`import gempy as gp
`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-041da87106af> in <module>()
----> 1 import gempy as gp

2 frames
/usr/local/lib/python3.6/dist-packages/gempy/core/model.py in <module>()
     15 from gempy.core.interpolator import InterpolatorModel, InterpolatorGravity
     16 from gempy.utils.meta import _setdoc, _setdoc_pro
---> 17 import gempy.utils.docstring as ds
     18 from gempy.plot.decorators import *
     19 

AttributeError: module 'gempy' has no attribute 'utils'

```

**Desktop:**
  * OS: Ubuntu 18.04 (current in colab)
  * GemPy Version 2.2.3
  * Jupyter Version 5.2.2 (current in colab)

**Comment by Dionaea** [comment]
The same error appears on Linux 16 laptop with gempy installed via pip and github

**Comment by AlexanderJuestel** [comment]
Hey @Dionaea,

Unfortunately, our core development team who could deal with these things is on holidays. They will tackle the issue once they are back.

Maybe try installing a previous version of GemPy like 2.2.1. That one should run without issues.

Sorry that I cannot be of more help. 

Cheers Alex

**Comment by Japhiolite** [comment]
@Dionaea so you want to run GemPy using Google colab, right?  
The OS Version or Jupyter Version are not really important to know, this may most likely have something to do with your python version. Python 3.6 can cause some importing issues with the current state of gempy (e.g. trying to import `annotations`).

What is your python version? I assume it'll be 3.6.9 - standard on colab, but just to be sure, can you run `!python --version` in a code cell and share the result?

I could not replicate this specific error on a colab server, but the mentioned `annotations` error above.

**Comment by Dionaea** [comment]
Yes, I did , but gave up on running gempy in colaba already and installed it on my laptop.
Looks like python version is the key, since gempy runs without errors on my laptop with python 3.8.
I keep getting the error in colab :
![image](https://user-images.githubusercontent.com/9076612/89197922-a4a1b480-d5d6-11ea-9f3a-fc754af2a4a4.png)
But since it is not a problem anymore, should this issue be closed?

**Comment by Japhiolite** [comment]
Good to hear that it now works locally. 

Keep the issue open, I'll look into the problem in the next days, to see if I find a solution to this.

Or, we simply state that python >= 3.7 is necessary for gempy. ;)

**Comment by AlexanderJuestel** [comment]
Hell @Dionaea and hello @Japhiolite any news here? Otherwise we could close this issue then :)
