### ISSUE TITLE
Pandas: TypeError: take() got an unexpected keyword argument 'allow_fill'

### ISSUE THREAD

**Issue by prisae** [cgre-aachen/gempy#497]
**Describe the bug**

Invoking `gempy.init_data` results in
```
Pandas: TypeError: take() got an unexpected keyword argument 'allow_fill'
```

**To Reproduce**

1. Update pandas
2. Run this:
```
geo_model = gempy.create_model('mymodel')
data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
gempy.init_data(
    geo_model,
    [0, 2000., 0, 2000., -2000, 40.], [50, 50, 51],
    path_o=data_path+"/data/input_data/tut_chapter1/simple_fault_model_orientations_geophy.csv",
    path_i=data_path+"/data/input_data/tut_chapter1/simple_fault_model_points_geophy.csv",
)
```

It fails with the above error. When I install `pandas<1` it works.

**Comment by Japhiolite** [comment]
A small addition: I had the same error now with `pandas 1.1.0`.  With the previous version `pandas 1.0.5`, it works for me. 
So sth. in the [change from 1.0.5 to 1.1.0](https://pandas.pydata.org/docs/whatsnew/v1.1.0.html) must cause this error, right?

**Comment by prisae** [comment]
That might be. It didn't work with the newest version, so I just installed the version <1 without dissecting in more detail...

**Comment by alexanderzimmerman** [comment]
Yeah, my interpretation after digging more-than-I-would-have-liked into `pandas` is that they improved their validation which apparently is to stop users from doing weird things, but then they didn't catch an internal mistaken argument (that you ran into) with their tests. See #502 . I haven't managed to make a MWE for `pandas` to begin fixing that, so for now I just froze to `pandas==1.0.5` (#504 ).

`pandas` is quite central to `gempy`, so this feels really patchy to me and I want us to do better. We are putting some thought into how to protect our releases from this type of issue ( #506 ).

Thanks for reporting this!

**Comment by prisae** [comment]
OK, sounds good for the moment. As an advice, I would really avoid pinning things with `==` -> this is what often causes dependencies conflict with installation. If something else has `pandas==1.0.0` it will all break and you cannot install the two things. It would be better to do `pandas<=1.0.5`, which gives at least some freedom.

**Comment by alexanderzimmerman** [comment]
> It would be better to do `pandas<=1.0.5`, which gives at least some freedom.

Yes, that would have been a better patch. Thanks for pointing this out.
