### ISSUE TITLE
Ask for permission to redistribute modified models

### ISSUE THREAD

**Issue by prisae** [cgre-aachen/gempy#498]
Dear GemPy Team,

First of all thanks for the great tool including docs and models, really appreciated!

My question goes back to work I started with @Leguark at Transform2019. We worked on integrations of GemPy/discretize/PyVista/SimPEG/emg3d etc. Since then, I use the *simple_fold_model* in my examples.

Currently I am moving in a grey zone there. You released the models under the LGPL-3.0. I think it should be OK when I do changes to that model within the example, but it is probably not OK to store the model (and subsequently use it in other examples); because emg3d uses the Apache 2.0 license.

The example is located here: https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-I.html

Currently I have a text that says:
> **Note:** The original model (simple_fault_model) hosted on https://github.com/cgre-aachen/gempy_data is released under the LGPL-3.0 License.

However, I would like to store the *resulting resistivity model* (not the GemPy-files) and re-use it. Therefore _I kindly ask GemPy for permission to modify your *simple_fold_model* and redistribute within emg3d the resulting resistivity model under the Apache 2.0 license_.

I would adjust the above text accordingly, eg:
> **Note:** The original model (simple_fault_model) hosted on https://github.com/cgre-aachen/gempy_data is released under the LGPL-3.0 License. Permission to modify and redistribute the resulting resistivity model has been given to emg3d by GemPy, see https://github.com/cgre-aachen/gempy/issues/498.

I would also like to create a second model based on the Perth Basin, see https://github.com/prisae/tmp-share/blob/master/gempy-discretize-emg3d/GemPy-discretize-SimPEG.ipynb

Again, I would take the model, make a marine case out of it, assign resistivities to the lithologies, and the thing I would like to distribute is the actual, final resistivity model (not the GemPy files).

I am not a lawyer, I am not sure if it is necessary or not, and I am pretty sure that you are OK with it either way. I just would like to make it a bit more formally so either way we should be good. A simple "yes" from your side should suffice I guess :smile: 

Thanks everyone for your work!

**Comment by prisae** [comment]
Both mentioned examples are now there, https://empymod.github.io/emg3d-gallery/gallery/index.html#interactions:
- https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-I.html
- https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-II.html

**Comment by AlexanderJuestel** [comment]
@Leguark @flohorovicic this may still need your attention :)

**Comment by prisae** [comment]
We had some discussions on Swung in this regard. Software licenses are probably not appropriate for models in the first place, and it might be worth discussing if changing to a CC licence instead wouldn't be better.

For the ones on Swung, here the links to the discussions:
- https://swung.slack.com/archives/C0AG7T5UP/p1596179119194900
- https://swung.slack.com/archives/C0AG7T5UP/p1596191048198600

@Leguark concluded also with
> Maybe I should just set the CC-BY-SA license to it

which I think would be a great move and resolve all similar issues.

**Comment by Leguark** [comment]
oh wow I missed this threat completely (I remember the slack conversation). Thank you @AlexanderJuestel from bring it up.

So for me the question is how to place a license to data. Do you know if it is enough to place it in the repository root or has to go for each folder?

**Comment by prisae** [comment]
It is probably good to have it in each folder, for two reasons:
- Someone will most likely just copy a folder to somewhere, because he/she is only interested in one particular model. If the license is not in that folder it will be lost.
- Different models could potentially have different licenses.

Then, in the root, you can still put a License, and note that by default all models are under license X, unless something else is specified in the model-folder.

**Comment by Leguark** [comment]
alright. Thanks for the advise. Task in my stack
