### ISSUE TITLE
Model for fractures/faults in homogeneous rock

### ISSUE THREAD

**Issue by shakasaki** [cgre-aachen/gempy#500]
Hello, I'm quite new to gempy and not still sure if what i'm trying to do is possible.

In summary, I want to build a geological model where I can visualize fractures and faults as discrete entities (surfaces that can bend and can be bounded within the modeling domain) within a homogeneous rock matrix (granite). This is somewhat like building a discrete fracture network (DFN) that will be mainly conditioned to borehole data. 

From the borehole data I get the orientations and positions of faults. Several boreholes exist, and some of these faults traverse all of them. So I though that I can import these in gempy as surfaces points and orientations, and compute the model that will eventually be a surface.

Trying this, the resulting surface does not honor the orientations given. Anyone has an idea of why this is? I assume it is an interpolation problem, where the orientations are too close together to well condition the surface. Any other feedback is very welcome and appreciated.

Attached is the resulting gempy model and below is the code to produce it. Thanks!

![model-screenshot](https://user-images.githubusercontent.com/7264182/89630694-02b4ed00-d8a0-11ea-8794-6e71f86cc3dc.png)

I followed the code from the gempy tutorial on surface creation

```


import gempy as gp

geo_model = gp.create_model('Bedretto')
geo_model = gp.init_data(geo_model, extent=[-125, -75, -50, 0, 1375, 1425], resolution=[100, 100, 100])
gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
geo_model.surfaces
geo_model.set_default_surfaces()

# Fracture points includes X Y Z X_orientation Y_orientation Z_orientation
frac_points = [[-113.4,   -37.5,    1387.0,    0.04891,   -0.12311,    0.10030],
               [-105.9,   -30.9,    1395.7,    0.05759,   -0.12078,    0.10677],
               [-100.1,   -25.8,    1402.7,    0.05336,   -0.11213,    0.07916]];
                
for frac in range(2):
    geo_model.add_surface_points(X=frac_points[frac][0], Y=frac_points[frac][1], Z=frac_points[frac][2], surface='surface1')
    geo_model.add_orientations(X=frac_points[frac][0], Y=frac_points[frac][1], Z=frac_points[frac][2], surface='surface1', pole_vector=(frac_points[frac][3], frac_points[frac][4], frac_points[frac][5]))

gp.compute_model(geo_model)
geo_model.additional_data.kriging_data
geo_model.additional_data.rescaling_data
gp.plot.plot_3D(geo_model, show_surfaces=True)






```

**Comment by AlexanderJuestel** [comment]
Hey,

@shakasaki, welcome to GemPy. Currently, it is holiday season and lake time (because of the heat), so most of our developers are gone.

We will get back to you as soon as possible!

Stay tuned!
Cheers Alex

**Comment by domist07** [comment]
Hi @shakasaki,
If you want the orientations to be included exactly in the calculation, set the smoothing factor to zero:
`geo_data._orientations.df['smooth'] = 0`

**Comment by shakasaki** [comment]
Hello to both and thanks for the quick response!

@domist07 I tried what you suggest with the following line 

`geo_model.orientations.df.smooth[:] = 0`

which I run just prior to computing the model (`gp.compute_model(geo_model)` in the code snippet above). But I stil get the same smoothed surface..

**Comment by shakasaki** [comment]
Well let me slightly correct the comment above. The suggested approach does work, when I input some dummy points that are well placed apart, and with orientations that are identical (screenshot attached). But it still does not work well for the real coordinates and orientations I use above. So I suppose it might be a problem of finding the correct interpolation (?)
![dummy_model](https://user-images.githubusercontent.com/7264182/89779935-ba503600-db10-11ea-9556-3ee0b1bb0a5e.png)

**Comment by domist07** [comment]
Which GemPy version did you use? I use 2.2.3 and my result looks much different: 
![grafik](https://user-images.githubusercontent.com/59735059/89781573-e9b47200-db13-11ea-965f-7a5c25a6bb27.png)
Additionally I have to write `for frac in range(3):`. Otherwise I have only two points and orientations.

**Comment by shakasaki** [comment]
@domist07 indeed, that was the issue. I had an older version of gempy (2.1.1) which did not seem to work. I updated and it now works perfectly (the range(2) was a typo). Thank you for the time you put into responding!
