### ISSUE TITLE
Regression in master because of change in pandas

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#502]
The master branch isn't passing Travis tests, so PR branches are also failing. This shows up e.g. in this CRON build: https://travis-ci.org/github/cgre-aachen/gempy/builds/714780814 , where the error was

```
____________ ERROR collecting test/test_core/test_data_mutation.py _____________
test/test_core/test_data_mutation.py:11: in <module>
    mm.add_surfaces(['surface1', 'foo1', 'foo2', 'foo3'])
gempy/core/model.py:737: in add_surfaces
    self._surfaces.add_surface(surface_list, update_df)
gempy/core/data.py:596: in add_surface
    self.map_series()
gempy/core/data.py:760: in map_series
    self.sort_surfaces()
gempy/core/data.py:678: in sort_surfaces
    self.df.sort_values(by=['series', 'order_surfaces'], inplace=True)
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/frame.py:5301: in sort_values
    indexer, axis=self._get_block_manager_axis(axis), verify=False
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/internals/managers.py:1415: in take
    new_axis=new_labels, indexer=indexer, axis=axis, allow_dups=True
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/internals/managers.py:1259: in reindex_indexer
    for blk in self.blocks
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/internals/managers.py:1259: in <listcomp>
    for blk in self.blocks
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/internals/blocks.py:1720: in take_nd
    new_values = self.values.take(indexer, fill_value=fill_value, allow_fill=True)
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/core/series.py:829: in take
    nv.validate_take(tuple(), kwargs)
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/compat/numpy/function.py:68: in __call__
    validate_kwargs(fname, kwargs, self.defaults)
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/util/_validators.py:148: in validate_kwargs
    _check_for_invalid_keys(fname, kwargs, compat_args)
../../../miniconda/envs/tenv/lib/python3.7/site-packages/pandas/util/_validators.py:122: in _check_for_invalid_keys
    raise TypeError(f"{fname}() got an unexpected keyword argument '{bad_arg}'")
E   TypeError: take() got an unexpected keyword argument 'fill_value'
```

@Leguark said he doesn't remember even using `fill_value`, so it might be a bug inside of `pandas`. Anyway, I'll start digging into it.

**Comment by alexanderzimmerman** [comment]
I get the same error locally after upgrading to pandas 1.1.0.

**Comment by alexanderzimmerman** [comment]
It's starting to look like there is an incompatibility between the pandas and numpy versions.

**Comment by alexanderzimmerman** [comment]
The problem line in pandas is `new_values = self.values.take(indexer, fill_value=fill_value, allow_fill=True)` in their pandas/core/internals/blocks.py . Their own validator, which checks keyword arguments passed to numpy functions (via the pandas interface), now says that `allow_fill` is not valid. But pandas 1.0 also passed `fill_value` here. `numpy.take` indeed has no `fill_value` keyword argument. So my understanding is that they added better internal validation in 1.1, but this `take_nd` method is not tested during pandas development.

**Comment by alexanderzimmerman** [comment]
I'm having a hard time writing a script (other than the existing gempy test) which can even manage to execute that line of code in `pandas/core/internals/blocks.py`. This is deep inside of pandas.

**Comment by Leguark** [comment]
just fix the version of pandas in the requirements

**Comment by alexanderzimmerman** [comment]
> just fix the version of pandas in the requirements

Locally when I ran on pandas 1.0 it fixed this but it threw another error on a different test.

**Comment by alexanderzimmerman** [comment]
I'm kind of impressed that we get this error only with

```
import gempy as gp


def test_add_surfaces():

    mm = gp.ImplicitCoKriging()

    mm.add_surfaces(['surface1', 'foo1', 'foo2', 'foo3'])
```

so I just started looking into `ImplicitCoKriging.add_surfaces`, but yeah I'm running out of time to spend on this one.

**Comment by alexanderzimmerman** [comment]
Yeah I'm done with this for the day and will decide how to proceed in the morning. I wanted to raise an issue on the pandas side, but right now I can't even manage to write a MWE that reproduces the error without importing gempy. Probably there is a way to set up a minimal `pandas.DataFrame` such that the same error occurs.

Tomorrow morning I can try fixing pandas==1.0 and see if the bug on that front is easier to fix.

**Comment by alexanderzimmerman** [comment]
Looks like pandas==1.0.5 should be fine.

**Comment by alexanderzimmerman** [comment]
Probably `pandas` is central enough to `gempy` that we will want to figure out the root problem and get back to using the latest pandas, so I'll leave this open for now.

**Comment by alexanderzimmerman** [comment]
Fixed by #504

**Comment by AndrewAnnex** [comment]
@alexanderzimmerman is this fixed as of pandas 1.1.1?

**Comment by Leguark** [comment]
we would have to try. If you are able to run anything with pandas 1.1.1 probably is fixed because the change broke a function we are using all the time. Next time I work in gempy I will check this out

**Comment by alexanderzimmerman** [comment]
@AndrewAnnex and @Leguark , Travis is checking this in #515.

**Comment by alexanderzimmerman** [comment]
Ah, also @AndrewAnnex had already made #514 to test `pandas==1.1.1.`  Travis passed #514.
