### ISSUE TITLE
Fault_Block

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#503]
**What is your question?**
Dear all,

Hope doing well and being healthy. I have a question about the possibility of showing the effect of a fault on the output model of gempy. To my understanding, after exporting our model the block ID of faults (lets say 1) is not observed in the grids which means faults have not any volume i.e. faults just displace adjacent blocks. A way is to propagate a layer sandwiching the fault between layers (a highly informative example is presented in https://github.com/Japhiolite/gempy-tests/blob/master/notebooks/Test-model_dyke.ipynb). In this example, a dyke layer is proposed to represent the effect of fault. But it seems too tricky to develop a very thin layer around the fault in a 3D model.
Is there any other way to show the effect of the faults (except displacing layers) on the model?
In advance, I appreciate any contribution and help.

Cheers,
Ali

**Comment by javoha** [comment]
Hello @Ali1990dashti,

as of now there is no function in Gempy to add fault core or damage zone. Some reasonable workarounds are discussed here: #326 . It is also on our list and might become a feature in the future. Can you maybe also specifiy why the solution in the notebook you linked does not work for you scenario?

Best wishes,
Jan

**Comment by Ali1990dashti** [comment]
Hi @javoha 

Thanks for your informative response. The solution in the notebook cannot be applied fpr 3d models. I added several surface points and orientations for the dyke but still this series doesn't propagate like a thin layer parallel to the fault. By adding the inputs of the dyke, model was getting more and more local and it is giving me the dyke as finite bodies around the input data, instead a of a layer with parallel boundaries. A screenshot is dragged here.
![pic](https://user-images.githubusercontent.com/62764899/90370251-6e037980-e06d-11ea-9528-b76fb8e37a6f.png)

Also by decreasing the thinckness of dyke, the results of model get more problematic. 
I tried to play with the range parameter of kriging (using geo_model.modify_kriging_parameters('range', ...)) and increased it but still it was not enough and I could not achieve my goal.
Thanks again to the community for being responsible and making research easier.

**Comment by flohorovicic** [comment]
Dear @javoha and @Ali1990dashti ,

This could also be another potential application of a hierarchical modelling method, as a bit of a workaround, by maybe giving @Ali1990dashti what is needed at the moment.

Essentially, it would be a combination of two models:

1. The "base" model with the fault as offset, as it is now;
2. A "dike"/ "fault core" model, which contains _only_ the points and orientations for the fault - shifted in plus/minus directions orthogonal to the fault plane and **in a conventional "geological series" order** 

Finally, you would have to re-combine results of both models for visualisation and export. To see how this could work, I would suggest to start with a voxel export first - and simply to replace the voxels of model 1 with those of model 2 where the dyke/ fault core is present. 

Not sure if this approach would solve your question, @Ali1990dashti , but maybe worth a try.

**Comment by Ali1990dashti** [comment]
Dear @flohorovicic and @javoha 

I really appreciate your excellent hints.
I tried to make two separate models (base model and dyke model) and replace the dyke layer of my dyke model with the existing lithology ids in the base model. The simplest way to replace it is using pandas dataframe (`base_model.loc[dyke_model.lith_id==2, 'lith_id']=5`).
The following picture was the result:
![fig](https://user-images.githubusercontent.com/62764899/90391739-e9752300-e08d-11ea-8cd2-4b5e68e07f2a.jpg)

**Comment by javoha** [comment]
This looks pretty great and like a straighforward and solid solution. Is this sufficient to solve your problem?

**Comment by Ali1990dashti** [comment]
Yes, proposed methods were truly efficient.
Thanks for helping.

**Comment by flohorovicic** [comment]
Great to see that the solution worked! Seems like you are approaching a "gempy-wizard" status!

**Comment by AlexanderJuestel** [comment]
Closing this issue as it seems the problem was solved. Feel free to reopen it if there are more problems coming up.
