### ISSUE TITLE
AssertionError: One or more columns do not match with the expected values --- even though it seems ok

### ISSUE THREAD

**Issue by polyye** [cgre-aachen/gempy#510]
I'm trying to simply plot my 2D model, using surface points and surface orientations data, but it is not happening. I was wondering if the model is too big and therefore gempy wouldn't handle that amount of points. There is a total of 1648 points.

I get the following error 

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-4-380014fe7174> in <module>
>       5 geo_data = gp.create_data('viz_2d', [0, 778000, 0, 192900, 0, 50000], resolution=[10, 10, 10],
>       6                           path_o=data_path + "surface_points.csv",
> ----> 7                           path_i=data_path + "orientations.csv")
> 
> ~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\gempy_api.py in create_data(project_name, extent, resolution, **kwargs)
>     147     geo_model = create_model(project_name)
>     148     return init_data(geo_model, extent=extent, resolution=resolution,
> --> 149                      project_name=project_name, **kwargs)
>     150 
>     151 
> 
> ~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\gempy_api.py in init_data(geo_model, extent, resolution, **kwargs)
>     183 
>     184     if 'path_i' in kwargs or 'path_o' in kwargs:
> --> 185         read_csv(geo_model, **kwargs)
>     186 
>     187     if 'surface_points_df' in kwargs:
> 
> ~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\gempy_api.py in read_csv(geo_model, path_i, path_o, **kwargs)
>     228     if path_i is not None or path_o is not None:
>     229         try:
> --> 230             geo_model.read_data(path_i, path_o, **kwargs)
>     231         except KeyError:
>     232             raise KeyError('Loading of CSV file failed. Check if you use commas '
> 
> ~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\core\model.py in read_data(self, source_i, source_o, add_basement, **kwargs)
>    1639             self._surface_points.read_surface_points(source_i, inplace=True, **kwargs)
>    1640         if isinstance(source_o, pn.DataFrame) or source_o:
> -> 1641             self._orientations.read_orientations(source_o, inplace=True, **kwargs)
>    1642         if add_basement is True:
>    1643             self._surfaces.add_surface(['basement'])
> 
> ~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\core\data_modules\geometric_data.py in read_orientations(self, table_source, debug, inplace, kwargs_pandas, **kwargs)
>     854                 "- the '{}' of the orientation, can be normal (1) or reversed (-1) \n".format(polarity_name)+\
>     855                 "- the name of the surface: '{}'\n".format(surface_name)+\
> --> 856                 "Your headers are "+str(list(table.columns))
>     857 
>     858             if inplace:
> 
> AssertionError: One or more columns do not match with the expected values, which are: 
> - the locations of the measurement points 'X','Y' and 'Z' 
> - EITHER 'azimuth' (trend direction indicated by an angle between 0 and 360 with North at 0 AND 'dip' (inclination angle, measured from horizontal plane downwards, between 0 and 90 degrees) 
> - OR the pole vectors of the orientation in a cartesian system 'G_x','G_y' and 'G_z' 
> - the 'polarity' of the orientation, can be normal (1) or reversed (-1) 
> - the name of the surface: 'formation'
> Your headers are ['X', 'Y', 'Z', 'formation']

I checked the headers in both CSV files and they match the required: 
X | Y | Z | formation       and
X | Y | Z | azimuth | dip | polarity | formation

the locations of the measurement points 'X','Y', and 'Z' are also within the range of the plot. I set the azimuth of all the points to be equal to 90. Dips are between 0 and 90. I set the polarity of the points to be equal to 1. Formations names have no space, only underscore when needed.

Here is what I'm running:

> import numpy as np
> import pandas as pd
> import matplotlib.pyplot as plt
> np.random.seed(1515)
> pd.set_option('precision', 2)

> data_path = 'D:/gempy-master/data/output/'
> 
> geo_data = gp.create_data('viz_2d', [0, 778000, 0, 192900, 0, 50000], resolution=[10, 10, 10],
>                           path_o=data_path + "surface_points.csv",
>                           path_i=data_path + "orientations.csv")

I don't know what else I could be doing wrong.
Thank you!

**Comment by javoha** [comment]
Hi @polyye,
this defnitiley looks a little awkward. The problem seems purely related to reading the csv files. Can you check if they are really comma separated again - Here a raw example of what it should look like: https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/data/input_data/jan_models/model5_orientations.csv.

If you can share your input files we might be able to take a closer look.

Best wishes and good luck!

**Comment by polyye** [comment]
[orientations.txt](https://github.com/cgre-aachen/gempy/files/5093502/orientations.txt)
[surface_points.txt](https://github.com/cgre-aachen/gempy/files/5093503/surface_points.txt)

I'm using .csv files (converted to .txt just so I could upload them in here).

**Comment by javoha** [comment]
Hi @polyye,

thanks for sharing the input files. I think I found the main problem - Your coordinates feature dots for digit grouping:

```13248.404,192120.381,111.3283734,Lasseter_Shear_Zone```

If you remove those (I just used find and replace all dots with nothing) it works for me. 

A small general warning: The amount of data, but especially the amount of formations your are using seems very ambitious. We generally advice to start modeling the main structural features/domains and adding complexity and detail later. 

Cheers, 
Jan

**Comment by polyye** [comment]
Hi @javoha,

So the coordinates don't work if they are float type? Even if they're, for example, 854321.34?

Thank you for your help.

**Comment by javoha** [comment]
That should work, but in your case it had multiple dots for digit grouping (see example) in the surface_points file. Did you try fixing it and does it work now?

**Comment by javoha** [comment]
Ok I will close this issue then - feel fre to reopen if you have any further problems with the input data. Have a great day and good luck with your model!
