### ISSUE TITLE
Finding z coordinates and order of formations at x and y coordinates 

### ISSUE THREAD

**Issue by saalnafisi** [cgre-aachen/gempy#518]
**What is your question?**
Hello 

Is there a way to get the non-rescaled z coordinates of each surface at a given x and y coordinate locations after interpolation? I would like also to return the id of each surface present along the given x and y. 

Thanks in advance.

**Comment by javoha** [comment]
Hello @saalnafisi ,

it sounds like your are looking to extract/visualize a borehole log based on your model? If that is true, take a look at gemgis, a new library aiming to integrate gempy and gis software. There is a function that provides pretty much what youu need I guess:

https://github.com/cgre-aachen/gemgis/blob/master/notebooks/08_GemGIS_Extracting_Boreholes_and_Depth_Maps.ipynb

If you have any questions, @AlexanderJuestel is the expert for gemgis.

Hopefully this solves your problem - if it doesnt please let us know and we will take another look.

Best wishes and have a great day!

**Comment by AlexanderJuestel** [comment]
Hey,

@javoha is completely right. We currently have a very basic functionality to extract boreholes. However, if you let us know what annotations you would like to have or other features, we are more than happy to prioritize this implementation as that was already on our to do list but has been postponed for now. 

Cheers Alex

**Comment by saalnafisi** [comment]
Perfect, I think the gemgis example is working for me well. The functionality is very useful and it would be more beneficial if I can get the values of the bottom layer of each surface with the ids for that specific borehole log. I posted this as a question in the gemgis github so I apologize if there is a duplication.

**Comment by AlexanderJuestel** [comment]
Closing that as it was moved to GemGIS
