### ISSUE TITLE
Same surface colours?

### ISSUE THREAD

**Issue by natuzza** [cgre-aachen/gempy#519]
Hi, is there a way to have the same colour for different layers? e.g. having one colour for coal seams.

If so, how?

**Comment by Japhiolite** [comment]
Hi @natuzza 

this can be done using the `change_colors()` method. 

You just have to set up a color dictionary, where you assign colors to your model surface. For instance, say you have model called `geo_model` with the surfaces 'Coal_seam1', 'Sandstone', 'Coal_seam2': 

```python
color_dict = {'Coal_seam1': '#63510e', 'Sandstone': '#eef20f', 'Coal_seam2': '#63510e'}

# then change colors of your geo_model by:
geo_model.surfaces.colors.change_colors(colordict=color_dict)
```

You should then have updated the colors of your `geo_model` object.

**Comment by natuzza** [comment]
> Hi @natuzza
> 
> this can be done using the `change_colors()` method.
> 
> You just have to set up a color dictionary, where you assign colors to your model surface. For instance, say you have model called `geo_model` with the surfaces 'Coal_seam1', 'Sandstone', 'Coal_seam2':
> 
> ```python
> color_dict = {'Coal_seam1': '#63510e', 'Sandstone': '#eef20f', 'Coal_seam2': '#63510e'}
> 
> # then change colors of your geo_model by:
> geo_model.surfaces.colors.change_colors(colordict=color_dict)
> ```
> 
> You should then have updated the colors of your `geo_model` object.

Thank you!
