### ISSUE TITLE
Normal fault?

### ISSUE THREAD

**Issue by natuzza** [cgre-aachen/gempy#521]
Hello

Sorry if this is such a basic question but I am trying to model a normal fault. With the geo_model.set_is_fault or set_bottom_relation commands, however, of course the model appears to have a reverse fault. I have data on both sides of the fault with the 'hanging' side being 'deeper'. Is there a way to get this to look like a normal fault?

Thank you

**Comment by AlexanderJuestel** [comment]
Hey,

Could you send us an image of a cross section? How have you defined your surfaces in both sides of the fault?

Cheers Alex

**Comment by natuzza** [comment]
> Hey,
> 
> Could you send us an image of a cross section? How have you defined your surfaces in both sides of the fault?
> 
> Cheers Alex

Hi Alex, 

Here's a photo of it.
![vv](https://user-images.githubusercontent.com/68003413/92387397-090ce200-f148-11ea-8e41-0c737e2f7051.JPG)

I've just defined the purple surface as surface1 in the Default series with Erosion as the bottom relation, then I simply added the fault feature and surface and setting the bottom relation as Fault.

Thank you

**Comment by javoha** [comment]
Hello @natuzza,

if I am following your modeling steps correctly here are two suggestions: make sure all your stratigraphic surfaces (apart from basement) are in one series (so I see blue and red surface points - both should be in the same series). Also, do not define the bottom relation of these surfaces as erosion - as you do not want to model an unconformity fromy what I understand.

I hope this helps and have a great day!
