### ISSUE TITLE
Vertices of models generated through a loop 

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#526]
Dear all,
hope doing well and being healthy
**What is your question?**
I wanted to do an uncertainty analysis and run several models through a for loop. Then, I want to extract vertices generated each run. For lithology IDs I can do it simply by a reshape command (`lith_blocks.reshape(number_of_iterations, -1)`). But for vertices, the size of the numpy array is not fixed through each loop. Have a any idea how I can split the final vertices array based on each iteration?
In advance, I appreciate any contribution.

**Comment by javoha** [comment]
Hello @Ali1990dashti,

so just to clarify if I get your problem correctly: You create different models through a loop and while the grid (e.g lith_block) has the same shape in all instances, the vertices of the corresponding meshes vary for each model? 
The reason for this is, that the meshes are generated using the Marching Cubes algorithm, and if your models feature even slightly different geometries (which I guess they should if there is any uncertainty) the resulting surface meshes will have different shapes. 
I what way do you want to use those meshes and why do they need to be "fixed" through each loop? And what do you mean by "split the final vertices array based on iteration". You should get a different set of surface mehses for each iteration, right?

Best regards,
Jan

**Comment by Ali1990dashti** [comment]
Dear @javoha ,

You understood my question correctly.
I needed the vertices to make mesh from them. For example, I export vertices of the faults and generate my mesh (using Gmsh) based on the generated vertices in Gempy.
I wanted to find a way to specify the vertices generated in each iteration.
I tried the following syntax and it helped me to divide all the vertices based on the numbers of iterations:

```
indices = np.argwhere(np.all(np.diff(vertices_Fault, axis=0) < 0, axis=1))
vertices_Fault_each_iteration=np.array_split(vertices_Fault, indices.ravel()+1, axis=0)
```
These two lines break the whole data set of vertices into iterations, but it would be a better option if Gempy store vertices of each iteration separately (like what it is doing for `geo_model.solutions.lith_block`).

Cheers,
Ali

**Comment by AndrewAnnex** [comment]
the easiest thing to do would be to generate the model once, then re-use the resulting grids for each iteration to keep the vertices fixed, as @javoha points out by default gempy will recalculate different grids even if the input data does not very that much. This can be done by using the various get/set grid functions on the Model/Project class.

**Comment by AlexanderJuestel** [comment]
Any updates on that here @Ali1990dashti?
