### ISSUE TITLE
GemPy import failed: DLL Load Failed vtkIO.... error when using Pyvista 0.26.1

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#529]
**Describe the bug**
When installing GemPy via pip and trying to import it, a DLL load failed vtkio.... error is thrown. This is most likely due to the latest release of pyvista (0.26.1) @banesullivan 

**To Reproduce**
Install GemPy and Pyvista 0.26.1 and try to import GemPy

**Quick fix**
Try using an older version should fix the issue for now.

**Comment by banesullivan** [comment]
Huh, this is weird. @AlexanderJuestel, what was the solution?
