### ISSUE TITLE
How to scale z axis (depth) as most of geo simulators (Petrel, tNavigator) do?

### ISSUE THREAD

**Issue by kaki222** [cgre-aachen/gempy#537]
geo_model = gp.init_data(geo_model,
                         extent= [0, 13000 , 0, 7500, 0, 40], # of the regular grid
                         resolution=[100, 100, 10])         # of the regular grid
p3d = gp.plot_3d(geo_model, plotter_type='background', notebook=False) 

Basically my Z axis (depth) is too small compared to the x,y dimensions (lateral). How can I scale the z axis so as to see my 3d data comfortably.

My ultimate goal is to construct surface that best fit the data, then maybe with a flat basement I will have a reservoir.

Thanks in advance.
code, data and pic attached
[geo_grid-data.xlsx](https://github.com/cgre-aachen/gempy/files/5428784/geo_grid-data.xlsx)

[code.docs.txt](https://github.com/cgre-aachen/gempy/files/5428753/code.docs.txt)
![pic](https://user-images.githubusercontent.com/34009148/96990399-1df6d680-1538-11eb-929f-5f710981bfbc.jpg)

**Comment by domist07** [comment]
Simply multiple your Z values before plotting
```
scaling = 5
geo_model._surface_points.df['Z'] = geo_model._surface_points.df['Z'] * scaling
p3d = gp.plot_3d(geo_model, plotter_type='background', notebook=False)
```

**Comment by kaki222** [comment]
Thank you for ther answer.  How simple.

**Comment by AlexanderJuestel** [comment]
Hey, you can also just add `ve =5` to your plotting command for vertical exaggeration

**Comment by kaki222** [comment]
Thank you Alexander.

**Comment by AlexanderJuestel** [comment]
It seems like this worked, closing the issue. Feel free to reopen it if there are any more issues regarding that comming up.

**Comment by qq123hht** [comment]
Hey,I had a similar problem.
Every time I add to my plotting command for vertical exaggeration, there will be no value displayed on the Z-axis.
How can I solve this problem?
By the way, the X and Y axis ranges also change with the input data, so how to set the range of the axes to the model's extent?
geo_model.extent = [0, 2000, 0, 3000, 250, 350]
Thanks in advance.
Looking forward to your reply.
![12](https://github.com/cgre-aachen/gempy/assets/148225500/a79f2156-4744-4859-ae39-84222591d58a)
![normal](https://github.com/cgre-aachen/gempy/assets/148225500/d142df49-f63a-418f-9dfa-2f25131953aa)
![21](https://github.com/cgre-aachen/gempy/assets/148225500/53d1f717-f36f-4c99-a025-413c6dc230e7)

> Hey, you can also just add to your plotting command for vertical exaggeration`ve =5`
