### ISSUE TITLE
can I interpolation without direction?

### ISSUE THREAD

**Issue by yulongyu** [cgre-aachen/gempy#543]
I see your tutorial, the data in addition have coordinates, there is some points of direction, I do not know much about geology science, but my drilling data only have coordinates, no direction,I think data can interpolation without direction, but the gempy  tutorial no such demo,how can I  interpolate data into 3D geological model without  direction（Normal vector）?

**Comment by AlexanderJuestel** [comment]
Hey @yulongyu, 

By default, GemPy needs orientations. What you could try is obtaining orientations from your drillhole data. If you have 3 drillholes not separated by a fault and if the layer is more or less straight between the boreholes, you could just calculate a plane through these 3 points and get an orientations value?

Hoped that helped!
Cheers Alex

**Comment by yulongyu** [comment]
@AlexanderJuestel 
thankes for your reply，but I have another problem,In the file of orientations, there are only a few points,But if I randomly make a few points with orientations,The generated 3D model is incorrect，Not a plane but a curved surface，I think it is because too few points with directions lead to incorrect interpolation，But how many directional points do I need to make?I am not sure，If every drillholes needs a direction point in every formation,I think too much，so what should I do

**Comment by AlexanderJuestel** [comment]
Hey,
Could you provide us with a map of the spatial distribution of your boreholes?

**Comment by domist07** [comment]
Hi @yulongyu ,
I had the same issue and for that I write a function, which is still a pull request #318. You can add this functionallity by replacing the following file in your gempy installatoin folder by the file from my repo.
https://github.com/domist07/gempy/blob/master/gempy/api_modules/setters.py
Then you can calcluate the orientation for every point from the neighbour points of the same surface.

**Comment by Leguark** [comment]
There is also already  in the release version the function `gp.set_orientation_from_surface_points` that calculates the normal vector given 3 surface points.

Another way to go around this, is to set an orientation relatively far away from the input data pointing upwards
