### ISSUE TITLE
csv file

### ISSUE THREAD

**Issue by yang8038** [cgre-aachen/gempy#553]
![76b8e1e74a6d36b5fa46027ecdff362](https://user-images.githubusercontent.com/75457448/101106870-08330180-360c-11eb-8ada-ef915e2cd418.png)
I want to ask the code in the CSV file what is the meaning of the content of the inside, how to define, how in a points file using a few point to form a surface, in orientations file inside what's the meaning of the specific, want to ask if there is any specific tutorial to learn this part of knowledge, can to change the CSV file to get my own want model

**Comment by javoha** [comment]
Hello @yang8038,

if understand your question correctly you want to know the content of theses files and how it relates to gempy? Gempy requires surface points and orientations as input for the model interpolation. You can import this data basically in whatever way you want or you can also add them manually as shown in the tutorials.
 
For the examples we use _.csv_ files for simplicity. Surfaces require _X, Y_ and _Z_ coordinates as well as the corresponding _formation_. It is important to note that these points always refer to the bottom of a formation (layer). The orientations need the same information (_X, Y, Z, formation_) as well as the direction either by giving a pole _vector_ or _azimuth, dip and polarity_. 

So the content of these files is really just the input data for gempy, there is no code or anything special in them.

I hope this helps and good luck making your own model.

**Comment by yang8038** [comment]
First of all, thank you very much for your answer. I have got some insights. I would like to know how to determine the number of points needed to form a surface，Also want to know the meaning of each data in the picture and how to calculate it。
![1cffb55b50be4fc3123edad2a75fb0c](https://user-images.githubusercontent.com/75457448/101467135-e83d6e00-397c-11eb-91da-c8801c92637d.png)

**Comment by yang8038** [comment]
> Hello @yang8038,
> 
> if understand your question correctly you want to know the content of theses files and how it relates to gempy? Gempy requires surface points and orientations as input for the model interpolation. You can import this data basically in whatever way you want or you can also add them manually as shown in the tutorials.
> 
> For the examples we use _.csv_ files for simplicity. Surfaces require _X, Y_ and _Z_ coordinates as well as the corresponding _formation_. It is important to note that these points always refer to the bottom of a formation (layer). The orientations need the same information (_X, Y, Z, formation_) as well as the direction either by giving a pole _vector_ or _azimuth, dip and polarity_.
> 
> So the content of these files is really just the input data for gempy, there is no code or anything special in them.
> 
> I hope this helps and good luck making your own model.

First of all, thank you very much for your answer. I have got some insights. I would like to know how to determine the number of points needed to form a surface，Also want to know the meaning of each data in the picture and how to calculate it。

![](https://user-images.githubusercontent.com/75457448/101467135-e83d6e00-397c-11eb-91da-c8801c92637d.png)

**Comment by yang8038** [comment]
First of all, thank you very much for your answer. I have got some insights. I would like to know how to determine the number of points needed to form a surface，Also want to know the meaning of each data in the picture and how to calculate it。


On 12/8/2020 16:50，Jan von Harten<notifications@github.com> wrote：

Hello @yang8038,

if understand your question correctly you want to know the content of theses files and how it relates to gempy? Gempy requires surface points and orientations as input for the model interpolation. You can import this data basically in whatever way you want or you can also add them manually as shown in the tutorials.

For the examples we use .csv files for simplicity. Surfaces require X, Y and Z coordinates as well as the corresponding formation. It is important to note that these points always refer to the bottom of a formation (layer). The orientations need the same information (X, Y, Z, formation) as well as the direction either by giving a pole vector or azimuth, dip and polarity.

So the content of these files is really just the input data for gempy, there is no code or anything special in them.

I hope this helps and good luck making your own model.

**Comment by AlexanderJuestel** [comment]
Hello @yang8038,

here a short explanation of the data columns in your picture:
A: Index of your point
B-D: Real world X,Y,Z coordinates of your point
E-G: Rescaled X,Y,Z coordinates within your model framework
H: Dip value (this means your data point is an orientation value)
I: Azimuth of your orientation value
J: Polarity of your orientation value
K: The formation your orientation value belongs to
L: The series your orientation belongs to. In this case, it is a fault
M/N: It shows that this the only formation you have(???)
O: The fault is set as true, which is good.

In order to form a surface you need at least two interface points and one orientation value in accordance with the implicit modeling approach we are using. 

![image](https://user-images.githubusercontent.com/45469915/105961034-497ce600-607e-11eb-86fc-387d1230711c.png)

**Comment by yang8038** [comment]
Hello, can I get in touch with you through WeChat or QQ?Hope to get your contact information


On 1/27/2021 16:06，AlexanderJuestel<notifications@github.com> wrote：

Hello @yang8038,

here a short explanation of the data columns in your picture:
A: Index of your point
B-D: Real world X,Y,Z coordinates of your point
E-G: Rescaled X,Y,Z coordinates within your model framework
H: Dip value (this means your data point is an orientation value)
I: Azimuth of your orientation value
J: Polarity of your orientation value
K: The formation your orientation value belongs to
L: The series your orientation belongs to. In this case, it is a fault
M/N: It shows that this the only formation you have(???)
O: The fault is set as true, which is good.

In order to form a surface you need at least two interface points and one orientation value in accordance with the implicit modeling approach we are using.

**Comment by AlexanderJuestel** [comment]
Hey @yang8038,

let us keep the conversation here on Github also for future users to see it. Thanks

**Comment by yang8038** [comment]
Hello, I would like to ask how to use Gempy to add tunnels into 3D geological models. Is there any relevant materials I can learn


On 1/27/2021 16:37，AlexanderJuestel<notifications@github.com> wrote：

Hey @yang8038,

let us keep the conversation here on Github also for future users to see it. Thanks

**Comment by AlexanderJuestel** [comment]
Hello @yang8038,

this was mentioned already in #407 and is not part of this issue. Please open another issue for new questions. 

However, as a tunnel is not a geological object, I would suggest creating a tube-like mesh with PyVista and letting the tube object intersect with the geological layers. I added an issue to our GemGIS package for tackling this: https://github.com/cgre-aachen/gemgis/issues/133

**Comment by yang8038** [comment]
The tubular grid you mentioned intersects the geological layers. Is there any code related to it


On 1/29/2021 15:22，AlexanderJuestel<notifications@github.com> wrote：

Hello @yang8038,

this was mentioned already in #407 and is not part of this issue. Please open another issue for new questions.

However, as a tunnel is not a geological object, I would suggest creating a tube-like mesh with PyVista and letting the tube object intersect with the geological layers. I added an issue to our GemGIS package for tackling this: cgre-aachen/gemgis#133

**Comment by AlexanderJuestel** [comment]
Hey, like I said, please open a new issue for that if it is not related to the original issue ;)

**Comment by AlexanderJuestel** [comment]
Hey @yang8038, 
I mentioned you here in this issue with respect to your tunnel, check it out: https://github.com/cgre-aachen/gemgis/issues/133#issuecomment-770239478

**Comment by yang8038** [comment]
Is there code to generate this kind of tubular tunnel? Can't find the code in your tutorial?


On 1/31/2021 00:28，AlexanderJuestel<notifications@github.com> wrote：

Hey @yang8038,
I mentioned you here in this issue with respect to your tunnel, check it out: cgre-aachen/gemgis#133 (comment)

**Comment by AlexanderJuestel** [comment]
Closing this now. Discussion continued in #407
