### ISSUE TITLE
How to export model  to vtk ?

### ISSUE THREAD

**Issue by tanny1023** [cgre-aachen/gempy#556]
**What is your question?**
**How to export model  to vtk ?**
I want to export the gempy model to a vtk, and I read the reply of the close issue"Using gempy with pyvista - export to vtk # 531"，I try to use  solution "use .save function in pyvista objects" ,and I got the  pyvista objects use  "result=d.surface_points_mesh" and result=d.orientations_mesh,But only have points in the File.
![image](https://user-images.githubusercontent.com/45989898/101885249-d950f880-3bd4-11eb-8676-575827f4d5e7.png)
Where can I get the whole Model vtk like"gp.plot_3d(geo_model) " shows?
![image](https://user-images.githubusercontent.com/45989898/101885629-567c6d80-3bd5-11eb-963d-f69a45bd2b45.png)

   I build my model and  get the <gempy.plot.vista.GemPyToVista>in Gempy,here is my code follow the tutorial [Claudius — GemPy 2.2.7 documentation]:
https://github.com/tanny1023/TannyGempy/blob/master/001_1_SimpleExample/Q20201211_WantToSaveVTKModel.ipynb

**Comment by AlexanderJuestel** [comment]
Hey @tanny1023,

As far as I know is GemPy wrapping the PyVista plotting functions which makes it a little bit tricky to actually access the data. There is functionality in our GemGIS package (https://github.com/cgre-aachen/gemgis) where you can extract the single meshes and save them directly with PyVista. Alternatively, you could also create a PyVista MultiBlock from all these meshes and then save it using PyVista. 

Let me know if you need any more assistance.
Cheers Alex
