### ISSUE TITLE
Potential field vs. scalar field vs. gradient, and how to obtain them

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gempy#560]
Hello! It's been a while but I have a new question!

I would like to use the orientation of the lithology (i.e. the direction of greatest dip) in each grid cell as an input to a different project ([https://github.com/randlab/pyKasso]), to direct karst conduit formation downdip.

However, I'm confused about the terminology and how to extract what I need.

1. Is the gradient the same thing as the orientation?

2. If yes, I can't extract the gradient from the solution. `solution.gradient` yields an empty array. I tried setting `output='gradient'` instead of `output='geology'` but got  `ValueError: Cannot setitem on a Categorical with a new category, set the categories first`

3. I assume that I could instead calculate the gradient myself from the potential field, but how do I extract the potential field? Is the potential field the same thing as the scalar field? Can I use `solution.scalar_field_matrix`? If yes, that should be upated in the documentation as it's not clear.

Thanks in advance!

**Comment by javoha** [comment]
Hello @cfandel ,

maybe I can answer some of your questions:

1. The gradient of a scalar field points in the direction of greates increase of its value. In gempy this does not correspond to the direction of greatest dip, at least if I understand your question correctly. Instead the gradient in gempy is "pointing upwards" in a sense of time (or depositional age), being normal to the resulting scalar field.

2. I think the direct gradient calculation is disabled in gempy at the moment as there is still some work that needs to be done. You can use `gx, gy, gz = np.gradient(sol.scalar_field_matrix.reshape(res))` to obtain the gradient via numpy.

3. To clarify: We use the word potential field as this is the name of the underlying method (potential field method) in literature. The field though is a scalar field by definition, thats why both terms occur often.

Best wishes and have a nice end of the year!

**Comment by cfandel** [comment]
Thank you! Yes this is very helpful. 
One more clarifying question: my goal is to obtain a gradient field that I can use to direct conduit formation down-dip. It seems like from your description, if the gradient calculated from the potential field points "up," the gradient that I need would be orthogonal to that? If so, then I think that I should be able to calculate it externally from the potential field.
Thanks!

**Comment by AndrewAnnex** [comment]
@cfandel yes, effectively the gradient you would get from np.gradient is effectively the "normal vector", so there are a number of ways to convert a cartesian vector to spherical coordinates (strike/dip, dip/dip-azimuth).

**Comment by cfandel** [comment]
OK great - that's what I needed. Thank you!
