### ISSUE TITLE
can you design GUI by pyqt5 or what with gempy?

### ISSUE THREAD

**Issue by AIjieling** [cgre-aachen/gempy#561]
**What is your question?**
i want to deign GUI with gempy , to view 2d plot or 3d . such as add a button etc.

**Comment by AlexanderJuestel** [comment]
Hey @AIjieling, 

what exactly is your question here?

Cheers Alex

**Comment by AIjieling** [comment]
have you try  converting to exe by pyinstaller?

**Comment by AlexanderJuestel** [comment]
Hello @AIjieling,

this seems similar to the other issue you have opened. You want to design a GUI for GemPy . How can we help you with that?

**Comment by Leguark** [comment]
Hi @AIjieling, if you are doing any progress on this end it would be great to have a detailed issue with a design plan so we can help. 

From our side there are some chances that it will be a project to develop a gempy interface but from now nothing is sure.

For now I will close this issue
