### ISSUE TITLE
pyinstaller  gempy              can it work?

### ISSUE THREAD

**Issue by AIjieling** [cgre-aachen/gempy#562]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndrewAnnex** [comment]
I serious doubt that pyinstaller would be able to work well with gempy due to the number of dependencies and theano in particular. A better, but not easy solution would be to create a conda environment yaml configuration to freeze dependencies.

**Comment by AlexanderJuestel** [comment]
@AIjieling,

do you still have any issues with that?

**Comment by Leguark** [comment]
hopefully the `numpy` version of `gempy`, that will come during 2021, will enable to have an easier installation including pyinstaller. 

If you do not have any other comment I will close the issue for now.
