### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gempy#563]
**What is your question?**

For an easier installation in a conda environment, would it make sense to provide a `environment.yml`-file? Or is this redundant with the already existing installation methods (e.g. over pip, in a new environment)?

**Comment by AndrewAnnex** [comment]
@flohorovicic a conda environment would be better able to handle the multi-platform issues with theano and I have developed environment.yml files for both GPU and non-GPU host systems. That said, this is partially already done by the https://github.com/conda-forge/gempy-feedstock feedstock that I maintain, so if you use the conda-forge channel you should be able to just run `conda install gempy` for a minimally working environment

**Comment by AlexanderJuestel** [comment]
@flohorovicic would you still like to add an environment file to the repository or can this issue be closed?

**Comment by AlexanderJuestel** [comment]
Will be fixed with #640
