### ISSUE TITLE
Creation of 2D / 3D features

### ISSUE THREAD

**Issue by kitsl** [cgre-aachen/gempy#565]
Is it possible to create 3D simple geometric figure inside of model as sphere, cube..., for calculation (for example gravity field)?

**Comment by AlexanderJuestel** [comment]
Hey @kitsl, 

thanks for your question. If I understand your question correctly, this could be done with explicit modeling which @MohammadCGRE is currently working on. It is certainly possible to insert other geometric objects for visualization but I am pretty sure that we cannot model in an explicit way. I assume that you are talking about something like an ore body, correct?

Cheers Alex

**Comment by Leguark** [comment]
At the moment it is not functionality already implemented in gempy. What it is always possible is to get the output  of `gempy` (in `geo_model.solutions.lith_block`) and overprint a regular shape on that 3D array. However if you do so you will need another package to compute the geophysics (`pygimli` or `simpeg`) 

Being able to include any array within the gempy process is one of the features available in GemPy 3 (ETA end of 2021)
