### ISSUE TITLE
Getting Started Tutorial: IndexError during add_model_surfaces()

### ISSUE THREAD

**Issue by Martytalius** [cgre-aachen/gempy#566]
Hi All, I've been going through the getting started tutorial jupyter notebook and have been getting an IndexError whenever I get to the step on adding surface points. 

> %matplotlib inline
> from pyvista import set_plot_theme
> set_plot_theme('document')
> 
> import gempy as gp
> import numpy as np
> import matplotlib.pyplot as plt
> import matplotlib.image as mpimg
> 
> geo_model = gp.create_model('Model1')
> geo_model = gp.init_data(geo_model, extent=[0, 791, 0, 200, -582, 0], resolution=[100, 10, 100])
> gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
> p2d = gp.plot_2d(geo_model)
> img = mpimg.imread('wells.png')
> p2d = gp.plot_2d(geo_model, show=False)
> p2d.axes[0].imshow(img, origin='upper', alpha=.8, extent=(0, 791, -582, 0))
> plt.show()
> 
> geo_model.surfaces
> geo_model.set_default_surfaces()
> geo_model.add_surface_points(X=223, Y=0.01, Z=-94, surface='surface1')

**Screenshots**
![Error_Gempy](https://user-images.githubusercontent.com/45382905/104688736-3e4fbf00-573c-11eb-84d3-5fda89878cb5.PNG)

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version 2.2.7

**Comment by AlexanderJuestel** [comment]
Hey @Martytalius,

thanks for the issue and sorry for getting back to you that late. Could you try providing an index (`idx`) for your surface point? The default value for `idx` in GemPy is `None`, which is indeed not an integer and could be the reason for your index error.

```ruby
Signature:
geo_model.add_surface_points(
    X,
    Y,
    Z,
    surface,
    idx: Union[int, Iterable[int]] = None,
    recompute_rescale_factor=False,
)
```

Cheers Alex

**Comment by Leguark** [comment]
Dear @Martytalius thanks for catching this issue. This was a change in pandas that broke gempy. In master it is already fixed. I will try to release a new pip version this week.

Please reopen the issue if by the next week (with the new version) you still have problems
