### ISSUE TITLE
UserWarning: Surfaces not computed due to: No surface found at the given iso value..

### ISSUE THREAD

**Issue by PeterBetlem** [cgre-aachen/gempy#569]
I have run into the following error several times now:

`UserWarning: Surfaces not computed due to: No surface found at the given iso value.. The surface is: Series: No surface found at the given iso value.; Surface Number:0`

which then results in another error:

`ValueError: shape mismatch: value array of shape (4,) could not be broadcast to indexing result of shape (3,)`

Any idea on how one might solve this? or any idea as to what might cause this?

**Comment by AlexanderJuestel** [comment]
Hey @PeterBetlem,

at what stage of the modeling process did that occur? During the model computation? I think we need some more information :)

Cheers Alex

**Comment by PeterBetlem** [comment]
My sincerest apologies - I must have been half-awake whilst submitting this terribly-explained issue...

This indeed happens during the model computation:

MWE: 

<details>
<summary>Click to expand</summary>

```
import gempy as gp
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import os

surface_points_df = df = pd.read_csv("coordinates_mwe.csv")
orientations_df = pd.read_csv("orientations_mwe.csv")
geo_model = gp.create_model("Deltaneset")
gp.init_data(geo_model,[df.X.min()-50, df.X.max()+50, df.Y.min()-50, df.Y.max()+50, df.Z.min()-50, df.Z.max()+50,], [50, 50, 50],
             #path_o="simple_fault_model_orientations.csv",
              #path_i="simple_fault_model_points.csv",
              surface_points_df = surface_points_df,
             orientations_df = orientations_df,
              default_values=True)

fault_list = []
series = {"Strat_Series": surface_points_df.loc[~surface_points_df["formation"].str.contains("fault"),"formation"].unique().tolist()}

for fault in surface_points_df.loc[surface_points_df["formation"].str.contains("fault"),"formation"].unique():
    series[fault] = fault
    fault_list.append(fault)
    
geo_model.surfaces
gp.map_stack_to_surfaces(geo_model,
                          series,
                          remove_unused_series=True)
geo_model.surfaces
geo_model.stack
geo_model.set_is_fault(fault_list)
geo_model.faults.faults_relations_df

plot = gp.plot_2d(geo_model, show_lith=False, show_boundaries=True)
plt.show()

gp.set_interpolator(geo_model,
                    compile_theano=True,
                    theano_optimizer='fast_run',
                    )
gp.get_data(geo_model, 'kriging')

sol = gp.compute_model(geo_model)

geo_model.solutions
```

</details>

Results in:

<details>
<summary>Click to expand</summary>

```

Setting kriging parameters to their default values.
Compiling theano function...
Level of Optimization:  fast_run
Device:  cpu
Precision:  float64
Number of faults:  2
Compilation Done!
Kriging values: 
                     values
range              401.702
$C_o$              3842.01
drift equations  [3, 3, 3]
[...]\site-packages\gempy\core\solution.py:284: UserWarning: Surfaces not computed due to: No surface found at the given iso value.. The surface is: Series: No surface found at the given iso value.; Surface Number:0
  '; Surface Number:' + str(s_n))
[...]\site-packages\gempy\core\solution.py:284: UserWarning: Surfaces not computed due to: No surface found at the given iso value.. The surface is: Series: No surface found at the given iso value.; Surface Number:1
  '; Surface Number:' + str(s_n))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-ce2c444f109b> in <module>
      9 gp.get_data(geo_model, 'kriging')
     10 
---> 11 sol = gp.compute_model(geo_model)
     12 
     13 geo_model.solutions

~\.conda\envs\gempy\lib\site-packages\gempy\gempy_api.py in compute_model(model, output, at, compute_mesh, reset_weights, reset_scalar, reset_block, sort_surfaces, debug, set_solutions, **kwargs)
    320 
    321         if sort_surfaces:
--> 322             model.set_surface_order_from_solution()
    323         return model.solutions
    324 

~\.conda\envs\gempy\lib\site-packages\gempy\core\model.py in set_surface_order_from_solution(self)
   1464             self._sfai_order_0 = sfai_order
   1465             sel = self._surfaces.df['isActive'] & ~self._surfaces.df['isBasement']
-> 1466             self._surfaces.df.loc[sel, 'sfai'] = sfai_order
   1467             self._surfaces.df.sort_values(by=['series', 'sfai'], inplace=True, ascending=False)
   1468             self._surfaces.reset_order_surfaces()

~\.conda\envs\gempy\lib\site-packages\pandas\core\indexing.py in __setitem__(self, key, value)
    669             key = com.apply_if_callable(key, self.obj)
    670         indexer = self._get_setitem_indexer(key)
--> 671         self._setitem_with_indexer(indexer, value)
    672 
    673     def _validate_key(self, key, axis: int):

~\.conda\envs\gempy\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
   1010                     labels, value, plane_indexer, lplane_indexer, self.obj
   1011                 ):
-> 1012                     setter(labels[0], value)
   1013 
   1014                 # per label values

~\.conda\envs\gempy\lib\site-packages\pandas\core\indexing.py in setter(item, v)
    960                     s._consolidate_inplace()
    961                     s = s.copy()
--> 962                     s._data = s._data.setitem(indexer=pi, value=v)
    963                     s._maybe_update_cacher(clear=True)
    964 

~\.conda\envs\gempy\lib\site-packages\pandas\core\internals\managers.py in setitem(self, **kwargs)
    559 
    560     def setitem(self, **kwargs):
--> 561         return self.apply("setitem", **kwargs)
    562 
    563     def putmask(self, **kwargs):

~\.conda\envs\gempy\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, filter, **kwargs)
    440                 applied = b.apply(f, **kwargs)
    441             else:
--> 442                 applied = getattr(b, f)(**kwargs)
    443             result_blocks = _extend_blocks(applied, result_blocks)
    444 

~\.conda\envs\gempy\lib\site-packages\pandas\core\internals\blocks.py in setitem(self, indexer, value)
    909         # then use the resultant dtype
    910         elif exact_match:
--> 911             values[indexer] = value
    912 
    913             try:

ValueError: shape mismatch: value array of shape (4,) could not be broadcast to indexing result of shape (3,)
```

</details>

[mwe files.zip](https://github.com/cgre-aachen/gempy/files/5878569/gempy.zip)

**Comment by AlexanderJuestel** [comment]
Alright, no problem ;) 

Have you checked that your DataFrames are properly formatted? E.g. that you provided the correct delimiter?


Also, I am not completely sure but I usually pass a tuple of formation names to `map_stack_to_surfaces()`. In addition, it seems like you are appending the faults to the end of your list. Faults are usually put at the top of the stack. 

```ruby
fault_list = []
series = {"Strat_Series": surface_points_df.loc[~surface_points_df["formation"].str.contains("fault"),"formation"].unique().tolist()}

for fault in surface_points_df.loc[surface_points_df["formation"].str.contains("fault"),"formation"].unique():
    series[fault] = fault
    fault_list.append(fault)
```

Maybe check these points and if they all check out, we look further :)

**Comment by PeterBetlem** [comment]
Thanks @AlexanderJuestel, different changes and different outcomes:

- [x] changing all lists to tuples does not appear to make a difference, at least re: UserWarning
- [ ] changing faults to top of the series indeed removes the UserWarning; however, the ValueError remains. From the plot it does appear only one of the two formation surfaces gets plotted, which might explain the error?
- [x] interestingly, running the model computation a second time (i.e., after the error is thrown, without rerunning other parts), results in a successful computational run. Now both surfaces appear to have been plotted?

**Comment by AlexanderJuestel** [comment]
Interesting :D 

Would you mind posting some screenshots of your data table? `geo_model.surface_points.df` and `geo_model.orientations.df` or so. Maybe something is missing there or not correct

**Comment by PeterBetlem** [comment]
Here you go:

<details>
<summary>geo_model.surface_points.df </summary>

X | Y | Z | X_r | Y_r | Z_r | surface | series | id | order_series | smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
202.931564 | 0.338399 | 231.115026 | 0.749892 | 0.332978 | 0.542860 | b | Default series | 1 | 1 | 0.000002
188.080578 | 4.718820 | 230.557488 | 0.712903 | 0.343888 | 0.541472 | b | Default series | 1 | 1 | 0.000002
176.534771 | 8.357239 | 230.344141 | 0.684147 | 0.352950 | 0.540940 | b | Default series | 1 | 1 | 0.000002
167.788132 | 13.150993 | 229.819488 | 0.662362 | 0.364890 | 0.539634 | b | Default series | 1 | 1 | 0.000002
156.303478 | 14.763196 | 229.584125 | 0.633758 | 0.368905 | 0.539047 | b | Default series | 1 | 1 | 0.000002
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
3.233411 | 115.703811 | 219.461117 | 0.252517 | 0.620311 | 0.513835 | a | Default series | 2 | 1 | 0.000002
45.771786 | 81.803732 | 227.753931 | 0.358464 | 0.535878 | 0.534489 | fault_b | Default series | 3 | 1 | 0.000002
75.653567 | 125.345060 | 204.822611 | 0.432889 | 0.644324 | 0.477376 | fault_b | Default series | 3 | 1 | 0.000002
81.112902 | 97.914798 | 211.941987 | 0.446486 | 0.576005 | 0.495107 | fault_a | Default series | 4 | 1 | 0.000002
55.654948 | 59.894653 | 225.438097 | 0.383080 | 0.481311 | 0.528721 | fault_a | Default series | 4 | 1 | 0.000002



X | Y | Z | X_r | Y_r | Z_r | surface | series | id | order_series | smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
202.931564 | 0.338399 | 231.115026 | 0.749892 | 0.332978 | 0.542860 | b | Default series | 1 | 1 | 0.000002
188.080578 | 4.718820 | 230.557488 | 0.712903 | 0.343888 | 0.541472 | b | Default series | 1 | 1 | 0.000002
176.534771 | 8.357239 | 230.344141 | 0.684147 | 0.352950 | 0.540940 | b | Default series | 1 | 1 | 0.000002
167.788132 | 13.150993 | 229.819488 | 0.662362 | 0.364890 | 0.539634 | b | Default series | 1 | 1 | 0.000002
156.303478 | 14.763196 | 229.584125 | 0.633758 | 0.368905 | 0.539047 | b | Default series | 1 | 1 | 0.000002
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
3.233411 | 115.703811 | 219.461117 | 0.252517 | 0.620311 | 0.513835 | a | Default series | 2 | 1 | 0.000002
45.771786 | 81.803732 | 227.753931 | 0.358464 | 0.535878 | 0.534489 | fault_b | Default series | 3 | 1 | 0.000002
75.653567 | 125.345060 | 204.822611 | 0.432889 | 0.644324 | 0.477376 | fault_b | Default series | 3 | 1 | 0.000002
81.112902 | 97.914798 | 211.941987 | 0.446486 | 0.576005 | 0.495107 | fault_a | Default series | 4 | 1 | 0.000002
55.654948 | 59.894653 | 225.438097 | 0.383080 | 0.481311 | 0.528721 | fault_a | Default series | 4 | 1 | 0.000002

</details>

<details>
<summary>geo_model.orientations.df </summary>

X | Y | Z | X_r | Y_r | Z_r | G_x | G_y | G_z | dip | azimuth | polarity | surface | series | id | order_series | smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
200.012265 | 0.774779 | 231.094950 | 0.742621 | 0.334065 | 0.542810 | -0.039779 | 0.035313 | 0.998584 | 3.049118 | 311.596481 | 1 | a | Default series | 2 | 1 | 0.01
117.462994 | 17.806491 | 228.001247 | 0.537021 | 0.376485 | 0.535105 | -0.039779 | 0.035313 | 0.998584 | 3.049118 | 311.596481 | 1 | a | Default series | 2 | 1 | 0.01
62.488756 | 83.334423 | 222.850485 | 0.400100 | 0.539691 | 0.522276 | 0.047752 | 0.015899 | 0.998733 | 2.884864 | 71.585266 | 1 | a | Default series | 2 | 1 | 0.01
37.469888 | 115.520831 | 222.420938 | 0.337787 | 0.619855 | 0.521207 | -0.031294 | 0.142721 | 0.989268 | 8.401675 | 347.632861 | 1 | a | Default series | 2 | 1 | 0.01
31.467016 | 127.704926 | 220.936243 | 0.322836 | 0.650202 | 0.517509 | -0.052441 | 0.035742 | 0.997984 | 3.638585 | 304.276923 | 1 | a | Default series | 2 | 1 | 0.01
16.680371 | 131.407607 | 219.217478 | 0.286008 | 0.659424 | 0.513228 | -0.092784 | 0.086030 | 0.991963 | 7.269151 | 312.836693 | 1 | a | Default series | 2 | 1 | 0.01
175.557398 | 8.800373 | 230.366636 | 0.681713 | 0.354054 | 0.540996 | -0.049954 | -0.061176 | 0.996876 | 4.529944 | 219.234054 | 1 | b | Default series | 1 | 1 | 0.01
140.489988 | 16.802600 | 228.927135 | 0.594373 | 0.373984 | 0.537411 | -0.049954 | -0.061176 | 0.996876 | 4.529944 | 219.234054 | 1 | b | Default series | 1 | 1 | 0.01
56.589492 | 90.919674 | 222.798196 | 0.385407 | 0.558583 | 0.522146 | 0.063573 | 0.035851 | 0.997333 | 4.185479 | 60.579668 | 1 | b | Default series | 1 | 1 | 0.01
37.286999 | 119.411765 | 221.232464 | 0.337332 | 0.629546 | 0.518246 | 0.779127 | 0.319051 | 0.539600 | 57.343598 | 67.730970 | 1 | b | Default series | 1 | 1 | 0.01
35.599354 | 123.057406 | 221.133805 | 0.333128 | 0.638626 | 0.518001 | -0.303392 | -0.166325 | 0.938237 | 20.242376 | 241.267567 | 1 | b | Default series | 1 | 1 | 0.01
22.044691 | 134.877047 | 219.468535 | 0.299369 | 0.668065 | 0.513853 | -0.102454 | 0.034512 | 0.994139 | 6.206413 | 288.616431 | 1 | b | Default series | 1 | 1 | 0.01
95.335269 | 122.823087 | 196.641523 | 0.481909 | 0.638043 | 0.456999 | -0.063357 | 0.538039 | 0.840535 | 32.803293 | 353.284024 | 1 | fault_a | Default series | 4 | 1 | 0.01
75.526316 | 85.423471 | 219.415988 | 0.432572 | 0.544894 | 0.513722 | -0.444772 | 0.617795 | 0.648465 | 49.574002 | 324.248537 | 1 | fault_a | Default series | 4 | 1 | 0.01
65.047981 | 115.485619 | 210.961404 | 0.406474 | 0.619768 | 0.492665 | 0.509554 | 0.131987 | 0.850255 | 31.760539 | 75.478116 | 1 | fault_b | Default series | 3 | 1 | 0.01



</details>

**Comment by PeterBetlem** [comment]
Here you go:

<details>
<summary>geo_model.surface_points.df </summary>

X | Y | Z | X_r | Y_r | Z_r | surface | series | id | order_series | smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
202.931564 | 0.338399 | 231.115026 | 0.749892 | 0.332978 | 0.542860 | b | Default series | 1 | 1 | 0.000002
188.080578 | 4.718820 | 230.557488 | 0.712903 | 0.343888 | 0.541472 | b | Default series | 1 | 1 | 0.000002
176.534771 | 8.357239 | 230.344141 | 0.684147 | 0.352950 | 0.540940 | b | Default series | 1 | 1 | 0.000002
167.788132 | 13.150993 | 229.819488 | 0.662362 | 0.364890 | 0.539634 | b | Default series | 1 | 1 | 0.000002
156.303478 | 14.763196 | 229.584125 | 0.633758 | 0.368905 | 0.539047 | b | Default series | 1 | 1 | 0.000002
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
3.233411 | 115.703811 | 219.461117 | 0.252517 | 0.620311 | 0.513835 | a | Default series | 2 | 1 | 0.000002
45.771786 | 81.803732 | 227.753931 | 0.358464 | 0.535878 | 0.534489 | fault_b | Default series | 3 | 1 | 0.000002
75.653567 | 125.345060 | 204.822611 | 0.432889 | 0.644324 | 0.477376 | fault_b | Default series | 3 | 1 | 0.000002
81.112902 | 97.914798 | 211.941987 | 0.446486 | 0.576005 | 0.495107 | fault_a | Default series | 4 | 1 | 0.000002
55.654948 | 59.894653 | 225.438097 | 0.383080 | 0.481311 | 0.528721 | fault_a | Default series | 4 | 1 | 0.000002
</details>

<details>
<summary>geo_model.orientations.df </summary>

X | Y | Z | X_r | Y_r | Z_r | G_x | G_y | G_z | dip | azimuth | polarity | surface | series | id | order_series | smooth
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
200.012265 | 0.774779 | 231.094950 | 0.742621 | 0.334065 | 0.542810 | -0.039779 | 0.035313 | 0.998584 | 3.049118 | 311.596481 | 1 | a | Default series | 2 | 1 | 0.01
117.462994 | 17.806491 | 228.001247 | 0.537021 | 0.376485 | 0.535105 | -0.039779 | 0.035313 | 0.998584 | 3.049118 | 311.596481 | 1 | a | Default series | 2 | 1 | 0.01
62.488756 | 83.334423 | 222.850485 | 0.400100 | 0.539691 | 0.522276 | 0.047752 | 0.015899 | 0.998733 | 2.884864 | 71.585266 | 1 | a | Default series | 2 | 1 | 0.01
37.469888 | 115.520831 | 222.420938 | 0.337787 | 0.619855 | 0.521207 | -0.031294 | 0.142721 | 0.989268 | 8.401675 | 347.632861 | 1 | a | Default series | 2 | 1 | 0.01
31.467016 | 127.704926 | 220.936243 | 0.322836 | 0.650202 | 0.517509 | -0.052441 | 0.035742 | 0.997984 | 3.638585 | 304.276923 | 1 | a | Default series | 2 | 1 | 0.01
16.680371 | 131.407607 | 219.217478 | 0.286008 | 0.659424 | 0.513228 | -0.092784 | 0.086030 | 0.991963 | 7.269151 | 312.836693 | 1 | a | Default series | 2 | 1 | 0.01
175.557398 | 8.800373 | 230.366636 | 0.681713 | 0.354054 | 0.540996 | -0.049954 | -0.061176 | 0.996876 | 4.529944 | 219.234054 | 1 | b | Default series | 1 | 1 | 0.01
140.489988 | 16.802600 | 228.927135 | 0.594373 | 0.373984 | 0.537411 | -0.049954 | -0.061176 | 0.996876 | 4.529944 | 219.234054 | 1 | b | Default series | 1 | 1 | 0.01
56.589492 | 90.919674 | 222.798196 | 0.385407 | 0.558583 | 0.522146 | 0.063573 | 0.035851 | 0.997333 | 4.185479 | 60.579668 | 1 | b | Default series | 1 | 1 | 0.01
37.286999 | 119.411765 | 221.232464 | 0.337332 | 0.629546 | 0.518246 | 0.779127 | 0.319051 | 0.539600 | 57.343598 | 67.730970 | 1 | b | Default series | 1 | 1 | 0.01
35.599354 | 123.057406 | 221.133805 | 0.333128 | 0.638626 | 0.518001 | -0.303392 | -0.166325 | 0.938237 | 20.242376 | 241.267567 | 1 | b | Default series | 1 | 1 | 0.01
22.044691 | 134.877047 | 219.468535 | 0.299369 | 0.668065 | 0.513853 | -0.102454 | 0.034512 | 0.994139 | 6.206413 | 288.616431 | 1 | b | Default series | 1 | 1 | 0.01
95.335269 | 122.823087 | 196.641523 | 0.481909 | 0.638043 | 0.456999 | -0.063357 | 0.538039 | 0.840535 | 32.803293 | 353.284024 | 1 | fault_a | Default series | 4 | 1 | 0.01
75.526316 | 85.423471 | 219.415988 | 0.432572 | 0.544894 | 0.513722 | -0.444772 | 0.617795 | 0.648465 | 49.574002 | 324.248537 | 1 | fault_a | Default series | 4 | 1 | 0.01
65.047981 | 115.485619 | 210.961404 | 0.406474 | 0.619768 | 0.492665 | 0.509554 | 0.131987 | 0.850255 | 31.760539 | 75.478116 | 1 | fault_b | Default series | 3 | 1 | 0.01



</details>

**Comment by Leguark** [comment]
Dear @PeterBetlem thank you for your detailed issue. After taking a look to the model you provided I just found couple of unexpected behaviours:

- [ ] Last surface is interpolated even when is marked as basement
- [ ] Having the faults under the formations in the pile breaks the masking logic

For now the easiest way for you to keep working is by adding the following two lines before interpolating:
```
geo_model.reorder_features(['fault_a', 'fault_b', 'Strat_Series'])
geo_model.add_surfaces("basement")
```

This is the result I get by doing that:

![image](https://user-images.githubusercontent.com/12543466/106915390-3c0ece00-6706-11eb-84a6-796f8cb12e94.png)

If it is fine with you I will add your example code as test of the couple of bugs you found

**Comment by PeterBetlem** [comment]
Thanks @Leguark - I will do so :). And please, go ahead and use it as example code :)
