### ISSUE TITLE
Orientations as gradient values

### ISSUE THREAD

**Issue by hentsd** [cgre-aachen/gempy#573]
Hey!

Is there a possibility to import orientations as gradient values (G_x, G_y and G_z) instead of dip, azimuth and polarity? Or is there a way to convert gradient valuesto dip, azimuth and polarity?

hentsd

**Comment by AndrewAnnex** [comment]
@hentsd the equations used to convert between the two can be found around here:     https://github.com/cgre-aachen/gempy/blob/738c6084dedea50a6b16f9b673ce2bb9e2e8a311/gempy/core/data_modules/geometric_data.py#L704
and https://github.com/cgre-aachen/gempy/blob/738c6084dedea50a6b16f9b673ce2bb9e2e8a311/gempy/core/data_modules/geometric_data.py#L728
So you can just calculate them for yourself by defining a helper function or two.
