### ISSUE TITLE
Issue when adding points to surface

### ISSUE THREAD

**Issue by shakasaki** [cgre-aachen/gempy#592]
Hello,
I'm trying to add points to a surface and then compute a model, but I'm getting an error that did not use to be there a while back...maybe I had a different version of Gempy? Not sure. Well, the error is reproduced easily here:

Input:
```
import gempy as gp
import numpy.random as npr
print(gp.__version__)
geo_model = gp.create_model('test_model')
surface_name = 'test_surface'
XYZ = npr.rand(10,3)
orientations = npr.rand(10,3)

layer_names = list(['top',surface_name,'bottom'])
geo_model.add_surfaces(layer_names)

for index, row in enumerate(XYZ):
    geo_model.add_surface_points(X=row[0], Y=row[1], Z=row[2], surface=surface_name)        
    geo_model.add_orientations(X=row[0], Y=row[1], Z=row[2], surface=surface_name, pole_vector=(orientations[index,0], orientations[index,1], orientations[index,2]))
```

Output:
```
2.2.7
*** IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

I had a look in the documentation and source code but could not figure out what's wrong. I appreciate the help!

**Comment by shakasaki** [comment]
I did a "pip install gempy" again in my conda environment and now it works.. 
Still, I had not changed anything in the source code before and my current gempy version is the same
gp.__version__
Out[7]: '2.2.7'

**Comment by flohorovicic** [comment]
Hi Alexis, glad to hear that it resolved with a re-install! @Leguark is currently restructuring the backend a bit, probably related to that?

**Comment by shakasaki** [comment]
Hi Florian, could be, I had some other issues in the last week of using gempy but all seems to be resolved now with the fresh install
