### ISSUE TITLE
gempy installation error？

### ISSUE THREAD

**Issue by yjw754** [cgre-aachen/gempy#605]
Why did I still encounter this error after this step(pip install theano --force-reinstall)?
![error](https://user-images.githubusercontent.com/48661703/117447168-b94d1780-af6f-11eb-9080-e4894746713f.png)

**Comment by javoha** [comment]
Hello @yjw754,

it might be that there are some recent problems with newer python versions. Please try to follow the instructions given in this new tutorial video (https://www.youtube.com/watch?v=1oS6xTJkRwo) to create a virtual environment with python 3.8.5.

Please let us know if this works, we are working on resolving the issues with other versions.

Best regards and good luck!

**Comment by yjw754** [comment]
I just follow this video tutorial to install gempy, but it can't work.

This is my installation step:
1.conda create --name gempy python==3.8.5
2.conda install theano
3.pip install gempy
4.pip install theano --force-reinstall

**Comment by javoha** [comment]
Mmh, ok then it looks like it is an issue with your C-compiler. Do you know which one you are using at the moment? I am not an expert on this but maybe we can figure it out together.

**Comment by javoha** [comment]
Hi again and sorry for the late reply - I just checked and my versions are the same, so that should not be the problem. I still think there is something wrong in the way your c-compiler is set up, but I am really not proficient enough in this to tell what. Maybe @Leguark has an idea?

**Comment by yjw754** [comment]
oh，thanks very much!
If I have any progress, I'll tell yours.

**Comment by caasox** [comment]
Hi,
same problem here. Tried reinstalling a few times and get the same error message. My versions are also the same. Any solutions?

Best regards,

caasox

**Comment by AlexanderJuestel** [comment]
@caasox,

do you still have this issue?

Cheers Alex
