### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mcoffey77** [cgre-aachen/gempy#624]
Hello,
I had used gempy a bit before without problems, but recently I had to reinstall it and the following error keeps appearing. I tried to uninstall and install it again, to install it in different environments, I followed both gempy and gemgis installation guides, I reinstall scikit-image, but nothing seems to work. Does anyone know how to solve this? Or anyone has been through the same issue? 

![image](https://user-images.githubusercontent.com/70020582/124484430-b02fc980-ddab-11eb-8620-c5b3b25bcfd5.png)

Thanks for your time

**Comment by AlexanderJuestel** [comment]
Hello @mcoffey77,

sorry for the late reply. Could you provide us with some more information on how you installed GemPy.

Cheers Alex

**Comment by mcoffey77** [comment]
Hello

No problem. I basically followed the steps in Gemgis official site, which included the installation of Gempy (I am using a Mac). I solved it by using python version 3.8 instead of 3.9, as I read that with 3.9 I could have the error from above.

Regards
