### ISSUE TITLE
Geologic map flipped on 3D topography

### ISSUE THREAD

**Issue by s-eham** [cgre-aachen/gempy#628]
The geologic map looks like it is flipped along the y-axis when displayed on the 3D topography.
I have seen it has been an issue before. Any workarounds?

**Comment by AlexanderJuestel** [comment]
Hey,

The issue has not been resolved yet but I will post a workaround shortly!

**Comment by AlexanderJuestel** [comment]
```ruby
# Getting the shape and the data from the GemPy Solution
shape = geo_model._grid.topography.values_2d[:, :, 2].shape
geolmap = np.rot90(geo_model.solutions.geological_map[0].reshape(shape),1)

# Defining colors for two layer model
cols = ['#b35a2a', '#525252']

# Creating figure
plt.figure(figsize=(10,10))
plt.imshow(geolmap extent=geo_data.extent[:4], alpha=0.75, cmap=ListedColormap(cols))
```

**Comment by s-eham** [comment]
Thank you.
Two questions:
- how can i plot the rotated map using gp.plot_2d with topography?
- how do I get the extent from geo_model?

**Comment by AlexanderJuestel** [comment]
Hello,

- Do you mean by topography the hillshades of your digital elevation model? 
- The extent of your model is stored in `geo_model.grid.regular_grid.extent`. Thanks for pointing it out. I changed it in the comment above

**Comment by s-eham** [comment]
Yes, I would like to plot the altitude contour lines on top of the geology.

Do you know why the gp.plot_3d is not showing correctly with my topographic map? 
Looks like it has something to do with the extent.
When running the topography example the 3D-plot shows up correctly.

**Comment by AlexanderJuestel** [comment]
@s-eham 

If you have more general questions, I would like to redirect you to our Discussions: https://github.com/cgre-aachen/gempy/discussions 

With regards to your contour lines I opened an issue at our GemGIS package. This would be a nice feature that could be implemented, see https://github.com/cgre-aachen/gemgis/issues/183 

I do not know why your plot is not showing without having more information on your DEM.

**Comment by s-eham** [comment]
Thank you very much for your help. The plot issue was error in the orientation file. I got it working and it looks like I can use Gempy for my work.

Thanks again.
