### ISSUE TITLE
Output model problem

### ISSUE THREAD

**Issue by hadismasihi** [cgre-aachen/gempy#630]
**What is your question?**
Hi, I can not model my area. And the shape of the output model does not match the structure of the region. Is there a special way to extract data from Google earth? Or structures must have certain properties in order to be able to model them?
The image below is of the tunnel area I have to model.

![My area1](https://user-images.githubusercontent.com/63184005/127765167-04da7c71-a840-44dd-9110-896365bc83fa.PNG)
![Output model44](https://user-images.githubusercontent.com/63184005/127765170-cdd3c2aa-31cd-4131-944a-1478df427c31.PNG)
![model4_orientations](https://user-images.githubusercontent.com/63184005/127774124-e88bd1a0-3cdd-415b-8012-4888edc175a3.PNG)
![model4_surface_points](https://user-images.githubusercontent.com/63184005/127774126-290b92d2-3764-4b60-8899-d4bd04ca7c90.PNG)

**Comment by AlexanderJuestel** [comment]
@hadismasihi, 

@flohorovicic has experience with extracting data from Google Earth but he is currently on vacation. 

What kind of data do you want to extract? Interface Points and orientations? Also it would be helpful to see your input data in relation to the image you showed us. 

Cheers Alex

**Comment by hadismasihi** [comment]
Yes, I extract surface contact points and sets of points to determine plane orientations, coordinate information ( lat, long) and altitude.
I am a beginner . Want to know what other people get their data from the field? And information like X, Y, Z that are geographical coordinates in Gempy Tutorials?
I am providing a file of extracted information. Maybe you will notice the problems of my work. (This is just the information of the tunnel layers and it is easier)
![Sangan Tunnel](https://user-images.githubusercontent.com/63184005/127773843-a039f8aa-c06a-4a71-8269-edfea211b54f.PNG)
![gempy model](https://user-images.githubusercontent.com/63184005/127773855-b2438721-3255-40bd-abb2-7929b3c2c058.PNG)
![model1_orientations](https://user-images.githubusercontent.com/63184005/127773960-9b751a36-2920-4921-ae62-0b39a16b964b.PNG)
![model1_surface_points](https://user-images.githubusercontent.com/63184005/127773965-c3f704db-f655-4e21-aa5e-6a16d388d8a7.PNG)

**Comment by AlexanderJuestel** [comment]
Hello again, 

I am getting my data from geological maps, borehole logs, structural maps (depth maps of layers), seismic data or data from the field (mostly orientations there). 

Orientations can be created from structural maps or 3D seismic data or when collected in the field. 

We developed the GemGIS package (https://github.com/cgre-aachen/gemgis) to make the processing of data easier. 

What you could also try is to load XYZ Tiles of Google maps in QGIS and digitize the data there using point or line shape files. You could then use GemGIS to extract the altitude from a Digital Elevation Model. 

Have a look at the GemGIS Documentation: https://gemgis.readthedocs.io/en/latest/

Let me know if you need any more help

**Comment by hadismasihi** [comment]
Thanks, I'll take a look. 🌸

**Comment by hadismasihi** [comment]
Hello again
I followed the method you suggested and it was a good method. But when executing the example code "08 Sampling Interfaces and Orientations from Raster" an error is created.
I did this with examples of my site and data, but in the end both of them gave this error:

"TypeError: points_from_xy () got an unexpected keyword argument 'crs'
![EROOR](https://user-images.githubusercontent.com/63184005/128587718-04d319ec-98d0-45f8-bd51-7046354a8b61.PNG)

**Comment by hadismasihi** [comment]
> Hello again,
> 
> I am getting my data from geological maps, borehole logs, structural maps (depth maps of layers), seismic data or data from the field (mostly orientations there).
> 
> Orientations can be created from structural maps or 3D seismic data or when collected in the field.
> 
> We developed the GemGIS package (https://github.com/cgre-aachen/gemgis) to make the processing of data easier.
> 
> What you could also try is to load XYZ Tiles of Google maps in QGIS and digitize the data there using point or line shape files. You could then use GemGIS to extract the altitude from a Digital Elevation Model.
> 
> Have a look at the GemGIS Documentation: https://gemgis.readthedocs.io/en/latest/
> 
> Let me know if you need any more help
