### ISSUE TITLE
Interpretation of the geo_model.solutions.lith_block values

### ISSUE THREAD

**Issue by phaehnel** [cgre-aachen/gempy#631]
Dear GemPy team,

first, thanks for providing this great package.
Currently, I'm trying to create a geological model with five surfaces where each surface is also its own series.
Looking at the results of the model, I'm uncertain how to correctly interpret the values of "lith_block" or have a wrong understanding of the data provided there. Sorry should this be redundant but I couldn't find anything about it in the documentation, GitHub issues or the GemPy related publications.

My understanding from the documentation is that the values provided give the ID values of the different layers defined in the geo_model.surfaces. However, I'm unsure how to treat the floats provided by "lith_block" deviating from the layer ID (see figure). 
![hist_lith_block_gempy_question_github](https://user-images.githubusercontent.com/77672877/128328580-406eb530-1494-4a40-b35a-d37faf4b2c7e.png)
Is it correct that this happens when a voxel is not located entirely within a single layer but intersected by a surface?

My objective is to use the geological model to get an conceptual idea of the subsurface in my study area and use it to get an idea of the hydraulic parameters required for a groundwater flow model. So I would mainly be interested in attributing each voxel to a single layer  ID. Can I do this in some way or should the values be kept as they are?
If so is it as simple as performing something like np.round(lith_block)?

Thank you in advance for taking the time.

Greetings, 
Patrick

**Comment by javoha** [comment]
Hi @phaehnel ,

thanks for this interesting plot. I am actually not sure if the float values contain any additional information (like voxels that are cut by a surface) or if they are just artefacts of the computation - but doing what you suggested (np.round) has worked perfectly for me in the past: Just as an example, I have used the following code piece to extract grid coordinates for a single unit:

```
# Round Lithlogy block from gempy
rounded_lithblock = sol.lith_block.round(0)
rounded_lithblock = rounded_lithblock.astype(int)

# Mask by array of input surfaces (by id, can be from different series)
mask = np.isin(rounded_lithblock, [1])

# Get coordinates by mask
dom_grid = sol.grid.values[mask]
```

**Comment by phaehnel** [comment]
Hello @javoha,

thanks for your reply and the example.
Yes, rounding seemed kind of reasonable comparing the results with the data. Since I'm not too familiar with the theory on geological modelling, I just wanted to make sure I'm not missing something. 
Nice that it's this simple.

Greetings,
Patrick
