### ISSUE TITLE
adding license blocks over surface 

### ISSUE THREAD

**Issue by Espressorite** [cgre-aachen/gempy#633]
Hi all,

I am wanting to add license blocks over the surface of my model. Ideally as a black line with no fill. Has anyone done something similar, a code example or tips would be greatly appreciated! 

Cheers

**Comment by AlexanderJuestel** [comment]
Hey @Espressorite, 

this sounds much like what you can see here in the image, correct?

What you can do is using the GemGIS package also created by our department: https://github.com/cgre-aachen/gemgis

There we have functionality to extract single surfaces: https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/18_creating_depth_maps_from_gempy_models.html 

This mesh can then be visualized with PyVista. 

Afterwards, you can use the following function to create polydata from a GeoDataFrame containing the outline of your license: https://github.com/cgre-aachen/gemgis/blob/9f8e8a000f26eadb011d36e8610a37aace4f6f64/gemgis/visualization.py#L45-L58

Let me know if that helped you further or let me know if you have any questions!

Cheers Alex

![image](https://user-images.githubusercontent.com/45469915/131310474-986fe02a-8e25-4e3e-9047-44ab69276a3b.png)

**Comment by Espressorite** [comment]
Hi Alex!

Fantastic, thanks for this reply and advice. I will give it a go!

Regards,
Joe

**Comment by AlexanderJuestel** [comment]
Any luck with the suggested solution so far?
