### ISSUE TITLE
No Qt bindings could be found

### ISSUE THREAD

**Issue by aigulakberova** [cgre-aachen/gempy#634]
**Describe the bug**
Hello,
Afer installing pip install gempy on Mac and trying to run it, mistake appeared. 
Previous installation in July 2021 was successful. Printscrins of mistakes are attached
![Screen Shot 2021-09-01 at 18 34 09](https://user-images.githubusercontent.com/84881672/131710088-6bf231a8-b99b-4f83-b045-6727039eaadf.png)
![Screen Shot 2021-09-01 at 18 34 36](https://user-images.githubusercontent.com/84881672/131710093-31b88074-72a6-4111-89ba-eb93f87bcf7b.png)

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.
2.
3.
...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
  * OS: (e.g. iOS)
  * GemPy Version
    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable)

**Additional context**

**Comment by AlexanderJuestel** [comment]
Hello,

Could you maybe try installing pyqt5? This may solve your installation issue :)

**Comment by AlexanderJuestel** [comment]
Any luck with the suggested solution so far?

**Comment by AlexanderJuestel** [comment]
Will be fixed with #640
