### ISSUE TITLE
Adding Planned Drill Holes (no Z data) 

### ISSUE THREAD

**Issue by Espressorite** [cgre-aachen/gempy#635]
Hi all, 

I am wanting to add planned drill holes to my model. I have the surface coordinates, the drill holes will be vertical and then a slight angle. Displaying these with a line from the surface point to the planned depth is my goal.  

Any advice on how to achieve this? 

Thanks

Joe

**Comment by AlexanderJuestel** [comment]
Hey @Espressorite, 

this is also something GemGIS can do! 

Have a look at this Tutorial here: https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/35_plotting_borehole_data_with_pyvista.html

You would have to export your surfaces and then you can create a new PyVista plotter to plot your surface and the borehole. 

For the borehole you would need the XYZ coordinates of the bends as DataFrame (see Tutorial). GemGIS will then create a PolyData set, a tube, which you can then plot :) 

Hope that helps! Let me know if you need any more assistance!
