### ISSUE TITLE
About the application effect of gp.plot_3d()

### ISSUE THREAD

**Issue by ghost** [cgre-aachen/gempy#636]
I follow the  Getting Started tutorial to run the code.
When I run the following code, I find that the effect is different from the tutorial：

`gp.plot_3d(geo_model,show_surfaces=True)`

Here is my effect:
![image](https://user-images.githubusercontent.com/30280059/132480610-6d6650cc-7d90-4f50-8445-aacbc4b41236.png)
Here is the effect of the official tutoria：
![image](https://user-images.githubusercontent.com/30280059/132480700-4a63b881-48bb-4f41-a95e-b88826691ad4.png)

At the same time, when the line of code is run, it appears “PyvistaDeprecationWarning: ”
![image](https://user-images.githubusercontent.com/30280059/132481050-5a0a277f-d490-4e64-9cd4-26685a4072f0.png)

I did not find any related solutions from the Internet search. I hope to get your help. 
Thank you guys!

**Comment by javoha** [comment]
Hello @Panjichuan,

Thanks for pointing that out, can you try:
```gp.plot_3d(geo_model, show_surfaces=True, show_lith=False)```

Does that solve the problem?

**Comment by PanJichuan** [comment]
First, thanks u all for help. I encountered this issue when running the code in virtual linux, After re-buiding the gempy environment on windows, the issue dissapeared. I speculate that the performance of the virtualized graphics card is insufficient.
