### ISSUE TITLE
Ability to use engineering geological surface data for modeling with gempy

### ISSUE THREAD

**Issue by hadismasihi** [cgre-aachen/gempy#639]
In part of my dissertation work I want to do modeling using surface data and GEMPY. Can surface survey data such as RMR or engineering geological features be used in modeling with GEMPY?
I was able to get a model by taking a series of points from Google Earth and the slope and azimuth of the layers, but I do not know how true this is.
![111111](https://user-images.githubusercontent.com/63184005/132939111-186b3ded-cea3-44b5-8387-fb80f674fca0.JPG)

**Comment by AlexanderJuestel** [comment]
Hey @hadismasihi could you specify the data a little more that you would like to integrate? In general, GemPy needs orientation data and interface points. If you have additional data, you could try to infer orientation values or even interface points from that. 

Let me know if we can assist you any further
