### ISSUE TITLE
Error while exporting to vtk: "ValueError: Number of scalars (8000) must match either the number of points (9261) or the number of cells (8000)."

### ISSUE THREAD

**Issue by mkondratyev85** [cgre-aachen/gempy#641]
**Bug description**
I try to modify the example from [the tutorial 1.1](https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_1_basics.html#sphx-glr-tutorials-ch1-fundamentals-ch1-1-basics-py) to export the result to vtk at the end of the script. But, I receive the following error:

    ValueError: Number of scalars (8000) must match either the number of points (9261) or the number of cells (8000).

**To Reproduce**
Here is the modified version of the script from [the tutorial 1.1](https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_1_basics.html#sphx-glr-tutorials-ch1-fundamentals-ch1-1-basics-py):

``` python
import gempy as gp

# Importing auxiliary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os


# Setting options
np.random.seed(1515)
pd.set_option('precision', 2)

geo_model = gp.create_model('Tutorial_ch1_1_Basics')
data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
# Importing the data from CSV-files and setting extent and resolution
gp.init_data(geo_model, [0, 2000., 0, 2000., 0, 750.], [20, 20, 20],
             path_o=data_path + "/data/input_data/getting_started/"
                                "simple_fault_model_orientations.csv",
             path_i=data_path + "/data/input_data/getting_started/"
                                "simple_fault_model_points.csv",
             default_values=True)


gp.map_stack_to_surfaces(geo_model,
                         {"Fault_Series": 'Main_Fault',
                          "Strat_Series": ('Sandstone_2', 'Siltstone',
                                           'Shale', 'Sandstone_1', 'basement')},
                         remove_unused_series=True)

gp.set_interpolator(geo_model, compile_theano=True, theano_optimizer='fast_compile')

gp.compute_model(geo_model)


gp._plot.export_to_vtk(geo_model, 'ep.vtk')
```

The result of the script execution is this error message:

    ValueError: Number of scalars (8000) must match either the number of points (9261) or the number of cells (8000).

And the comic aspect of this message is that the number of scalars (8000) does indeed match the number of cells (8000) and yet I receive this error.

EDIT: Add full stack of the error message:

```
Traceback (most recent call last):
  File "m2.py", line 38, in <module>
    gp._plot.export_to_vtk(geo_model, 'ep.vtk')
  File "/home/user/.local/lib/python3.7/site-packages/gempy/plot/_plot.py", line 99, in export_to_vtk
    path=path)
  File "/home/user/.local/lib/python3.7/site-packages/gempy/plot/visualization_3d.py", line 1182, in export_vtk_lith_block
    out['Lithology'] = lith
  File "/home/user/.local/lib/python3.7/site-packages/pyvista/core/dataset.py", line 658, in __setitem__
    raise_not_matching(scalars, self)
  File "/home/user/.local/lib/python3.7/site-packages/pyvista/utilities/helpers.py", line 725, in raise_not_matching
    raise ValueError(f'Number of scalars ({scalars.size}) '
ValueError: Number of scalars (8000) must match either the number of points (9261) or the number of cells (8000).
```

**Desktop:**
  * OS: Ubuntu 19.10
  * GemPy Version 2.2.9
  * Python Version 3.7

**Comment by javoha** [comment]
Hi @mkondratyev85 ,

thanks for catching this. There seems to be an issue with the voxel export. We need to take a closer look. If you are just interested in exporting the surfaces, try:

```gp._plot.export_to_vtk(geo_model, 'ep.vtk', voxels=False)```

This worked for me with your example. Just a small note - in my case the fault series you defined was not recognized automatically as a fault. You might want to add the following line before setting the interpolator and computing the model:

```geo_model.set_is_fault('Fault_Series')```

Hopefully this helps!
