### ISSUE TITLE
gp.set_interpolator not working!!!! What should i do

### ISSUE THREAD

**Issue by RajdeepTarafder** [cgre-aachen/gempy#642]
Showing the following error
{Setting kriging parameters to their default values.
Compiling theano function...
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '9048' (I am process '5296')
C:\Users\Rajdeep\.conda\envs\Mineral1\lib\site-packages\theano\scan_module\scan_perform_ext.py:75: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  warnings.warn(

You can find the C code in this temporary file: C:\Users\Rajdeep\AppData\Local\Temp\theano_compilation_error_541d58lr
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5296/3541010238.py in <module>
----> 1 gp.set_interpolator(
      2     geo_model,
      3     output=['geology'], # In built outputs. More about this later on
      4     theano_optimizer='fast_compile') # alternatives: 'fast_run' or
      5                                      # check http://deeplearning.net/software/theano/tutorial/modes.html

~\.conda\envs\Mineral1\lib\site-packages\gempy\api_modules\setters.py in set_interpolator(geo_model, output, compile_theano, theano_optimizer, verbose, grid, type_, update_structure, update_kriging, **kwargs)
    106         geo_model._interpolator.set_all_shared_parameters(reset_ctrl=True)
    107 
--> 108         geo_model._interpolator.compile_th_fn_geo(inplace=True, grid=grid)
    109     else:
    110         if grid == 'shared':

~\.conda\envs\Mineral1\lib\site-packages\gempy\core\interpolator.py in compile_th_fn_geo(self, inplace, debug, grid)
   1122 
   1123         th_fn = theano.function(input_data_T,
-> 1124                                 self.theano_graph.theano_output(),
   1125                                 updates=[
   1126                                     (self.theano_graph.block_matrix, self.theano_graph.new_block),

~\.conda\envs\Mineral1\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py in theano_output(self)
    629         # self.compute_type = ['lithology', 'topology']
    630         if 'geology' in self.compute_type:
--> 631             solutions[:9] = self.compute_series()
    632             # solutions[:12] = self.compute_series_oct()
    633         if 'topology' in self.compute_type:

~\.conda\envs\Mineral1\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py in compute_series(self, grid, shift)
    463 
    464         # Looping
--> 465         series, self.updates1 = theano.scan(
    466             fn=self.compute_a_series,
    467             outputs_info=[

~\.conda\envs\Mineral1\lib\site-packages\theano\scan_module\scan.py in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict, return_list)
    841     # user if inputs of the inner function are missing.
    842     try:
--> 843         dummy_f = function(dummy_args,
    844                            dummy_outs,
    845                            updates=updates,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    304         # note: pfunc will also call orig_function -- orig_function is
    305         #      a choke point that all compilation must pass through
--> 306         fn = pfunc(params=inputs,
    307                    outputs=outputs,
    308                    mode=mode,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    481         inputs.append(si)
    482 
--> 483     return orig_function(inputs, cloned_outputs, mode,
    484                          accept_inplace=accept_inplace, name=name,
    485                          profile=profile, on_unused_input=on_unused_input,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1839                   name=name)
   1840         with theano.change_flags(compute_test_value="off"):
-> 1841             fn = m.create(defaults)
   1842     finally:
   1843         t2 = time.time()

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function_module.py in create(self, input_storage, trustme, storage_map)
   1712         try:
   1713             theano.config.traceback.limit = theano.config.traceback.compile_limit
-> 1714             _fn, _i, _o = self.linker.make_thunk(
   1715                 input_storage=input_storage_lists, storage_map=storage_map)
   1716         finally:

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\link.py in make_thunk(self, input_storage, output_storage, storage_map)
    695 
    696     def make_thunk(self, input_storage=None, output_storage=None, storage_map=None):
--> 697         return self.make_all(input_storage=input_storage,
    698                              output_storage=output_storage,
    699                              storage_map=storage_map)[:3]

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\link.py in make_all(self, input_storage, output_storage, storage_map)
    824             # Note : ops that implement their own make thunk don't usually
    825             # have this attribute defiend !!
--> 826             thunks += [node.op.make_thunk(node,
    827                                           storage_map,
    828                                           compute_map,

~\.conda\envs\Mineral1\lib\site-packages\theano\scan_module\scan_op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    859         # we do not want to recompile the inner fct every time.
    860         if not getattr(self, 'fn', None):
--> 861             self.fn = function(wrapped_inputs,
    862                                wrapped_outputs,
    863                                mode=compilation_mode,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    304         # note: pfunc will also call orig_function -- orig_function is
    305         #      a choke point that all compilation must pass through
--> 306         fn = pfunc(params=inputs,
    307                    outputs=outputs,
    308                    mode=mode,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    481         inputs.append(si)
    482 
--> 483     return orig_function(inputs, cloned_outputs, mode,
    484                          accept_inplace=accept_inplace, name=name,
    485                          profile=profile, on_unused_input=on_unused_input,

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1839                   name=name)
   1840         with theano.change_flags(compute_test_value="off"):
-> 1841             fn = m.create(defaults)
   1842     finally:
   1843         t2 = time.time()

~\.conda\envs\Mineral1\lib\site-packages\theano\compile\function_module.py in create(self, input_storage, trustme, storage_map)
   1712         try:
   1713             theano.config.traceback.limit = theano.config.traceback.compile_limit
-> 1714             _fn, _i, _o = self.linker.make_thunk(
   1715                 input_storage=input_storage_lists, storage_map=storage_map)
   1716         finally:

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\link.py in make_thunk(self, input_storage, output_storage, storage_map)
    695 
    696     def make_thunk(self, input_storage=None, output_storage=None, storage_map=None):
--> 697         return self.make_all(input_storage=input_storage,
    698                              output_storage=output_storage,
    699                              storage_map=storage_map)[:3]

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
   1085                 # no need to cause duplicate c code by passing
   1086                 # no_recycling here.
-> 1087                 thunks.append(node.op.make_thunk(node,
   1088                                                  storage_map,
   1089                                                  compute_map,

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    952                               compute_map=compute_map, impl='c')
    953             try:
--> 954                 return self.make_c_thunk(node, storage_map, compute_map,
    955                                          no_recycling)
    956             except (NotImplementedError, utils.MethodNotDefined):

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    855                 raise NotImplementedError("float16")
    856         _logger.debug('Trying CLinker.make_thunk')
--> 857         outputs = cl.make_thunk(input_storage=node_input_storage,
    858                                 output_storage=node_output_storage)
    859         thunk, node_input_filters, node_output_filters = outputs

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1213         """
   1214         init_tasks, tasks = self.get_init_tasks()
-> 1215         cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1216             input_storage, output_storage, storage_map,
   1217             keep_lock=keep_lock)

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1151         input_storage = tuple(input_storage)
   1152         output_storage = tuple(output_storage)
-> 1153         thunk, module = self.cthunk_factory(error_storage,
   1154                                             input_storage,
   1155                                             output_storage,

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1621             for node in self.node_order:
   1622                 node.op.prepare_node(node, storage_map, None, 'c')
-> 1623             module = get_module_cache().module_from_key(
   1624                 key=key, lnk=self, keep_lock=keep_lock)
   1625 

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1187             try:
   1188                 location = dlimport_workdir(self.dirname)
-> 1189                 module = lnk.compile_cmodule(location)
   1190                 name = module.__file__
   1191                 assert name.startswith(location)

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cc.py in compile_cmodule(self, location)
   1518         try:
   1519             _logger.debug("LOCATION %s", str(location))
-> 1520             module = c_compiler.compile_str(
   1521                 module_name=mod.code_hash,
   1522                 src_code=src_code,

~\.conda\envs\Mineral1\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2396             # prints the exception, having '\n' in the text makes it more
   2397             # difficult to read.
-> 2398             raise Exception('Compilation failed (return status=%s): %s' %
   2399                             (status, compile_stderr.replace('\n', '. ')))
   2400         elif config.cmodule.compilation_warning and compile_stderr:

Exception: ('The following error happened while compiling the node', for{cpu,Looping}(Elemwise{minimum,no_inplace}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, Number of points per surface used to split rest-ref, fault relation matrix, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, Nugget effect of gradients, Nugget effect of scalar, Attenuation factor, Sigmoid Outside, Sigmoid slope, <TensorType(int32, vector)>, <TensorType(bool, vector)>, <TensorType(int32, vector)>, Coordinates of the grid points to interpolate, All the surface_points points at once, Position of the dips, Angle of every dip, Azimuth, Polarity, Values that the blocks are taking), '\n', 'The following error happened while compiling the node', Elemwise{deg2rad,no_inplace}(Subtensor{int32:int32:}.0), '\n', 'Compilation failed (return status=1): C:\\Users\\Rajdeep\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-3.8.5-64\\tmpkl9mfnl6\\mod.cpp:360:25: internal compiler error: Segmentation fault\r.                          V1_i = V3_i * (M_PI / 180.0);;\r.                          ^\r. libbacktrace could not find executable to open\r. Please submit a full bug report,\r. with preprocessed source if appropriate.\r. See <https://sourceforge.net/projects/msys2> for instructions.\r. ', '[Elemwise{deg2rad,no_inplace}(<TensorType(float64, vector)>)]'

**Comment by javoha** [comment]
Hello @RajdeepTarafder ,

this seems to be a problem regarding theano and your c compiler. Have you tried reinstalling gempy and theano in a fresh environment? Also I would suggest you check the setup of you c compiler, but as this is not directly a gempy related problem and as I am not an expert in this, I cannot make any guess where exactly the issue arises.

Good luck and best regards!

**Comment by RajdeepTarafder** [comment]
I have tried everything in all possible ways but it is showing this error 
C:/Users/Rajdeep/.conda/envs/Mineral1/Library/mingw-w64/include/c++/5.3.0/complex:795:5: internal compiler error: Segmentation fault

     { return std::log(__z) / log(_Tp(10.0)); }

     ^

libbacktrace could not find executable to open

**Comment by Japhiolite** [comment]
Hi @RajdeepTarafder 

is there still a problem? This issue is rather old. Could you manage in the meantime?
If the problem persists, did you install Theano properly according to their [installation instructions](https://theano-pymc.readthedocs.io/en/latest/install_windows.html) (assuming you run Windows)?

Especially `conda install numpy scipy mkl-service libpython <m2w64-toolchain> pytest` is important if you use conda, which you should probably.

**Comment by Japhiolite** [comment]
Hi @RajdeepTarafder 

I'm closing this issue, as there was no further activity. If your problem was not solved, feel free to re-open this issue.

Best
Jan

**Comment by RajdeepTarafder** [comment]
Yeh...
