### ISSUE TITLE
 pyqt5 missing from installation requirements

### ISSUE THREAD

**Issue by jeff788** [cgre-aachen/gempy#644]
**Describe the bug**
I have tried to install using pip via PyPi and manually using the current GitHub release on Ubuntu 20.04 with Python 3.8.5 (os supplied version) and 3.7 (installed from source). Both installations work great and have been used extensively for other projects.

With Python3.8.5, in a virgin venv, the install appears to go smoothly. However, when I try to import gempy I get the following error message (redacted some file paths):

> Python 3.8.5 (default, May 27 2021, 13:30:53) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import gempy
> No module named 'osgeo'
> Traceback (most recent call last):
>   File "xxx_venv/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
>     from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
> ModuleNotFoundError: No module named 'PySide'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "xxx_venv/lib/python3.8/site-packages/gempy/__init__.py", line 24, in <module>
>     from gempy.gempy_api import *
>   File "xxx_venv/lib/python3.8/site-packages/gempy/gempy_api.py", line 17, in <module>
>     from gempy.core.model import Project
>   File "xxx_venv/lib/python3.8/site-packages/gempy/core/model.py", line 20, in <module>
>     from gempy.plot.decorators import *
>   File "xxx_venv/lib/python3.8/site-packages/gempy/plot/decorators.py", line 2, in <module>
>     from gempy.plot.vista import GemPyToVista
>   File "xxx_venv/lib/python3.8/site-packages/gempy/plot/vista.py", line 39, in <module>
>     import pyvistaqt as pvqt
>   File "xxx_venv/lib/python3.8/site-packages/pyvistaqt/__init__.py", line 3, in <module>
>     from pyvistaqt.plotting import BackgroundPlotter, MainWindow, MultiPlotter, QtInteractor
>   File "xxx_venv/lib/python3.8/site-packages/pyvistaqt/plotting.py", line 56, in <module>
>     from qtpy import QtCore
>   File "xxx_venv/lib/python3.8/site-packages/qtpy/__init__.py", line 216, in <module>
>     raise PythonQtError('No Qt bindings could be found')
> qtpy.PythonQtError: No Qt bindings could be found
> >>> 

With Python 3.7, same setup (virgin venv) I get:

> Python 3.7.10 (default, Apr  5 2021, 15:04:00) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import gempy as gp
> xxxxx_venv/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
>   warnings.warn(msg)
> No module named 'osgeo'
> 
> You can find the C code in this temporary file: /tmp/user/210369/theano_compilation_error__svqh4ln
> Traceback (most recent call last):
>   File "xxxx_venv/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
>     actual_version, force_compile, _need_reload))
> ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "xxxx_venv/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
>     actual_version, force_compile, _need_reload))
> ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True
> 
> 

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1. Ubuntu 20.04 with native python3 installation
2. create venv with python3 -m venv <venv>
3. activate venv
4. pip install gempy
5.  launch python and try to import gempy
...

**Comment by AlexanderJuestel** [comment]
Hello,

Please try installing pyqt5 using 'pip install pyqt5' and see if that works :)

**Comment by jeff788** [comment]
No, that didn't change anything

**Comment by agzimmerman** [comment]
@Leguark said he's quite close to making a release that includes this fix.
