### ISSUE TITLE
GemPy not properly installable in fresh conda environment via pip

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#652]
The latest release (2.2.10) could not be installed using pip. It seems like there are several dependency conflicts. I will check it out and open a PR to fix it! 

Cheers Alex

**Comment by Japhiolite** [comment]
Hi Alex, 
how is the status on this?

**Comment by AlexanderJuestel** [comment]
@Japhiolite I have not followed up on that further, sorry

**Comment by Japhiolite** [comment]
Allright, I will give it a go with certain fixed dependencies (as #660 has similar topic).

**Comment by Japhiolite** [comment]
I created fresh environments with gempy on different OS and did not run into problems curiously.
I've exported the environments to .yml files with frozen dependency versions.

**Comment by Japhiolite** [comment]
I close this issue for now. We have a minor new release ahead, so this issue will likely be obsolete (and hopefully not repeat itself).
