### ISSUE TITLE
 question about displaying faults in two-dimensional sections

### ISSUE THREAD

**Issue by hadismasihi** [cgre-aachen/gempy#656]
Hi, I have prepared sections from a real model in which the shape of the faults is as follows. One of my professors thinks that this shape of the faults is incorrect and has an inappropriate output, and another professor thinks that this is a spatial representation of the faults and is absolutely correct. I want to know your opinion so that I can make the right decision.
![S33](https://user-images.githubusercontent.com/63184005/147603904-e3490941-f42a-47e7-8e7c-527e0b8c6ebd.JPG)
![147603928-cef091e6-fc78-4d3c-9c6a-3045341ad5b7](https://user-images.githubusercontent.com/63184005/147874431-145b6919-c516-4baa-9d7b-e16c315ee867.jpg)

**Comment by hadismasihi** [comment]
No one?

**Comment by AlexanderJuestel** [comment]
Hello,

As you know it was the end of the year and the beginning of the new year so many of us are on vacation. We will get back to you soon!

Cheers Alex

**Comment by AlexanderJuestel** [comment]
What exactly do you describe? Where is your fault? What do we see?

**Comment by hadismasihi** [comment]
Hello dear Alex, happy new year
I modeled the subsurface layers of an area and, as I specified in the 3D model, obtained a section of this model in which the effect of faults in the two-dimensional section is seen as curves. I paid attention to the examples on the site and the faults of your examples are more direct and without curvature, and in fact one dimension of them can be seen.
And now I do not know whether this form of display of faults in my model is right or wrong?

**Comment by AlexanderJuestel** [comment]
From the 3d model you posted it seems that the faults look reasonable. The curvature in the section is probably caused by the let's term it angular intersection of the fault planes with the section. So as long as the faults look alright in 3d I think you are fine. Maybe try arbitrary section more perpendicular to your faults as well

**Comment by Japhiolite** [comment]
Hi @hadismasihi is there any news here? Could you check out the faults in different cross-sections?
As Alex pointed out, fault traces _can_ look rather peculiar on oblique cross sections.

**Comment by Japhiolite** [comment]
Hi @hadismasihi 

I'm closing this issue, as there's been no response. If your problems with the fault traces are not solved, feel free to re-open this issue, or start a discussion on the Discussions tab.

kind regards,
Jan
