### ISSUE TITLE
What exactly does the input data mean and how can it be obtained.

### ISSUE THREAD

**Issue by ChenLei906** [cgre-aachen/gempy#659]
**What is your question?**
Q1:Hi,aswe all known,if we went to builde a model and use plot_3d to show it ,two types of data are required.eg:"simple_fault_model_points2.csv"can be obtained from borehole data,But how do I get orientations?like the date"azimuth,dip ,polarity"?
Q2:Can I create a new 3D model by drawing a random area, like drawing  a section to split the original cube，so I can cut any block out of the original cube and Analyze this new one.If GemPy can do that ,what 's the steps?
Q3:I already have DEM data for the study area,how do I fit it into a geological model of the study area?Is there a coordinate conversion problem?

**Comment by Japhiolite** [comment]
Hi @ChenLei906 

thanks for asking the questions

Q1: Connected to #658 Orientations are hard to come by, can be estimated by geological experience or from at least 3 points in space (which are not to far away from each other). A first rough estimation from a 2D geological profile might already give you a feel, if it comes close to the real orienation of your geological surface.

Q2: For this, you would need to create a new model, i.e. a new grid. I have to have a look, if such a new grid can also be 3D and a subset of the original grid. I'll keep you updated.

Q3: You need to orient the DEM to your model extent and orientation. GemPy Models work easiest if their orientation is X - EastWest, Y - NorthSouth (or vice-versa). When defining a model, you can set the model dimensions in real coordinates, like in the example below. The model needs to have the same coordinate system as the DEM! If dimensions and orientation fit, you should be able to add the tif as a topography grid.
![Screenshot 2022-01-18 at 15 52 35](https://user-images.githubusercontent.com/13364692/149960602-331807c3-4dd8-4490-96a2-051ed9fc4c27.png)

**Comment by Japhiolite** [comment]
Hi @ChenLei906 

I'm closing this issue for now as there was no response. Feel free to re-open it.

Cheers
Jan
