### ISSUE TITLE
Color rendering problem in gp.plot_2d

### ISSUE THREAD

**Issue by Linya-Peng** [cgre-aachen/gempy#679]
**What is your question?**
Hi everyone!
I'm totally new in 3DGM and trying to use Gempy to build a 3D geological model from borehole data.
I construct the intersurface points from the original data and try to plot them in 2d, but I found that the color of the points can't be rendered correctly, how can I deal with this problem?
![image](https://user-images.githubusercontent.com/61902717/156963363-cb1bf901-54a3-458e-8750-a2820f6c6e9d.png)

Thank you in advance~

**Comment by Japhiolite** [comment]
Hi @Linya-Peng 

we are aware of this bug in the current release of GemPy. Unfortunately, it is not easy to find. We're assuming that matplotlib is causing this behaviour, as orientation data are plotted in color using the plot API.
As a workaround, you can use a private function `gempy._plot.plot_data(geo_model)`

**Comment by Linya-Peng** [comment]
> Hi @Linya-Peng
> 
> we are aware of this bug in the current release of GemPy. Unfortunately, it is not easy to find. We're assuming that matplotlib is causing this behaviour, as orientation data are plotted in color using the plot API. As a workaround, you can use a private function `gempy._plot.plot_data(geo_model)`

Thank you for your reply~ Using a private function do plot the right result

**Comment by Japhiolite** [comment]
should be resolved with #499
