### ISSUE TITLE
Welly : AttributeError: 'NoneType' object has no attribute 'position'

### ISSUE THREAD

**Issue by neha845** [cgre-aachen/gempy#681]
**The class WellyToSubsurfaceHelper contains the methods to create a welly project and export it to a subsurface data class.**
Error in the following line of code.
wts = sb.reader.wells.WellyToSubsurfaceHelper(collar_df=collar, survey_df=survey, lith_df=lith)

**Screenshots**
<img width="824" alt="image" src="https://user-images.githubusercontent.com/56668663/157988337-3b1d0133-7b45-45fa-896d-199fe02729e9.png">

**Desktop (please complete the following information):**
  * OS: Windows
  * GemPy Version - 2.2.10

**Trying on the same dataset as provided in the t21 tutorial - kim_ready.csv**
https://github.com/cgre-aachen/gempy_workshops/blob/33e4f8651250494c1e76f4c7149aa8a021ce5ddb/workshops/Transform2021/t21_gempy.ipynb

**Comment by Japhiolite** [comment]
Hi @neha845 

I will transfer this issue over to the subsurface repository, as this Error has to do with subsurface (and welly) more than with gempy.
It is [Issue 57](https://github.com/softwareunderground/subsurface/issues/57) over there. I guess, that this change was implemented with welly 0.5, which included major rework of the welly software.

Best,
Jan
