### ISSUE TITLE
Remove Pandas Future Warning

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#682]
Current test results in a Pandas Future warning:

```
tests/test_utils.py::test_show_number_of_data_points[dem0-gdf_orientations10-gdf_interfaces1_lines0]
  /usr/share/miniconda/envs/gemgis_testing/lib/python3.9/site-packages/gempy/core/model.py:792: FutureWarning: The `inplace` parameter in pandas.Categorical.add_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
```

https://github.com/cgre-aachen/gempy/blob/c64023b8b3b1da10797b566d2bacd8f74079c88b/gempy/core/model.py#L790-L795

I will remove the inplace parameter in a PR soon.

**Comment by Japhiolite** [comment]
Do you know, if this also affects the categorical methods `cat.remove_categories` or `cat.rename_categories` ? Those currently also use the `inplace` argument in GemPy.

**Comment by AlexanderJuestel** [comment]
Yes and yes

https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.remove_categories.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html

**Comment by Japhiolite** [comment]
Allright, maybe we should include that in the PR aswell. There are a few categorical calls in `model.py`
