### ISSUE TITLE
Inadequate geological map from gp.plot_2d(geo_model, section_names = ["topography"])

### ISSUE THREAD

**Issue by mkondratyev85** [cgre-aachen/gempy#688]
If you add topography to geo_model in gempy then you can generate nicely looking geological map by using gempy function
`plot_2d`.

This process is described in details in the gempy manual:
https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_3b_cross_sections.html#sphx-glr-tutorials-ch1-fundamentals-ch1-3b-cross-sections-py

However, there is s a subtle error in the process of constructing of the resulting map. This error is so subtle it's even made its way into the manual mentioned above.

![sphx_glr_ch1_3b_cross_sections_004 png](https://user-images.githubusercontent.com/32978900/161871811-28cf03f1-e878-45b0-9a79-098feb39325e.png)

Section 1 looks nice.

But If you look closer on section 2 on the resulting map from the manual you'll see that geology that is presented on the section differs from the geology under the trace of section 2 on the map. The same issue with section 3.

The problem here lies not in the section but in how this geological map is compiled. It's relief is drawn correctly. It's data points are placed on the correct positions. But the lithology and contacts are flipped along diagonal axis. That's why section1 looks correct.

**Comment by Japhiolite** [comment]
Thanks for noticing and implementing a change @mkondratyev85 👍 
I'll have a look at the PR

**Comment by Japhiolite** [comment]
PR is merged. Thanks again @mkondratyev85
