### ISSUE TITLE
pymc dependancy

### ISSUE THREAD

**Issue by WesleyTheGeolien** [cgre-aachen/gempy#69]
Hey, 

Thanks for all the work. I have been trying to get gempy running however I notice in gempy/posterior_analysis.py pymc is imported. I believe gempy is python3 based and pymc python2? You also write that pymc or pymc3 is optional is there a reason to use pymc over pymc3?

**Comment by Leguark** [comment]
Hi wesley. 
Good to see that there are brave people out there who tries to use gempy.
- Yes, gempy only works in python 3 and pymc2 for the installation they try to use python 2 version but pymc2 works as well in python 3. You just need to play a bit with the installation.

- PyMC3 requires all the Bayesian network to be written in theano. Most part of gempy is written in theano but not all (we are adding more and more functionality in theano everyday. Here you can see what is implemented in theano so far: https://cgre-aachen.github.io/gempy/build/html/_theory/core.html). So depending what you need to do you can use one or the other. Tutorial is an ugly attempt to use pymc3. In the middle term the hope is to move completely to pymc3 but in general pymc2 is easier to use and debug

**Comment by WesleyTheGeolien** [comment]
@Leguark Thanks for the quick reply, 

As you state installation of pymc is a bit tricky, especially on Windows, from memory I had to install from pymc from source as pip and anacodna wasn't playing ball. But all working now and ready to play!
