### ISSUE TITLE
Order when providing orientations

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#690]
The code states that the `orientation` argument in the `geo_model.add_orientations()` functions takes the orientation as an array in the form of ['azimuth', 'dip', 'polarity']. However, the API Reference at https://docs.gempy.org/Model/gempy.core.model.ImplicitCoKriging.html#gempy.core.model.ImplicitCoKriging.add_orientations states it as ['dip', 'azimuth', 'polarity']

https://github.com/cgre-aachen/gempy/blob/10596d8e5c4ab449fc5c36980a4666c34a2afb28/gempy/core/data_modules/geometric_data.py#L620-L622

![image](https://user-images.githubusercontent.com/45469915/163677982-5701d5c5-fa7c-45e4-9dff-3831058a358a.png)

This should be adapted either way.

**Comment by Japhiolite** [comment]
I remember changing that in the doc string in the past. Azimuth dip polarity is the correct one
