### ISSUE TITLE
`gp.save_model()` doesn't save sections that were set with `geo_model.set_section_gird()`

### ISSUE THREAD

**Issue by mkondratyev85** [cgre-aachen/gempy#691]
If you set sections to `geo_model` with `geo_model.set_section_grid()` and then save the model with `gp.save_model()`
it ignores those sections and saves only topography as clearly seen in the code from that function:

https://github.com/cgre-aachen/gempy/blob/10596d8e5c4ab449fc5c36980a4666c34a2afb28/gempy/core/model.py#L1662-L1702

I use sections a lot and want to save time by saving the whole model with sections so I won't have to recompile my model each time I need to work with it. I think function `save_model()` has to save sections too (and load them via function `load_model()`).

**Comment by Japhiolite** [comment]
Hi @mkondratyev85 

Thanks for posting. I agree. I'll add this to gempy's roadmap for the next minor release.

Cheers

**Comment by mkondratyev85** [comment]
Hi @Japhiolite 

Thank you for implementing this enhancement!
