### ISSUE TITLE
Typo in the repo's about

### ISSUE THREAD

**Issue by xandrade** [cgre-aachen/gempy#693]
Hey team, just noted that there is a type in the repo's about section. I think it should be address instead of adress, right?

_GemPy is an open-source, Python-based 3-D structural geological modeling software, which allows the implicit (i.e. automatic) creation of complex geological models from interface and orientation data. It also offers support for stochastic modeling to **adress** parameter and model uncertainties._

**Comment by Japhiolite** [comment]
Thanks for noticing @xandrade, I corrected the typo. 👍
