### ISSUE TITLE
¿Environment.yml for windows?

### ISSUE THREAD

**Issue by Nauj29** [cgre-aachen/gempy#695]
I have tried install gempy for many months in windows but I have failed. I mean, when this is installed doesn´t work well.
I tried: 
Windows installation guide (March 2020) from webpage.
the solution in https://github.com/conda-forge/gempy-feedstock
Docker
So, I was wondering if someone  could send me an environment.yml of windows to try to copy it, please.

In advance thanks for the help

**Comment by Japhiolite** [comment]
Hi @Nauj29 

try to use this environment. 
I compiled it for a course using gempy I taught in February, and it worked for most of the people out of the box: https://github.com/Japhiolite/environments/blob/master/environment_geo_windows.yml

Best
Jan

**Comment by Nauj29** [comment]
¡muy agradecido! el entorno funciona muy bien.
