### ISSUE TITLE
windows or linux

### ISSUE THREAD

**Issue by Nauj29** [cgre-aachen/gempy#696]
Hi every one

is it better to use gempy on linux or windows?

thanks

**Comment by Japhiolite** [comment]
Hi @Nauj29 

both work. The installation of theano on windows is rumored to be difficult and error-prone, but I myself never ran in big issues.
However, theano may be the culprit why you could not install gempy properly, as described in issue #695 

I have environments for all major OS if you need them. My collection of different .yml files can be found [here](https://github.com/Japhiolite/environments).

Best
Jan

**Comment by Nauj29** [comment]
Hi @Japhiolite, Thanks for your time. your connection was very useful for me.
