### ISSUE TITLE
Elevation data

### ISSUE THREAD

**Issue by NourSoltani** [cgre-aachen/gempy#699]
Hello,
I hope you are doing very well!
I was wondering since a while about a specific subject and I was asking if I could solve it using GemPy.
I have Elevation data(Lidar) with .tif extension. Is it possible to take these point clouds and by using GemPy, we can represent the 3D model?

**Comment by SimonVirgo** [comment]
Hello Nour, 
From what I understood you are trying to do, GemPy is probably not the right tool. there are easier ways to achieve this. Have a look here,for example: https://gis.stackexchange.com/questions/121561/seeking-tool-to-generate-mesh-from-dtm

**Comment by NourSoltani** [comment]
Thank you for responding @SimonVirgo  I really appreciate it!
The link you have associated is really interesting.
To explain more, what I am willing to do is to create a surface model from a point cloud because I have Lidar data(Which means I have point coordinates as input) and I am really interested to work with this superb tool. 
For instance, this is an approximated image: 
http://www.lidar3d.pl/upload/5c125b6f0879620181213141645.original.png
But I am not looking for accuracy like this.. I don't care if it's less accurate.

**Comment by NourSoltani** [comment]
Hello @SimonVirgo 
I appreciate your help.
Thank you very much!
