### ISSUE TITLE
crop surface polydata at intersections

### ISSUE THREAD

**Issue by okottwitz** [cgre-aachen/gempy#700]
Hey gempy-team,

First of all, thank you for providing this very useful software to the community! I really admire the effort you put in maintaining, documenting and helping people using it!

I started to use GemPy a couple of months ago to generate a 3D structural model containing faults, joints, and layers of a limestone formation from borehole image logs and pavement traces and have been pretty happy with the results so far. I use the polydata of the resulting surfaces and "voxelise" them into a continuum model used in hydraulic simulations, where each voxel contains an individual, anisotropic permeability tensor (which I can then add up to the resulting voxel model of gempy, populated with hydraulics of the formation layers). 

In my model, I have one fault that stops at another one, which I could model with your "set_is_finite_fault" option and setting the stopping criteria properly in the "fault_relations_df".
I am now wondering, if there is the possibility to crop the polydata when it intersects with another polydata, to avoid the spurious visualization artifacts in the output polydata, probably arising from the marching-cube algorithm (see screenshot below). Or is it maybe possible to tell GemPy thto stop the generation of the surface data, when it encounters another surface and not "dragging" it along the other surface?

Thanks in advance for your help and again for your valuable open-source contribution :)
Cheers,
Oskar

![gempyIssue_IntersectingFault](https://user-images.githubusercontent.com/106579755/171119539-dcc7d0e0-496d-49f1-8fc0-30af6c8a53a2.png)

**Comment by AlexanderJuestel** [comment]
@okottwitz thanks for your question and sorry for the late answer! Our development team will get back to you with a response as soon as possible!

**Comment by Japhiolite** [comment]
Hi Oskar,
we're currently working on a new release of gempy, which does not rely on marching cubes anymore (a side effect of those is this "draping" of surfaces along other surfaces), in favor of dual contouring. That will most likely drastically improve the visualization of gempy models (and help with getting watertight meshes).
Unfortunately I cannot provide you with a robust date when this'll be released.

Oh and thanks for your kind words, means a lot and is motivating!

Best
Jan

**Comment by AlexanderJuestel** [comment]
Closing as this feature will be available in a future release.
