### ISSUE TITLE
Using gp plot_ 2D, only gray white points are displayed in the image

### ISSUE THREAD

**Issue by qazwsx1314** [cgre-aachen/gempy#703]
Using gp plot_ 2D, only gray white points are displayed in the image
![image](https://user-images.githubusercontent.com/92284966/173501638-a4e95694-a15d-4e0b-8207-3e728cc10bba.png)

**Comment by Japhiolite** [comment]
Hi @qazwsx1314 
this was a bug in the current gempy release and is fixed in the current master of the repository. I'll see, if we can make a small pip release to fix this... in the meantime you could use the current master branch for running gempy. There, it should be fixed.

**Comment by Japhiolite** [comment]
I had a look, this was solved in PR #499

**Comment by Japhiolite** [comment]
Can you check, which gempy version you have installed?

**Comment by Japhiolite** [comment]
On pip is 2.2.11 which should solve the issue

**Comment by qazwsx1314** [comment]
OK, thanks, the problem is solved
