### ISSUE TITLE
cannot import  gempy 

### ISSUE THREAD

**Issue by AlphaDragon009** [cgre-aachen/gempy#710]
**Describe the bug**
I  am trying to install  gempy, but it  cannot be imported. 
Below is the process:   

Envirment: ubuntu 22.04
Intel CPU i9-9900

step1 : install gempy 
conda  create --name env  python=3.6

conda   activate env 
 
pip install gempy

step2: run python  and import gempy.
Error appears as below: 

$python 
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gempy 
libssl.so.1.0.0: cannot open shared object file: No such file or directory
Not subsurface compatibility available
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File /.../anaconda3/envs/model_building/lib/python3.6/site-packages/gempy/__init__.py", line 24, in <module>
    from gempy.gempy_api import *
  File "/.../anaconda3/envs/model_building/lib/python3.6/site-packages/gempy/gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "/.../anaconda3/envs/model_building/lib/python3.6/site-packages/gempy/core/model.py", line 20, in <module>
    from gempy.plot.decorators import *
  File "/.../anaconda3/envs/model_building/lib/python3.6/site-packages/gempy/plot/decorators.py", line 2, in <module>
    from gempy.plot.vista import GemPyToVista
  File "/.../anaconda3/envs/model_building/lib/python3.6/site-packages/gempy/plot/vista.py", line 26
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

But the  libssl.so.1.0.0 is there. 

$ sudo find . -name libssl.so.1.0*
./anaconda3/pkgs/openssl-1.0.2u-h516909a_0/lib/libssl.so.1.0.0
./anaconda3/pkgs/openssl-1.0.2u-h7b6447c_0/lib/libssl.so.1.0.0
./anaconda3/envs/gempy/lib/libssl.so.1.0.0
 

I also try python version 3.7, they  have the same issue. Thanks !

**Comment by Japhiolite** [comment]
Hi @AlphaDragon009 

do you have theano installed in your created environment? It does not appear in your step1 description.
Once created the environment, you can try also to use the conda-forge feedstock: https://anaconda.org/conda-forge/gempy
Further, best to use python 3.8 or 3.9 (3.10 should also work, but might give some quirks).

**Comment by Japhiolite** [comment]
Any progress here?

**Comment by Japhiolite** [comment]
Closed due to inactivity
