### ISSUE TITLE
A Problem on tutorial of ch1_4Unconformity relationships Importing gempy

### ISSUE THREAD

**Issue by ChinLu** [cgre-aachen/gempy#722]
**Describe the bug**
When I run the third cell on Jupyter-Notebook of ch1_4 Unconformity relationships, The system show me that there exists Error

**Expected behavior**

![图片1](https://user-images.githubusercontent.com/44860575/190294532-2cb655ac-4eab-4ad4-812f-16867551de3b.png)

**Screenshots**
The above picture is the expected result. But my result is
![图片2](https://user-images.githubusercontent.com/44860575/190295128-7114f18c-959f-4855-b27c-240b797398e2.png)

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version
    I install Gempy by pip, GemPy version is 2.2.12
    
  * Jupyter Version is1.0.0

**Additional context**

**Comment by Japhiolite** [comment]
As stated in the error message, the model data for loading the gempy model cannot be found.
For the unconformity Tutorial, it should be Tutorial_ch1-8_... 
These files can be found here: https://github.com/cgre-aachen/gempy_data/tree/master/data/gempy_models/Tutorial_ch1-8_Onlap_relations

Best clone the gempy_data repository, adapt the path in the loading part of Tutorial ch 1_4 to the path you have your data, and proceed from there.

**Comment by ChinLu** [comment]
I have created a folder which contains the files on https://github.com/cgre-aachen/gempy_data/tree/master/data/gempy_models/Tutorial_ch1-8_Onlap_relations.
And I have given the folder appropriate name and path.
But when I run the jupyter-notebook of Tutorial ch 1_4 , there still exist ERROR.
![image](https://user-images.githubusercontent.com/44860575/190943037-e07b3a27-a244-45d8-bbfd-7626c434cd29.png)
![image](https://user-images.githubusercontent.com/44860575/190943054-9ece381c-ead5-406b-bdfa-8cae7866e2a6.png)
