### ISSUE TITLE
Problem in model computation after using velocity value

### ISSUE THREAD

**Issue by hembramsasmita** [cgre-aachen/gempy#723]
Hello,
I am using the GemPy fault model to build a velocity model. The velocity values are assigned to the fault model by using 
![11](https://user-images.githubusercontent.com/44606939/190404740-1d9af9ac-0c08-453e-8da0-8887d1723d70.JPG) and the model becomes horizontal layers with no sign of fault.

![2](https://user-images.githubusercontent.com/44606939/190407292-e15d5aee-c111-47ee-a9d9-ae742ffec032.png)
![1](https://user-images.githubusercontent.com/44606939/190407301-2a1b8f8b-7fdf-4b09-968f-975ed79bc8a2.png)
The velocity values are attached 
 
![3](https://user-images.githubusercontent.com/44606939/190407942-15a2011b-5286-4387-963d-b87c1f67fa9e.JPG)

What should I do to fix this problem?
Thank you in advance.

**Comment by Japhiolite** [comment]
Without knowing how you created the second plot and what to see there, it is difficult to help. `geo_model.add_surface_values()` extends the surface dataframe by a column with the parameter (in your case `vp` as the header), like shown in [this example](https://docs.gempy.org/getting_started/get_started.html#additional-features).

**Comment by hembramsasmita** [comment]
I have used the following

![20](https://user-images.githubusercontent.com/44606939/190843779-7a2fc1c3-3211-4ea3-8fde-8c824c0b2fa9.JPG)
![11](https://user-images.githubusercontent.com/44606939/190843666-0a5dbb11-71aa-4b78-92a1-13601c10c1c2.JPG)
![12](https://user-images.githubusercontent.com/44606939/190843671-b7ba3614-6712-4ff0-80b1-97d0d71a3470.JPG)
![13](https://user-images.githubusercontent.com/44606939/190843734-6c22787c-8b66-4d41-8122-517fa8ef25ff.JPG)
![21](https://user-images.githubusercontent.com/44606939/190843953-3ba2da12-d774-4124-a2fc-e9dcf6927219.JPG)
![14](https://user-images.githubusercontent.com/44606939/190843673-55c8611d-f2bd-4694-a0e6-419b6da71f35.JPG)
![15](https://user-images.githubusercontent.com/44606939/190843676-411a6a46-7c09-456d-bd0b-47c92a5c1a6a.JPG)
![16](https://user-images.githubusercontent.com/44606939/190843678-42eb0237-cfa0-4a70-965a-e7b8c711c155.JPG)
![17](https://user-images.githubusercontent.com/44606939/190843686-0d275da5-b2e4-4bc9-8948-b6bed08576cd.JPG)
![18](https://user-images.githubusercontent.com/44606939/190843689-957ecd44-8fe7-47ea-9f72-4c1fa4ae5f0b.JPG)
![19](https://user-images.githubusercontent.com/44606939/190843691-b1717439-a2a5-495e-85ee-b3a10da979c4.JPG)

**Comment by Japhiolite** [comment]
Remember that `reshaped` is also a 3D array, so to be sure, you should slice it by stating all three dimensions, i.e. `reshaped[:,25,:]` to get the slice in y-direction at the 25th cell number. Like this, you slice in X direction, where the model indeed only shows the two layers (the red line I drew in the following screenshot). 

If you reshape your array, the order (C or F) is also important for slicing correctly. You can go by using C, I think though that gempy normaly uses the fortran (so F) schema. Anyway, when you slice your reshaped `values_matrix` correctly like on the image, you get the correct figure.

![image](https://user-images.githubusercontent.com/13364692/190987506-af66942f-5c68-475b-8db4-02c6db13e92e.png)

**Comment by hembramsasmita** [comment]
Thank you very much @Japhiolite
