### ISSUE TITLE
how not to cross faults?

### ISSUE THREAD

**Issue by Nauj29** [cgre-aachen/gempy#726]
**What is your question?**
Hi everybody, I have tried replicating tutorial 1.5 Fault relations but with my own data. Unfortunately, I have not achieved that the faults do not cross (first image) like the tutorial (second image).
![my_example](https://user-images.githubusercontent.com/65965364/196306257-727916aa-41c3-402d-941e-134498fdcec3.png)

![1 5tutorial](https://user-images.githubusercontent.com/65965364/196306127-f9db047a-ca08-4299-a50f-6af01aa741b8.png)

I have tried to resolve this with "geo_model.set_fault_relation()" but it hasn't worked.
.
I would really appreciate your help.
I attach the model 
[Fallas.zip](https://github.com/cgre-aachen/gempy/files/9805300/Fallas.zip)

**Beforehand thank you very much**

**Comment by Japhiolite** [comment]
Hi @Nauj29 

apparently this is due too few surface points for the faults. I reran your model without the desired output.
However, adding two test surface points to your model (here, the model object is named `geo_model`) for the faults like 
```python
geo_model.add_surface_points(50, 45, 35, "Falla_1")
geo_model.add_surface_points(50, 55, 45, "Falla_2")
```

yields such a cross section:
![image](https://user-images.githubusercontent.com/13364692/196398171-d7721444-f7af-4950-8b92-7e169328cdfe.png)

**Comment by Nauj29** [comment]
Hi @Japhiolite

Thanks for your quick response.
