### ISSUE TITLE
Save PyVista Mesh of a GemPy Surface to Raster

### ISSUE THREAD

**Issue by hntigkakis** [cgre-aachen/gempy#727]
Hi everyone! Is there a way to export the generated surfaces to a raster for use in QGIS?

**Comment by AlexanderJuestel** [comment]
Hello,

We are currently working in the GemGIS package on a way to export the pyvista Meshes to rasters. There is an experimental export to the ZMAP grid format though which works for simple Meshes so far.

We keep you posted!

**Comment by AlexanderJuestel** [comment]
Dear @hntigkakis, 

please have a try by extracting the mesh from your geomodel using the GemGIS function ```gg.visualization.create_depth_maps_from_gempy```. Afterwards, use the PyVista function ```mesh.project_points_to_plane``` (https://docs.pyvista.org/examples/01-filter/project-plane.html) and then the GemGIS function ```gg.raster.save_as_tiff```. 

Before saving, you will have to reshape the data array containing the elevation/depth values according to the dimensions of your mesh. 

This should provide you with a raster as shown here in QGIS (it is the project to plane Pyvista Example). 

Let me know if I can provide more details for you! 

![image](https://user-images.githubusercontent.com/45469915/196868956-7a923bd6-130d-4427-be71-82e342c23a0c.png)

**Comment by hntigkakis** [comment]
Thanks for you help @AlexanderJuestel.

Could you maybe walk me through it? How do I go from the PolyData object that I get from `mesh.project_points_to_plane` to an array that I can save with `gg.raster.save_as_tiff` ?

For reference, I am using a 50x50m regular grid

**Comment by AlexanderJuestel** [comment]
Hello @hntigkakis, 

I would actually propose a different solution now, sorry for the confusion:

- Extracting the surface from GemPy
```ruby
dict1 = gg.visualization.create_depth_maps_from_gempy(geo_model, surfaces='Carbon_bot')
```

- Using the following function to get an array of the values (the actual ZMAP export fails until now)

```ruby
z_values = gg.utils.extract_zmap_data(surface=dict1['Carbon_bot'][0],
                                      cell_width=100)
z_values
```



- Saving the raster (the extent was obtained from the bounds of the mesh)

```ruby
gg.raster.save_as_tiff(z_values, 'raster.tif', extent= [32318339.14,
 32383228.86,
 5679778.444766998,
 5702991.091537476,], crs='EPSG:4647',overwrite_file=True)
```

**Comment by hntigkakis** [comment]
Thank you @AlexanderJuestel for all your help. It works perfectly
