### ISSUE TITLE
[DEP] NumPy and Pandas are currently not compatible with GemPy

### ISSUE THREAD

**Issue by yurivict** [cgre-aachen/gempy#748]
I was going to port GemPy to FreeBSD but Pandas and Numpy incompatibilities prevent this.

Any idea when when this will be fixed?

**Comment by Japhiolite** [comment]
Hi @yurivict 

with Pandas, I cannot give you a serious estimate. However, as the numpy requirement is due to the deprecated theano package, that is fixed and will stay as long as gempy uses theano (all versions up to version 2.3 which will hopefully be released in the coming weeks).

Regards
Jan

**Comment by AlexanderJuestel** [comment]
@yurivict I added your issue to our GemPy 2.3 Milestone. We hope to release GemPy 2.3 in the coming weeks

**Comment by AlexanderJuestel** [comment]
GemPy 2.3 has been released and the issue should have been solved now! Please reopen if you still have issues with the installation.

See https://github.com/cgre-aachen/gempy/releases/tag/v2.3.0 for more information
