### ISSUE TITLE
Create environment with Gempy, subsurface, welly, pooch and spyder

### ISSUE THREAD

**Issue by affe73** [cgre-aachen/gempy#749]
**Describe the bug**
Cannot get gempy, subsurface, welly, pooch to run in a virtual environment together 

**To Reproduce**
Provide detailed steps to reproduce the behavior:

Hello, I am gratefull to read advices regarding creating an environment where the following packages can coexist, work: gempy, subsurface, welly, pooch, spyder. I have made different attempts and got different problems. The latest I tried was to install in this order: python 3.6, welly (from geotrove -welly), striplog (conda-forge), pooch, subsurface, spyder (on win 11). As written, have got different kinds of conflicts, for instance:
-Spyder failed to start because no Qt platform plugin could be initialized
-spyder does not load QObject::moveToThread: Current thread (0x27f8f4f9db0) is not the object's thread (0x27f9050c4e0).
-Exit code: 3221226505 spyder
-python - ModuleNotFoundError: No module named 'matplotlib.pyplot'
Note that I insist to install spyder because jupiter is not an alternative in my case.
...

**Expected behavior**
To be able to use Spyder in a virtual environment using gempy, subsurface, welly, pooxh

**Screenshots**

**Desktop (please complete the following information):**
  * OS: Win 11
  * GemPy Version
    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable)

**Additional context**

**Comment by affe73** [comment]
A contradiction is that todays version of welly run with Python 3.6 as highest version, while subsurface from v. 0.2.0 to v 0.2.9 can only run in python **>=3.7**. So I wonder  how people is able to install these two packages together, i.e. in the same vir environment.

**Comment by Japhiolite** [comment]
Hi @affe73 
As of their Github page, Welly is compatible with Python 3.6 - Python 3.10.
![image](https://user-images.githubusercontent.com/13364692/214345778-2248d181-5b72-453c-90ed-fb37d2dbe598.png)

**Comment by affe73** [comment]
Thanks @Japhiolite , I see that. Do you think that the issues I have may be related to the order in which the packages are installed? I wonder why conda complaints that welly requires python 3.6 and subsurface needs python>=3.7.

**Comment by Japhiolite** [comment]
I assume, because you install welly from a weird channel "from geotrove -welly" <- as you wrote.
Use the installation steps written in the **real** welly repo documentation.

**Comment by AlexanderJuestel** [comment]
@affe73, did you manage to install the packages?

**Comment by Japhiolite** [comment]
closed due to inactivity
