### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by anneschulz1991** [cgre-aachen/gempy#751]
Hello to all,
I would like to install Gempy on my new computer and would like to use manual installation for this. Cloning the folder was no problem (git clone https://github.com/cgre-aachen/gempy.git) however when I run the following command I get the following error message:
python gempy/setup.py install
Traceback (most recent call last):
  File "/home/blinki/gempy/setup.py", line 4, in <module>
    with open("README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'.
I have checked the file README.md exists so I don't know where the error could be. Can someone help me?
Many greetings
Anne

**Comment by Japhiolite** [comment]
Hi Anne,

try calling `python setup.py install` from inside the gempy folder. Might give other version errors though, as we're currently facing requirement problems.

Best
Jan

**Comment by AlexanderJuestel** [comment]
@anneschulz1991 were you able to solve your issue?

**Comment by Japhiolite** [comment]
closed due to inactivity
