### ISSUE TITLE
[DEP] PyVista parse_color deprecated 

### ISSUE THREAD

**Issue by adamchengtkc** [cgre-aachen/gempy#754]
Just to share some info on installing with pip

There are some breaking changes with pyvista and its dependency vtk.

To resolve this, you will need to have pyvista 0.34.2:
This is a version that:
- before pyvista remove parse_color from plotting. So it will work with gempy
- After pyvista has fixed vtk import with newer vtk version https://github.com/pyvista/pyvista/pull/2585/commits/e23aec738afc95bb08ec3f3e528adc5a606cd2b6

**Comment by AlexanderJuestel** [comment]
@adamchengtkc 
Thanks for reporting that. We are aware of the issue and it will be fixed in GemPy 2.3 coming out in the next couple of weeks. Stay tuned :)

**Comment by AlexanderJuestel** [comment]
GemPy 2.3 has been released and the issue should have been solved now! Please reopen if you still have issues with the installation.

See https://github.com/cgre-aachen/gempy/releases/tag/v2.3.0 for more information
