### ISSUE TITLE
[DOC] Add GemPy Project description to PyPi

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gempy#755]
Currently, there is no GemPy Project description on PyPi. This can be easily added within `setup.py`.  A PR follows soon...

![image](https://user-images.githubusercontent.com/45469915/220598434-3f51a910-31a0-4aca-aed7-c19e4715bd81.png)

**Comment by Japhiolite** [comment]
seems like the integration of the readme fell out of `setup(...)` some point in time...we were declaring a long_description at least in `setup.py`. I went ahead and added the long description again.

**Comment by AlexanderJuestel** [comment]
Awesome, thanks!
