### ISSUE TITLE
[DEP] AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by Geobro1** [cgre-aachen/gempy#772]
**Describe the bug**
When calling import gempy as gp this error occurs. 
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**To Reproduce**
import gempy as gp

**Possible Solution**
pip3 install mxnet-mkl==1.6.0 numpy==1.23.1 may work as a solution or changing source code.

**Comment by AlexanderJuestel** [comment]
Dear @Geobro1, 
thanks for reaching out. We are aware of this issue with theano and will fix it with the upcoming release of GemPy 2.3
