### ISSUE TITLE
ImportError: cannot import name 'parse_color' from 'pyvista.plotting' 

### ISSUE THREAD

**Issue by Geobro1** [cgre-aachen/gempy#773]
**Describe the bug**
Error when importing gempy - ImportError: cannot import name 'parse_color' from 'pyvista.plotting' 

**To Reproduce**
import gempy as gp

**Additional context**
Unsure how to fix, any help would be much appreciated.

**Comment by AlexanderJuestel** [comment]
This issue is already known from https://github.com/cgre-aachen/gempy/issues/754

Closing as it is a duplicate. The current workaround would be to downgrade your PyVista Version. We are working on a fix here.
