### ISSUE TITLE
Installation issues: ValueError in fresh environment

### ISSUE THREAD

**Issue by NilsChudalla** [cgre-aachen/gempy#780]
**Describe the bug**
ValueError when installing Gempy in a fresh environment with Python 3.10.

<details>
<summary>Error message in notebook on import</summary>
<br>
-----------------------------------------------------------------
ValueError                      Traceback (most recent call last)
Cell In[1], line 1
----> 1 import gempy

File ~\.conda\envs\test\lib\site-packages\gempy\__init__.py:25
     21 SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
     22 sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))
---> 25 from gempy.gempy_api import *
     26 from gempy.api_modules.getters import *
     27 from gempy.api_modules.setters import *

File ~\.conda\envs\test\lib\site-packages\gempy\gempy_api.py:17
     15 from typing import Union
     16 import warnings
---> 17 from gempy.core.model import Project
     18 from gempy.core.solution import Solution
     19 from gempy.utils.meta import _setdoc, _setdoc_pro

File ~\.conda\envs\test\lib\site-packages\gempy\core\model.py:11
      8 from typing import Union, Iterable
      9 import warnings
---> 11 from gempy.core.data_modules.geometric_data import Orientations, SurfacePoints, \
     12     ScalingSystem, Surfaces, Grid
     13 from gempy.core.data_modules.stack import Stack, Faults, Series
     14 from gempy.core.data import AdditionalData, MetaData, Options, Structure, \
     15     KrigingParameters

File ~\.conda\envs\test\lib\site-packages\gempy\core\data_modules\geometric_data.py:10
      7 import numpy as np
      8 import pandas as pn
---> 10 from gempy.core.data import Surfaces, Grid
     12 from gempy.core.checkers import check_for_nans
     13 from gempy.utils import docstring as ds

File ~\.conda\envs\test\lib\site-packages\gempy\core\data.py:8
      6 import numpy as np
      7 import pandas as pn
----> 8 import seaborn as sns
     10 try:
     11     import ipywidgets as widgets

File ~\.conda\envs\test\lib\site-packages\seaborn\__init__.py:5
      3 from .utils import *  # noqa: F401,F403
      4 from .palettes import *  # noqa: F401,F403
----> 5 from .relational import *  # noqa: F401,F403
      6 from .regression import *  # noqa: F401,F403
      7 from .categorical import *  # noqa: F401,F403

File ~\.conda\envs\test\lib\site-packages\seaborn\relational.py:17
      8 from ._oldcore import (
      9     VectorPlotter,
     10 )
     11 from .utils import (
     12     locator_to_legend_entries,
     13     adjust_legend_subtitles,
     14     _default_color,
     15     _deprecate_ci,
     16 )
---> 17 from ._statistics import EstimateAggregator
     18 from .axisgrid import FacetGrid, _facet_docs
     19 from ._docstrings import DocstringComponents, _core_docs

File ~\.conda\envs\test\lib\site-packages\seaborn\_statistics.py:31
     29 import pandas as pd
     30 try:
---> 31     from scipy.stats import gaussian_kde
     32     _no_scipy = False
     33 except ImportError:

File ~\.conda\envs\test\lib\site-packages\scipy\stats\__init__.py:485
      1 """
      2 .. _statsrefmanual:
      3 
   (...)
    480 
    481 """
    483 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    484                                DegenerateDataWarning, FitError)
--> 485 from ._stats_py import *
    486 from ._variation import variation
    487 from .distributions import *

File ~\.conda\envs\test\lib\site-packages\scipy\stats\_stats_py.py:39
     36 from numpy.lib import NumpyVersion
     37 from numpy.testing import suppress_warnings
---> 39 from scipy.spatial.distance import cdist
     40 from scipy.ndimage import _measurements
     41 from scipy._lib._util import (check_random_state, MapWrapper,
     42                               rng_integers, _rename_parameter, _contains_nan)

File ~\.conda\envs\test\lib\site-packages\scipy\spatial\__init__.py:105
      1 """
      2 =============================================================
      3 Spatial algorithms and data structures (:mod:`scipy.spatial`)
   (...)
    102    QhullError
    103 """
--> 105 from ._kdtree import *
    106 from ._ckdtree import *
    107 from ._qhull import *

File ~\.conda\envs\test\lib\site-packages\scipy\spatial\_kdtree.py:4
      1 # Copyright Anne M. Archibald 2008
      2 # Released under the scipy license
      3 import numpy as np
----> 4 from ._ckdtree import cKDTree, cKDTreeNode
      6 __all__ = ['minkowski_distance_p', 'minkowski_distance',
      7            'distance_matrix',
      8            'Rectangle', 'KDTree']
     11 def minkowski_distance_p(x, y, p=2):

File _ckdtree.pyx:1, in init scipy.spatial._ckdtree()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
</details>

**To Reproduce**
Follow installation guide by @AlexanderJuestel from [gemgis](https://gemgis.readthedocs.io/en/latest/getting_started/installation.html):
1. Fresh environment (Python 3.10)
2. `conda config --env --add channels conda-forge`
3. `conda config --env --set channel_priority strict`
4. `conda install -c conda-forge jupyter`
5. `pip install gemgis`
6. `jupyter notebook` -> create new notebook
7. `import gempy`

**Expected behavior**
Obviously, should install gempy properly

**Desktop:**
  * OS: Windows 11 Pro Education
  * GemPy Version (2.2.12)
  * Jupyter Version (1.0.0)
  
**Additional context**
I encountered a similar error in another environment. However, it was caused by skimage in that environment. Find attached the detailed environment used. Currently, numpy 1.21.6 was used, and in different projects, this was not the source of a comparable error.
[env.txt](https://github.com/cgre-aachen/gempy/files/11072430/env.txt)

**Comment by javoha** [comment]
Hi Nils,
I was able to reproduce the same error. For just running gempy going back to Python 3.9 worked, with a bonus step of downgrading pyvista:
```conda create -n gempy_test python==3.9
conda activate gempy_test
conda install -c conda-forge jupyter
conda install theano
pip install gempy
pip install pyvista==0.34.2```

Not sure though if this will work with the rest of the gemgis requirements, especially GDAL seems to be an issue.
