### ISSUE TITLE
Top series becomes isActive=False after running gp.map_stack_to_surfaces

### ISSUE THREAD

**Issue by lucianomarquetto** [cgre-aachen/gempy#781]
**What is your question?**
Hi all! Thank you for your support so far, it has been really enjoyable learning gempy. 

This might be a bug, but I will leave to you to define because it might also be me doing something wrong. 

I am having an issue similar to https://github.com/cgre-aachen/gempy/issues/348. If I load my data and leave all my surfaces in the 'default series' everything is ok, but if I run 'gp.map_stack_to_surfaces' to define different series for each surface, the top surface/series always become 'isActive=False'. I have 47 surface points divided in 3 series, and my top series has the same number of points as my middle series (18), while the bottom series has less (8). 

Running 'geo_model.surfaces.df['isActive'] = True' and 'geo_model.stack.df['isActive'] = True' after 'gp.map_stack_to_surfaces' changes all surfaces and series to 'isActive=True', but when I compute the model ('gp.compute_model(geo_model)') I get the same error I get when the top surface/series is 'isActive=False', which is:

'ValueError: Must have equal len keys and value when setting with an iterable'

I was able to "solve" the problem by running 'gp.map_stack_to_surfaces' twice, which then switch the top surface/series to 'isActive=True' and allow to compute the model normally (and beautifully, by the way, thanks to your package!).

So basically after all that, my question is: Am I doing something wrong or is that really some kind of bug? If it is a bug, please let me know if you rather have me post this in the respective section and following the guidelines from there.

Thank you all!

My code:
`
-Importing GemPy
import gempy as gp

-Importing auxiliary libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import osgeo
import os
import pyvista as pv

-Return current working directory
cwd = os.getcwd()
data_path = cwd

-Creating the model
geo_model = gp.create_model('Modelo_LN')
geo_model = gp.init_data(geo_model, extent=[560000, 595000, 6670000, 6700000, -130, 30], 
                         resolution=[100, 100, 100],
                         path_o=data_path + '/Gempy_files/Gempy_input_orientations_VES_collischonn_2022.csv',
                         path_i=data_path + '/Gempy_files/Gempy_input_surfaces_VES_collischonn_2022.csv')

-Add surfaces and define names to match the ones in the paper. 
gp.map_stack_to_surfaces(geo_model,
                         {"Unit3": ('unit3'), #top
                          "Unit2": ('unit2'), #middle
                          "Unit1": ('unit1'), #bottom
                          "Basement": ('basement')},
                          )`

-Check if surfaces and series are all isActive=True:
geo_model.surfaces.df
geo_model.stack

-Run the below lines again if getting any surfaces/series isActive=False

geo_model.surfaces.df['isActive'] = True **--->does not solve the problem**
geo_model.stack.df['isActive'] = True **--->does not solve the problem**

gp.map_stack_to_surfaces(geo_model,  **--->running this again solves the problem**
                         {"Unit3": ('unit3'), 
                          "Unit2": ('unit2'), 
                          "Unit1": ('unit1'), 
                          "Basement": ('basement')},
                          )`

-Run the interpolator
gp.set_interpolator(geo_model, theano_optimizer='fast_run', verbose=[])

-Compute model
gp.compute_model(geo_model)

**Comment by Japhiolite** [comment]
Hi @lucianomarquetto 

without looking much into your workflow, I just wanted to quickly say that you might have encountered an errorneous state of your model. Currently gempy might not catch all of those, simply because of different approaches by users to create a model, i.e. different sequential execution of methods. 

However, you mention 
> If I load my data and leave all my surfaces in the 'default series' everything is ok, but if I run 'gp.map_stack_to_surfaces' to define different series for each surface, the top surface/series always become 'isActive=False'.

Does every series have their own orientations (at least one) and interface points (at least two)?

**Comment by lucianomarquetto** [comment]
Hi @Japhiolite, thanks for responding to my question! 

My three series (Unit1, Unit2, Unit3) have 18, 18 and 8 interface points respectively. I do not know if this is good practice or not but I considered all those 44 points to have orientations, as I'm dealing with horizontal stratigraphy (so azimuth = 0, dip = 0 and polarity = 1 for each). 

About this "erroneous state", is something I have to worry about in the long term (i.e. is this something that will affect any future improvement of my model or the post-processing of data obtained from the model itself)? If not then I will be fine running gp.map_stack_to_surfaces twice, and will try changing the sequential execution of commands.

Cheers!

**Comment by Japhiolite** [comment]
No, it's nothing majorly concerning, as it does not affect simulation results.

**Comment by lucianomarquetto** [comment]
Great, thanks for the explanation Jan!
