### ISSUE TITLE
Cannot import Gempy due to ImportError

### ISSUE THREAD

**Issue by thelearningcurves** [cgre-aachen/gempy#783]
**Describe the bug**
I am trying to install Gempy on WSL2 ubuntu. there is an import error "

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1. pip gempy

...

**Expected behavior**
I was expecting it to import gempy in python 3.10 version

**Screenshots**
![image](https://user-images.githubusercontent.com/71737718/228527360-748933c9-ce52-4711-96a9-70c66da4ee91.png)

**Desktop (please complete the following information):**
  * OS: (e.g. WSL2 UBUNTU)
  * GemPy Version
    *Via pip - 2.2.12
    
 

**Additional context**

**Comment by Japhiolite** [comment]
See Issue #754 how to solve this for now.
Will be fixed with the next release.
