### ISSUE TITLE
GemPy installation

### ISSUE THREAD

**Issue by GiuliaLisi** [cgre-aachen/gempy#792]
Dear Sirs,
I am trying to install GemPy following instructions on your web site.
Unfortunately it does not work.
When I try to execute python import command as: import gempy as gp there is error messages as you can see in the attached file.
The error happens in numpy even though the numpy package has been installed during the pip install gempy command.

Please see the attached files.

[Install_error.pdf](https://github.com/cgre-aachen/gempy/files/11290636/Install_error.pdf)
[Installed_packages.txt](https://github.com/cgre-aachen/gempy/files/11290637/Installed_packages.txt)

Thanks a lot.

g.lisi96@outlook.it

**Comment by javoha** [comment]
Hi, 
there are some dependency issues that we are trying to resolve for the next release. Maybe try the suggestion in #780 for a short term solution.
I really hope it helps and have fun using gempy!

**Comment by GiuliaLisi** [comment]
Good morning, 
I have followed all the instructions written in the suggestion #780. 
The problem persists when I run "import gempy as gp", as you can see in the screenshot below...

![Immagine1](https://user-images.githubusercontent.com/131407692/233638380-cbe33969-b437-490b-bf8a-ee6e9f1a507c.png)

I have also verified that the version of numpy installed in my environment is 1.21.6 !!

Please, do you have any other suggestions?
Thank you again

**Comment by javoha** [comment]
Hi,
could you also share the version of scikit-mage in that new environment?

**Comment by VLSAR24** [comment]
@GiuliaLisi  Hi, the error was solved for me through downgrading through python 3.9. 
You can try that.

**Comment by AlexanderJuestel** [comment]
GemPy 2.3 has been released and the issue should have been solved now! Please reopen if you still have issues with the installation.

See https://github.com/cgre-aachen/gempy/releases/tag/v2.3.0 for more information
