### ISSUE TITLE
When will the new version be released？

### ISSUE THREAD

**Issue by cugb-suerwei** [cgre-aachen/gempy#793]
This is really a great project, and I really want to use it in my own project immediately. But I have already failed many times during the installation of the environment, and various problems are really beyond my control. I really want to know when version 2.13 will be released and these dependency issues will be resolved.

**Comment by AlexanderJuestel** [comment]
@cugb-suerwei, 

we are desperately waiting on the new version as well. However, due to private reasons, one of our core developers, who is in charge of the new release, is currently not available.  We hope to have the release ready in the next few weeks though. 

In the meantime, which dependencies are causing issues? Maybe we can help you out and get it running for now!

Cheers 
Alex

**Comment by cugb-suerwei** [comment]
from pyvista.plotting import parse_color
ImportError: cannot import name 'parse_color' from 'pyvista.plotting'
I have been encountering the above error all along，I hope you can help me

**Comment by javoha** [comment]
Hi,
can you try the following installation guide in a fresh environment? That would be a workaround solution until the new version is released.

```conda create -n gempy_test python==3.9
conda activate gempy_test
conda install -c conda-forge jupyter
conda install theano
pip install gempy
pip install pyvista==0.34.2

**Comment by cugb-suerwei** [comment]
Thank you very much for your answer. I am now able to run the sample code. Although there are some warning messages, the program can run. This is really great!

**Comment by cugb-suerwei** [comment]
![image](https://user-images.githubusercontent.com/24865219/236613057-c8cbe6d8-ce1b-4e66-be05-e0b891126a0d.png)
![image](https://user-images.githubusercontent.com/24865219/236613239-f751ff2f-1b15-4ae1-930b-17d150455640.png)

I can now run the sample code, but I have encountered another problem. The model I constructed only has faces and no geological bodies. I completely used the data from the sample document, but the results were different.
The above image is the model I built, and the following is the model in the document

**Comment by stoaschaedl** [comment]
Have you tried to set `show_lith=true` when calling `gempy.plot_3d`? According to [the docs](https://docs.gempy.org/Plot/gempy.plot_3d.html#gempy.plot_3d) it should default to true, but i seem remember facing this issue once.

Cheers

**Comment by cugb-suerwei** [comment]
@stoaschaedl

**Comment by cugb-suerwei** [comment]
I conducted further testing and found that running the same code on a Linux system can build a body model, but on a Windows system, only a surface model of the stratum can be built.
