### ISSUE TITLE
Gempy is good to use soft-sediment model?

### ISSUE THREAD

**Issue by Changwan-planet** [cgre-aachen/gempy#794]
I have two questions.

I am working in the field of paleoseismology. We usually trench to find the active faults or deformed shallow structures ( 3~5  m depth).

1.
If we have multiple slices of trench section at a certian site, please imagine you cut a slab cake into multiple thin pieces, and we found a similar geological structure continuously show in the multiple sections,  Can we make a model of the structure from **gempy**  although our target is unconsolidated sediment?

2.
Another question is that if we make a metioned model above from you program, 
Can we test a model for dynamic simulation with **gempy**?

Many thanks

**Comment by stoaschaedl** [comment]
>1. If we have multiple slices of trench section at a certian site, please imagine you cut a slab cake into multiple thin pieces, and we found a similar geological structure continuously show in the multiple sections, Can we make a model of the structure from gempy although our target is unconsolidated sediment?

I did look into GemPy a while ago for modeling sedimentary structures especially for site remediation. In general, it is possible, however, i personally did find it a bit fiddly to add multiple substructures like lenses or high resolution precise shapes. If those are important for your use case, a workaround could be to create substructures in separate models and combine those, as suggested in #584, but i did not try that.

This [YouTube-tutorial](https://youtu.be/n0btC5Zilyc?t=456) and the tutorials [here](https://www.gempy.org/tutorials) did help me a lot to get started. Theres also a part starting at around [27:26](https://youtu.be/n0btC5Zilyc?t=1587) on how to use existing sections (like boreholes or yours from trenching) to pick surface points. Text version is provided [here](https://github.com/cgre-aachen/gempy_workshops/blob/master/workshops/transform2020/t20_gempy.ipynb).

Cheers

**Comment by AlexanderJuestel** [comment]
Closed as completed
