### ISSUE TITLE
How to use the create_orientation_from_surface_points function？

### ISSUE THREAD

**Issue by Geo-LiuDaLi** [cgre-aachen/gempy#795]
Hello! I've only recently started using GemPy,My goal is to build a fault model, but currently I only have surface point data and dip, azimuth data for the fault. 

I am trying to use the create_orientation_from_surface_points function to calculate the orientation coordinates and pole_vector, but I am currently encountering such an error：Cannot find reference to 'create_orientation_from_surface_points' in '__init__.py'

Is this the correct calculation or if not, Can you tell me how to solve this problem?

Many thanks for your assistance.

**Comment by NilsChudalla** [comment]
Dear @Geo-LiuDaLi,

can you attach your code you try to run? 

If you have surface points and orientations measurements, you should be able to model a fault without trying to compute orientations from surface points. Check out the [Transform 2019](https://docs.gempy.org/integrations/gempy_striplog.html?highlight=transform#transform-2019-integrating-striplog-and-gempy) tutorial for an excellent example of how to add surface and orientation data after setting up a model or [Model 1.5](https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_5_fault_relations.html#sphx-glr-tutorials-ch1-fundamentals-ch1-5-fault-relations-py) for how to initialize a fault model from a data frame or csv file. 

Best regards
Nils

**Comment by Geo-LiuDaLi** [comment]
Dear @NilsChudalla 

I'm sorry for the late reply，Here is a list of the data I currently have: dip and azimuth data for the fault,and the coordinate point data extracted on the exposed line of the fault surface by using ArcGIS software, In other words, I have no deep data for faults,So I don't know how to get the orientation coordinate data on the section.
In fact, I'm not yet sure if these data are sufficient for GemPy to build fracture models.

![fault](https://user-images.githubusercontent.com/107994853/237045284-2606c40d-52fd-401a-a390-0844e3f3f240.png)
![image](https://user-images.githubusercontent.com/107994853/237048370-8a4ef793-b707-4b75-8516-a4d42ca3ff06.png)

And I think I haven't correctly understood the meaning of gradient in Gempy. I try to write a function to calculate the pole_vector required for modeling, but I am not sure if this is correct, or if there is a better calculation method.

import math
import csv
def compute_vector(dip, dip_direction):
    dip_rads = math.radians(dip)
    dip_direction_rads = math.radians(dip_direction)
    x = math.sin(dip_rads) * math.sin(dip_direction_rads)
    y = math.sin(dip_rads) * math.cos(dip_direction_rads)
    z = math.cos(dip_rads)
    return x, y, z

filename = 'E:\Gempy_Tutorial\pole_vector\pole_vector_test.csv'
with open(filename, 'r') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)
    with open('E:\Gempy_Tutorial\pole_vector\pole_vector_result.csv', 'w', newline='') as resultfile:
        writer = csv.writer(resultfile)
        writer.writerow(['X', 'Y', 'Z'])
        for row in reader:
            dip = float(row[0])
            dip_direction = float(row[1])
            pole_vector = compute_vector(dip, dip_direction)
            writer.writerow(pole_vector)


And  here's the code I'm currently trying to run

import gempy as gp
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

geo_model = gp.create_model("Fault_model_test")
orientations =pd.read_csv('E:\\F1_fault_test_data\\F1_TEST_Orientations_1.csv',sep=',')
surface = pd.read_csv('E:\\F1_fault_test_data\\F1_TEST_surface_points.csv',sep =',')

geo_model = gp.init_data(geo_model, extent=[330000., 360000., 3400000., 3490000., 4200., 5500.], resolution=[50, 50, 50],
                        surface_points_df = surface,
                        orientations_df = orientations,
                        default_values = True)

geo_model.add_surfaces('basement')
geo_model.add_features(['Fault_Series1',"Fault_Series2","Fault_Series3", 'Strat_Series'])
print(geo_model.surfaces)

gp.map_stack_to_surfaces(geo_model,
                         {"Fault_Series1":['Main_Fault'],
                          "Fault_Series2":['Fault2'],
                          "Fault_Series3":['Fault3'],
                           "Strat_Series": ['basement']},
                          remove_unused_series=True)

geo_model.set_is_fault(['Fault_Series1',"Fault_Series2","Fault_Series3"])
gp.plot_3d(geo_model)
gp.set_interpolator(geo_model,theano_optimizer='fast_compile', verbose=[])
gp.compute_model(geo_model)
gp.plot_3d(geo_model, show_topography=True)

Thanks in advance!

**Comment by AlexanderJuestel** [comment]
@Geo-LiuDaLi did the suggestion by @NilsChudalla help or could you still provide us with the code?

**Comment by Geo-LiuDaLi** [comment]
Hi! @AlexanderJuestel 
 Thanks for your reply!
  I apologize for the late reply. After I check out the [Transform 2019](https://docs.gempy.org/integrations/gempy_striplog.html?highlight=transform#transform-2019-integrating-striplog-and-gempy) tutorial and [Model 1.5](https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_5_fault_relations.html#sphx-glr-tutorials-ch1-fundamentals-ch1-5-fault-relations-py), I have successfully constructed the fault model by use the surface points and orientations measurements. 
  thanks again!
