### ISSUE TITLE
Calculating orientations from surface points

### ISSUE THREAD

**Issue by hntigkakis** [cgre-aachen/gempy#798]
Hi everyone!

I am trying to model the superficial thickness of an area, using only borehole data. So essentially I only have 1 surface (superficial deposits), plus the basement (bedrock). Because I only have borehole points and no orientation measurements, I am using the _select_nearest_surfaces_points_ and _set_orientation_from_neighbours_all_ functions to estimate my orientations. My problem is that using 2 nearest neighbours in the _select_nearest_surfaces_points_ function produces weird artefacts: 
![Screenshot 2023-05-19 130531](https://github.com/cgre-aachen/gempy/assets/99178328/a8c98385-09ac-46c7-bbf4-4e431c4372df)
My assumption is that this happens because I have areas with clustered data, since adjusting to another number of nearest neighbours, or switching to radius-search seems to fix my problem, or at least the surface looks more plausible (example with a 200. m radius search):
![Screenshot 2023-05-19 131358](https://github.com/cgre-aachen/gempy/assets/99178328/0dbcfab7-3939-46c2-9363-1749ba68c8ca)
So it seems that my problem is the selection of neighbours, but I cannot come up with a solution. Can anyone offer any advice on how to pick a method and a number? If I'm using the radius search method, how do I pick a radius? Any examples of literature would be greatly appreciated.

Thank you in advance!

**Comment by AlexanderJuestel** [comment]
@javoha, maybe you can help out here :)

**Comment by Amasiani** [comment]
Hi Good morning am interested in learning about this project. Can we have a chat ?
