### ISSUE TITLE
How to export to OBJ format

### ISSUE THREAD

**Issue by Geo-LiuDaLi** [cgre-aachen/gempy#825]
HI!
I would like to ask if there is an interface to export the constructed geological model to OBJ format for saving?

**Comment by AlexanderJuestel** [comment]
@Geo-LiuDaLi,

Have a look at our GemGIS package that can easily export the meshes. You can then use PyVista to save the meshes to VTK format, not OBJ

Installation of GemGIS: `pip install gemgis` (you need GeoPandas, Rasterio and PyVista for that)
Tutorial for extracting the depth maps: https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/18_creating_depth_maps_from_gempy_models.html
Saving meshes using PyVista: https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.PolyData.save.html 

I hope that helps :)

**Comment by Geo-LiuDaLi** [comment]
Thank you very much, that did solve the problem I was having!

**Comment by CHONGE** [comment]
> Thank you very much, that did solve the problem I was having!
How is this achieved?thanks
