### ISSUE TITLE
How to create the orientations data ?

### ISSUE THREAD

**Issue by 66mengyu** [cgre-aachen/gempy#829]
**What is your question?**
Now I only have borehole data.What need for creating the orientations data ？please help me.thank you.

**Comment by AlexanderJuestel** [comment]
Hey @66mengyu, 
orientation data consists of dip and azimuth values of the respective layers. Do you have dipmeter measurements from your borehole? If not, you have to assume values or look in the literature of your research area to find some. If you have at least 3 boreholes, you could also put a plane through them and calculate the dip of plane.

Cheers 
Alex

**Comment by 66mengyu** [comment]
@AlexanderJuestel I know. thank you.I'll go look it up.
