### ISSUE TITLE
p2d.plot_data(ax,cell_number=5)

### ISSUE THREAD

**Issue by 66mengyu** [cgre-aachen/gempy#830]
**What is your question?**
helllo ,In the"p2d.plot_data(ax,cell_number=5)",what is stand for "cell_number"?thank you.

**Comment by AlexanderJuestel** [comment]
The cell number is the number of your cell which is used to plot the cross section. At the beginning, you define resolutions of let us say 50,50,50, so cell size 25 in x direction would be equal to a cross section in the middle of the model. 

If you do not have a bug, please feel free to ask the question in the discussion forum: https://github.com/cgre-aachen/gempy/discussions
