### ISSUE TITLE
How to truncate the fault so that only the lower half remains

### ISSUE THREAD

**Issue by nearfuture625** [cgre-aachen/gempy#833]
Gemmy is a great geological modeling tool that uses Gemmy to build a four-layer geological model with a 135-degree main fault running through the four layers. There are also 45-degree branch faults that only contain the third and fourth layers, but in the gempy modeling process, the 45-degree faults run through the entire model, how do I deal with it so that the branch faults only pass through the next two layers, looking forward to your answer.
![微信图片_20231014155511](https://github.com/cgre-aachen/gempy/assets/145415488/b95392a0-7b8f-4083-82ca-8cc329b9f560)

**Comment by AlexanderJuestel** [comment]
@nearfuture625, have you had a look at the fault relations?

**Comment by nearfuture625** [comment]
thank you
