### ISSUE TITLE
gp.set_interpolator(geo_model, output=['geology'], compile_theano=True)         ImportError: Scan code version mismatch

### ISSUE THREAD

**Issue by CHONGE** [cgre-aachen/gempy#835]
**What is your question?**
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\aesara\scan\scan_perform_ext.py", line 50, in <module>
    raise ImportError("Scan code version mismatch")
ImportError: Scan code version mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\aesara\link\vm.py", line 1243, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "D:\anaconda3\Lib\site-packages\aesara\scan\op.py", line 1524, in make_thunk
    from . import scan_perform_ext
  File "D:\anaconda3\Lib\site-packages\aesara\scan\scan_perform_ext.py", line 89, in <module>
    cmodule.GCC_compiler.compile_str(
  File "D:\anaconda3\Lib\site-packages\aesara\link\c\cmodule.py", line 2654, in compile_str
    raise CompileError(
aesara.link.c.exceptions.CompileError: Compilation failed (return status=1):
"D:\anaconda3\Library\mingw-w64\bin\g++.exe" -shared -g -fwrapv -O2 -fno-strict-aliasing -march=broadwell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mclflushopt -mxsavec -mxsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=12288 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"D:\anaconda3\Lib\site-packages\numpy\core\include" -I"D:\anaconda3\include" -I"D:\anaconda3\Lib\site-packages\aesara\link\c\c_code" -L"D:\anaconda3\libs" -L"D:\anaconda3" -o "C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\scan_perform.pyd" "C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp" "D:\anaconda3\python311.dll"
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp: In function 'PyObject* __pyx_pf_6aesara_4scan_12scan_perform_2perform(PyObject*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyObject*, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyObject*, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, PyObject*, PyObject*, __Pyx_memviewslice, PyObject*, PyObject*, PyObject*, __Pyx_memviewslice, PyObject*)':
D:\anaconda3\include/pyport.h:135:27: error: 'INTPTR_MAX' was not declared in this scope
 #   define PY_SSIZE_T_MAX INTPTR_MAX
                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:946:43: note: in definition of macro 'likely'
   #define likely(x)   __builtin_expect(!!(x), 1)
                                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:781:28: note: in expansion of macro 'PY_SSIZE_T_MAX'
           likely(v < (type)PY_SSIZE_T_MAX ||\
                            ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:1673:6: note: in expansion of macro '__Pyx_fits_Py_ssize_t'
     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
      ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:3642:19: note: in expansion of macro '__Pyx_GetItemInt'
       __pyx_t_2 = __Pyx_GetItemInt(__pyx_t_1, 0, long, 1, __Pyx_PyInt_From_long, 0, 0, 0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 225, __pyx_L1_error)
                   ^
D:\anaconda3\include/pyport.h:135:27: error: 'INTPTR_MAX' was not declared in this scope
 #   define PY_SSIZE_T_MAX INTPTR_MAX
                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:946:43: note: in definition of macro 'likely'
   #define likely(x)   __builtin_expect(!!(x), 1)
                                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:781:28: note: in expansion of macro 'PY_SSIZE_T_MAX'
           likely(v < (type)PY_SSIZE_T_MAX ||\
                            ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:1673:6: note: in expansion of macro '__Pyx_fits_Py_ssize_t'
     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
      ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:3783:17: note: in expansion of macro '__Pyx_GetItemInt'
     __pyx_t_2 = __Pyx_GetItemInt(__pyx_t_3, 0, long, 1, __Pyx_PyInt_From_long, 0, 0, 0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 238, __pyx_L1_error)
                 ^
D:\anaconda3\include/pyport.h:135:27: error: 'INTPTR_MAX' was not declared in this scope
 #   define PY_SSIZE_T_MAX INTPTR_MAX
                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:947:43: note: in definition of macro 'unlikely'
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:781:11: note: in expansion of macro 'likely'
           likely(v < (type)PY_SSIZE_T_MAX ||\
           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:781:28: note: in expansion of macro 'PY_SSIZE_T_MAX'
           likely(v < (type)PY_SSIZE_T_MAX ||\
                            ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:1718:6: note: in expansion of macro '__Pyx_fits_Py_ssize_t'
     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
      ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:3870:20: note: in expansion of macro '__Pyx_SetItemInt'
       if (unlikely(__Pyx_SetItemInt(__pyx_v_outer_outputs_idx, 0, __pyx_t_2, long, 1, __Pyx_PyInt_From_long, 0, 0, 0) < 0)) __PYX_ERR(0, 252, __pyx_L1_error)
                    ^
D:\anaconda3\include/pyport.h:135:27: error: 'INTPTR_MAX' was not declared in this scope
 #   define PY_SSIZE_T_MAX INTPTR_MAX
                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:946:43: note: in definition of macro 'likely'
   #define likely(x)   __builtin_expect(!!(x), 1)
                                           ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:781:28: note: in expansion of macro 'PY_SSIZE_T_MAX'
           likely(v < (type)PY_SSIZE_T_MAX ||\
                            ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:1673:6: note: in expansion of macro '__Pyx_fits_Py_ssize_t'
     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
      ^
C:\Users\ThinkPad\AppData\Local\Aesara\compiledir_Windows-10-10.0.22621-SP0-Intel64_Family_6_Model_166_Stepping_0_GenuineIntel-3.11.5-64\scan_perform\mod.cpp:3898:17: note: in expansion of macro '__Pyx_GetItemInt'
     __pyx_t_2 = __Pyx_GetItemInt(__pyx_v_outer_outputs_idx, 0, long, 1, __Pyx_PyInt_From_long, 0, 0, 0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 255, __pyx_L1_error)

**Comment by qq123hht** [comment]
HELLO,I have the same problem as you, have you solved it?

**Comment by CHONGE** [comment]
> have you solved it?

Compiling aesara function...

You can find the C code in this temporary file: C:\Users\ThinkPad\AppData\Local\Temp\aesara_compilation_error_v1n10b5v
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\aesara\scan\scan_perform_ext.py", line 50, in <module>
    raise ImportError("Scan code version mismatch")
ImportError: Scan code version mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\aesara\scan\scan_perform_ext.py", line 71, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

**Comment by CHONGE** [comment]
aesara seems to have a problem, but don't know how to solve it, please God

**Comment by CHONGE** [comment]
aesara 2.8.11 and gempy 2.31 and python version 3.11,

**Comment by Japhiolite** [comment]
Aesara will cause this error with python 3.11.
Please use 3.10 (see here: https://github.com/cgre-aachen/gempy/issues/810 )

**Comment by CHONGE** [comment]
> Aesara will cause this error with python 3.11. Please use Python 3.10 (see here: #810 )
thank you,
