### ISSUE TITLE
installation Attributeerror

### ISSUE THREAD

**Issue by MarinCronograph** [cgre-aachen/gempy#836]
**Hi.

i got an attributeError after setting up conda environment and installing gempy. Could this be a critical issue ?**

"

C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing
Traceback (most recent call last):

  File ~\untitled0.py:9
    import gempy

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\gempy\__init__.py:9
    import pandas

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\__init__.py:182
    import pandas.testing

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\testing.py:7
    from pandas.util.testing import (

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27
    import pandas._libs.testing as _testing

  File pandas/_libs/testing.pyx:10 in init pandas._libs.testing

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\numpy\__init__.py:305 in __getattr__
    raise AttributeError(__former_attrs__[attr])

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Output from spyder call 'get_namespace_view':
C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing

Output from spyder call 'get_var_properties':
C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing

runcell(1, 'C:/Users/Eier/untitled0.py')
C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing
Traceback (most recent call last):

  File ~\untitled0.py:9
    import gempy

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\gempy\__init__.py:9
    import pandas

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\__init__.py:182
    import pandas.testing

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\testing.py:7
    from pandas.util.testing import (

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27
    import pandas._libs.testing as _testing

  File pandas/_libs/testing.pyx:10 in init pandas._libs.testing

  File ~\anaconda3\envs\gempy_mm\lib\site-packages\numpy\__init__.py:305 in __getattr__
    raise AttributeError(__former_attrs__[attr])

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Output from spyder call 'get_namespace_view':
C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing

Output from spyder call 'get_var_properties':
C:\Users\Eier\anaconda3\envs\gempy_mm\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing

"

**Comment by AlexanderJuestel** [comment]
Dear @MarinCronograph, 

there are a lot of NumPy and Pandas showing up in your error code. What are your respective versions?

Cheers
Alex

**Comment by MarinCronograph** [comment]
Dear @AlexanderJuestel 

numpy is 1.24.4

pandas is 0.25.3

rgds

**Comment by AlexanderJuestel** [comment]
Wow, 0.25 really old. 2.0.1 is a version that I would recommend for pandas. How have you installed everything?

**Comment by MarinCronograph** [comment]
@AlexanderJuestel 

I have used conda  " install -c conda-forge gempy " after I created environment in conda.  https://anaconda.org/conda-forge/gempy

Shouldn't this create all of the rightversions and dependencies ?

rgds

**Comment by AlexanderJuestel** [comment]
It seems like the package hasn't been updated there. I recommend using pip. There you have the latest version GemPy.

**Comment by MarinCronograph** [comment]
hi @AlexanderJuestel  , thanks , i have installed as you said  1. $ conda install theano 2. $ pip install gempy 3. clone the repository (git ) .  Then I open Anaconda - Import gempy , I get warning under. Can this be corrected ?

"No module named 'osgeo'
WARNING (aesara.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (aesara.configdefaults): g++ not detected!  Aesara will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set Aesara flags cxx to an empty string.
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions."

**Comment by AlexanderJuestel** [comment]
Theano is no longer  needed as we are using aesara right now. Pip install gempy should install everything you need

**Comment by MarinCronograph** [comment]
hi @AlexanderJuestel 

I have :  
1. created new conda environment in Anaconda prompt
2. activated new environment 
3. installed -pip install gempy
4. opened - jupyter notebook
5. imported gempy -import gempy as gp 

WARNING 

" No module named 'osgeo'
C:\Users\Eier\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
WARNING (aesara.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (aesara.configdefaults): g++ not detected!  Aesara will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set Aesara flags cxx to an empty string.
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions."

**Comment by AlexanderJuestel** [comment]
This warning can be ignored! You can use GemPy normally

**Comment by MarinCronograph** [comment]
> This warning can be ignored! You can use GemPy normally

@AlexanderJuestel , thanks 👍
