### ISSUE TITLE
Enhanced topology node labeling

### ISSUE THREAD

**Issue by pytzcarraldo** [cgre-aachen/gempy#84]
Along the lines of `"{fb_id}_{lb_id}_{instance}"` to conveniently and clearly identify fault block location and lithology id of the node at a glance. For multiple regions of same lithology in fault block add instance iterator (a,b,c,...)

Future problem: How does this work with finite faults?

**Comment by Leguark** [comment]
My plan for the new structure is to create a solution class that contains everything so you do not have to be passing many arrays.

Finite faults... are going to give you a finite topology node I guess :D
