### ISSUE TITLE
The fault model lacks undulations

### ISSUE THREAD

**Issue by Geo-LiuDaLi** [cgre-aachen/gempy#847]
Hi~
I have successfully constructed a series of fault models using Gempy, but the model I have constructed it lacks undulation and I am wondering if there is something I am doing wrong? And how can I go about fixing this problem.
Thanks~Looking forward to your reply :）
![image](https://github.com/cgre-aachen/gempy/assets/107994853/23da2db8-c7dd-4465-9550-8417c74e8c04)
![image](https://github.com/cgre-aachen/gempy/assets/107994853/7553ece2-a2c8-4ec0-a9c8-a82b597b0259)

**Comment by javoha** [comment]
Hello,
can you maybe specify the expected result? Right now I am seeing a single fault plane with no other rock units? The plane looks correct as it respects your input data. 
Cheers, Jan

**Comment by Geo-LiuDaLi** [comment]
Hi~ @javoha 
I apologise for the late reply.
As you can see, I just constructed a simple fault plane that is consistent with my existing input data.
This is a fault model that I have constructed through software, and I would like the upper surface of the fault to undulate like this, so that I can construct a fault model that is more in line with the current state of the geology. But I don't know how I should realise this requirement, can you give me some advice?
Thanks~Looking forward to your reply :）
![image](https://github.com/cgre-aachen/gempy/assets/107994853/bbc37c3f-a337-47d8-baf6-d666ee8e9b34)
![image](https://github.com/cgre-aachen/gempy/assets/107994853/3c15669d-758b-4d76-870b-2638ca2b3b82)
