### ISSUE TITLE
Reversal of strattigraphic series when data unevenly distributed

### ISSUE THREAD

**Issue by Peter80er** [cgre-aachen/gempy#88]
Dear GemPyers,
I observed frequently now that the potential between conformable stratigraphies is not honoring the age relationship among them, e.g. the resulting potentials in confomable order are [-149.45674 , -149.4612  , -149.46297 , -149.4624  , -149.46335 , -149.46562 , -149.46648 , -149.46748 , -149.47075 , -149.47293 , -149.47319 , -149.4768  , -149.47504 , -149.47722 , -149.48634 , -149.47495 , -149.48016]. As you may observe the potentials of the last 5 stratigraphies are "jumping". From my observations, I would attribute it to the spatially clustered nature of the input data with only little information about the order within the same boreholes. However, I think the model should honor the a-priori knowledge of age relationships, Do you have any suggestion how to solve it? Otherwise great package! Cheers

**Comment by Leguark** [comment]
Hi Peter, 
I like the term GemPyers term. I will order some T-shirts.

Within a conformable series there is no way to force a layer to be on top of another though the pile. It is just take the order that reduce variability (basically what Kriging does). I would just try to model that individual series and maybe even just those formations to understand what is going on.
Right now you are on unexplored territory. I have never seen 20 series/faults in a single model in GemPy yet

**Comment by Leguark** [comment]
"The colors/series names are assigned to increasing order of potentials without altering the input order."

what do you mean exactly?

**Comment by Peter80er** [comment]
Hi Miguel,
currently the color code for the  cross sections follows the order of the potentials of the surfaces. However, the data points follow the order of the input sequence. Hence, whenever the output potential do not increase in the order of the input, there is an offset between the colors of the surfaces and the colors of the data points.

**Comment by Leguark** [comment]
Hi Peter,
okay now I see what you mean. Yes you are totally right. The thing is that if your "output potential" has a different order than the input (sequential pile) then I would say that the input is wrong isnt it?

Changing the colors automatically can be quite confusing if suddenly a layer change the color unexpected. But I am open to suggestions in regards what do you think that makes more sense

**Comment by Peter80er** [comment]
Well, see comment from 08/27. The problem is the data distribution... Hence, no, the input is not wrong but the model is just not capable to honor the geological time constraints due to spatially clustered data.

**Comment by Leguark** [comment]
Mmm but actually that is what the algorithm does (as long as the layers are in the same series). Or the jump is between series?
