### ISSUE TITLE
Read-in of exported Petrel fault stick files

### ISSUE THREAD

**Issue by pytzcarraldo** [cgre-aachen/gempy#90]
Read function for kingdom fault sticks / charisma fault sticks files (essentially chaotically delimited csv) as fault evidence (grouped by stick per fault)

**Comment by pytzcarraldo** [comment]
+ fit orientation values between consecutive stick sets (every n sticks grouped together)

**Comment by Leguark** [comment]
is this done?

**Comment by anyuzoey** [comment]
Hi, pytzcarraldo,

I'm know trying to convert Petrel fault sicks to numpy array. Do you have any progress on this? 

> * fit orientation values between consecutive stick sets (every n sticks grouped together)

**Comment by pytzcarraldo** [comment]
Hey @anyuzoey 

I have two functions for reading fault stick files exported by Petrel into Python. You can currently find them at https://github.com/pytzcarraldo/gio/blob/master/gio/faults.py 

- Kingdom fault sticks `gio.faults.read_kingdom()`
- Charisma fault sticks `gio.faults.read_charisma()`

This loads the fault sticks into pandas dataframes, which you can then convert into numpy arrays!

**Comment by anyuzoey** [comment]
Hi @pytzcarraldo 

Thank you so much for your speedy reply. I'll check the code now. Thanks again.

**Comment by anyuzoey** [comment]
Hi @pytzcarraldo 
I notice that your code converts ASCII text to dataframe. Maybe I didn't explain my query clearly. I want to convert fault sticks ASCII file to a fault network stored as something like numpy array. Do you happen to have any insights on this? The difficult part is which points should be connected to a line, and which points should be connected to a plane. Is it a smooth surface or a triangle surface?
But thanks for your code.

**Comment by pytzcarraldo** [comment]
Hey @anyuzoey 
Once you read in the fault stick file, the resulting pandas dataframe contains the information of which fault points belong to which fault stick in the column `"stick id"`. So if you want to access all points belonging to fault stick #4 in a dataframe called `fault_df`, you can filter it using `fault_df[fault_df["stick id] == 4]`. 
So the fault stick files exported by Petrel are not surfaces, but simple point clouds with information about which points make up a fault stick. If you want a meshed surface, you'd need to either create a surface in Petrel and export it as a surface, or mesh the fault stick points into a surface in Python using maybe Delaunay triangulation or other algorithms.

Hope that helps!

**Comment by anyuzoey** [comment]
Hi @pytzcarraldo 

Thank you very much for your reply. I have tried with filter by stick id. However, seems like my fault stick file is too large (29182 points, multi faults, multi stick id) that it is more complex than just connect points with the same stick number to 1 surface. Probably need filter both fault id and stick id. I'm thinking about another way to generate the fault network using high-resolution images crop by Petrel. 
Finger cross.

Thank you again for your kind help.

**Comment by Leguark** [comment]
@pytzcarraldo is this close?

**Comment by Leguark** [comment]
@pytzcarraldo Can you create fast a test for this so we can close the issue?

**Comment by pytzcarraldo** [comment]
I'll get this done by Monday

**Comment by pytzcarraldo** [comment]
This is now merged into `subsurface/master`

**Comment by pytzcarraldo** [comment]
This will be resolved with PR #357

**Comment by alexanderzimmerman** [comment]
@Leguark , did you mention that this issue should still be open?
