### ISSUE TITLE
Fold axes

### ISSUE THREAD

**Issue by gasiva** [cgre-aachen/gempy#97]
@Leguark at the moment seems that gempy does not take into consideration fold axes to correctly model fold hinges. If true, will this feature be developed in the future?

**Comment by Leguark** [comment]
Hi @gasiva 
folds with GemPy has to be done by carefully place the input data in the right place. As far as I know, no other implicit geological modelling software is able to deal with this properly. Or do you know some that you can point me to? I know Monash University is working on that (I will meet them in a few weeks) but I am not sure how feasible is to implement it into the main code yet.

In any case, any suggestion how to solve it is welcome!
