### ISSUE TITLE
Gradient of potential field vs. gradient derived from orientation data

### ISSUE THREAD

**Issue by Peter80er** [cgre-aachen/gempy#98]
Hi Miguel,
I try to match the gradient data derived from the input order (as you calculate it) with the gradients calculated from the output potential field. However, there is seems to be a factor/normalization, which I am not able to find out about... May you enlighten me? ;-) Thx!

**Comment by Leguark** [comment]
mmm do you mean the comparison between doing np.grad to the scalar field and the Gx, Gy, Gz interpolated when you choose output = 'gradient'?

If that is what you mean to be honest I just plotted both and I saw that they were the same (except at the offset boundaries where the interpolated gradient is much more consistent.). It is a constant factor over the whole volume?
